### ISSUE TITLE
IDbCommandInterceptor does not fire when using BulkSaveChanges

### ISSUE THREAD

**Issue by ViktorBergman** [zzzprojects/EntityFramework-Extensions#100]
Using EF 6.2 and latest bits of EntityFramework-Extensions from nuget.
Was expecting to see some INSERT commands being fired on NonQueryExecuting.
If IDbCommandInterceptor is not supported how would I go about to intercept these changes? I am using it to clear my cache.

**Comment by JonathanMagnan** [comment]
Thank you Viktor,

What about using the log options: http://entityframework-extensions.net/logging?

You will be able to find out the table from it.

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment]
It's also possible to support somewhat the Audit feature from Entity Framework Plus: http://entityframework-plus.net/audit

You will need to implement your own `BulkSaveChanges` method calling our:


```csharp
public void BulkSaveChanges()
{
	var audit = new Audit();
	audit.PreSaveChanges(this);
	DbContextExtensions.BulkSaveChanges(this);
	audit.PostSaveChanges();
	
	// Clear your cache using value found from the audit object
}
```

Let me know if one of these options can do the job.

Best Regards,

Jonathan

**Comment by ViktorBergman** [comment]
Logging seems to do the trick! Thanks for quick response! =)
