### ISSUE TITLE
Type not supported yet (LazyType): bpchar

### ISSUE THREAD

**Issue by armitagemderivitec** [zzzprojects/EntityFramework-Extensions#101]
Hi,

I am migrating one of our MsSql databases to Postgres and I now receive the following error when using the BulkInsert method for audit entries: 

```
System.Exception: Type not supported yet (LazyType): bpchar
   at .(String , PrimitiveType )
   at .<>c.(Property )
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at ..(SchemaEntityType )
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at .(Schema , Boolean )
   at .(Schema , Boolean )
   at .(XDocument )
   at .(DbContext )
   at DbContextExtensions.GetModel(DbContext this)
   at .(DbContext this, String )
   at .[](DbContext this, BulkOperation`1 , IEnumerable`1 , List`1 )
   at .[](BulkOperation`1 this, DbContext , IEnumerable`1 , List`1 )
   at DbContextExtensions.BulkInsert[T](DbContext this, IEnumerable`1 entities, Action`1 bulkOperationFactory)
   at DbContextExtensions.BulkInsert[T](DbContext this, IEnumerable`1 entities)
   at Derivitec.Infrastructure.Data.Db.Common.Models.PortfolioDbContext.SaveChanges()
```

My overridden SaveChanges method is as follows:

```
 var audit = new Audit();
            audit.PreSaveChanges(this);
            this.BulkSaveChanges();
            audit.PostSaveChanges();

            if (audit.Entries.Count > 0)
            {
                this.BulkInsert(audit.Entries);

                // The ID must be set, there is currently no navigation properties in the AuditEntryProperty class
                audit.Entries.ForEach(x => x.Properties.ForEach(y => y.AuditEntryID = x.AuditEntryID));

                // Don't output the Id for EntryProperty for more performance
                this.BulkInsert(audit.Entries.SelectMany(y => y.Properties), operation =>
                    {
                        operation.AutoMapOutputDirection = false;
                        operation.BatchSize = 50000;
                    });
            }

            return this.ChangeTracker.Entries().Count(w => w.State != EntityState.Unchanged);
```

Is this a genuine bug or am I doing something wrong?

Many thanks in advance.

Cheers 

Michael Armitage

**Comment by JonathanMagnan** [comment]
Hello @armitagemderivitec ,

No, you did nothing wrong. The type `bpchar` is not a common type so our library doesn't support it yet.

We will look at it.

Best Regards,

Jonathan

**Comment by armitagemderivitec** [comment]
Hi @JonathanMagnan,

Thanks so much for the quick response. Absolutely no pressure but what's the turn around on something like this? 

I'm looking at overriding the sql migration generator to use a different type so if I have any luck I'll let you know.

Cheers 

Mike

**Comment by JonathanMagnan** [comment]
Hello @armitagemderivitec ,

Unless something happens, a new version will be available with the fix tomorrow.

There is nothing you can do meanwhile on your side to `skip` it. But we will try to add a new method as well in case you have more unsupported types to allow you to map it until we fix it.

Best Regards,

Jonathan

**Comment by armitagemderivitec** [comment]
Hi @JonathanMagnan,

That's fantastic news! I'm delighted we chose to use your framework, I really appreciate the immediate response.

Best regards,

Mike

**Comment by JonathanMagnan** [comment]
Hello @armitagemderivitec ,

The v3.14.23 has been released.

We mapped the PostgreSQL type `bpchar` to the C# type `string`

As said, we also added a new method named `TemporaryStringToTypeAction` to allow you to map more type if some are missing and report us back to allow us to add it to our library.

Example:

```csharp
EntityFrameworkManager.TemporaryStringToTypeAction = dict => { 
	dict.Add("bpchar", typeof(string));
	dict.Add("anotherType", typeof(int));
};
```

Let me know if everything work as expected.

Best Regards,

Jonathan

**Comment by armitagemderivitec** [comment]
Hi @JonathanMagnan,

I've upgraded to v3.14.23 and it works perfectly. I have been able to run all my migrations, seed and run all unit/integration tests with complete success. I didn't need type mapping code as all other types appear to be covered already. 

Thank you so much for the quick turn around. 

Regards 

Mike
