### ISSUE TITLE
EF6 + EntityFramework Profiler DeleteFromQuery Exception

### ISSUE THREAD

**Issue by skippycoder** [zzzprojects/EntityFramework-Extensions#102]
Most Bulk operations are working with EntityFramework Profiler as part of the application.  I am trying to profile DeleteFromQuery for a comparision to BulkDelete performance.  An exception is thrown when DeleteFromQuery is called:

 Exception: Unable to cast object of type 'System.Data.SqlClient.SqlCommand' to type 'HibernatingRhinos.Profiler.Appender.ProfiledDataAccess.ProfiledCommand'

Is there a setting or configuration to allow DeleteFromQuery to use the ProfiledCommand when EntityFramework Profiler is being used?

**Comment by JonathanMagnan** [comment]
Hello @skippycoder ,

Thank you for reporting.

We will investigate this issue and try to make it compatible with HibernatingRhinos.

`DeleteFromQuery` should be way faster since it doesn't need to load entities for deleting them.

Best Regards,

Jonathan

**Comment by mkeuschn** [comment]
I have the same Problem. Are there any news?

`Unable to cast object of type 'System.Data.SqlClient.SqlCommand' to type 'HibernatingRhinos.Profiler.Appender.ProfiledDataAccess.ProfiledCommand'.`

**Comment by JonathanMagnan** [comment]
Hello @mkeuschn ,

Thank you for bringing back alive this issue. I don't understand why it has not been done yet.

I will assign this request to my developer, we already support `HibernatingRhinos` for multiple methods, I don't understand why that request has never been done.

**Comment by JonathanMagnan** [comment]
Hello @skippycoder , @mkeuschn ,

Sorry for forgetting about this request.

A new v3.16.43 has been released.

Let me know if that's now working as expected.

Best Regards,

Jonathan
