### ISSUE TITLE
BulkInsert Option to ignore columns is not working

### ISSUE THREAD

**Issue by mmiller678** [zzzprojects/EntityFramework-Extensions#103]
I am trying to use the column defaults setup on the table so I want to ignore these columns on bulk insert.
```
            Context.BulkInsert(values, x =>
            {
                x.BatchSize = batchSize;
                x.IncludeGraph = false;
                x.IgnoreOnSynchronizeInsertExpression = entity => new { entity.DateCreated, entity.DateModified };
                x.IgnoreOnMergeInsertExpression = entity => new { entity.DateCreated, entity.DateModified };
            });

```
I tried both the IgnoreOnSynchronizeInsertExpression  and IgnoreOnMergeInsertExpression without success.  Below is the generated SQL:

```
exec sp_executesql N'MERGE INTO [dbo].[QueryPeriod] AS DestinationTable
USING
(
SELECT * FROM #ZZZProjects_154ccff7_d948_41f6_a67b_168dfce97b08
WHERE ZZZ_Index >= @IndexStart AND ZZZ_Index <= @IndexEnd
) AS StagingTable
ON 1 = 2
WHEN NOT MATCHED THEN
    INSERT ( [DataFieldId], [DateCreated], [DateModified], [DataFieldEndDate], [DataFieldStartDate], [PeriodEndDate], [PeriodStartDate], [QueryIdentifier] )
    VALUES ( [DataFieldId], [DateCreated], [DateModified], [DataFieldEndDate], [DataFieldStartDate], [PeriodEndDate], [PeriodStartDate], [QueryIdentifier] )
OUTPUT
    $action,
    StagingTable.ZZZ_Index,
    INSERTED.[QueryPeriodId] AS [QueryPeriodId_zzzinserted], INSERTED.[Version] AS [Version_zzzinserted]

;',N'@IndexStart int,@IndexEnd int',@IndexStart=0,@IndexEnd=999
```
EF Core: 2.1.0-preview1-final
z.entityframework.extensions.efcore:  2.1.11

**Comment by JonathanMagnan** [comment]
Hello @mmiller678 ,

The options `IgnoreOnInsertExpression` that you are looking for doesn't exist.

The `IgnoreOnSynchronizeInsertExpression` only work with BulkSynchronize and `IgnoreOnMergeInsertExpression` only work with BulkMerge.

We added this task to our list.

We will try to provide you a new version with this options on next Monday.

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment]
Hello @mmiller678 ,

The v3.14.24 has been released. We added the `IngoreOnInsertExpression` and `IgnoreOnUpdateExpression` options.

You should now be able to ignore some column using the following code:

```csharp
Context.BulkInsert(values, x =>
{
	x.BatchSize = batchSize;
	x.IncludeGraph = false;
	x.IgnoreOnInsertExpression = entity => new { entity.DateCreated, entity.DateModified };
});
```

Let me know if everything is working correctly.

Best Regards,

Jonathan

**Comment by mmiller678** [comment]
This works great!  Thanks for the quick turn around.

**Comment by kinch-tech** [comment]
really don't understand why ignore should be an expression....
