### ISSUE TITLE
batch update and batch delete 

### ISSUE THREAD

**Issue by zhuyangping** [zzzprojects/EntityFramework-Extensions#105]
Hi, I found that the last generated SQL will use inner join. It will cause database deadlock. Why use inner join in design? 
SQL
DELETE A
FROM `yy_travels_follow` AS A
INNER JOIN ( SELECT
`Extent1`.`id`
FROM `yy_travels_follow` AS `Extent1`
 WHERE (`Extent1`.`userID` = 72) AND (`Extent1`.`travelsID` = 58) ) AS B ON A.`id` = B.`id`

**Comment by JonathanMagnan** [comment]
Hello @zhuyangping ,

Which provider are you using?

Some `SQL` has been designed this way since we don't control the `SQL` generated, Entity Framework does. So we have sometimes limited since we need to support multiple scenarios.

Best Regards,

Jonathan

**Comment by ViktorBergman** [comment]
I am also experiencing overwhelmingly more deadlocks since I started using BulkSaveChangesAsync(). Using SQL Server.

**Comment by ViktorBergman** [comment]
@JonathanMagnan Any progress on this issue?

**Comment by JonathanMagnan** [comment]
Hello @zhuyangping ,

Sorry for the late answer, we missed this request.

Are you using `Entity Framework Extensions` or `Entity Framework Plus`? I believe this request belongs EF+ which generate the query slightly differently.

**Comment by zhuyangping** [comment]
Yes. This request belongs EF+.

**Comment by JonathanMagnan** [comment]
Currently, the only way to avoid deadlock in this library is using the `UseTableLock` option to true.

For example:

```csharp
ctx.Users.Where(x => x.LastLoginDate < date)
         .Delete(x => x.UseTableLock = true);
```

Let me know if that solution could work for you.

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment]
Hello @Jon,

This issue will be closed since it has been answered.

Feel free to reopen it if you feel otherwise.

Best Regards,

Jonathan
