### ISSUE TITLE
BulkSaveChanges not working with EF Core InMemory provider

### ISSUE THREAD

**Issue by juvenull** [zzzprojects/EntityFramework-Extensions#112]
BulkSaveChanges not working with EF Core InMemory provider

I have exception: System.InvalidOperationException : Relational-specific methods can only be used when the context is using a relational database provider.

**Comment by JonathanMagnan** [comment]
Hello @juvenull ,

Thank you, you are right. Our library doesn't support `EF Core InMemory` provider yet.

It's on our todo list but there is no date planned for it yet.

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment]
Hello @juvenull ,

I will close this request.

The support for `EF Core InMemory` has been added some month.

Sorry that we forget to answer you.

If there is anything, let us know.

Best Regards,

Jonathan
