### ISSUE TITLE
How to update with different data in each row or column using EF Plus

### ISSUE THREAD

**Issue by vinodkumar1080** [zzzprojects/EntityFramework-Extensions#114]
The following code supports only to update with same value on all the rows based conditions in where clause
```
var date = DateTime.Now.AddYears(-2);
ctx.Users.Where(x => x.LastLoginDate < date)
         .UpdateAsync(x => new User() { IsSoftDeleted = 1 });
```
But i have a list of updated data i need to update based on identity column value
In Entity Framework Extended there is one method i.e bulkupdate(<<listofupdateddata>>).
Is there any extended method available in EF plus .Can you please help me with some solution.

Thanks in advance.

**Comment by JonathanMagnan** [comment]
Hello @vinodkumar1080 ,

It depends what you want to do, you can already use some database value

```csharp
var date = DateTime.Now.AddYears(-2);
ctx.Users.Where(x => x.LastLoginDate < date)
         .UpdateAsync(x => new User() { IsSoftDeleted = x.IdentityColumnValue });
```

Let me know if that helped you, otherwise please project us a full examples.

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment]
Hello @vinodkumar1080 ,

This issue will be closed since it has been answered.

Feel free to reopen it if you feel otherwise.

Best Regards,

Jonathan
