### ISSUE TITLE
Exception on Bulk Merge

### ISSUE THREAD

**Issue by david-garcia-garcia** [zzzprojects/EntityFramework-Extensions#117]
I am reopening #79 in light of a possible cause for the issue:

ZZZ is internally using MemoryCache.Default + some internal static dictionaries.

When running several XUNIT tests in paralell for an application, XUNIT does not do Process Isolation (only application domain isolation) so basically... The contents of MemoryCache.Default LEAK between tests. Because the models are configured diferently in the different tests (properties ignored, etc...) this results in random failures.

Any chance that you could add an option to disable the usage of MemoryCache, or replace it's usage with some static storage?

**Comment by JonathanMagnan** [comment]
Hello @david-garcia-garcia ,

If we let you specify your own cache that inherits from `ObjectCache`, do you think that will work?

You will be able to create your own cache that could do static storage if you want.

Best Regards,

Jonathan

**Comment by david-garcia-garcia** [comment]
@JonathanMagnan thanks for the follow-up. That is potentially a good solution. Thanks!

**Comment by david-garcia-garcia** [comment]
Any ETA on this? So we can decide how to deal with this while it's fixed.

**Comment by JonathanMagnan** [comment]
Hello @david-garcia-garcia ,

The v3.14.33 has been released.

You should now be able to specify your own cache : `EntityFrameworkManager.Cache = MemoryCache.Default;`

Let me know if that helps you with your unit test

Best Regards,

Jonathan

**Comment by david-garcia-garcia** [comment]
Thanks! We have already implemented a custom cache override, but we are still seeing leakage.

We will be investigating further, it would be helpful if you could clarify something...

See the following exception and stack trace:

![image](https://user-images.githubusercontent.com/9599352/41222569-96145fdc-6d67-11e8-81b6-2f01d1bf6882.png)

Where is ZZZ obtaining the information for the missing column? It looks like it has some cached column name resolution, but later it obtains conflicting information coming from elsewhere.

**Comment by JonathanMagnan** [comment]
Hello @david-garcia-garcia ,

The information is in the cache. So if you use a custom cache, it will be in your custom cache. However, we don't control the cache in Entity Framework, so perhaps there is still something missing to make all your tests work correctly with our library.

Do you think you could send us a project with that error so we could look if there is anything on our side we can do?

Best Regards,

Jonathan
