### ISSUE TITLE
License update doesn't work

### ISSUE THREAD

**Issue by PaulSchmitz** [zzzprojects/EntityFramework-Extensions#12]
Hi,

I have been using EF-extensions bulkinsert over the last few months (first major EF project) and it has always been working properly. Today I had to update to the latest version (3.9.44). Although the update was installed successfully, I get the following error message: {"The trial period is expired. Please buy a product license or go to http://www.zzzprojects.com and download the latest trial version."}.

I have tried to re-install several times but keep on getting the error message. I hope someone can help me to solve this issue.

Many thanks,

Paul

**Comment by zzzprojects** [comment]
Hello Paul,

We are sorry, we didn’t successfully release the trial for this month at time. You can download the latest version we just released a few minutes ago to fix this issue.

Let us know if the trial is now working for you.

Best Regards,

Jonathan

**Comment by PaulSchmitz** [comment]
Hello Jonathan,

 

Many thanks for your swift response, I have installed the latest version and it is working fine again!

 

Thank again!

 

Kind regards,

 

Paul

**Comment by zzzprojects** [comment]
Fixed. The trial has been released.
