### ISSUE TITLE
BulkInsert issue

### ISSUE THREAD

**Issue by EricNex** [zzzprojects/EntityFramework-Extensions#120]
I get the error 'Object reference not set to an instance of an object.' when I use BlukInsert Function.
db.BulkInsert(mpi1CfgLnks);
db.BulkSaveChanges();

The 'db' is a context with connection information.

Could you help for this problem?

**Comment by JonathanMagnan** [comment]
Hello @EricNex ,

Sure we can help but we will need a little bit more information to allow us to investigate it.

Could you provide us a project sample with that error?

Best Regards,

Jonathan

**Comment by EricNex** [comment]
Hi @JonathanMagnan,
The sasmple:
public Area1Repository()
{
        db = new Area1Context();
}

public Area1Repository(string dbConfigName)
{
        db = ContextGenerate.getContext<Area1Context>(ModelBuilderSetter.Area1DbModelBuilder(dbConfigName), dbConfigName);
}

public void BulkInsertArea1Mpi1CfgLnk(IEnumerable<Area1_Mpi1CfgLnk> mpi1CfgLnks)
{
            try
            {
                db.BulkInsert(mpi1CfgLnks);
                db.BulkSaveChanges();
            }
            catch (Exception e)
            { }
}

And when I call the function db.BulkInsert(mpi1CfgLnks), then catch the error.

Regards,
EricNex

**Comment by JonathanMagnan** [comment]
Hello @EricNex ,

The `BulkInsert` is a direct operation, so you don't need to call `BulkSaveChanges`.

I don't think we will be able to reproduce it with the information provided.

Is it possible to include the full stack trace and provide us with a complete example like the one below? You can also submit it directly to us here info@zzzprojects.com 

```csharp
using System.Collections.Generic;
using System.Data.Entity;
using System.Windows.Forms;

namespace Z.EntityFramework.Extensions.Lab
{
    public partial class Form_Request_BulkInsert_Template : Form
    {
        public Form_Request_BulkInsert_Template()
        {
            InitializeComponent();

            // CLEAN  
            using (var context = new EntityContext())
            {
                context.EntitySimples.RemoveRange(context.EntitySimples);
                context.SaveChanges();
            }


            // SEED  
            using (var context = new EntityContext())
            {
                context.EntitySimples.Add(new EntitySimple {ColumnInt = 1});
                context.EntitySimples.Add(new EntitySimple {ColumnInt = 2});
                context.EntitySimples.Add(new EntitySimple {ColumnInt = 3});

                context.SaveChanges();
            }


            // TEST  
            using (var context = new EntityContext())
            {
                var list = new List<EntitySimple>();
                list.Add(new EntitySimple {ColumnInt = 10});
                list.Add(new EntitySimple {ColumnInt = 11});
                list.Add(new EntitySimple {ColumnInt = 12});

                context.BulkInsert(list);
            }
        }

        public class EntityContext : DbContext
        {
            public EntityContext() : base("CodeFirstEntities")
            {
            }

            public DbSet<EntitySimple> EntitySimples { get; set; }

            protected override void OnModelCreating(DbModelBuilder modelBuilder)
            {
                modelBuilder.Types().Configure(x =>
                    x.ToTable(GetType().DeclaringType != null
                        ? GetType().DeclaringType.FullName.Replace(".", "_") + "_" + x.ClrType.Name
                        : ""));


                base.OnModelCreating(modelBuilder);
            }
        }

        public class EntitySimple
        {
            public int ID { get; set; }
            public int ColumnInt { get; set; }
            public string ColumnString { get; set; }
        }
    }
}
```

**Comment by EricNex** [comment]
Hi @JonathanMagnan,

The example take out from the project need more time.

The insert target database is oracle database. Does it need to change some configuration?

I had used OracleBulkCopy() before, and test ok, but the function will break the primary key.

**Comment by EricNex** [comment]
Hi @JonathanMagnan,

Is there a version limit of EntityFramework ?

I use the EntityFramework 5.0.0. Is it need higher version?

**Comment by JonathanMagnan** [comment]
Hello @EricNex,

Unfortunately, we do not support Oracle for `EF5` (In fact, we never tested it in this version, so it could certainly be possible), we start to support it starting from `EF6`.

Is it possible for you to upgrade your EF version?

Best Regards,

Jonathan

**Comment by EricNex** [comment]
Hi @JonathanMagnan,

But when I download the EF5, the description is:
Entity Framework: BulkSaveChanges, BulkInsert, BulkUpdate, BulkDelete, and BulkMerge.
Support: SQL Server, SQL Azure, SQL Compact, Oracle, MySQL, SQLite, and PostgreSQL.
This library is NOT free. FREE Trial always available for the current month.

Is the EF version must be 6 so it can support oracle?(mean that EF5 not support oracle?)

And other problem:
sqlserver and other database provider cost is different.
But only one download button, is it also support oracle?

Regards,
EircNex

**Comment by JonathanMagnan** [comment]
Hello @EricNex ,

The text has been modified a few months ago: https://www.nuget.org/packages/Z.EntityFramework.Extensions.EF5/ 

> Is the EF version must be 6 so it can support oracle?(mean that EF5 not support oracle?)
Only EF6 currently support Oracle.

Thank again for letting us know.

Best Regards,

Jonathan
