### ISSUE TITLE
Where have EntityFramework.MappingAPI gone?

### ISSUE THREAD

**Issue by trailmax** [zzzprojects/EntityFramework-Extensions#121]
There was a package EntityFramework.MappingAPI with quite a bit of useful stuff to get internal information out of EF. Now the package with code is marked [unlisted](https://www.nuget.org/packages/EntityFramework.MappingAPI/6.1.0.9), replaced by 2 empty placeholder packages.

In your documentation I don't see any mentions about MappingAPI. Is this gone for good?

**Comment by JonathanMagnan** [comment]
Hello @trailmax ,

Yes, unfortunately, the package is no longer supported.

However, EFE offers a method that's pretty similar and will give you most entity/table information as well.

Could you try:

```csharp
using (var ctx = new CurrentContext())
{
	var model = ctx.GetModel();
}
```

And see if you can get all your information required from the model.

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment]
Some business/marketing and legal reason. It's a little bit complex to write it here ;)

**Comment by trailmax** [comment]
OK, so you (as in EFE organisation) unlisted a good package, actively replaced it with a placeholder and a redirect. Killed publicly available source code that was open at the time (Codeplex repository).
 And you don't care to explain because it is too complex?

**Comment by JonathanMagnan** [comment]
You can always reference the package directly

> Install-Package EntityFramework.MappingAPI -Version 6.1.0.9

In short, we had to take some business decision that would affect people no matter what.

Either close a few libraries that were no longer supported

Either stop to support some free libraries that we support such as:
- Entity Framework Plus
- Entity Framework Effort
- Entity Framework Dynamic Filters
- Html Agility Pack
- .NET Fiddle
- SQL Fiddle
- Etc.

Best Regards,

Jonathan

**Comment by trailmax** [comment]
Stop supporting libraries and actively pushing dummies as nuget updates are different things entirely.

Great way to earn community trust! Have a good life.
