### ISSUE TITLE
Npgsql 4.0 breaking changes: NpgsqlBinaryImporter can't handle Nullable

### ISSUE THREAD

**Issue by tedypranolo** [zzzprojects/EntityFramework-Extensions#122]
As reported here https://github.com/npgsql/npgsql/issues/1965. The fix will be in Npgsql 4.1 (which will be several months away) https://github.com/npgsql/npgsql/pull/1993. In the meantime, can we get a workaround? Thank you.

**Comment by JonathanMagnan** [comment]
Hello @tedypranolo ,

Thank you for reporting. We will look at what can be done on our side meanwhile.

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment]
Hello @tedypranolo ,

Sorry for the long delay, it seems we forget to reply to you.

We tried to reproduce the issue with `Entity Framework` and our library but we didn't successfully reproduce it even when using a decimal column.

Do you think you could provide us with a test project with this issue?

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment]
Hello @tedypranolo ,

This issue will be closed since we had no reply and we are not sure you still have it.

Feel free to reopen if you can provide further information.

Best Regards,

Jonathan
