### ISSUE TITLE
Z.EntityFramework.Extensions.EF4 GetDbTransaction NullReferenceException

### ISSUE THREAD

**Issue by fengwusheng** [zzzprojects/EntityFramework-Extensions#132]
I invoke BulkSaveChanges with MySql and get NullReferenceException.
[NullReferenceException]
at DatabaseExtensions.GetDbTransaction(Database this)
at DbContextExtensions..(BulkOperation )
at Z.EntityFramework.Extensions.EntityBulkOperation`1.(Action`1 )
at DbContextExtensions.[](DbContext , Action`1 )
at DbContextExtensions.[](DbContext this, IEnumerable`1 , Action`1 , List`1 )
at .(DbContext , List`1 , List`1 , Action`1 , Boolean )
at DbContextExtensions.(DbContext this, Boolean , Action`1 , Boolean )

The code (by ILSpy) below not only for SqlConnection. The var connection may be MySqlConnection:

```csharp
// class: DatabaseExtensions in Z.EntityFramework.Extensions.EF4
public static DbTransaction GetDbTransaction(Database @this)
{
    DbConnection connection = @this.Connection;
    if (connection.State != ConnectionState.Open)
    {
        return null;
    }
    // !!! connection may NOT be SqlConnection !!! //
    object value = @this.Connection.GetType().GetProperty("InnerConnection", BindingFlags.Instance | BindingFlags.NonPublic)
        .GetValue(connection, null);
    object value2 = value.GetType().GetProperty("AvailableInternalTransaction", BindingFlags.Instance | BindingFlags.NonPublic).GetValue(value, null);
    if (value2 == null)
    {
        return null;
    }
    return (SqlTransaction)value2.GetType().GetProperty("Parent", BindingFlags.Instance | BindingFlags.NonPublic).GetValue(value2, null);
}
```

**Comment by JonathanMagnan** [comment]
Hello @fengwusheng ,

Thank you for reporting, it should be fixed and released tomorrow.

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment]
Hello @fengwusheng ,

The v3.15.13 has been released with the fix.

Could you let us known with `MySql` provider you are using with `EF4`? We tried on our side but run in some error.

Let me know if everything works as expected.
Best Regards,

Jonathan

**Comment by fengwusheng** [comment]
Hi, I have check the new version.
Only SqlTransaction change to DbTransaction help nothing.
"@this.Connection.GetType()" return MySqlConnection type, and this type has NOT a InnerConnection property.
@this.Connection.GetType().GetProperty("InnerConnection", BindingFlags.Instance | BindingFlags.NonPublic) returns null.
@this.Connection.GetType().GetProperty("InnerConnection", BindingFlags.Instance | BindingFlags.NonPublic).GetValue(connection, null) throw the NullReferenceException.

BTW, I use MySql.6.9.6.0
MySql.Data, Version=6.9.6.0, Culture=neutral, PublicKeyToken=c5687fc88969c44d
MySql.Data.Entity, Version=6.9.6.0, Culture=neutral,  PublicKeyToken=c5687fc88969c44d

**Comment by JonathanMagnan** [comment]
Thank @fengwusheng ,

That's weird, the `v6.9.6.0` has a dependency to `EF6`.  If we add it, the following package is added `MySql.Data.Entity.EF6`

Do you think you could provide us a project sample that enables `MySQL` for EF4 as your project use? It will ensure our next fix will work with your project.

Best Regards,

Jonathan

**Comment by fengwusheng** [comment]
MySql provider v6.9.6.0 for EF4 was downloaded from Oracle and the link has gone now.
You can get the older version from nuget, it can create the same exception as v6.9.6.0 :
https://www.nuget.org/packages/MySql.Data.Entity/6.7.9
https://www.nuget.org/packages/MySql.Data/6.7.9

MySql.Data.Entity, Version=6.7.9.0, Culture=neutral,  PublicKeyToken=c5687fc88969c44d
refer
EntityFramework, Version=4.4.0.0, Culture=neutral,  PublicKeyToken=b77a5c561934e089
(This is the last EF4 version.)

**Comment by fengwusheng** [comment]
I have send the dlls to your email box. Please check info@zzzprojects.com.

**Comment by JonathanMagnan** [comment]
Thank you, we will look at it tomorrow morning.

The Entity Framework `DLL` provided is no `EF4` but `EF5`.

Did we get the wrong DLL?

The Product version is `5.0.0.net40` and the file version is `4.4.20627.0` which exactly correspond to `EF5`: https://www.nuget.org/packages/EntityFramework/5.0.0

Just making sure we will test the right thing.

**Comment by fengwusheng** [comment]
Yes, you are right.
Microsoft call it EF5.0, but the version number is 4.4.20627.0.
EF5.0 DLL for .net4.5 is with version number 5.0.20627.0.
So it's weird. Oracle call this 4.4 version EF4 too as I dit when they release their provider.
No matter what it calls, I have send the dlls to you, hope you can fix the bug finally.

**Comment by JonathanMagnan** [comment]
Thank you,

No that's fine. That explains why my developer didn't success to make it work with EF4.

We will try again with EF5 .NET40

In your case, you will probably need as well to use `Z.EntityFramework.Extensions.EF5` instead since a few lines of code is different in our library between both version.

**Comment by fengwusheng** [comment]
Thanks. 
I notice that Z.EntityFramework.Extensions.EF5 for .NET4.0 refer the EF4.4. It's very good.
I use "AssemblyResolve" to remap the EF version before.
I will test it when you fix Z.EntityFramework.Extensions.EF5 for .NET4.0.

**Comment by JonathanMagnan** [comment]
Hello @fengwusheng ,

The v3.15.18 has been released.

We tested it with `MySQL` and we do not longer get this issue.

Let me know if everything now works as expected.

Best Regards,

Jonathan

**Comment by fengwusheng** [comment]
Thank you. It works now.

**Comment by JonathanMagnan** [comment]
Great ;)

I will close this request.

Best Regards,

Jonathan
