### ISSUE TITLE
Suggestion - Create BulkColumnStoreInsert + BulkColumnStoreMerge extension methods

### ISSUE THREAD

**Issue by jzabroski** [zzzprojects/EntityFramework-Extensions#139]
Following guidance from Microsoft, here: [Columnstore indexes - Data loading guidance](https://docs.microsoft.com/en-us/sql/relational-databases/indexes/columnstore-indexes-data-loading-guidance?view=sql-server-2017)

Note: This is not a high priority for us, but just a potentially generally good feature for your library. You can say to customers that you automatically follow Microsoft guidance.

**Comment by JonathanMagnan** [comment]
Hello @jzabroski ,

Thank you, we will read about this tomorrow probably.

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment]
Hello @jzabroski ,

We will close this request.

I do not believe it will ever happen as it has not been accepted by our architect and the solution was often slower than a traditional table. At this point, I don't think adding more complexity by our library will also be a good idea. 

Best Regards,

Jonathan

**Comment by outinspace** [comment]
Hi @JonathanMagnan, I am trying to use this library to bulk insert into a columnstore table. I understand from your comment that BulkInsert/BulkInsertOptimized were not created with columnstore tables in mind. Is there a better option that you would recommend for the use case of inserting 100k-500k rows into a columnstore table?

**Comment by jzabroski** [comment]
@outinspace  This is marked as closed/completed.  I'd recommend you open a new issue.  You can copy-paste my initial specification idea.
