### ISSUE TITLE
Question: Batch Updates with DB Operations

### ISSUE THREAD

**Issue by Magidiss** [zzzprojects/EntityFramework-Extensions#14]
Hi guys,

I am look for a good lybrary for EF Batch Operations. 

I have a quick question, which I didn't find as an answer on Your Wikis.:

Does Your library supports operation of followed example:

Let's say I have a class:
public class Foo
{
   public int Id { get; set; }
   public int Sort { get; set; }
   public string Name { get; set; }
}

Can I make with Your library some operations like this (Increment):
`context.Foo.Where(e => e.Id == 123).Update(e => new Foo { Sort = Sort + 1 }); `
which is equal to MySQL:
`UPDATE foo WHERE id=123 SET sort=sort+1;`

and this like:
`context.Foo.Update(e => new Foo { Name = Name.Replace("abc", "def") }); `
which is equal to MySQL:
`UPDATE foo SET name=REPLACE(name, 'abc', 'def');`

**Comment by zzzprojects** [comment]
Hello Magidiss,

Currently, FromQueryUpdate is only supported for SQL Server.

However, our free library [Entity Framework Plus](https://github.com/zzzprojects/EntityFramework-Plus) should already support MySQL for EF+ Query Batch Update feature.

We currently need to decide if we want to make this feature fully free or we want to continue to support it (so supporting MySQL) in our PRO version. 

Please, let me know if that answer to your question

**Comment by Magidiss** [comment]
Thank You for the quick answer.

Do You plan to implement FromQueryUpdate functionality for the MySQL?

I saw, that Your Entity Framework Plus supports Batch Update, but does it support FromQueryUpdate?

**Comment by zzzprojects** [comment]
EF+ Batch Update is the same feature as EFE FromQueryUpdate. They both do the same thing but with a different name.

As I said, we need to take the decision very soon to know if we continue to support "FromQueryDelete" and "FromQueryUpdate" in Entity Framework Extensions or we only support it in our free library EF+. We will for sure try to support all major providers if we continue to support it in EFE Library.

Unfortunately, for now, we try to pause the development to complete the documentation re-writing, so we recommend you trying EF+ version.

**Comment by zzzprojects** [comment]
Closing Comment: Question answered
