### ISSUE TITLE
Bulk-merge attempting to insert duplicate data with IncludeGraph

### ISSUE THREAD

**Issue by kelseyabreu** [zzzprojects/EntityFramework-Extensions#145]
Hey guys,

Im trying to use the bulk-merge extension and I keep getting this error:
![exception](https://user-images.githubusercontent.com/1827665/44291046-dc788b80-a249-11e8-8599-c8698edc8d10.png)

I then decided to see what was being outputed in SQL and I see this query giving me the error that the exception throws:
![sqlprofiler](https://user-images.githubusercontent.com/1827665/44291047-dc788b80-a249-11e8-96bf-62c2dff97e40.PNG)

I found that really strange since the object I am trying to update, a DriverPlan, does in fact have children that contain 2 of the same StopAction, but it's intended. 

![debugtree](https://user-images.githubusercontent.com/1827665/44291045-dc788b80-a249-11e8-81cc-e6004e41e5c6.png)

Small things to note is that I turned off ProxyCreationEnabled and LazyLoadingEnabled.

So the main questions are these:

1. If there is only 2 objects, why is it trying to insert 3 (like you see in the SqlProfiler picture)? How does it generate that query?
2. What exactly does Bulk-Merge do codewise? Does it look at the DbContext at all? Does it create the bulk query based on the EntityStates? Does it call SaveChanges?

Also, is there a possibility that bulk-merge is going up the parent of the DriverPlan, Plan, and reading the other jobs which include more StopActions?

**Comment by JonathanMagnan** [comment]
Hello @kelseyabreu ,

When you use `IncludeGraph = true`, everything is included.

Under the hood, a new context is created and we use the `AddRange` method before retrieving object to `Merge` from the ChangeTracker.

That error happens often when people create a new object for the same `ID` instead of re-using an existing one. So for the same ID, multiple object instance exists which should not happen.

We normally recommend people to use a dictionary when they create the object on their side and retrieve the same object

Here is an example:

```csharp
public static class DictionaryExtensions
{
    public static TValue GetOrAdd<TKey, TValue>(this IDictionary<TKey, TValue> @this, TKey key, Func<TKey, TValue> valueFactory)
    {
        if (!@this.ContainsKey(key))
        {
            @this.Add(new KeyValuePair<TKey, TValue>(key, valueFactory(key)));
        }

        return @this[key];
    }
}

private static List<Top> CreateLevel1Data()
{
    var level1_1 = new Level1 {Id = 1, Name = "Level1 1"};
    var level1_2 = new Level1 {Id = 2, Name = "Level1 2"};
    var level1_3 = new Level1 {Id = 3, Name = "Level1 3"};

    Dictionary<int, Top> topsDictionary = new Dictionary<int, Top>();
    var top1 = topsDictionary.GetOrAdd(1, x => new Top {Id = 1, Name = "Top 1", Level1s = new List<Level1>()});
    top1.Level1s.AddRange(new List<Level1> { level1_1, level1_2 });

    var top2 = topsDictionary.GetOrAdd(1, x => new Top { Id = 1, Name = "Top 1", Level1s = new List<Level1>() });
    top1.Level1s.AddRange(new List<Level1> { level1_2, level1_3 });

    var list = new List<Top> {top1, top2};

    return list;
}
```

Let me know if that explains the cause and if this solution can be used on your side.

Best Regards,

Jonathan

**Comment by kelseyabreu** [comment]
@JonathanMagnan Thanks for quickly getting back! That would explain a lot.

However, idk how I would use that

**Comment by kelseyabreu** [comment]
That does explain a lot. 

I think the problem happens when using Automapper, as it might be breaking the references and creating new objects.

What do you think would be the best way to check if "Everything" in that object, that's passed to BulkMerge, is using the objects in context?

**Comment by JonathanMagnan** [comment]
Hello @kelseyabreu ,

The answer highly depends on how you use `AutoMapper` and `EFE`.

Do you think you could provide us a project sample? We will be happy to look at it to provide some recommendations.

You can send it to info@zzzprojects.com

**Comment by kelseyabreu** [comment]
Hey @JonathanMagnan, I ended up making a method where it nulls parents Navigation properties, but not their ID and it's working nicely!

next question i'd like to ask is, now that I've removed the parents Navigation property amd BulkMerged nicely, how should I load the objects again assuming they all exist in the Datacontext

**Comment by JonathanMagnan** [comment]
That's a very good question.

I believe all `plan` is not attached to the context? If you don't have a lot of plan, I would suggest to simply retrieve it `Where(x => listIds.Contains(x.PlanId))` and Entity Framework should handle all relations by itself but perhaps you cannot do it?

We are supposed to look very soon more deeply at `GraphDiff` to either redo it or improve it. Perhaps that will answer to your situation as well.

**Comment by kelseyabreu** [comment]
heh funny thing is, I tried that. But the DbContext actually references the same object I nullified the parents to, so i receive the same object.

I think I might have to recursively check each navigation property, make sure i havent traversed it, and compare to see if i have the object in the context. 

Maybe that could be something to implement? Pass an object in, and it tries to connect object and it's children that are in context. The two modes could be context wins or your object wins

**Comment by kelseyabreu** [comment]
Hey @JonathanMagnan, been doing more trial and error and I'm doing really good. However one thing still confuses me, in the following picture you will see that Job, Subscriber, and the StopAction navigation property all are nulled out but have their Ids. After the merge only Job and Subscriber get set back. 

Would you happen to know why it might be doing this?

![What's Happening?](https://user-images.githubusercontent.com/1827665/44430025-70f32e80-a567-11e8-9f3c-6e2e34d4368b.png)

**Comment by kelseyabreu** [comment]
Understood. I decided, for now, to just use BulkSaveChanges since it works perfectly out of the box. When there's more time, ill continue striving to get BulkMerge to work.

Thanks @JonathanMagnan for all the help

**Comment by Velocity540** [comment]
@kelseyabreu 

How did you get around this issue in the end?  I am facing the same problem. I have an entity, that has a collection of sub-entities. if I leave IncludeGraph out of the Bulk Merge the main entity is added/updated as one might expect.

if I set IncludeGraph = true, seems as if the Extensions are always trying to insert a new record. Should be  straightforward use case I would think.
