### ISSUE TITLE
UpdateFromQuery not working with subqueries

### ISSUE THREAD

**Issue by LuisNebreda** [zzzprojects/EntityFramework-Extensions#148]
HI,

We need to update a large list of entities with the sum of their childs spends:

```
db.Set<CampaignMediaPlan>()
                .Where(x => x.CampaignId == Id)
                .UpdateFromQuery(x => new CampaignMediaPlan()
                {
                    PlannedSpend = x.CampaignMediaSpends.Sum(y => y.PlannedSpend)
                });
```

With this code, we hope something like:

```
MERGE INTO [Trading].[CampaignMediaPlans] AS DestinationTable
USING
( SELECT 
    [Extent1].[Id] AS [Id]
    FROM [Trading].[CampaignMediaPlans] AS [Extent1]
    WHERE ([Extent1].[CampaignId] ='D992491A-0715-4C82-9CE5-B7D0F01DBB76')
) AS StagingTable
ON StagingTable.Id = DestinationTable.Id
WHEN MATCHED THEN
    UPDATE
    SET     [PlannedSpend] =  (select SUM(PlannedSpend) FROM [Trading].[CampaignMediaSpends] AS [Extent2]
		WHERE ([Extent2].[CampaignMediaPlanId] = DestinationTable.Id) );
```

But, instead of that we have a 

> System.Data.SqlClient.SqlException: The multi-part identifier "Project1.C1" could not be bound.

Besause it cannot build the subquery, there is something I can do to skip this error?

**Comment by JonathanMagnan** [comment]
Hello @LuisNebreda ,

Do you think you could parse the query in error?

We have fixed some similar issue that's caused about how the SQL query is generated, but we need the query in error to determine if we can do something or not.

Best Regards,

Jonathan

**Comment by LuisNebreda** [comment]
This is the generated query:

```
exec sp_executesql N'MERGE INTO [Trading].[CampaignMediaPlans] AS DestinationTable
USING
(
SELECT 
    [Extent1].[Id] AS [Id]
    FROM [Trading].[CampaignMediaPlans] AS [Extent1]
    WHERE ([Extent1].[CampaignId] = @p__linq__0)
) AS StagingTable
ON StagingTable.Id = DestinationTable.Id
WHEN MATCHED THEN
    UPDATE
    SET     [PlannedSpend] =  
    [Project1].[C1]
;',N'@p__linq__0 uniqueidentifier',@p__linq__0='00000000-0000-0000-0000-000000000000'
```

As you could see, the subquery was missing

**Comment by JonathanMagnan** [comment]
Thank a lot,

We will look at it,

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment]
Hello @LuisNebreda ,

This issue will be closed as it's currently too hard to solve without having side impact.

We already planned to re-write fully this feature later this year, so we will keep it open in our internal issue tracker and hope that we will successfully fix it.

Best Regards,

Jonathan

**Comment by virzak** [comment]
I'm running into a similar issue. Just wondering if this has ever been addressed?

https://dotnetfiddle.net/Kz3nGJ
Not sure if this has ever been addressed between 2019 and now.

Additionally I wonder if it's possible to generate Update with Join using UpdateFromQuery ?

```sql
UPDATE 
    t1
SET 
    t1.c1 = t2.c2,
    t1.c2 = expression,
    ...   
FROM 
    t1
    [INNER | LEFT] JOIN t2 ON join_predicate
WHERE 
    where_predicate;
```

**Comment by JonathanMagnan** [comment]
Hello @virzak ,

For the `Join`, that is something we believe that we might implement during the summer. We have a few requests to complete before but that's currently in our plan to allow something similar to this.

My developer also told me that this kind of issue is not fixed but the code he wants to implement to allow the `Join` will fix this kind of case.

So in short, that's currently not supported but that's something we are looking forward to during the summer.

Best Regards,

Jon

**Comment by virzak** [comment]
@JonathanMagnan That would be super helpful.

Yes, `Join` and indeed cover all cases.
My fiddle contains one possible syntax.

Let me know if I can help with beta testing or a PR. The code base I'm working on contains a few instances where raw sql could be replaced with UpdateFromQuery with a Join.

**Comment by virzak** [comment]
Any update on `Join`?

**Comment by virzak** [comment]
Checking in a few years later. Any plans?

**Comment by JonathanMagnan** [comment]
Hello @virzak ,

I will speak with my employee next week about this.

I know for December, we are focusing on the documentation the whole month but there is several changes we want to improve on this feature in early 2025, so I will be able to give you a better update very soon.

Best Regards,

Jon
