### ISSUE TITLE
Use BulkInsert,not support  associated tables

### ISSUE THREAD

**Issue by cdefg198** [zzzprojects/EntityFramework-Extensions#15]
eg: 
![qq 20160901104651](https://cloud.githubusercontent.com/assets/3070114/18153641/75c211b4-7031-11e6-8698-e600451e5be3.png)

var tableAs = new List<TableAs>();
                for (var i = 0; i < 1000; i++)
                {
                    var tableB = new TableB { BName = "" };
                    var tableA = new TableA();
                    tableA.TableBs = new List<TableBs>();
                    tableA.TableBs.Add(tableB);
                    tableAs.Add(tableA);
                }
                BulkInsert(TableAs);

Only Insert TableA data,can't insert TableB data.
but this article [https://www.infoq.com/news/2014/12/EF-Bulk-Operations](https://www.infoq.com/news/2014/12/EF-Bulk-Operations)   has

> This method supports all kinds of associations and entity types (TPC, TPH, and TPT).

Why is this?

**Comment by zzzprojects** [comment]
BulkInsert does not save related entities or use change tracker to be as fast as possible. However, it supports navigation properties and all inheritance.

To save and include related entities, try BulkSaveChanges instead

```csharp
ctx.TableAs.AddRange(tableAs);
ctx.BulkSaveChanges
```

BulkSaveChanges work exactly like SaveChanges but faster!

Let me know if that answer to your question.

**Comment by cdefg198** [comment]
@zzzprojects  
That's cool.Inculde associated tables data,total rows is 50000,the local work use time 15s.But azure sql database use time 7min. /(ㄒoㄒ)/~~
Thank you very much.

**Comment by zzzprojects** [comment]
Hello @cdefg198,

I'm not sure if your last sentence was about reporting an issue with SQL Azure taking 7min or you was simply telling it's now taking 15s in local.

Let me know if you are currently reporting a new issue or we can close this one.

Best Regards,

Jonathan

**Comment by cdefg198** [comment]
@zzzprojects can close this case,Thank you very much.

**Comment by zzzprojects** [comment]
Closing: The question has been answered.
