### ISSUE TITLE
BulkInsert fails with exception 'SQLite Error 19: 'UNIQUE constraint failed: SourceFile.Id'.' (SQLite provider)

### ISSUE THREAD

**Issue by marius-stanescu** [zzzprojects/EntityFramework-Extensions#151]
When the BulkInsert method is run on a newly created empty table, it fails with the exception `'SQLite Error 19: 'UNIQUE constraint failed: SourceFile.Id'.'`. But if the table is not empty, then the command doesn't fail. It seems that if there was a row previously inserted then the command runs ok.

**Comment by JonathanMagnan** [comment]
Hello @marius-stanescu ,

We tried it on our side and everything works fine.

Here are a few questions to help us:
- What version of `Entity Framework` are you using?
- Is the `SaveChanges` work when the table is empty

It's possible for you to reproduce this error in a simple project test?

Best Regards,

Jonathan

**Comment by marius-stanescu** [comment]
Hello @JonathanMagnan,

I reproduced the error in a simple project.
NuGet package versions:

- Microsoft.EntityFrameworkCore (2.1.3)
- Microsoft.EntityFrameworkCore.Design (2.1.3)
- Microsoft.EntityFrameworkCore.Sqlite (2.1.2)
- Z.EntityFramework.Extensions.EFCore (2.1.31)

```csharp
using Microsoft.Data.Sqlite;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Design;
using System;
using System.Collections.Generic;
using Z.EntityFramework.Extensions;

namespace EntityFrameworkExtensionsTest
{
    internal static class Program
    {
        private static void Main(string[] args)
        {
            EntityFrameworkManager.ContextFactory = _ => new FileCopyContext();

            using (var context = new FileCopyContext())
            {
                context.BulkInsert(new List<SourceFile>
                {
                    new SourceFile
                    {
                        RelativePath = "test",
                    },
                    new SourceFile
                    {
                        RelativePath = "test 2",
                    },
                });
            }

            Console.ReadLine();
        }
    }

    public class SourceFile
    {
        public int Id { get; set; }

        public string RelativePath { get; set; }

        public ulong SizeInBytes { get; set; }

        public int SourcePathId { get; set; }
    }

    public class FileCopyContext : DbContext
    {
        private readonly bool _created;

        public FileCopyContext()
        {
            if (!_created)
            {
                Database.Migrate();
                _created = true;
            }
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<SourceFile>()
                .HasKey(sf => sf.Id);
            modelBuilder.Entity<SourceFile>()
                .Property(sf => sf.RelativePath)
                .IsRequired();
            modelBuilder.Entity<SourceFile>()
                .HasIndex(sf => sf.RelativePath)
                .IsUnique();

            base.OnModelCreating(modelBuilder);
        }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            var builder = new SqliteConnectionStringBuilder
            {
                DataSource = @"C:\EntityFrameworkExtensionsTest\testDb.db",
                Cache = SqliteCacheMode.Default,
            };
            optionsBuilder.UseSqlite(builder.ConnectionString);

            base.OnConfiguring(optionsBuilder);
        }
    }

    public class FileCopyContextFactory : IDesignTimeDbContextFactory<FileCopyContext>
    {
        public FileCopyContext CreateDbContext(string[] args)
        {
            return new FileCopyContext();
        }
    }
}
```

**Comment by JonathanMagnan** [comment]
Hello @marius-stanescu ,

Thank for the example, however, my developer was not able to reproduce it.

He first thought he did it but since the column was not autoincrementing, the `Id` value was required,.

When he specify it, everything worked perfectly. He tried also with an autoincrement column but everything worked perfectly.

Is your column have the autoincrement attribute? It's possible that your table has a trigger that causes this?

**Comment by marius-stanescu** [comment]
The column is already set to autoincrement. Here is a screenshot with the table schema:
![image](https://user-images.githubusercontent.com/40517717/46333443-113d7800-c629-11e8-8454-62e6a5a4072d.png)

Did he try to reproduce the problem using the code I provided? Did he generate the database using migrations, as I did? Maybe it's related to that somehow.

Thank you.

**Comment by JonathanMagnan** [comment]
Hello @marius-stanescu ,

Thank you for all your help. We successfully reproduced it.

The v2.1.33 has been released

Let me know if everything works now correctly when there is no row.

Best Regards,

Jonathan

**Comment by marius-stanescu** [comment]
Hello,

Your welcome. Everything works fine now, thank you.
