### ISSUE TITLE
Error: 0013

### ISSUE THREAD

**Issue by RingJp** [zzzprojects/EntityFramework-Extensions#158]
Hi
we execute Z.EntityFramework.Extensions BulkInsert  but not Success  this is Error.  and this Error is Unexpected events.
Error: 0013: Oops! A general error has occurred. Please report the issue including the stack trace to our support team: info@zzzprojects.com

Is there something I can do to fix this, or is it a bug?

**Comment by JonathanMagnan** [comment]
Hello @RingJp ,

This error happens when an `illegal license` is used with our library.

If that's the case, please make sure to use a `legal license`.

I have answered you via email with some more information.

Let me know if that answer correctly to your question.

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment]
Hello @RingJp ,

Could you contact us directly info@zzzprojects.com and providing us your license or your company name. We will verify with your license.

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment]
Hello @RingJp ,

This issue will be closed since we haven't heard back from you.

Feel free to reopen if you can provide further information.

Best Regards,

Jonathan
