### ISSUE TITLE
IDbCommandInterceptor or alike for logging?

### ISSUE THREAD

**Issue by ddeml** [zzzprojects/EntityFramework-Extensions#159]
Hi Jonathan,

it's me again, the "Async" guy. I am now attempting to log all commands sent to the database and added a IDbCommandInterceptor. However, if i observed it correctly, the commands sent through the Execute...Async() methods are not forwarded to the interceptor. Is there an existing feature that allows me to intercept the commands that is sent to the database from the extension methods?

In particular, I would like to investigate the case where it seems that I still have the issue that sometimes, the DbContext.Database.CommandTimeout is still not recognized. I seem to experience this with public static Task<int> DatabaseExtensions.ExecuteNonQueryAsync(this Database @this, Action<DbCommand> commandFactory, CancellationToken cancellationToken = default(CancellationToken)); from Z.EntityFramework.Extensions, Version=3.16.7.0.

But as I would like to log all commands, I am seeking for this feature regardles of this particular issue...

Best regards - Richard

**Comment by JonathanMagnan** [comment]
Hello again Richard ,

We will look if that's possible to do it.

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment]
Hello @Jon,

This issue will be closed since it has been completed.

Feel free to reopen it if you feel otherwise.

Best Regards,

Jonathan

**Comment by ddeml** [comment]
Hi Jonathan,

yes, it works as expected, thank you very much! :)

Best regards – Richard

Von: Jonathan Magnan <notifications@github.com>
Gesendet: Dienstag, 6. November 2018 02:28
An: zzzprojects/EntityFramework-Extensions <EntityFramework-Extensions@noreply.github.com>
Cc: Hafner, Richard <hafner@hafner-software.de>; Author <author@noreply.github.com>
Betreff: Re: [zzzprojects/EntityFramework-Extensions] IDbCommandInterceptor or alike for logging? (#159)


Hello Richard,

The v3.16.10 has been released.

The support for IDbCommandInterceptor has been added to all execute method.

Let me know if everything is working as expected.

Best Regards,

Jonathan
