### ISSUE TITLE
Support for EF Core 2.1 Value Conversion?

### ISSUE THREAD

**Issue by will-heger** [zzzprojects/EntityFramework-Extensions#162]
https://docs.microsoft.com/en-us/ef/core/modeling/value-conversions

I have several ".HasConversion" options declared in my model, but I'm getting an Exception where, for example, it says that it cannot convert LocalDate to DateTime without an IConvertible interface.

These conversions work ok within EF Core.  Is this not yet supported within EntityFramework Extensions?

**Comment by JonathanMagnan** [comment]
Hello @will-heger ,

Thank you for reporting. It might not be supported yes in our library but we will look at it probably today.

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment]
Hello @will-heger ,

Sorry for the delay, this request has been more complex on our side than we thought.

The v2.1.39 has been released

Value conversion should now be correctly supported. Let me know if everything works as expected.

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment]
Hello @will-heger ,

This issue will be closed since it has been resolved.

Feel free to reopen it if you feel otherwise.

Best Regards,

Jonathan

**Comment by will-heger** [comment]
Hi @JonathanMagnan,

My client needs to decide to re-introduce bulk insert before I can report back on whether it works.   I wish it were otherwise, but until then, I'll be waiting for the ticket to be re-opened.

I hope I get to use extensions on a new project if it stalls here.

Thanks,
-Will

**Comment by JonathanMagnan** [comment]
Thank for your for the follow up ;)

**Comment by cpwood** [comment]
Just confirming that I had the same problem and that updating to the latest version has fixed it for me.
