### ISSUE TITLE
Provide a way to pass in a predefined set of options to bulk operation methods

### ISSUE THREAD

**Issue by mmiller678** [zzzprojects/EntityFramework-Extensions#165]
Currently there doesn't appear to be a way to specify a predefined set of options when calling bulk methods.  

Here is what we would like to do:

```
//Do this is some concrete repository
var myOptions = new BulkOperation<MyEntityType>();

//Do this is some abstract generic repository
context.BulkMerge(entities, myOptions); 
```
 This doesn't appear to be an overload that takes an instance of BulkOperation<T>.  Is this something you can add?  Ideally this would be for all bulk operations not just merge.

**Comment by JonathanMagnan** [comment]
Hello @mmiller678 ,

This issue will be closed since it has been answered.

Feel free to reopen it if you feel otherwise.

Best Regards,

Jonathan
