### ISSUE TITLE
what's the limt of FREE trial version

### ISSUE THREAD

**Issue by jrt324** [zzzprojects/EntityFramework-Extensions#17]
I want to know about EntityFramework-Extensions : what's the limit of FREE trial version? or if i still use the trial version, is there the time expiration limit ?
because i will using it in my production environment

**Comment by zzzprojects** [comment]
The FREE trial expires at the end of every month.

We always try to release a new version with a trial for the next month before it expires. By example, we released today the trial for October.

The FREE trial let you evaluate our product until you are ready to go in production. You shouldn't use a trial in a production environment.

Let me know if I answered to your question correctly.

**Comment by magicyu90** [comment]
Hi, I want to know is that possible to buy just some functions for ef.extensions not all, in our project I just need bulk insert and bulk update, so 599$ is a little high for our company, thanks for your answers in advance.

**Comment by zzzprojects** [comment]
Hello @magicyu90,

We offer bundle price when purchasing more than one product but unfortunately, we do not offer a discount when using only a subset of a product feature.

I believe you bought this product this morning so I will close this question

Best Regards,

Jonathan
