### ISSUE TITLE
BulkInsert - error by using reserved word - Order entity/table

### ISSUE THREAD

**Issue by hegviktor** [zzzprojects/EntityFramework-Extensions#172]
Hi,

I want to insert to Order table with BulkInsert extension.

There is a bug, because the table name does not contains [] characters in BulkInsert low level SQL script - i think.

Now it is using Order name of the table but it should use [Order] table name because the first one is a reserved word in SQL.

How can I fix it or insert to Order table with this extension?
Is there any table mapping option?

Thanks,
Viktor

**Comment by JonathanMagnan** [comment]
Hello @hegviktor ,

This case should already work. See this online example: https://dotnetfiddle.net/5QRpJw

Which provider are you using?

Best Regards,

Jonathan

**Comment by hegviktor** [comment]
Hello Jonathan, 

Thank you for your prompt answer.

I use MSSQL and latest Entity Framework. How can I look that what provider I using?

It does not work yet :(

Exception Message:
**Incorrect syntax near the keyword 'Order'.
Incorrect syntax near the keyword 'AS'.**

I use singular by table names: 
public DbSet<Order> Order { get; set; }

And use 	[Table("Order")] attribute.

Thanks,
Viktor

**Comment by JonathanMagnan** [comment]
Just to make sure before we investigate more on our side, are you using `Entity Framework Extensions` for `Bulk Insert` or another third party library? (It happens sometimes that people report us bug from other libraries)

**Comment by hegviktor** [comment]
Ohh, this product is not yours. Apologies. I thought that these are the same. Sorry.

https://github.com/andreisabau/EFBulkInsert

**Comment by JonathanMagnan** [comment]
No problem ;)

If you wish to use our library, at least you already know that we support those scenarios.

Best Regards,

Jonathan

**Comment by hegviktor** [comment]
Now I am using your BulkInsert Extension. 

Older one:
https://www.nuget.org/packages/EntityFramework.BulkInsert-ef6/

But it throw an Object null reference exception.

**Comment by JonathanMagnan** [comment]
That's why you should use `Entity Framework Extensions` ;)

We support all scenarios including:
- All inheritances (TPC, TPH, TPT)
- All relationships
- All operations (Insert, update, delete, merge)
- Table reserved keyword (table name escape)
- Etc

Which others third party library doesn't.

The EF.BulkInsert-EF6 is no longer supported since 2014

Best Regards,

Jonathan

**Comment by hegviktor** [comment]
Entity Framework Extensions Bulk Insert is working well. Cool. Thanks.

BulkInsert is free or later will be disabled after install?

Viktor

**Comment by JonathanMagnan** [comment]
Entity Framework Extensions is not free. The trial will stop at the end of the month.

The trial can be extended for several months by downloading the latest version at the beginning of every month.

So for personal use, you can easily indefinitely use it by downloading the library once per month,
