### ISSUE TITLE
BulkMerge using Shadow Property?

### ISSUE THREAD

**Issue by matthew-horne** [zzzprojects/EntityFramework-Extensions#174]
Is it possible to use BulkMerge with a shadow property FK?  In a one to many relationship the "many" side has a navigation property back to the "one" side using an entity property and not directly exposing the foreign key.  

I need to build a ColumnPrimaryKeyExpression that consists of another field as well as the foreign key.  Something like this:

options.ColumnPrimaryKeyExpression = image => new {image.Hotel.Id, image.Priority};

The above does not work.  From what I understand EF creates a shadow property that holds the FK.  Is it possible to create valid expression key given the above?

Thanks,
Matt

**Comment by JonathanMagnan** [comment]
Hello @matthew-horne ,

It seems there is no easy way on our side to do this at the moment.

We will look at it and implement a solution.

Do your column name is named "HotelId" in your table?

Best Regards,

Jonathan

**Comment by matthew-horne** [comment]
Hi Jonathan - 

Thanks for looking into it.  Yes, the FK is called HotelId.

Matt

**Comment by matthew-horne** [comment]
Hi Jonathan - 

Just checking in to see if you had any luck looking into this issue.

Thank you,
Matt

**Comment by JonathanMagnan** [comment]
Hello @matthew-horne ,

Sorry for the very late reply.

I talked with my developer and the answer will depend on how you have mapped this `Shadow Property`.

For example, in the following case: https://dotnetfiddle.net/4W9fcV

It was required to add all `Images` in the `ChangeTracker`. `BulkMerge` normally doesn't use it but in this case, due to how we coded the logic to handle `Shadow Property`, it was necessary.

If that's not your case, it's possible to provide us with an example of how you make your map? I will make sure we answer you as soon as possible this time.

**Comment by JonathanMagnan** [comment]
So similar to this new Fiddle example: https://dotnetfiddle.net/KfVuLU ?

>  Is this change in the current release?

I'm not sure to understand the question

**Comment by matthew-horne** [comment]
Sorry, I just mean that I wasn't sure if you had to make changes to your library to support this.

Since the records are coming from CSV and I will not have the full hotel, the use case is more like this which works OK in your fiddle sample.

Does this look like a valid approach?
```

using (var ctx = new CurrentContext())
{
	var images = new List<Image>();

	Hotel hotel2 = new Hotel();
	hotel2.Id = 1;  // read from CSV file
			
	for (var i = 0; i < 1; i++)
	{
		images.Add(new Image {Name = "New_Image_" + i, Hotel = hotel2, Priority = i});
	}
	ctx.Images.AddRange(images);
	ctx.BulkMerge(images, options => options.ColumnPrimaryKeyExpression = image => new {image.Hotel.Id, image.Priority});
			
	FiddleHelper.WriteTable(ctx.Images);
}
```

**Comment by JonathanMagnan** [comment]
> Since the records are coming from CSV and I will not have the full hotel

In this case, you will need to also use the `ColumnInputExpression` option

```csharp
ctx.BulkMerge(images, options => {
	options.ColumnInputExpression = image => new { image.Hotel.Id, image.Priority, image.Name };
	options.ColumnPrimaryKeyExpression = image => new {image.Hotel.Id, image.Priority};
});
```
