### ISSUE TITLE
Find how many rows were inserted

### ISSUE THREAD

**Issue by marius-stanescu** [zzzprojects/EntityFramework-Extensions#175]
Is there any way to find how many rows were inserted when executing a `BulkInsert` with `InsertIfNotExists = true`?

_I am using the SQLite provider._

**Comment by JonathanMagnan** [comment]
Hello @marius-stanescu ,

Unfortunately, we don't provide yet the number of the row inserted or row affected information.

There is currently no short-term plan to provide this information but that's for sure something we will look when we will refactor the library and all SQL generated behind.

Let me know if that answer to your question.

Best Regards,

Jonathan

**Comment by marius-stanescu** [comment]
Thanks, @JonathanMagnan. Yes, it does answer the question.

I guess I'll have to find some workaround until this will be implemented.
