### ISSUE TITLE
Entity Framework Cache issue with BulkSaveChanges

### ISSUE THREAD

**Issue by MounaMouna88** [zzzprojects/EntityFramework-Extensions#176]
Hello,

I'm using EF6 + 2nd Level Cache for Entity Framework 6.1 (EFCache). And i use BulkSaveChanges (Z.EntityFramework Extension) to save my changes.

Problem : I get a value from my database and display it, i make changes to it, then savechanges. In my IHM, i got the old values => no update in the IHM but the database it's OK.
After 2 minutes (absoluteExpiration time of then EFCache) the data is updated.
It was working with SaveChanges of Entity framewok. When i replaced SaveChanges  by BulkSaveChanges, I have got this problem.

The cache of Entityframework it's not updated. How can i avoid this problem?

I tried to refresh the entities by doing this:

```csharp
            var refreshableObjects = this._dbContext.ChangeTracker.Entries().Select(c => c.Entity).ToList();
            var ctx = ((IObjectContextAdapter)this._dbContext).ObjectContext;
            ctx.Refresh(RefreshMode.StoreWins, refreshableObjects);

            foreach (DbEntityEntry entry in refreshableObjects)
            {
                (this._dbContext).Entry(entry.Entity).Reload();
                (this._dbContext).Entry(entry.Entity).State = System.Data.Entity.EntityState.Modified;
                (this._dbContext).GetObjectContext().Refresh(RefreshMode.StoreWins, entry.Entity);
            }
```

And Detatch the entities:

```csharp
            foreach (var entity in this._dbContext.ChangeTracker.Entries())
            {
                entity.State= System.Data.Entity.EntityState.Detached;
            }
```

But it still doesn't work.
Thank you

For information this is the cache code i use:

```csharp
if (Boolean.TryParse(efCaching, out useCaching))
                {
                    if (useCaching)
                    {
                        var transactionHandler = new CacheTransactionHandler(new InMemoryCache());
                        AddInterceptor(transactionHandler);

                        var cachingPolicy = new CustomCachingPolicy();
                        
                          Loaded +=
                          (sender, args) => args.ReplaceService<DbProviderServices>(
                            (s, _) => new CachingProviderServices(s, transactionHandler,
                              cachingPolicy));
                    }
                }


       protected override void GetExpirationTimeout(ReadOnlyCollection<EntitySetBase> affectedEntitySets, out TimeSpan slidingExpiration, out DateTimeOffset absoluteExpiration)
        {
            absoluteExpiration = DateTimeOffset.UtcNow.AddSeconds(120);
            slidingExpiration = TimeSpan.FromSeconds(120);
        }
```

And to save changes i use:

```csharp
this._dbContext.BulkSaveChanges();
```

**Comment by JonathanMagnan** [comment]
Hello @MounaMouna88 ,

There is no interceptor in our library, so it currently doesn't support the `EFCache` library by default.

What it looks is that you need to invalid set:
https://github.com/moozzyk/EFCache/blob/24898cb719d6c37fe9515b4a319d878abbf9041b/EFCache/CacheTransactionHandler.cs#L51-L54

The easiest might be to create and set a new whole cache using reflection (so all item will be refreshed): https://github.com/moozzyk/EFCache/blob/24898cb719d6c37fe9515b4a319d878abbf9041b/EFCache/CacheTransactionHandler.cs#L17

Let me know if one of those solution might work for you.

Best Regards,

Jonathan

**Comment by MounaMouna88** [comment]
Thanks for the feedback.

For information, we have purchased the library : we have a license name and a license key. So, if there is another way to report the issue, please let me know it.

How can i invalid set ? i check the two links given but  i don't know how to implement the solutions suggested.

In have in my code, one class that heritate from DbConfiguration:


     public class EBudgetDbConfiguration : DbConfiguration
        {
            public EBudgetDbConfiguration()
            {
               string efCaching = ConfigurationManager.AppSettings["EFCaching"];
               if (!String.IsNullOrWhiteSpace(efCaching))
               {
                   bool useCaching;
                   if (Boolean.TryParse(efCaching, out useCaching))
                  {
                      if (useCaching)
                      {
                          var transactionHandler = new CacheTransactionHandler(new DacheCacheProvider());
                          AddInterceptor(transactionHandler);
                          var cachingPolicy = new CustomCachingPolicy();
                        
                Loaded +=
                    (sender, args) => args.ReplaceService<DbProviderServices>(
                    (s, _) => new CachingProviderServices(s, transactionHandler,
                              cachingPolicy));
	      }
	   }
	   }
	   }
	    } 

and my method Commit:

        public void Commit()
        {
            List<AuditEntry> auditEntries = new List<Z.BulkOperations.AuditEntry>();
            this._dbContext.BulkSaveChanges(options =>
                 {
                     options.UseAudit = true;
                     options.BulkOperationExecuted = bulkOperation => auditEntries.AddRange(bulkOperation.AuditEntries);
                 }) ;
	}


how can i call the method InvalidateSets?

Best Regards.

**Comment by JonathanMagnan** [comment]
Hello @MounaMouna88 ,

One way to easily to it is to reset the cache.

Online example: https://dotnetfiddle.net/wrh6Jo

```csharp
public static void ResetCache()
{
	// use reflection for call method Purge to remove all item from cache. 

	var cacheField = EBudgetDbConfiguration.TransactionHandler.GetType()
		.GetField("_cache", BindingFlags.NonPublic | BindingFlags.Instance);

	var cache = cacheField.GetValue(EBudgetDbConfiguration.TransactionHandler);


	var purgeMethod = cache.GetType().GetMethod("Purge", BindingFlags.Public | BindingFlags.Instance, null, new Type[] { typeof(Boolean) }, null);
	purgeMethod.Invoke(cache, new[] { (object)true });
}
```

_(You can probably do it with a code cleaner if you have access to the original memory cache you are using)_

Doing it by set or by entry could probably be possible but way more complex since our library doesn't support other third party libraries.

Let me know if this example solve your issue or not.

Best Regards,

Jonathan

**Comment by MounaMouna88** [comment]
Hello @JonathanMagnan,

Thank you for the help and the additional information. 

I tried the solution below and it works for me.

I create a new method in my EBudgetDbConfiguration class: InvalidateSets that call InvalidateSets of the TransactionHandler as shown below:

    public class EBudgetDbConfiguration : DbConfiguration
    {
        public static CacheTransactionHandler TransactionHandler { get; set; }
        public EBudgetDbConfiguration()
        {
           string efCaching = ConfigurationManager.AppSettings["EFCaching"];


            if (!String.IsNullOrWhiteSpace(efCaching))
            {
                bool useCaching;

                if (Boolean.TryParse(efCaching, out useCaching))
                {
                    if (useCaching)
                    {
                        TransactionHandler = new CacheTransactionHandler(new InMemoryCache());
                        AddInterceptor(TransactionHandler);

                        var cachingPolicy = new CustomCachingPolicy();

                        Loaded +=
                            (sender, args) => args.ReplaceService<DbProviderServices>(
                            (s, _) => new CachingProviderServices(s, TransactionHandler,
                                      cachingPolicy));
                    }
                }
            }
        }

        public static void InvalidateSets(DbContext dbContext)
        {
            IEnumerable<String> entitySetName = ((System.Data.Entity.Infrastructure.IObjectContextAdapter)dbContext).
                ObjectContext.MetadataWorkspace.GetEntityContainer("CodeFirstDatabase", DataSpace.SSpace).EntitySets.Select(e => e.Name);
            TransactionHandler.InvalidateSets(null, entitySetName);
        }

    }


Which i call it in my commit class in the repository Layer:

        public void Commit()
        {
            List<AuditEntry> auditEntries = new List<Z.BulkOperations.AuditEntry>();
            this._dbContext.BulkSaveChanges(options =>
                  {
                      options.UseAudit = true;
                      options.BulkOperationExecuted = bulkOperation => auditEntries.AddRange(bulkOperation.AuditEntries);
                  });
            SaveAuditEntries(auditEntries);
            EBudgetDbConfiguration.InvalidateSets(this._dbContext);
	}


Is that OK?
Best Regards,

**Comment by MounaMouna88** [comment]
Hello @JonathanMagnan,

Yes as i said before, i have tried it and it works for me.
My reply was in order to have your opinion about the implementation.

Thank you very much,
Best Regards,

Mouna.

**Comment by JonathanMagnan** [comment]
We will close this request since it seems that you have implemented a working solution.

Just let me know if you need more help.
