### ISSUE TITLE
acces support

### ISSUE THREAD

**Issue by rachidtabet** [zzzprojects/EntityFramework-Extensions#177]
bonjour,

je voudrai savoir comment procéder pour utiliser le support d'une année offert avec l'achat d'une licence 
Entity Framework Extensions - SQL Server (5-9 seats) 
merci.

**Comment by JonathanMagnan** [comment]
Bonjour @rachidtabet,

Je ne suis pas sûre de comprendre la question.

Avez-vous une demande spéciale?

Cordialement,

Jonathan

**Comment by rachidtabet** [comment]
Bonjour
On vient d acquérir une licence EFE pour 9 développeurs
Avec cette licences on a Un accès au support pour 12 mois
Je voudrai savoir comment procèder pour utiliser ce support en cas de
besoins.

Crdlt.

Le ven. 4 jan. 2019 à 20:10, Jonathan Magnan <notifications@github.com> a
écrit :

**Comment by JonathanMagnan** [comment]
Nous conseillons de nous contacter directement à notre courriel : info@zzzprojects.com, ou bien de simplement d’écrire sur GitHub comme tu viens de le faire 😉

**Comment by rachidtabet** [comment]
ok.
Merci.
