### ISSUE TITLE
Support for Redshift and custom db provider

### ISSUE THREAD

**Issue by pippolino** [zzzprojects/EntityFramework-Extensions#180]
Hi,

we tried to use  CData Redshift Provider but without success, is possible to implement it ? Or have a configuration to be able to extend some features like "EntityContainerEntitySet".

Even if we try to use Npgsql, the generated sql is not compatible with Redshift

Thanks

**Comment by JonathanMagnan** [comment]
Hello @pippolino ,

We looked at it during the weekend but unfortunately, we choose to not implement a new provider for now and concentrate our time on documentation instead.

Honestly, I'm not sure if we will ever implement this provider as it's a lot of effort which probably is better spent by improving the code for an existing provider such as `SQL Server`.

Best Regards,

Jonathan

**Comment by pippolino** [comment]
Hi @JonathanMagnan

I see it, but I’m sorry because in my opinion it could be useful.

**Comment by JonathanMagnan** [comment]
Hello @pippolino ,

I agree with you but unfortunately, we need first to concentrate on existing supported provider before adding a new one. There is still a lot of improvement to do on existing one.

**Comment by JonathanMagnan** [comment]
Hello @pippolino ,

We will close this issue since there is no short term plan to support it.

However, this issue will remain open in our internal issue tracker.

`Redshift` is for sure a provider we will look when we will be ready to add additional providers.

Best Regards,

Jonathan

**Comment by pippolino** [comment]
Thanks @JonathanMagnan 

Regards,
Federico
