### ISSUE TITLE
BulkSaveChanges (EF Core) fails when ambient transaction is present

### ISSUE THREAD

**Issue by idesfosses** [zzzprojects/EntityFramework-Extensions#181]
An exception occurs when trying to add new items within an ambient transaction.

 ```
using (var ts = new TransactionScope())
using (var db = new MyDbContext())
{
    var thing = new Thing { Id = Guid.NewGuid(), Number = -5 };
    db.Add(thing);
    db.BulkSaveChanges();

    ts.Complete();
}
```

The exception:
```
Unhandled Exception: System.InvalidOperationException: An ambient transaction has been detected. The ambient transaction needs to be completed before beginning a transaction on this connection.
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.EnsureNoTransactions()
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.BeginTransaction(IsolationLevel isolationLevel)
   at ?.?(DbContext this, Action`1 ?)
   at ConsoleApp1.Program.Main()
```

When trying this out with .NET Framework version and EF6, this exception does not occur.

What would be the reason for getting this exception?

**Comment by JonathanMagnan** [comment]
Hello @idesfosses ,

Which version of `System.Data.SqlClient` are you using?

Perhaps the `TransactionScope` is not available in the one you use? See:https://github.com/dotnet/corefx/issues/24282

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment]
Thank for the additional info,

We will look at it today.

**Comment by JonathanMagnan** [comment]
Hello @idesfosses ,

The v2.1.47 has been released.

`BulkSaveChanges` will now work correctly with `TransactionScope`.

Let me know if everything works as expected.

Best Regards,

Jonathan

**Comment by idesfosses** [comment]
@JonathanMagnan,

Great work. I verified the functionality and it works as I would expect.

Thanks for the quick implementation!

Kind regards,

Igor
