### ISSUE TITLE
BulkSaveChanges signature > return int ? (.NET Core)

### ISSUE THREAD

**Issue by idesfosses** [zzzprojects/EntityFramework-Extensions#182]
Hi @JonathanMagnan ,

I was wondering if you could "improve" the signature of the BulkSaveChanges and BulkSaveChangesAsync methods to return the same result as one would expect from the EF built-in SaveChanges and SaveChangesAsync methods.

The built-in methods return an integer, informing the caller how many rows were affected.

This would allow us to properly override the default implementation without losing functionality:

```csharp
public class IngDbContext : DbContext
{
    public override int SaveChanges(bool acceptAllChangesOnSuccess)
    {
        return this.BulkSaveChanges();
    }

    public override Task<int> SaveChangesAsync(bool acceptAllChangesOnSuccess, CancellationToken cancellationToken = default(CancellationToken))
    {
        return this.BulkSaveChangesAsync(cancellationToken);
    }
}
```

FYI, we are currently using Z.EntityFramework.Extensions.**EFCore** v2.1.47

Kind regards,
Igor

**Comment by JonathanMagnan** [comment]
Hello @idesfosses ,

Thank you for your request.

We don't know the number of rows affected in the database since we use bulk operations but we probably know the number of rows affected in the `ChangeTracker`, so returning this result is probably better than returning a `void`.

We will investigate it.

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment]
Hello @idesfosses ,

We will close this request as we have no short-term plan to make it happen (too much internal code need to be modified to handle it correctly for all case).

However, this request is still open in our internal backlog as we hope to eventually be able to complete it.

Best Regards,

Jonathan
