### ISSUE TITLE
Column 'StageTableId' is constrained to be unique.  Value '1' is already present.

### ISSUE THREAD

**Issue by meeper34** [zzzprojects/EntityFramework-Extensions#183]
Hello,

I am trying to capture the bulk insert output ids from a staging table where the primary key is an IDENTITY column.  I am getting the error Column 'StageTestId' is constrained to be unique.  Value '1' is already present.  I'm not sure what I'm doing wrong here.  I'm using version 3.15.17.

```sql
CREATE TABLE StageTest
(
   StageTestId INT IDENTITY(1,1),
   Name VARCHAR(100)
)
```

```csharp
string primaryKey = "StageTestId";

var bulkInsert = new BulkOperation(dbConn);
bulkInsert.BatchSize = batchSize;
bulkInsert.BatchTimeout = BatchTimeout;

foreach (DataColumn column in data.Columns)
{
	if (column.ColumnName != primaryKey)
	{
		bulkInsert.ColumnMappings.Add(column.ColumnName, column.ColumnName, false);
	}
}

bulkInsert.ColumnMappings.Add(primaryKey, primaryKey, ColumnMappingDirectionType.Output);

bulkInsert.DestinationTableName = tableName;
bulkInsert.BulkInsert(data);
```

**Comment by JonathanMagnan** [comment]
Hello @meeper34 ,

We trying to reproduce the issue but it works as expected on our side: https://dotnetfiddle.net/gW0iAq

Let me know what we are missing in our online example to get the same error.

Best Regards,

Jonathan

**Comment by meeper34** [comment]
I can reproduce in the test app if I set the first data column to have a unique constraint.  Is this working by design?

var col = data.Columns.Add("StageTestId", typeof(int));
		col.AllowDBNull = false;
		col.AutoIncrement = true;
		col.Unique = true;
		data.Columns.Add("Name");

**Comment by meeper34** [comment]
Seems like I can work around it by doing this:

dataTable.PrimaryKey = null;
dataTable.Columns[tablePrimaryKey].Unique = false;

**Comment by JonathanMagnan** [comment]
Thank you,

We successfully reproduced it: https://dotnetfiddle.net/8c2rIU

We will look at it even if you have found a workaround.

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment]
Hello @meeper34 ,

We looked at your scenario.

The issue happens because of these two following options:

```csharp
col.AutoIncrement = true;
col.Unique = true;
```

- When you insert two rows in your data table, your first 2 ID taken is `0` and `1`
- When you insert in the database (using Fiddle) the first row has an ID equal to `1`

So since the row 2 already have an ID equal to `1`, it throws an error since you have made the column unique.

Let me know if that answer correctly to this problem. I don't think anything here is related to our library.

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment]
Is there a reason why you enable `AutoIncrement = true` by the way?

**Comment by JonathanMagnan** [comment]
Hello @meeper34 ,

Oh I understand, you don't create the DataTable. It's created from your `SELECT` statement.

Yes, that's probably due because of the `IDENTITY` columns.

There is not so much we can do on our side since we don't "own" this DataTable.
