### ISSUE TITLE
BulkSaveChanges generates lower case user types names

### ISSUE THREAD

**Issue by SmartK8** [zzzprojects/EntityFramework-Extensions#187]
Hi, when I'm using a simple BulkSaveChanges after a context updated one row it generates SQL with user type names in lower case. Example:

DECLARE @#ZZZProjects_e4079cba_879c_4609_b672_4d90afebd5ed TABLE ( [IdGroupType] [dbo].[typekeydatatype].... (SQL cut short here)

Notice the typekeydatatype, the real type name is TypeKeyDataType. Unfortunately this causes SQL Server to throw an exception:

Column, parameter, or variable #1: Cannot find data type dbo.typekeydatatype.

Can I somehow switch bulk save to case sensitive SQL generator?

regards,
Kate

**Comment by JonathanMagnan** [comment]
Hello @SmartK8 ,

Thank you for reporting.

We will look at it to make sure we honor the right casing by default.

Best Regards,

Jonathan

**Comment by SmartK8** [comment]
Thanks, I can confirm that it works when I turn off case sensitivity in our database. Unfortunately that is not a solution for our production build. Looking forward for a potential fix, I'll switch back to old SaveChanges/non-bulk version until then, but I'll keep EF-Extensions integrated.

regards,
Kate

**Comment by JonathanMagnan** [comment]
Hello @SmartK8 ,

Sorry for the long delay, my developer finally finds out how to reproduce it.

The v3.16.29 has been released and now support correctly this scenario.

Let me know if everything works as expected.

Best Regards,

Jonathan

**Comment by SmartK8** [comment]
Thanks. It seem to be working now.

best regards,
Kate
