### ISSUE TITLE
XXX-FromQueryAsync not Respecting Casing

### ISSUE THREAD

**Issue by svernyi** [zzzprojects/EntityFramework-Extensions#189]
Heyo,

After switching from MSSQL to MariaDB/MySQL, I've got some issues when running `DeleteFromQuery` and `UpdateFromQuery`. 
![image](https://user-images.githubusercontent.com/29544451/52987443-2a24ab00-33c9-11e9-94b1-4ddad4e3f928.png)

Now, I get this same exception when I run BulkInsert, BulkDelete, etc... but I can resolve these issues by configuring the Bulk commands to be case-insensitive. However, I don't have a way to configure case-insensitivity on the UpdateFromQuery and DeleteFromQuery commands. Is there another solution?

**Comment by JonathanMagnan** [comment]
Hello @svernyi ,

Thank you for reporting, we will look at it.

I believe we have enough information with the "case sensitive" to try to reproduce it.

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment]
Hello @svernyi ,

We tried several different version of MySQL but we never success to reproduce the issue.

Do you think you could provide us a project sample with the issue?

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment]
Hello @svernyi ,

We will close the request due to lack of information to reproduce it.

If you success to reproduce this issue in a project, just post it here and we will re-open and look at it as soon as possible.

Best Regards,

Jonathan
