### ISSUE TITLE
Can't get the expected behavior from BulkInsert when specifying the ColumnInputExpression option

### ISSUE THREAD

**Issue by thomkle** [zzzprojects/EntityFramework-Extensions#190]
Hi,

The goal is to bulk-insert, but exclude certain columns (`adjValueTwo` in this example).

I'm getting the following error when I'm trying to use `BulkInsert` when specifying the `ColumnInputExpression` option:
```csharp
Missing Colum : Id
On entity : Adjustment
On Table : [dbo].[Adjustment]
```

The `BulkUpdate` is working fine with this `ColumnInputExpression` when updating the same type of objects. The `BulkInsert` is working fine without the `ColumnInputExpression`.

The object looks like this:
```csharp
    [Table("Adjustment")]
    public class Adjustment : Entity<long>
    {
        [Key]
        [Column("adjID")]
        public override long Id { get; set; }

        // For convenience with current table; only get
        public virtual long adjID { get { return Id; } }

        [Index("IX_adjIndexOne_adjIndexTwo", 1, IsUnique = true)]
        public long adjIndexOne { get; set; }

        [Index("IX_adjIndexOne_adjIndexTwo", 2, IsUnique = true)]
        [Column(TypeName = "date")]
        public DateTime adjIndexTwo { get; set; }

        public decimal? adjValueOne { get; set; }

        public decimal? adjValueTwo { get; set; }

        [ForeignKey("adjIndexOne")]
        public virtual IndexOne IndexOne { get; set; }
    }
```

The `BulkInsert` is being used in the following way:
```csharp
await Context.BulkInsertAsync(adjustments,
    options =>
    {
        options.ColumnInputExpression = a => new { a.Id, a.adjIndexOne, a.adjIndexTwo, a.adjValueOne };
    });
```

I'm not sure if I'm using it wrong or maybe it's not compatible with some of the attributes in the object that is to be inserted. Any help on solving this would be greatly appreciated. Let me know if more information is needed.

**Comment by JonathanMagnan** [comment]
Hello @thomkle ,

Which version of Entity Framework are you using?

We will look at this issue.

Best Regards,

Jonathan

**Comment by thomkle** [comment]
Hi @JonathanMagnan ,

We're using EntityFramework 6.2.0 and Z.EntityFramework.Extensions 3.16.23
Great!

**Comment by JonathanMagnan** [comment]
Hello @thomkle ,

The v3.16.25 has been released

We fixed the issue that was not allowing you to add the primary key in the `InputExpression`

We added a task on our side to review all this kind of `Expression` and mapping next month.

Let me know if everything is working as expected.

Best Regards,

Jonathan

**Comment by thomkle** [comment]
Hi @JonathanMagnan ,

It's working great now, thanks for the quick help and solution!
