### ISSUE TITLE
Problem found to handle large amount of data.

### ISSUE THREAD

**Issue by narayanmitra** [zzzprojects/EntityFramework-Extensions#191]
I have used your free version tool ‘**Entity Framework Extensions**’ to insert large amount of data but I have found few issues. 

**Scenario:**
**Total tables** - 17 ( Each are related with primary and foreign key relationship)
**Total Records** -  Parent table contains 200000 (two lakhs) and each child table contains minimum of 200000 records.

**Activities:** 
1.	Use BulkInsert() method		
Result - It is taken near about 20 minutes to complete. No records are inserted into tables and **'System.OutOfMemoryException'** was thrown.
2.	Use BulkInsert() with batch size 1000.
		Result – It is taken near about 18 minutes 38 seconds to complete. No records are inserted into tables and **'System.OutOfMemoryException'** was thrown.
3.	Use BulkSaveChanges() 
		Result - It is taken near about 16 minutes 48 seconds to complete. No records are inserted into tables and **'System.OutOfMemoryException**' was thrown.
4.	Use BulkSaveChanges()  with batch size 1000.
		Result - It is taken near about 16 minutes 23 seconds to complete. No records are inserted into tables and **'System.OutOfMemoryException'** was thrown.
e:

The above exception is overcome by setting **‘EntityFrameworkManager.DefaultEntityFrameworkPropagationValue = false**’
But to insert those records Use **BulkSaveChanges()** method taking more time in compared to **SqlBulkCopy.WriteToServer(**) method. 
**SqlBulkCopy.WriteToServer()** method taking only 5 minitues 30 seconds to insert those records.

So confirm me if you have any faster way to insert those records. If any payment is required then agree to pay.

**Code Snippet.**
EntityFrameworkManager.DefaultEntityFrameworkPropagationValue = false;
List<FreightBillInvoice> freightBillInvoices=FreightBillDataPreparation(138225);
EFSaveChangesWithOutBatch(freightBillInvoices);
private static void EFSaveChangesWithOutBatch(List<FreightBillInvoice> freightBillInvoices)
        {
            using (var dbCtx = new ImpactFBEntities())
            {
                dbCtx.FreightBillInvoices.AddRange(freightBillInvoices);
                try
                {
                    dbCtx.BulkSaveChanges(false);
                  }
                catch (Exception e)
                {
                    throw e;
                }
            }
        }

**Comment by JonathanMagnan** [comment]
Hello @narayanmitra ,

We already answered you in the email you sent to us.

I will close this issue so we could keep the discussion in one place.

Best Regards,

Jonathan
