### ISSUE TITLE
Bulk-merge attempting to insert duplicate data with IncludeGraph

### ISSUE THREAD

**Issue by Velocity540** [zzzprojects/EntityFramework-Extensions#192]
Im not sure if this is an exact duplicate of 

Issue #145 

but here goes.

Title says it all.. Have a set of entitiies Im trying to perform BulkMerge on.
one of the properties is a sub-collection of entities.. if I do not includegraph all works as expected. If I do set IncludeGraph = true, it always tried to insert a new record. Even if the sub-collection is null.

Out of Ideas on this

**Comment by JonathanMagnan** [comment]
Hello @Velocity540 ,

It's something you could reproduce in a sample project?

We will be happy to look at it if you could provide us more information.

Best Regards,

Jonathan

**Comment by Velocity540** [comment]
I’m not sure how you would like me to sample it?

Do you have a fully working sample of BulkMerge or BulkSyncronize working using IncludeGraph = true?

After trying to get this to work, I have given up on BulkMerge and BulkSync.

I figure the best I can do is BulkDelete the items not in the list.. BukInsert the items into the DB that do not exists. 

Those commands work fine..

The problem I have now is the BulkUpdate seems to be conflicting with the keys.. I would take an actual working sample of BulkUpdate in place of the others.


I think my question stated exactly what I am trying to do, and I’m sure others do the same thing. I’m sure its something I’m not doing right thought

**Comment by Velocity540** [comment]
Ok.. lets try a simple example

Lets say we have a model like below (Id's are your Key in SQL)
PeopleId of Cars points to People (1 to many relationship)

Lets say we get this JSON and want to save it to DB
{

    "people": [
        {
            "name": "john",
            "cars": [
                {
                "make": "honda",
                "make": "toyota"
            }
            ]
        }
    ]
}

We should see 1 record in People and 2 in cars inside the DB..
Using BulkInsert, this works fine.

Lets say tomorrow I get this JSON


    {
    "people": [
        {
            "name": "john",
            "cars": [
                {
                "make": `"chevy"`
            }
            ]
        }
    ]
}

Using BulkUpdate, how would I get cars table to only reflect one item? is that possible? Do I use BulkMerge? BulkSync? Or do I need to loop through people and check each cars table?

    public class People
    {
        public int Id { get; set; }

        public string Name { get; set; }

        public List<Cars> Cars { get; set; }
    }

    public class Cars
    {
        public int Id { get; set; }
        
       public string Make { get; set; }
        public People People { get; set; }

        public int PeopleId { get; set; }
    }

**Comment by JonathanMagnan** [comment]
Thank @Velocity540 ,

Let start with this online example using your scenario: https://dotnetfiddle.net/rMq0nR

From what I understand:
- You want to merge Person (you probably doesn't get every person every day, so you don't want to delete those you didn't get data)
- You want to synchronize Cars (remove car no longer belong a person)

I would not use `IncludeGraph` in this situation. Unless I'm misunderstanding your scenario, that's not what you want. I would instead use and call myself multiple bulk operation methods.

Let me know what should be changed from this online example.

Best Regards,

Jonathan

**Comment by Velocity540** [comment]
thanks Jonathan,

Quick Points
1 -The Id's are Primary Key Ints Database Generated but, for people (the top level) I also have a unique guid for each. This value is NOT sql determined but set when I retrieve the objects. I wonder if I should key off that?

2- context.BulkMerge(people); Will need to change to BulkSync, but I assume this will work as the rest of my Bulk Syncs. I have cascade delete turned on for the child entities. Also, this is a multi-tenant, so I have been using 
 await EntityContext.BulkSynchronizeAsync(itemData, o =>
                {
                    o.Log += s => Log.Information(s);

                    // Key off something important and the tenantId
                    o.ColumnPrimaryKeyExpression = i => new {i.ObjectId, i.TenantId};

                    // Stick the deletes to only this tenantId
                    o.ColumnSynchronizeDeleteKeySubsetExpression = i => i.TenantId;

                });

3- Lets take the sample one step further. Lets assume cars have a rims collection. WOuld the same pattern apply? My guess is it would.

thanks for this, much appreciated.

**Comment by JonathanMagnan** [comment]
> The Id's are Primary Key Ints Database Generated but, for people (the top level) I also have a unique guid for each. This value is NOT sql determined but set when I retrieve the objects. I wonder if I should key off that?

Well, I don't know your situation. Sometime GUID is good practices, sometimes a bad. However, for our library, it doesn't matter as long as you have the value

> 2- context.BulkMerge(people); Will need to change to BulkSync, but I assume this will work as the rest of my Bulk Syncs. I have cascade delete turned on for the child entities. Also, this is a multi-tenant, so I have been using

If the multi-tenant ID is on every class, it will not cause problem. However, if the multi-tenant ID is only in the people class, I don't think it will work. 

> 3- Lets take the sample one step further. Lets assume cars have a rims collection. WOuld the same pattern apply? My guess is it would.

Yes, the same pattern would apply.

Unfortunately, .NET Fiddle is currently down or have hard time to run the example I updated so I cannot show it at this moment.

**Comment by Velocity540** [comment]
Johnathan,
after working on this for 2/3 days, I'v come to realize perhaps this cannot be done the way I am doing it.

Since (in the sample) I would not know the ID of people when inserting people and cars.

Im guessing I can use BulkInsert (IncludeGraph) to insert missing entities. I can use BulkDelete to delete entities that are in DB but not source

the update is what I am stuck on.

I am open to suggestions at this point, I have about another day or so I can invest in this. Otherwise its back to doing this in SP's in SQL for best performace

**Comment by JonathanMagnan** [comment]
> Since (in the sample) I would not know the ID of people when inserting people and cars.

What do you mean by you will not know the ID of people? I'm missing something here.
