### ISSUE TITLE
Unable to cast object of type "System.String" to type "System.Guid"

### ISSUE THREAD

**Issue by jruizx** [zzzprojects/EntityFramework-Extensions#193]
Hi guys,

I have an issue when I am testing my solution with SQL Lite. Our model uses Guid for identity columns. When I try to do a bulk insert I received an exception saying:  

**Unable to cast object of type "System.String" to type "System.Guid"**

In SQL Server works fine.

**Comment by JonathanMagnan** [comment]
Hello @jruizx ,

Could you let us know which version of Entity Framework and SQLite you are using?

Best Regards,

Jonathan

**Comment by jruizx** [comment]
Hi @JonathanMagnan,

Thank you so much for replying so quickly.  These are the versions that I am using:

<PackageReference Include="Microsoft.EntityFrameworkCore" Version="2.1.2" />
 <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="2.1.2" />

Kind regards,
JOrdi

**Comment by JonathanMagnan** [comment]
Thank you,

We will look at it.

**Comment by JonathanMagnan** [comment]
Hello @jruizx ,

It took us a while but we finally succeeded to fix it.

Could you try the v2.1.55 and let us know if everything works as expected.

Best Regards,

Jonathan

**Comment by jruizx** [comment]
Thank you Jonathan,

I will do it
