### ISSUE TITLE
Bug: The value can not be null. on BatchSaveChanges

### ISSUE THREAD

**Issue by JoseMancebo** [zzzprojects/EntityFramework-Extensions#194]
Im trying the new BatchSaveChanges on my EF6 project over SQL Server.

When i call BatchSaveChanges i am getting this crash:

El valor no puede ser nulo.
Nombre del parámetro: method

   en System.Linq.Expressions.Expression.Call(MethodInfo method, Expression arg0, Expression arg1, Expression arg2, Expression arg3, Expression arg4)
   en .()
   en ..ctor(DbContext )
   en DbContextExtensions.BatchSaveChanges(DbContext this)
   en Taaf.Infrastructure.Data.MainModule.UnitOfWork.MainModuleUnitOfWork.Commit() en C:\Desarrollo\TAAF\Dev\src\Infrastructure.Data.MainModule\UnitOfWork\MainModuleUnitOfWork.cs:línea 4885

**Comment by JonathanMagnan** [comment]
Hello @JoseMancebo ,

Thank you for reporting, we will check today if we are able to reproduce it.

We might need a project otherwise.

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment]
Hello Jose,

It's possible for you to provide a project sample with this error? 

We thought we know where this issue was but it looks that we are not able to reproduce it.

**Comment by JoseMancebo** [comment]
Hi Jonathan,

This is the sample project:
https://drive.google.com/file/d/1QPxlX_8TtNu0eD94igX1st350U8r42va/

The particularities of my project:
.net 4.0
Context generated with .edmx
EF 6.2

**Comment by JonathanMagnan** [comment]
Thank you, I will assign this to my developer

**Comment by JonathanMagnan** [comment]
Hello @JoseMancebo ,

The v3.16.33 has been released.

A reflection was made on an `async` method that doesn't exist in `.NET40`

Let me know if everything is now working as expected.

Best Regards,

Jonathan

**Comment by JoseMancebo** [comment]
Hello @JonathanMagnan,

Now, the first time works well, but the second time, the "batchsavechanges" return to execute the same commands. It seems that, after the "batchsavechanges" is executed do not clear the pending changes.

Its easy to test:
1- Insert a row
2-execute batchsavechages
3-execute batchsavechanges.

**Comment by JonathanMagnan** [comment]
Hello @JoseMancebo ,

Unfortunately, you are very right. It seems that we forget one `AcceptAllChanges` that was not needed in `EF Classic`.

The v3.16.34 has been released

It should now accept changes correctly to the second `BatchSaveChanges` will not save against entity.

Let me know if that work as expected.

Best Regards,

Jonathan

**Comment by JoseMancebo** [comment]
Im sorry but now on the first call to BatchSaveChanges crash it.... Null reference...

**Comment by JonathanMagnan** [comment]
I'm sorry for all of this, It seems the call is a little bit different on our side for .NET40

The v3.16.35 fixing this issue in `NET40` has been released.

I have added a task to add some unit net in `NET40` to make sure that never happen again (All our test are currently running in `NET45`).

**Comment by JoseMancebo** [comment]
Thanks @JonathanMagnan, 

Now seems to work well.

**Comment by JonathanMagnan** [comment]
Great ;) `net40` test has been added this morning on our side so that will not happen again.
