### ISSUE TITLE
Please remove the need to set static EntityFrameworkManager.ContextFactory

### ISSUE THREAD

**Issue by sandimschuh** [zzzprojects/EntityFramework-Extensions#195]
The problem: 
When unit testing I have tests that use different DbContext running in parallel. Because of the need to set static EntityFrameworkManager.ContextFactory (or to define a default constructor in DbContext) it is not possible to use this library to populate the test database using bulk inserts. 
The only workaround I discovered was to put the bulk inserts inside of a lock statement and set EntityFrameworkManager.ContextFactory for each thread. But that significantly slows down the tests.

Is there any better solution to overcome this?

**Comment by JonathanMagnan** [comment]
Hello @sandimschuh ,

The `EntityFrameworkManager.ContextFactory` should only be set once at the start of the application.

You should not set it for every `BulkInsert` you create.

Is there a reason why you set it directly in a thread? A common mistake is to return the same context when the factory requires a new context. We hope to eventually remove the `ContextFactory` requirement in a few months (we will try at least).

For example:

```csharp
EntityFrameworkManager.ContextFactory = context => new CurrentContext();

// ...code


// Thread_1
context.BulkInsert(listA);

// Thread_2
context.BulkInsert(listB);
```

Let me know if that answer correctly to your question.

Best Regards,

Jonathan

**Comment by sandimschuh** [comment]
Hi Jonathan,

thanks for the response. My problem is that I have to use different DB contexts but can only set the static ContextFactory for on context. So when I do a bulk insert on another context in any of my tests, how will this behave?

**Comment by JonathanMagnan** [comment]
The parameter context allows us to handle this kind of scenario. Since we know which context is currently used, we can create the right context in the factory by looking at the type.

For example:

```csharp
// code has been hand writted so may contains some typing error
EntityFrameworkManager.ContextFactory = context => {
	if(context.GetType() == typeof(EntityContext1))
	{
		return new EntityContext1();
	}
	else if(context.GetType() == typeof(EntityContext2))
	{
		return new EntityContext2();
	}
	
	throw new Exception("Oops! an unsupported context type has been provided: " + context.GetType());
};
```

**Comment by sandimschuh** [comment]
to be more precise, I use contexts of the same type but configured on different databases. So for example, one context for read-only operations, one context for inserts and updates, and maybe a further context on a large database for performance tests. Therefore I instantiate DbContext with different DbContextOptions.
Would this scenario also be possible?

**Comment by JonathanMagnan** [comment]
Sure,

All depend on how you did it. We usually copy the `DbContextOptions` but it's also possible to determine which context to use by looking at some info inside the context itself.

The context used in the `ContextFactory` doesn't make any save, it only used to use some method from Entity Framework without impacting your context.

For example:
```csharp
// code has been hand writted so may contains some typing error
EntityFrameworkManager.ContextFactory = context => {
	if(context is EntityContext1 as entityContext1)
	{
		if(entityContext1.IsForUnitTest)
		{
			return ...
		}
		else if(entityContext1.Database.Connection == "")
		{
			return ...
		}
		
		return new EntityContext1();
	}
	else if(context is EntityContext2)
	{
		return new EntityContext2();
	}
	
	throw new Exception("Oops! an unsupported context type has been provided: " + context.GetType());
};
```

**Comment by sandimschuh** [comment]
Thanks, Jonathan. With this information, I should be able to solve my problem :)
Best regards,
Michael

**Comment by JonathanMagnan** [comment]
Great,

I will close this issue but if there is anything else, let me know and we will re-open it.

Best Regards,

Jonathan
