### ISSUE TITLE
[Index(IsUnique=true)] fails on BulkMerge and BulkSync

### ISSUE THREAD

**Issue by hemirunner426** [zzzprojects/EntityFramework-Extensions#196]
My entity has a property with an Index attribute.  It's value is expected to be unique.

After an intial loading of data to the table I am expecting to update various values on the entity set table using a non-keyed properties which is uniquely indexed.  I don't expect the key properties to ever be updated from the data source.

I've tried various calls like this one to keep the extension from updating that particular column on update.
await this.BulkMergeAsync(entitiesToProcess, operation =>
                        {
                            operation.ColumnPrimaryKeyExpression = e => e.NALPath
                            operation.BatchSize = BulkBatchSize;
                            operation.AllowDuplicateKeys = true;
                            operation.IncludeGraph = true;
                            operation.AllowUpdatePrimaryKeys = false;
                            operation.IgnoreOnMergeUpdateExpression = e => e.NALPath
                        });

However, all combindations I've tried so far has resulted in  SqlException: SqlException: Cannot insert duplicate key row in object 'dbo.cpex_CmDistributionPointInfo' with unique index 'IX_NALPath'. The duplicate key value is (["Display=\\lab1-cmp2016.contoso.local\"]MSWNET:["SMS_SITE=LAB"]\\lab1-cmp2016.contoso.local\).
The statement has been terminated.

SQL profiler shows 2 MERGE operations executed when BulkMergeAsync is called:

exec sp_executesql N'MERGE INTO [dbo].[cpex_CmDistributionPointBase] AS DestinationTable
USING
(
SELECT @0_0 AS [Name], @0_1 AS [SiteCode], @0_2 AS [SiteName], @0_3 AS [ModifiedDate], @0_4 AS [ModifiedById], @0_5 AS [CreatedDate], @0_6 AS [CreatedById], @0_7 AS [Guid], @0_8 AS [IsDeleted], @0_9 AS [SourceType], @0_10 AS [PendingSync], @0_11 AS [Id], @0_12 AS ZZZ_Index
UNION ALL SELECT @1_0 AS [Name], @1_1 AS [SiteCode], @1_2 AS [SiteName], @1_3 AS [ModifiedDate], @1_4 AS [ModifiedById], @1_5 AS [CreatedDate], @1_6 AS [CreatedById], @1_7 AS [Guid], @1_8 AS [IsDeleted], @1_9 AS [SourceType], @1_10 AS [PendingSync], @1_11 AS [Id], @1_12 AS ZZZ_Index
) AS StagingTable
ON DestinationTable.[Id] = StagingTable.[Id]
WHEN MATCHED   THEN
UPDATE
SET     [Name] = StagingTable.[Name], [SiteCode] = StagingTable.[SiteCode], [SiteName] = StagingTable.[SiteName], [ModifiedDate] = StagingTable.[ModifiedDate], [ModifiedById] = StagingTable.[ModifiedById], [CreatedDate] = StagingTable.[CreatedDate], [CreatedById] = StagingTable.[CreatedById], [Guid] = StagingTable.[Guid], [IsDeleted] = StagingTable.[IsDeleted], [SourceType] = StagingTable.[SourceType], [PendingSync] = StagingTable.[PendingSync]
WHEN NOT MATCHED THEN
INSERT ( [Name], [SiteCode], [SiteName], [ModifiedDate], [ModifiedById], [CreatedDate], [CreatedById], [Guid], [IsDeleted], [SourceType], [PendingSync] )
VALUES ( [Name], [SiteCode], [SiteName], [ModifiedDate], [ModifiedById], [CreatedDate], [CreatedById], [Guid], [IsDeleted], [SourceType], [PendingSync] )
OUTPUT
    $action,
    StagingTable.ZZZ_Index,
    1,
    INSERTED.[Id] AS [Id_zzzinserted]

;',N'@0_0 nvarchar(255),@0_1 nvarchar(max) ,@0_2 nvarchar(max) ,@0_3 datetimeoffset(7),@0_4 bigint,@0_5 datetimeoffset(7),@0_6 bigint,@0_7 uniqueidentifier,@0_8 bit,@0_9 nvarchar(max) ,@0_10 bit,@0_11 bigint,@0_12 int,@1_0 nvarchar(255),@1_1 nvarchar(max) ,@1_2 nvarchar(max) ,@1_3 datetimeoffset(7),@1_4 bigint,@1_5 datetimeoffset(7),@1_6 bigint,@1_7 uniqueidentifier,@1_8 bit,@1_9 nvarchar(max) ,@1_10 bit,@1_11 bigint,@1_12 int',@0_0=N'LAB1-CMP2016.CONTOSO.LOCAL',@0_1=N'LAB',@0_2=N'CONTOSO LAB1',@0_3='2019-03-22 19:37:16.0649723 +00:00',@0_4=1,@0_5='2019-03-22 19:37:16.0649723 +00:00',@0_6=1,@0_7='7491010D-C3E7-45BF-8CFE-32AD4C1276C4',@0_8=0,@0_9=N'SMS_DistributionPointInfo',@0_10=0,@0_11=15,@0_12=0,@1_0=N'LAB1-SCCM.CONTOSO.LOCAL',@1_1=N'LAB',@1_2=N'CONTOSO LAB1',@1_3='2019-03-22 19:37:16.0649723 +00:00',@1_4=1,@1_5='2019-03-22 19:37:16.0649723 +00:00',@1_6=1,@1_7='1F8D61BA-D402-4E9A-8357-6B67BA6C70EE',@1_8=0,@1_9=N'SMS_DistributionPointInfo',@1_10=0,@1_11=14,@1_12=1

exec sp_executesql N'MERGE INTO [dbo].[cpex_CmDistributionPointInfo] AS DestinationTable
USING
(
SELECT @0_0 AS [Id], @0_1 AS [NALPath], @0_2 AS ZZZ_Index
UNION ALL SELECT @1_0 AS [Id], @1_1 AS [NALPath], @1_2 AS ZZZ_Index
) AS StagingTable
ON DestinationTable.[Id] = StagingTable.[Id]
WHEN MATCHED   THEN
UPDATE
SET     [NALPath] = StagingTable.[NALPath]
WHEN NOT MATCHED THEN
INSERT ( [Id], [NALPath] )
VALUES ( [Id], [NALPath] )
;',N'@0_0 bigint,@0_1 nvarchar(255),@0_2 int,@1_0 bigint,@1_1 nvarchar(255),@1_2 int',@0_0=15,@0_1=N'["Display=\\lab1-cmp2016.contoso.local\"]MSWNET:["SMS_SITE=LAB"]\\lab1-cmp2016.contoso.local\',@0_2=0,@1_0=14,@1_1=N'["Display=\\lab1-sccm.CONTOSO.LOCAL\"]MSWNET:["SMS_SITE=LAB"]\\lab1-sccm.CONTOSO.LOCAL\',@1_2=1

**Comment by hemirunner426** [comment]
Here is an example in .net fiddle:
https://dotnetfiddle.net/h20g3w

**Comment by JonathanMagnan** [comment]
Hello @hemirunner426 ,

When using `IncludeGraph`, all options must be specified inside the IncludeGraphOperationBuilder since every option might be different from an entity type to another

Fiddle: https://dotnetfiddle.net/CaBgbF

```csharp
FiddleHelper.WriteTable(list2);
context.BulkMerge(list2, options => {
	options.IncludeGraph = true;
	options.IncludeGraphOperationBuilder = buidler => {
		options.ColumnPrimaryKeyExpression = e => e.Name;
		options.AllowDuplicateKeys = true;
	};
});
```

Let me know if that answer successfully to your question.

Best Regards,

Jonathan

**Comment by hemirunner426** [comment]
I tried this and I still get the same exception.  It is reproducible on fiddle too:
https://dotnetfiddle.net/LqgPM5

Is there any more information I can give you?

**Comment by JonathanMagnan** [comment]
I believe we have all the informations required.

We will look at it probably tomorrow.

**Comment by JonathanMagnan** [comment]
Hello @hemirunner426 ,

Our Fiddle has been updated with your code: https://dotnetfiddle.net/CaBgbF

I'm sorry, I made a mistake when I created the fiddle the first time. I was not setting options correctly in the `IncludeGraphOperationBuilder`.

Here is how it should be done:

```csharp
context.BulkMerge(list2, options => {
	options.IncludeGraph = true;
	options.IncludeGraphOperationBuilder = builder =>
	{
		var customerBuilder = builder as BulkOperation<Customer>;
		if (customerBuilder != null)
		{
			customerBuilder.ColumnPrimaryKeyExpression = e => e.Name;
			customerBuilder.AllowDuplicateKeys = true;
		}
	};		
});
```

Let me know if that version is working.

**Comment by hemirunner426** [comment]
That seems of have me closer to getting it to work.  It now works in the fiddler examples we've been using.  However, in my application it is now throwing a Exception: Missing Colum : ResourceId
On entity : CmGroup
On Table : [dbo].[cpex_CmGroup]

The data model follows a TPT inheritance chain.  Is it still possible to use the BulkMerge/Insert/Delete functions?

**Comment by JonathanMagnan** [comment]
Our library should support all inheritances including `TPT`.

However, we don't support mixed inheritance (it's possible to have a table to be a somewhat a `TPH` and `TPT` (so basically a `TPT` with a discriminator in one of his table).

**Comment by hemirunner426** [comment]
I don't think the data model is TPH and TPT.  The tables lack a discrimiator column.  However, the column I am keying on is in the abstract class table.  It seems that BulkMerge is not joining CmGrouo table to its abstract class table.

**Comment by hemirunner426** [comment]
exec sp_executesql N'MERGE INTO [dbo].[cpex_CmResource] AS DestinationTable
USING
(
SELECT * FROM #ZZZProjects_3527b482_f1e2_4d40_a414_d749e2dbe317
WHERE ZZZ_Index >= @IndexStart AND ZZZ_Index <= @IndexEnd
) AS StagingTable
ON DestinationTable.[Id] = StagingTable.[Id]
WHEN MATCHED   THEN
UPDATE
SET     [ResourceId] = StagingTable.[ResourceId], [Name] = StagingTable.[Name], [ResourceType] = StagingTable.[ResourceType], [AgentNamesString] = StagingTable.[AgentNamesString], [AgentTimesString] = StagingTable.[AgentTimesString], [LastChangeTime] = StagingTable.[LastChangeTime], [ModifiedDate] = StagingTable.[ModifiedDate], [ModifiedById] = StagingTable.[ModifiedById], [CreatedDate] = StagingTable.[CreatedDate], [CreatedById] = StagingTable.[CreatedById], [Guid] = StagingTable.[Guid], [IsDeleted] = StagingTable.[IsDeleted], [SourceType] = StagingTable.[SourceType], [PendingSync] = StagingTable.[PendingSync]
WHEN NOT MATCHED THEN
INSERT ( [ResourceId], [Name], [ResourceType], [AgentNamesString], [AgentTimesString], [LastChangeTime], [ModifiedDate], [ModifiedById], [CreatedDate], [CreatedById], [Guid], [IsDeleted], [SourceType], [PendingSync] )
VALUES ( [ResourceId], [Name], [ResourceType], [AgentNamesString], [AgentTimesString], [LastChangeTime], [ModifiedDate], [ModifiedById], [CreatedDate], [CreatedById], [Guid], [IsDeleted], [SourceType], [PendingSync] )
OUTPUT
    $action,
    StagingTable.ZZZ_Index,
    1,
    INSERTED.[Id] AS [Id_zzzinserted]

;',N'@IndexStart int,@IndexEnd int',@IndexStart=0,@IndexEnd=32

There is the MERGE statement captured from SQL profiler.  CmResource table is the base table for CmGroup.  The key property expression is ResourceId.  This appears to be correct.  I'm not sure what else is missing.

**Comment by JonathanMagnan** [comment]
We tried it but unfortunately, we didn't success to reproduce the issue even with `TPT` and `Abstract` class

Do you think you could provide a runnable project/solution with the issue?

In the worse case, your model (or at least, the `CmResource` and `CmGroup` entity).

You can send private file here: info@zzzprojects.com

**Comment by hemirunner426** [comment]
So it appears that if you have a TPT with an abstract and concrete hierarchy and set IncludeGraph = true then the operation builder will resolve two builders, one for the abstract and the other for the concrete.  The primary keys must resolve properly for each time or you'll get a missing column exception.

If you set IncludeGraph = false the operation fails with:
Inner Exception 1:
Exception: Missing Colum : GroupId
On entity : CmDistributionPointGroup
On Table : [dbo].[cpex_CmDistributionPointBase]

Where CmDistributionPointGroup is the child class of the abstract CmDistributionPointBase and column GroupId exists on CmDistributionPointGroup.

**Comment by JonathanMagnan** [comment]
Still cannot reproduce: https://dotnetfiddle.net/ToIlw8

We tried several other scenarios directly in Visual Studio.

Unfortunately, after spending 2h to try to reproduce it, we will need a runnable project/solution/fiddle with that issue.

**Comment by hemirunner426** [comment]
I totally understand.  I spent some time this morning mocking it up in fiddle and was able to reproduce it.

https://dotnetfiddle.net/g4UiGP

Thank for the quick responses!

**Comment by JonathanMagnan** [comment]
Hello @hemirunner426 ,

Just to let you know,

The issue is caused by this line:
`customerBuilder.ColumnPrimaryKeyExpression = e => e.ResourceId;`

The `ResourceId` is not part of the table that's saved. It's part of the table `CmResource`.

We will investigate more this issue but I'm not sure if custom key outside the `table` would be supported for `TPT`.

**Comment by JonathanMagnan** [comment]
Hello @hemirunner426 ,

I believe you have reached a limit of our library. We looked at how we could support a scenario when the key to use is part of another table and that's, unfortunately, asking us WAY too many changes to the library if we want to support it.

One way for you to handle it is looking in the database first and populating the `Id`. So you will be able to use the true PK to handle the merge.

**Comment by hemirunner426** [comment]
Thanks that's exactly the solution I implemented.  I'll go ahead a close this ticket.
