### ISSUE TITLE
Bulk operation fails with default value.

### ISSUE THREAD

**Issue by ordinarytype** [zzzprojects/EntityFramework-Extensions#198]
Hello @JonathanMagnan,

I've found an issue, that bulk operation fails conversion to DateTime.
Sample project is attached. 

Thanks!
[BulkIssue.zip](https://github.com/zzzprojects/EntityFramework-Extensions/files/3033221/BulkIssue.zip)

**Comment by JonathanMagnan** [comment]
Thank you for your project,

We will try to look at it today.

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment]
Hello @ordinarytype ,

Which version of MySQL are you using?

Your migration currently tries to set a `CURRENT_TIMESTAMP` default value to a `DateTime` column.

However, as specified here: https://stackoverflow.com/a/9005872 it's only available on timestamp column.

It seem some later version allow it on DateTime but it seems we don't success to make it work on our side.

Let us know which version you are using.

Best Regards,

Jonathan

**Comment by ordinarytype** [comment]
> Which version of MySQL are you using?

We're using 10.3.11-MariaDB.

Thanks!

**Comment by JonathanMagnan** [comment]
Hello @ordinarytype ,

A new version v3.17.3 has been released.

Could you try it and let me know if everything now works as expected.

Best Regards,

Jonathan

**Comment by ordinarytype** [comment]
Hello @JonathanMagnan,

Thanks, it's working for my case! 

But will fail with other default values, for example:

```
    public class Product
    {
        public int Id { get; set; }

        public string Description { get; set; }

        public short InStock { get; set; }

        public DateTime DateInsert { get; set; }
    }
```

```
    public class ProductConfiguration : IEntityTypeConfiguration<Product>
    {
        public void Configure(EntityTypeBuilder<Product> builder)
        {
            builder.Property(e => e.DateInsert).ValueGeneratedOnAdd().HasDefaultValueSql("CURRENT_TIMESTAMP");

            builder.Property(e => e.InStock).ValueGeneratedOnAdd().HasDefaultValue(1);
        }   
    }
```

**Comment by JonathanMagnan** [comment]
Thank,

We will investigate more `MariaDB` in this case and check why it happens to this provider.

**Comment by JonathanMagnan** [comment]
Is there a reason why you closed it?

**Comment by ordinarytype** [comment]
Oh, sorry, nevermind.

**Comment by JonathanMagnan** [comment]
Hello @ordinarytype ,

A new version (v2.2.3) has been released.

Let me know if everything is fixed for you in this version.

Best Regards,

Jonathan

**Comment by ordinarytype** [comment]
Hello @JonathanMagnan,

Yes, seems to be fixed.

Thanks!
