### ISSUE TITLE
Alternate T-SQL syntax for BatchSave

### ISSUE THREAD

**Issue by YuriAbele** [zzzprojects/EntityFramework-Extensions#201]
Hallo,

more faster as generated by BatchSaveChanges() T-SQL is to use [MERGE](https://docs.microsoft.com/en-us/sql/t-sql/statements/merge-transact-sql?view=sql-server-2017) operation with [Table-Value (example D)](https://docs.microsoft.com/en-us/sql/t-sql/queries/table-value-constructor-transact-sql?view=sql-server-2017#d-specifying-multiple-values-as-a-derived-source-table-in-a-merge-statement) as SOURCE.
I've tested in our solution - it works faster

**Comment by JonathanMagnan** [comment]
Hello @YuriAbele ,

Thank A LOT of sharing, we were not aware of Table Value Constructor.

Just looking at the syntax, I have no doubt that it will be faster.

We will for sure investigate it this week and see how to implement it.

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment]
Hello @YuriAbele ,

Thank you again for sharing this.

We investigated it and make some test but come to the conclusion that for existing SQL, no change will be made.

The number of rows is currently to low to make a performance difference.  Some features such as `AllowDuplicateKey` would not work either without a change, so we prefer to keep the current code.

However, we will for sure keep the `Table Value Constructor` in our mind for future features. That's for sure something to consider.

Best Regards,

Jonathan

**Comment by YuriAbele** [comment]
Hallo Jonathan,
the benefit of MERGE is - you can UPDATE, DELETE and INSERT (save ALL changes) in one trip (one table-scan).
Only for single type of DML operation you will find not big differences.
With MERGE you can also not only get back "INSERTED" virtual rows, but also type of action. From BOL:
_**$action**
**Is available only for the MERGE statement**. Specifies a column of type nvarchar(10) in the OUTPUT clause in a MERGE statement that returns one of three values for each row: 'INSERT', 'UPDATE', or 'DELETE', according to the action that was performed on that row._

**Comment by JonathanMagnan** [comment]
Hello @YuriAbele ,

Our library already uses `MERGE`, however, doesn't use `Table-Value`.

So we already take advantage of the merge statement ;)
