### ISSUE TITLE
AuditEntries types are not equal

### ISSUE THREAD

**Issue by ordinarytype** [zzzprojects/EntityFramework-Extensions#202]
Is it possible to make Z.EntityFramework.Plus.AuditEntry and Z.BulkOperations.AuditEntry equal?
Currently it will require additional conversion if you want to save audit entries from bulk operation.

**Comment by JonathanMagnan** [comment]
Hello @ordinarytype ,

They are from different libraries. So not really.

The EF Plus version take values directly from the `Change Tracker`
The Bulk Operations version take values directly from the Database

So they even work differently.

However, you can always "Import" manually value from an Audit to another by creating a mapping in your case. Pretty similar to the "Custom AuditEntry & Database First Approach" section in https://entityframework-plus.net/audit

Let me know if that answer correctly to your question.

Best Regards,

Jonathan

**Comment by ordinarytype** [comment]
Hello @JonathanMagnan 

I understand that they work differently, but seems that their structure is pretty close. 
Sharing this class between libraries will allow to easily use bulk operations with audit feature enabled. 

Thanks!

**Comment by JonathanMagnan** [comment]
We hope in the future EF Plus depend on EF Extensions.

My guess is that it will be done when `Batch Delete` and `Batch Update` would get the code re-write. At this moment, we will be able to share the `Audit` class but meanwhile, we prefer not doing it.

**Comment by ordinarytype** [comment]
Ok, so I will implement custom mapping on my end. 

Thanks!
