### ISSUE TITLE
BatchSaveChanges error when RollBack Executed on server (sample: in Trigger)

### ISSUE THREAD

**Issue by JoseMancebo** [zzzprojects/EntityFramework-Extensions#204]
### Description
When a RollBack Tran is fired on the server without an Begin Tran init on the server, the BatchSaveChanges throw an error.
If this action is executed with the standar SaveChanges, The error is clear: The transaction ended in the trigger. The lot was canceled.

If this action is executed with the BatchSaveChanges the error isn't clear, this is the complete stackTrace (Null Reference parameter connection):

> El valor no puede ser nulo.
> Nombre del parámetro: connection
> 
> System.ArgumentNullException
> 
> Message
> El valor no puede ser nulo.
> Nombre del parámetro: connection
> 
> ParamName
> connection
> Data
> System.Collections.ListDictionaryInternal
> TargetSite
> T NotNull[T](T, System.String)
> 
> StackTrace
>    en System.Data.Entity.Utilities.Check.NotNull[T](T value, String parameterName)
>    en System.Data.Entity.Infrastructure.Interception.DbTransactionInterceptionContext.WithConnection(DbConnection connection)
>    en System.Data.Entity.Infrastructure.Interception.DbTransactionDispatcher.Rollback(DbTransaction transaction, DbInterceptionContext interceptionContext)
>    en System.Data.Entity.Core.EntityClient.EntityTransaction.Rollback()
> 
> Source
> EntityFramework
> HResult
> -2147467261
> 
> System.Data.Entity.Core.EntityException
> Message
> Error del proveedor subyacente en Rollback.
> 
> Data
> System.Collections.ListDictionaryInternal
> 
> TargetSite
> Boolean Guardar()
> 
> StackTrace
>    en Taaf.Immo.Presentation.WPF.ViewModels.VMClientesFicha.Guardar() en D:\WORK\Proyectos\TAAF.IMMO TFS Service\Dev\src\Presentation.WPF\ViewModels\Clientes\VMClientesFicha.cs:línea 744
>    en Taaf.Immo.Presentation.WPF.ViewModels.VMClientesFicha.<>c__DisplayClass65_0.<SaveExecute>b__0() en D:\WORK\Proyectos\TAAF.IMMO TFS Service\Dev\src\Presentation.WPF\ViewModels\Clientes\VMClientesFicha.cs:línea 402
>    en Taaf.Immo.Presentation.WPF.Helpers.TaskUtilities`1.<>c__DisplayClass0_0.<CreateTask>b__0() en D:\WORK\Proyectos\TAAF.IMMO TFS Service\Dev\src\Presentation.WPF\Helpers\TaskUtilities.cs:línea 20
>    en System.Threading.Tasks.Task`1.InnerInvoke()
>    en System.Threading.Tasks.Task.Execute()
> 
> 
> Source
> Taaf.Immo.Presentation.WPF
> 
> HResult
> -2146233087
> 
> System.AggregateException
> InnerExceptions
> System.Collections.ObjectModel.ReadOnlyCollection`1[System.Exception]
> 
> Message
> Se han producido uno o varios errores.
> 
> Data
> System.Collections.ListDictionaryInternal
> 
> HResult
> -2146233088

Another question, if the rollback is executed by a verification process with a error control (RaiseError) in the SavaChanges the error texts is visible. On the BatchSaveChanges only appear the null error.

For reproduce it, you can create a simple trigger in a table like this:
```
CREATE TRIGGER [dbo].[TRIGER_NAME]
   ON  [dbo].[TABLE_NAME]
   AFTER INSERT,DELETE,UPDATE
AS 
BEGIN
	
	ROLLBACK TRAN
	RAISERROR (N'Custom error!!!!!', -- Message text.  
           16, -- Severity,  
           1 -- State
		   ); -- Second argument.   
	
END
```
And then execute a BatchSaveChange with an update.

### Further technical details
- EF version: 6.0
- EF Extensions version: 3.17.4
- Database Provider: SQL Server 2014
- Net Framework: 4.0

**Comment by JonathanMagnan** [comment]
Hello @JoseMancebo ,

Thank you for reporting,

We will look at it.

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment]
Hello @JoseMancebo ,

The v3.17.6 has been released 4 days ago (I forgot to answer here).

If you re-run your Fiddle, you will notice the message error is now fixed.

Let me know if everything works as expected.

Best Regards,

Jonathan

**Comment by JoseMancebo** [comment]
Thanks Jonathan,
The issue seems solved.
