### ISSUE TITLE
BulkSaveChanges: after update to nuget 3.17.5 return error

### ISSUE THREAD

**Issue by pierom99** [zzzprojects/EntityFramework-Extensions#205]
### Description
BulkSaveChanges: after update to nuget 3.17.5 return error.
I am calling BulkSaveChanges inside a transaction where I have some new row to insert and some to update (of non related tables). The new rows are inserted in the db despite the transcation not committed!
After restoring the 3.17.4 the problem is no more present.

### Exception
An error occurred while updating the entries. See the inner exception for details. - Riferimento a un oggetto non impostato su un'istanza di oggetto. -    in lambda_method(Closure , DbTransaction )

   in .(DbTransaction )

   in ..(BulkOperation )

   in .Execute()

```
Exception message:
Stack trace:
```

### Further technical details
- EF version:3.17.5
- EF Extensions version:
- Database Provider:sqls erver

**Comment by JonathanMagnan** [comment]
Hello @pierom99 ,

We have indeed modified something with TransactionScope in the v3.17.5

Do you think you could share with us some code that will help us to discover what is happening?
You can send it in private here info@zzzprojects.com

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment]
Hello @pierom99 ,

Did you succeed to get a few more information on your side?

We made additional test today but found nothing again.

**Comment by pierom99** [comment]
Hi Jonathan

I replied some days ago to info@zzzprojects.com

This is what I wrote:

>
My code is really complex but I reproduce the problem with few instructions:

System.Exception: 'An error occurred while updating the entries. See the
inner exception for details. Stack:    in .Execute()
   in DbContextExtensions.(DbContext this, Boolean , Action`1 , Boolean
)
   in DbContextExtensions.BulkSaveChanges(DbContext this)
   in DbContextExtensions.BulkSaveChanges(ObjectContext this)
   in TTWE.test_testPiero.testTrans() in
C:\Users\Piero2\Desktop\TTWEVO\TTWE\TEST\testPiero.aspx.vb:riga 885 Inner:
Riferimento a un oggetto non impostato su un'istanza di oggetto.'
(translated: Object reference not set to an instance of an object)

with this simple code (VB)

            Dim oPP As PPTABLE
            Dim scopeOpt = New Transactions.TransactionScopeOption()
            Using transaction As New
System.Transactions.TransactionScope(scopeOpt, New TimeSpan(0, 10, 0))

                oPP = New PPTABLE
                oPP.CODICE_PRODOTTO = "aaa1"
                oPP.CODICE_CLIENTE = "bbb1"
                oPP.DATA_IF = Now.Date
                oPP.DATA_FF = DateAdd(DateInterval.Month, 1, Now.Date)
                oPP.ID_DITTA = 1 <http://clssession.oditta.id/>000
                oPP.ID_PS2_TIPO_CAUSALE =
clsEnum.enPs2CausalePrezzo.Trasferimento
                _dc.AddToPPTABLE(oPP)

                oPP = New PPTABLE
                oPP.CODICE_PRODOTTO = "aaa2"
                oPP.CODICE_CLIENTE = "bbb2"
                oPP.ID_DITTA =1000
                oPP.DATA_IF = Now.Date
                oPP.DATA_FF = DateAdd(DateInterval.Month, 1, Now.Date)
                oPP.ID_PS2_TIPO_CAUSALE =
clsEnum.enPs2CausalePrezzo.Trasferimento
                _dc.AddToMA_PS2_PREZZI(oPP)


                _dc.BulkSaveChanges()   'ERROR HERE
                transaction.Complete()
                _dc.AcceptAllChanges()
            End Using

_dc is an objectcontext (database first with 600 tables)

I work with SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED

regards
Piero

Il giorno mar 23 apr 2019 alle ore 16:23 Jonathan Magnan <
notifications@github.com> ha scritto:

**Comment by lancewynn** [comment]
I don't know if this is related, but I updated to 3.17.8 and saw intermittent:
System.Data.Entity.Core.EntityException: The underlying provider failed on Open. ---> System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'Transaction'.

reverting back to 3.17.2 resolved the issue.

**Comment by JonathanMagnan** [comment]
Hello @lancewynn ,

Thank for reporting,

It could be highly related.

Are you using `Async` method with a transaction scope? If you do, could you provide an example of how you do it which throw an error?

I just want to make sure if that's an issue on our side or on your side about how you use TransactionScope.

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment]
Hello @lancewynn ,

The v2.3.8 has been released.

We improved the error message in this version. We believe that an async task was used but the transaction was already disposed of via the code before the task gets executed.

Similar to the following example:

```csharp
Task task = null;
using (var transaction = new TransactionScope())
{
	task = ctx.BulkInsertAsync(list);
}

Task.WaitAll(task);
```

**Comment by lancewynn** [comment]
Thanks! It's also nice to see I'm not the only one who makes this type of mistake 😁. I'm sure the actual code with the issue was much more complex though.

Great job!

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
