### ISSUE TITLE
UnitTests: System.Exception : Stream not found.

### ISSUE THREAD

**Issue by kirtanpl** [zzzprojects/EntityFramework-Extensions#207]
### Description
Hello. I am encountering an issue when trying to unit test code using .UpdateFromQueryAsync() using Effort library to mock context.

### Exception
Exception trace is presented below
```
System.Exception : Stream not found.
   at .(DbContext this, String )
   at .(DbContext this, List`1 , String )
   at .(DbContext )
   at .(DbContext )
   at DbContextExtensions.GetModel(DbContext this)
   at DbContextExtensions.UpdateFromQuery[TEntity](IQueryable`1 query, Expression`1 updateExpression, Action`1 bulkOperationFactory)
   at System.Threading.Tasks.Task.Execute()
```

- Before running update method I do populate database with required data. 
- I am using database first approach

My app.config:
```
  <connectionStrings>
    <add name="MyEntities" connectionString="metadata=res://*/MyEntities.csdl|res://*/MyEntities.ssdl|res://*/MyEntities.msl;provider=System.Data.SqlClient;provider connection string=&quot;data source=testDB;initial catalog=mycatalogue;Integrated security=true;MultipleActiveResultSets=True;App=EntityFramework&quot;" providerName="System.Data.EntityClient" />
  </connectionStrings>
  
  <entityFramework codeConfigurationType="MyDbConfiguration">
    <defaultConnectionFactory type="System.Data.Entity.Infrastructure.LocalDbConnectionFactory, EntityFramework">
      <parameters>
        <parameter value="mssqllocaldb" />
      </parameters>
    </defaultConnectionFactory>
    <providers>
      <provider invariantName="System.Data.SqlClient" type="System.Data.Entity.SqlServer.SqlProviderServices, EntityFramework.SqlServer" />
      <provider invariantName="Effort.Provider" type="Effort.Provider.EffortProviderServices, Effort" />
    </providers>
  </entityFramework>
  
  <system.data>
    <DbProviderFactories>
      <add name="Effort.Provider" invariant="Effort.Provider" description="Effort.Provider" type="Effort.Provider.EffortProviderFactory,Effort" />  
    </DbProviderFactories>
  </system.data>
```

My context initialization:
```
EffortProviderConfiguration.RegisterProvider();
var fakeConnection = Effort.EntityConnectionFactory.CreateTransient("name=MyEntities");
var context = new MyEntities(fakeConnection);
```

This issue seems (for me) to be related to this issue https://github.com/zzzprojects/EntityFramework-Classic/issues/7 

### Further technical details
- EF version: 6.2.0
- EF Extensions version: 3.17.6

**Comment by JonathanMagnan** [comment]
Hello @kirtanpl ,

Thank you for reporting, we will look at what we can do.

While it was possible to fix it in EF Classic, a different approach will need to be taken here since we cannot modify the `Entity Framework` code this time.

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment]
Hello @kirtanpl,

Do you think you will be able to provide a runnable project/solution with this issue? My developer didn't success to exactly reproduce it.

We highly believe that the solution will involve something like this:
```csharp
Effort.Provider.EffortProviderConfiguration.RegisterProvider();
```

Before any call to Entity Framework or Effort, so if you want, you can directly try this and let us know the result.

**Comment by kirtanpl** [comment]
Unfortunately I am not allowed to share the code and creating a custom project with fake EDMX is quite complex but I'll think about it if we won't find solution otherwise.

Regarding you suggested solution: `RegisterProvider` is called during each test run (it's in SetUp). You want me to run it more often?

**Comment by JonathanMagnan** [comment]
We usually do it in this method on our side:

```csharp
[AssemblyInitialize()]
public static void MyTestInitialize(TestContext testContext)
{}
```

but it might be the same depending on the test framework you are using.

**Comment by kirtanpl** [comment]
I understand. Unfortunately your solution does not work for me. Do you have any other suggestions or you'd need to have an example code? Maybe issue is with EDMX configuration?

**Comment by JonathanMagnan** [comment]
Hello @kirtanpl ,

Sorry for the long delay.

Unfortunately, we have not been able to fix this issue. It seems we are not able to find the model name in this case.

Something you can do on your side is providing it to our library.

For example:

```csharp
EntityFrameworkManager.ModelNameFactory = context =>
            {
                if (context is TestToDropEntities)
                {
                    return "TestToDropModel";
                }

                throw new Exception("Unsupported context");
            };
```

That's not the ideal solution but at least a working one.

Let me know if that work for you.

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment]
Hello @kirtanpl ,

Did you succeed to make it works?
