### ISSUE TITLE
specified type is not registered on the target server error in EF core for spatial point bulk insert using entity framework extension 

### ISSUE THREAD

**Issue by DnyaneshwarShivbhakta** [zzzprojects/EntityFramework-Extensions#209]
### Description
I am using .net core MVC,entity framework core,entity framework extension.I am trying to insert bulk addresspoint in EF core through BulkInsertAsync method but I am getting error. "specified type is not registered on the target server". As entity frameworkcore have nettopologysuite for spatial data type.the bulkInsert method of entity framework extension works fine in entity framework 6 but not in the entity framework core
`var geometryFactory = NetTopologySuite.NtsGeometryServices.Instance.CreateGeometryFactory(srid: 4326);
var newBreadcrumbs = (from b in addressPoints

                                      select new BreadCrumb
                                      {
                                          CarrierId = carrierID,
                                          Point = geometryFactory.CreatePoint(new Coordinate(b.Longitude, b.Latitude)),
                                          Speed = b.Speed.GetValueOrDefault() * (Decimal)2.237,
                                          Direction = b.Direction,
                                          CapturedFrom = b.CapturedFrom,
                                          CapturedAt = DateTime.UtcNow,
                                          Accuracy = (Decimal)b.Accuracy,
                                          IsDisconnect = b.IsDisconnect,
                                          CreatedOn = DateTime.UtcNow,
                                          IsActive = true,
                                          CreatedBy=0,
                                          ModifiedBy=0,
                                          ModifiedOn=null
                                      }).ToList();
                  await dbCOntext.BulkInsertAsync(newBreadcrumbs);//gives error`

### Exception
specified type is not registered on the target server error

```

### Further technical details
- EF version:EF Core 2.2
- EF Extensions version:2.2.3
- Database Provider: Azure Sql server 2017

**Comment by JonathanMagnan** [comment]
Hello @DnyaneshwarShivbhakta ,

Thank you for reporting.

We will look at this issue. Our library currently doesn't support `nettopologysuite`, so it is a good time to check it and start to support it.

Best Regards,

Jonathan

**Comment by DnyaneshwarShivbhakta** [comment]
@jonthan when I can expect this issue to be fixed.Is there any timeline in which I can expect that this issue to be fixed from Entity framework extenaion

**Comment by JonathanMagnan** [comment]
Hello @DnyaneshwarShivbhakta ,

We are supposed to look at it during the weekend, so I might be able to give you a better estimate on Monday or Tuesday.

If everything goes well, it might be fixed on Monday otherwise I will give you an update.

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment]
Hello @DnyaneshwarShivbhakta ,

The development to support Spatial Type has been successfully completed.

My development will complete some unit test this Monday and a version on Monday night should be released unless some issue that we cannot quickly fix is found.

**Comment by DnyaneshwarShivbhakta** [comment]
@JonathanMagnan Thanks. Much appreciated. Once you release this new feature. I need to take the latest version of entity framework core from the nuget package. Am I right?

**Comment by JonathanMagnan** [comment]
Yes, updating to the latest version of EF Extensions will be needed.

**Comment by DnyaneshwarShivbhakta** [comment]
okay.Thanks.So for Spatial data as well we are getting the same performance as we are getting for other BulkInsert in the .net core? are you solving this problem for other operations as well like Bulk Update, Bulk merge, Bulk SaveChanges?

**Comment by DnyaneshwarShivbhakta** [comment]
@JonathanMagnan As discussed, Can I download the latest version of the Ef Extension now for this issue?

**Comment by JonathanMagnan** [comment]
Hello @DnyaneshwarShivbhakta ,

The v2.2.7 has just been released.

The support for spatial has been added.

Let me know if everything works as expected.

**Comment by JonathanMagnan** [comment]
Hello @DnyaneshwarShivbhakta ,

Did you get the time to try the latest version?

**Comment by DnyaneshwarShivbhakta** [comment]
@JonathanMagnan  Thanks, Jonathan. I forgot to reply on this, It's working fine, Its simply awesome thing you provided to the new version 2.2.7. Much needed support for EF core. It helps me to optimize my code by removing the SqlBulkCopy code from my codebase.

**Comment by DnyaneshwarShivbhakta** [comment]
@JonathanMagnan you can close this thread now.
