### ISSUE TITLE
Exception : The wait operation timed out with BulkInsert

### ISSUE THREAD

**Issue by aymengrun** [zzzprojects/EntityFramework-Extensions#21]
When inserting a list of 900.000 lines with BulkInsert we always get the exception : "The wait operation timed out with BulkInsert".
Even with setting a 6 hours timeout we continue get this exception, we even tried a huge 2 days timeout and the result is the same.

**Comment by zzzprojects** [comment]
Hello @aymengrun ,

- How do you set the timeout?
- Can you show the stack trace?

We tested a BulkInsert with a timeout of 1s and here is the error we get:

> A timeout error occured. Please increase the timeout globally: ctx.Database.CommandTimeout = 60; or BulkOperationManager.BulkOperationBuilder = operation => operation.BatchTimeout = 60; or by operation: db.BulkSaveChanges(operation => operation.BatchTimeout = 60);

Which is different than yours. 

The BatchTimeout (1s) worked in our example.

```csharp
var list = new List<IssueBulkInsert>();
for (int i = 0; i < 1000000; i++)
{
    list.Add(new IssueBulkInsert());
}

ctx.BulkInsert(list, operation =>
{
    operation.BatchTimeout = 1;
    operation.BatchSize = 1000000;
});
```

So we are not sure yet if this is causing by our library (not taking correctly the timeout) or something else. The Strack Trace may help us to find out what's happening.

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment]
Hello @aymengrun ,

Do you still get the issue?

Can we close it?

**Comment by aymengrun** [comment]
Hello,

The problem is no longer relevant and also the trial period of the Library expired so we are no longer able to re test.

Thanx.

**Comment by JonathanMagnan** [comment]
Hello @aymengrun ,

To extend the trial, simply download the latest version.

We always release a new version every month with the trial enabled. So in short, you can evaluate the product for several months until your application is production ready by simply downloading the latest version at the beginning of each month.

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment]
Closing Comment: No longer relevant.
