### ISSUE TITLE
Exception on Update/UpdateFromQuery (invalid cast)

### ISSUE THREAD

**Issue by MaklaCof** [zzzprojects/EntityFramework-Extensions#210]
### Description
I get the same exception when I call `UpdateFromQueryAsync` or `UpdateAsync`.

### Exception

Exception message:
```
Invalid Cast. The update expression must be of type MemberInitExpression.
```
Stack trace:
```
   at Z.EntityFramework.Extensions.BatchUpdate.ResolveUpdateFromQueryDictValues[T](Expression`1 updateFactory)
   at Z.EntityFramework.Extensions.BatchUpdate.GetInnerValues[T](IQueryable`1 query, Expression`1 updateFactory, IEntityType entity)
   at Z.EntityFramework.Extensions.BatchUpdate.Execute[T](IQueryable`1 query, Expression`1 updateFactory)
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
--- End of stack trace from previous location where exception was thrown ---
   at OpPIS.Web.Core.Services.Shareable.TableServices`2.MarkAsDeleted(String lang, Int32[] ids) in E:\OpPIS.Web\OpPIS.Web.Core\Services\Shareable\ITable.Table.cs:line 468
```

### Partial source code
```
            var row = new TEntity();     //Generic
            ((IDbDeletedDateTime)row).DeletedDateTime = DateTime.UtcNow;
            ((IDbDeletedUserId)row).DeletedUserId =1;

            var tempData = await this.Query(t => ids.Contains(t.Id)).ToArrayAsync();        //Just for debugging
            await this.Query(t => ids.Contains(t.Id)).UpdateFromQueryAsync(t => row);
```
I also try with `UpdateAsync` although I don't know what's the difference.

Image:
![devenv_2019-05-09_10-38-50](https://user-images.githubusercontent.com/1589573/57439671-cc289680-7246-11e9-8734-afa6eb9af457.png)

### Further technical details
- `<PackageReference Include="Z.EntityFramework.Extensions.EFCore" Version="2.2.5" />`
- `<PackageReference Include="Z.EntityFramework.Plus.EFCore" Version="1.8.27" />`
- `<PackageReference Include="Microsoft.EntityFrameworkCore" Version="2.2.3" />`
- Database Provider: SQLServer

**Comment by MaklaCof** [comment]
I also prepared [fiddle](https://dotnetfiddle.net/0XBnVc).
I am starting to think this is not possible. (Creating object outside `Update` statement).

In this case, I have a question, how can I dynamically build what I want to update?

My real case is this:
```
var row = new TEntity();
if (typeof(IdbDeletedDateTime).IsAssignableFrom(typeof(TEntity)))
  ((IdbDeletedDateTime)row).DateTimeDeleted = DateTime.UtcNow;
if (typeof(IdbDeletedUser).IsAssignableFrom(typeof(TEntity)))
  ((IdbDeletedUser)row).UserDeleted = logged_in_user_id;
....UpdateAsync(t => row);
```

**Comment by JonathanMagnan** [comment]
Hello @MaklaCof ,

The `UpdateFromQuery` require an expression, you cannot directly pass the entity otherwise the method doesn't know which properties to update.

One easy way to do it is by using the C# Eval Expression library (Included in the EF Extensions Licenses)

The C# Eval Expressions allow you to execute code dynamically at runtime and a lot more.

For example, in this case: https://dotnetfiddle.net/oyJhZp

You can easily replace some part of the string with some parameter as well.

Perhaps taking some time to look at this library might worth it to support this kind of case?

Let me know if that answer to your issue.

Best Regards,

Jonathan

**Comment by MaklaCof** [comment]
Hi, I know eval and we are using it, but in this case we would like to avoid it.
What about feature request, where `UpdateAsync` would also accept `IDictionary<string, object>`? 

Should I make new issue? Does this make sense to your company. I think I am not the only PRO customer who would use this overload.

**Comment by JonathanMagnan** [comment]
Hello @MaklaCof ,

It makes a lot of sense.

We can probably easily on our side add an overload and create the Expression on our side.

We will probably check it this request during the weekend but I don't see any problem by supported a dictionary.

**Comment by JonathanMagnan** [comment]
Hello @MaklaCof ,

The v3.18.1 has been released.

We added support to IDictionary and ExpandoObject

Let me know if everything is working as expected.

Best Regards,

Jonathan

**Comment by MaklaCof** [comment]
Awesome. It works.
