### ISSUE TITLE
Increment with BulkMerge

### ISSUE THREAD

**Issue by vladrednic** [zzzprojects/EntityFramework-Extensions#214]
Is there a way to tell BulkMerge to execute on update: count = count + entityvalue

**Comment by JonathanMagnan** [comment]
Hello @vladrednic ,

It's currently possible but will require you to map all your properties.

We will look during the weekend if something can be done to make it easier on your side.

Best Regards,

Jonathan

**Comment by vladrednic** [comment]
I appreciate it!

**Comment by JonathanMagnan** [comment]
Hello @vladrednic ,

One way to do it is by using the `PostConfiguration` event which happens after everything is mapped (column, tableName, etc.)

Example:

```csharp
ctx.BulkMerge(list, options =>
{
	options.PostConfiguration = operations =>
	{
		var columnMappings = operations.ColumnMappings;

		var column = columnMappings.Single(x => x.SourceName == "ColumnInt");
		column.FormulaUpdate = "DestinationTable.ColumnInt + StagingTable.ColumnInt";
	};
});
```

In this example, we retrieve the column and set a Formula:
- DestinationTable: is the alias used for the table in which the operation is performed
- StagingTable: is the alias used for the table which contains all informations about data to update

We are still trying to make this code better but we wanted at least to give you a solution meanwhile.

Let me know if that solution could work for you or if you need more explanation.

**Comment by vladrednic** [comment]
Thank you. I'll give it a try and will get back to you.

**Comment by vladrednic** [comment]
I'm missing the PostConfiguration event. Updated to the latest version, still missing.

Using Z.EntityFramework.Extensions.EFCore (2.2.9) package with SQLite.

**Comment by vladrednic** [comment]
If you would tell me how to do this with UpdateFromQuery, I would appreciate it. I might need it in the future.

**Comment by JonathanMagnan** [comment]
Hello @vladrednic ,

Sorry for the long waiting.

We couldn't make it work with `UpdateFromQuery` due to how the syntax is made with SQLite.

However, the latest v2.3.7 should now work using the previous code:
- We recently added the `PostConfiguration` for EF Core
- We added support to the formula for SQLite (column name will be modified by parameter name before the SQL get executed.

Could you try again the following code with the latest version:

```csharp
ctx.BulkMerge(list, options =>
{
	options.PostConfiguration = operations =>
	{
		var columnMappings = operations.ColumnMappings;

		var column = columnMappings.Single(x => x.SourceName == "ColumnInt");
		column.FormulaUpdate = "DestinationTable.ColumnInt + StagingTable.ColumnInt";
	};
});
```

It should now work

**Comment by vladrednic** [comment]
In the meantime, I found a workaround. I'll give it a try and will let you know

**Comment by JonathanMagnan** [comment]
We will close this request since a solution has been released and you found a workaround.

If there is anything, please let us know and we will re-open it.

**Comment by vladrednic** [comment]
Finally got to try it with the latest version and it works fine. Thank you.

**Comment by JonathanMagnan** [comment]
Thank for letting me know ;)
