### ISSUE TITLE
Choose which columns are compared when doing a merge

### ISSUE THREAD

**Issue by mmiller678** [zzzprojects/EntityFramework-Extensions#219]
Is there a way to in BulkMerge to tell EFE what fields you would like to compare on for a update to occur.  For instance here is how I would like the merge to work.

 I want to match on on the PK value then do one of two things:
* If there is a match on PK but no changes  set the IsActive field to true
* if there is a match on PK and any of fields have changed set the IsActive field to true and set DateModified field to DateTime.Now
* If there isn't a match on PK do an insert (no change in behavior)

The logic for determining if "the fields have changed" is compare all the fields except for DateCreated/DateModified/IsActive

This might be outside the scope of how Merge works in SQL Server.

**Comment by JonathanMagnan** [comment]
Hello @mmiller678 ,

It is possible to choose to `UPDATE` or not depending as if there is a match and if a change happened or not.

However, the MERGE statement only allows 1 UPDATE, so both cases cannot be done at the same time.

Is the following logic could work for you:
- Make an UPDATE to set the IsActive field to true
- Make an MERGE
   - INSERT if there is no match
   - UPDATE if there is a match and any field has been modified
   - DO NOTHING if there is a match but no field has been modified

The option `IgnoreOnMergeMatchedAndOneNotConditionExpression` is what you are looking for.

It will check all fields but the one you want to ignore (DateModified?), and will only perform the UPDATE part is there is a value different.

Fiddle: https://dotnetfiddle.net/djAD9g

Let me know if you need some help to make it works. Those option are not obvious.

Best Regards,

Jonathan

**Comment by mmiller678** [comment]
I am a bit confused by the property names.  What is difference between:

options.MergeMatchedAndConditionExpression
options.MergeMatchedAndOneNotConditionExpression
options.IgnoreOnMergeMatchedAndConditionExpression
options.IgnoreOnMergeMatchedAndOneNotConditionExpression

Based you on your fiddle IgnoreOnMergeMatchedAndOneNotConditionExpression takes a list of fields that you want to use in the compare to determine if you want to do the update (based on the name I thought it would have been the fields NOT to use in the comparison).  Is there a way to specify the fields not to use in the comparison (I have over 100 properties on my merge object and keeping them in sync as I add more properties isn't ideal when I want to ignore a single property when determining if there is a on merge).

I don't see these documented on the site so its difficult to understand all the options (there are some additional properties as well such as Lamba based expressions). I think some documentation and examples around each of these would be very helpful.

**Comment by JonathanMagnan** [comment]
Yes, our documentation is lacking.

I tried to improve it myself but failed to find enough time to make a good one. So we hired someone that wrote several tutorials and dedicated only on the documentation.

He is still learning the library but he already added a lot of new pages that will be released on the website this weekend: https://github.com/zzzprojects/EntityFramework-Extensions/pull/217

**options.MergeMatchedAndConditionExpression**
Perform the `UPDATE` part only if all values for properties specified are equal to database value.

**options.MergeMatchedAndOneNotConditionExpression**
Perform the `UPDATE` part only if one value for properties specified is not equal to database value.

**options.IgnoreOnMergeMatchedAndConditionExpression**
Similar to MergeMatchedAndConditionExpression. However it map all properties by default and remove the one you choose to ignore.

**options.IgnoreOnMergeMatchedAndOneNotConditionExpression**
Similar to MergeMatchedAndOneNotConditionExpression. However it map all properties by default and remove the one you choose to ignore.

---

>  Is there a way to specify the fields not to use in the comparison (I have over 100 properties on my merge object and keeping them in sync as I add more properties isn't ideal when I want to ignore a single property when determining if there is a change and the merge should occur).

Yes, the option `IgnoreOnMergeMatchedAndOneNotConditionExpression` will map all properties but will ignore the one you choose. It's similar to map the other 99 properties in the `MergeMatchedAndOneNotConditionExpression`.

You can find the documentation not yet released here: https://github.com/zzzprojects/EntityFramework-Extensions/pull/217/commits/b08c559cb720980cf601f175974eb26dbd461598

Let me know if that answer correctly to your question.
