### ISSUE TITLE
DeleteFromQuery and UpdateFromQuery  SqlException

### ISSUE THREAD

**Issue by sonwoo** [zzzprojects/EntityFramework-Extensions#22]
Primary key has bigint type and Identitiy specifications enabled is error.
but It was normal after changing int type.

What should I do?

Error Message Contents=>
 위치: System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   위치: System.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   위치: System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   위치: System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   위치: System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString)
   위치: System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 timeout, Task& task, Boolean asyncWrite, SqlDataReader ds, Boolean describeParameterEncryptionRequest)
   위치: System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean asyncWrite)
   위치: System.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource`1 completion, String methodName, Boolean sendToPipe, Int32 timeout, Boolean asyncWrite)
   위치: System.Data.SqlClient.SqlCommand.ExecuteNonQuery()
   위치: ..(SqlCommand , BulkOperation , Int32 )
   위치: ..(DbCommand , BulkOperation , Int32 )
   위치: ..( )
   위치: ..(List`1 )
   위치: ..(List`1 )
   위치: ..(BulkOperation )
   위치: Z.BulkOperations.BulkOperation`1.(IQueryable , IQueryable )
   위치: DbContextExtensions.[](IQueryable`1 , Action`1 , CancellationToken )
   위치: DbContextExtensions.DeleteFromQuery[TEntity](IQueryable`1 query, Action`1 bulkOperationFactory)

**Comment by zzzprojects** [comment]
Hello soowoo,

Something is missed to let me reproduce this issue. Can you help me by using the code below?

As you seen, I have created two entities:
- One with int key and identity
- One with int64/bigint key and identity

But both are working correctly

```csharp
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Windows.Forms;

namespace Z.EntityFramework.Extensions.Lab
{
    public partial class Form_Request_DeleteFromQuery : Form
    {
        public Form_Request_DeleteFromQuery()
        {
            InitializeComponent();

            // SEED
            using (var ctx = new CurrentContext())
            {
                var listInt = new List<EntityInt>();
                var listBigInt = new List<EntityBigInt>();

                for (int i = 0; i < 5; i++)
                {
                    listInt.Add(new EntityInt() { ColumnInt = 1 });
                    listBigInt.Add(new EntityBigInt() { ColumnInt = 2 });
                }

                ctx.EntityInts.AddRange(listInt);
                ctx.EntityBigInts.AddRange(listBigInt);
                ctx.SaveChanges();
            }

            // TEST
            using (var ctx = new CurrentContext())
            {
                ctx.EntityInts.DeleteFromQuery();
                ctx.EntityBigInts.DeleteFromQuery();
            }
        }

        public class CurrentContext : DbContext
        {
            public CurrentContext()
                : base("CodeFirstEntities")
            {
            }

            public DbSet<EntityInt> EntityInts { get; set; }
            public DbSet<EntityBigInt> EntityBigInts { get; set; }

            protected override void OnModelCreating(DbModelBuilder modelBuilder)
            {
                modelBuilder.Types().Configure(x => x.ToTable(GetType().DeclaringType != null ? GetType().DeclaringType.FullName.Replace(".", "_") + "_" + x.ClrType.Name : ""));

                base.OnModelCreating(modelBuilder);
            }
        }

        public class EntityInt
        {
            public int ID { get; set; }

            public int ColumnInt { get; set; }
        }

        public class EntityBigInt
        {
            public Int64 ID { get; set; }

            public int ColumnInt { get; set; }
        }
    }
}
```

**Comment by sonwoo** [comment]
Yes you are right!
I did a comparison and found that I was wrong.
Thanks for your help.
