### ISSUE TITLE
BatchSaveChangesAsync method is not present for the Entity framework core library

### ISSUE THREAD

**Issue by DnyaneshwarShivbhakta** [zzzprojects/EntityFramework-Extensions#221]
### Description
I am not able to see BatchSaveChangesAsync method for the entity framework core library. Can you please provide support for this method in Entity framework core

### Exception

```
Exception message:
Stack trace:
```

### Fiddle or Project (Optional)
If you are able, 

Provide a Fiddle that reproduces the issue: https://dotnetfiddle.net/Uqe9sf

Or provide a project/solution that we can run to reproduce the issue.
- Make sure the project compile
- Make sure to provide only the code that is required to reproduce the issue, not the whole project
- You can send private code here: info@zzzprojects.com

Otherwise, make sure to include as much information as possible to help our team to reproduce the issue.

_Note: More information you provide, faster we can implement a solution._

### Further technical details
- EF Core version:2.0
- EF Extensions version:2.2.7
- Database Provider:Sql server 2017

**Comment by JonathanMagnan** [comment]
Hello @DnyaneshwarShivbhakta ,

Unfortunately, at this moment, one limitation of `BatchSaveChanges` is only EF6 is supported
See: https://entityframework-extensions.net/batch-savechanges#limitations

We will try to include it in our todo list for next month.

**Comment by tj111** [comment]
Is there any intention of bringing this to EF Core?

**Comment by JonathanMagnan** [comment]
Hello @tj111 ,

Unfortunately not at this moment.

`EF Core` already does a great job by batching in their `SaveChanges` method.

While we indeed succeed to improve the performance, the gain was not enough major that we preferred instead of not adding that feature.

Best Regards,

Jon
