### ISSUE TITLE
Bulk Operations / ChangeTracker / Soft Delete

### ISSUE THREAD

**Issue by afussit** [zzzprojects/EntityFramework-Extensions#23]
Hi,

is there a possibility to intercept bulk entities to perform for example a soft delete (change delete status to update status) or change some information in created/updated bulk entities before executed in the database? The bulk entities are not reachable in DbContext.ChangeTracker().Entities(). Could you please show an example how to do that? Thanks!

`    public class DbContextBase : DbContext
    {
        public override int SaveChanges()
        {
            this.ApplyConcepts()
            return base.SaveChanges();
        }

        protected override void ApplyConcepts()
        {
            var entries = this.ChangeTracker.Entries();

            if (entries != null)
            {
                foreach (var entry in entries)
                {
                    switch (entry.State)
                    {
                        case EntityState.Added:
                            this.ApplyCreationConcept(entry);
                            break;

                        case EntityState.Modified:
                            this.ApplyUpdateConcept(entry);
                            break;

                        case EntityState.Deleted:
                            this.ApplyDeletedConcept(entry);
                            break;
                    }
                }
            }
        }

        protected virtual void ApplyCreationConcept(DbEntityEntry entry)
        {
            // entry.XXX = ....
        }

        protected virtual void ApplyDeletedConcept(DbEntityEntry entry)
        {
            // soft delete (change to update)
            entry.State = EntityState.Modified;
            entry.IsDeleted = true;
        }

        protected virtual void ApplyUpdateConcept(DbEntityEntry entry)
        {
            // entry.XXX = ....
        }
    }`

**Comment by zzzprojects** [comment]
Hello @afussit ,

Thank you for contacting us with this question. I must currently leave for the morning but once I will be back, I will provide you a solution to allow Soft Delete.

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment]
GitHub unlocked my account,

You can find the article here: http://www.zzzprojects.com/entity-framework-extensions/docs/how/soft-delete

We will improve it over time with questions & comments.

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment]
Closing comment: Article provided
