### ISSUE TITLE
Transactions.Current setter is causing Disposed Transactions to Appear

### ISSUE THREAD

**Issue by jahn-swob** [zzzprojects/EntityFramework-Extensions#232]
### Description
The use of the setter for `Transaction.Current` is causing disposed transactions to appear when used with awaited (`async`) methods and resuming on the main thread.

This particular issue is highlighted with the use of `TransactionScope` with the `TransactionScopeAsyncFlowOption.Enabled` provided in the constructor.

Normally in the lifecycle of an async `TransactionScope`, the ambient transaction (`Transaction.Current`) set by the construction of the `TransactionScope` and removed at the disposal of the `TransactionScope`.  When this is done, the framework checks if the `TransactionScopeAsyncFlowOption.Enabled` was indicated and populates the Transaction in the `CallContext` instead of the `ThreadStatic` so that in subsequent asynchronous calls the `Transaction` is passed around successfully.  However, on manually setting the `Transaction.Current` in an application method, it assigns the `Transaction.Current` to the `ThreadStatic` instead of the `CallContext`, resulting in the `Transaction.Current` to have a reference in the original main invocation thread.  In these cases after the `TransactionScope` has completed in a different thread, the instance of the disposed `Transaction` is now available to the main thread and Entity Framework will eagerly attempt to Enlist to an available `Transaction.Current` that is not `null`.  However, in this case, the `TransactionScope` object has set the internal `Disposed` variable to true and upon accessing the object by Entity Framework to enlist into the Transaction will cause an `ObjectDisposedException` to occur.

The nature of this issue in practice can be semi-apparent based on thread disposal, but is a very real issue when encountered in a production environment (which we have and had to mitigate using Reflection into the `Transaction.Current` object), causing erroneous exceptions to occur in unexpected places. 

We have noticed that this product uses the `Transaction.Current` in numerous places and may have the capacity to trigger this issue.  We wanted to bring this to your attention in order to possibly fix this issue at large.  We have also created a sample GitHub repository to demonstrate the issue of using the setter of `Transaction.Current` in practice while not using your library within the code to show the overall issue of using the setter.
* https://github.com/ogsys/Zombies/blob/master/Tests.cs

Also another note, we noticed that the Async methods may not truly be asynchronous in nature and primarily just wrapping synchronous actions within a Task.Run, this can cause Thread waits instead of allowing a Thread to return to the ThreadPool to pursue available work.  This is more apparent in CPU sensitive environments, like the Cloud.

### Exception
* `ObjectDisposedException` from Transaction.Current

### Fiddle or Project (Optional)
* https://github.com/ogsys/Zombies/blob/master/Tests.cs

### Further technical details
- EF version: 6.2.0
- EF Extensions version: 3.20.1
- Database Provider: MSSQL 2017

**Comment by JonathanMagnan** [comment]
Hello @jahn-swob,

Thank a lot for all this information.

We will certainly look at it very attentively.

**Comment by JonathanMagnan** [comment]
Hello @jahn-swob ,

Thank again for reporting this and your great project. You surely showed that we were wrong.

The v3.21.0 has been released. We removed all assignation recently introduced to the `Transaction.Current`.

Let me know if the latest version works correctly for you.
