### ISSUE TITLE
Cancellable async operations

### ISSUE THREAD

**Issue by sergey-netdev** [zzzprojects/EntityFramework-Extensions#24]
It would be nice to have `DbContextExtensions` overloads that accept `CancellationToken` parameter :

```
public static class DbContextExtensions
{
    public static Task BulkDeleteAsync<T>(this DbContext @this, IEnumerable<T> entities) where T : class;
    public static Task BulkDeleteAsync<T>(this DbContext @this, IEnumerable<T> entities, Action<EntityBulkOperation<T>> bulkOperationFactory) where T : class;
....
}
```

Please?

**Comment by JonathanMagnan** [comment]
Hello @sergey-netdev ,

Thank you for reporting this issue. The CancellationToken overload will be added this weekend.

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment]
Hello @sergey-netdev ,

The v3.10.32 is now available.

You can now use the overload with CancellationToken. We check if a cancellation has been requested before every database round trip.

Let us know if we can close this issue.

Best Regards,

Jonathan

**Comment by sergey-netdev** [comment]
Thank you! Exactly what was needed.

**Comment by JonathanMagnan** [comment]
Great ;) Have a nice weekend.
