### ISSUE TITLE
No database provider has been configured for this DbContext

### ISSUE THREAD

**Issue by JasonDevStudio** [zzzprojects/EntityFramework-Extensions#241]
### Description
我在尝试更新的时候报下面的错误,我的程序使用 EntityFramework.Core 已经可以正常查询oracle里面的数据,在使用EFE.CORE时报错,请问怎么设置Oracle驱动?

### Exception
System.InvalidOperationException: No database provider has been configured for this DbContext. A provider can be configured by overriding the DbContext.OnConfiguring method or by using AddDbContext on the application service provider. If AddDbContext is used, then also ensure that your DbContext type accepts a DbContextOptions<TContext> object in its constructor and passes it to the base constructor for DbContext.
   在 Microsoft.EntityFrameworkCore.Internal.DbContextServices.Initialize(IServiceProvider scopedProvider, IDbContextOptions contextOptions, DbContext context)
   在 Microsoft.EntityFrameworkCore.DbContext.get_InternalServiceProvider()
   在 Microsoft.EntityFrameworkCore.DbContext.Microsoft.EntityFrameworkCore.Infrastructure.IInfrastructure<System.IServiceProvider>.get_Instance()
   在 Microsoft.EntityFrameworkCore.Infrastructure.DatabaseFacade.Microsoft.EntityFrameworkCore.Infrastructure.IInfrastructure<System.IServiceProvider>.get_Instance()
   在 Microsoft.EntityFrameworkCore.Internal.InternalAccessorExtensions.GetService[TService](IInfrastructure`1 accessor)
   在 Microsoft.EntityFrameworkCore.Infrastructure.AccessorExtensions.GetService[TService](IInfrastructure`1 accessor)
   在 .[](BulkOperation`1 this, DbContext , IEntityType , List`1 )
   在 .[](BulkOperation`1 this, DbContext , IEntityType , List`1 , BulkOperationActionType )
   在 .[](DbContext this, IEnumerable`1 , Action`1 )
   在 DbContextExtensions.BulkUpdate[T](DbContext this, IEnumerable`1 entities, Action`1 options)
   在 HisiCAD.EFCore.DataAccess.EFCoreHelper`1.BulkUpdate[TEntity](List`1 entities, String operateUser, Expression`1 keyExp, Expression`1 inputExp, Expression`1 ignoreExp) 位置 D:\02_Projects\00_LabDataStudio\90_HisiWisdom.CSharp.Framework\src\Utilities\HisiCAD.EFCore.DataAccess\EFCoreHelper.cs:行号 189
   在 Hisi.CAD.EFCore.DataAccess.Test.Program.Main(String[] args) 位置 D:\02_Projects\00_LabDataStudio\90_HisiWisdom.CSharp.Framework\src\Hisi.CAD.EFCore.DataAccess.Test\Program.cs:行号 34

 
### Further technical details
- EF version: Microsoft.EntityFrameworkCore 2.2.4 
- EF Extensions version: Z.EntityFramework.Extensions.EFCore 2.6.3
- Database Provider: Oracle.EntityFrameworkCore 2.0.19   Oracle.ManagedDataAccess 2.0.19.1

**Comment by JonathanMagnan** [comment]
Hello @JasonDevStudio ,

Is it possible for you to provide a runnable solution with this issue?

You can send it in private here info@zzzprojects.com

**Comment by JasonDevStudio** [comment]
`namespace DataAccess
{
    using System;
    using System.Data.Common;
    using System.Text;
    using HisiCAD.EFCore.DataAccess.Entities;
    using Microsoft.EntityFrameworkCore;

    #region Classes

    /// <summary>
    /// 使用的数据操作上下文 继承DbContext类
    /// </summary>
    public class DbContextBase : DbContext, IDisposable
    {
        #region Constructors

        /// <summary>
        /// Initializes a new instance of the <see cref="DbContextBase"/> class.
        /// </summary>
        public DbContextBase()
            : base()
        {
            this.DbLog = new StringBuilder();
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="DbContextBase"/> class.
        /// </summary>
        /// <param name="existingConnection">要用于新的上下文的现有连接。</param>
        /// <param name="contextOwnsConnection">如果设置为 true，则释放上下文时将释放该连接；否则调用方必须释放该连接。</param>
        public DbContextBase(DbConnection existingConnection, bool contextOwnsConnection)
        {
            this.DbLog = new StringBuilder();
            this.DbConnection = existingConnection;
            this.ContextOwnsConnection = contextOwnsConnection;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="DbContextBase"/> class.
        /// </summary>
        /// <param name="options">DbContextOptions</param>
        public DbContextBase(DbContextOptions options)
            : base(options)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="DbContextBase"/> class.
        /// </summary>
        /// <param name="dbinfo">The dbinfo<see cref="IDbInfo"/></param>
        public DbContextBase(IDbInfo dbinfo)
        {
            this.Host = dbinfo.HOST;
            this.Port = dbinfo.PORT;
            this.ServiceName = dbinfo.SID;
            this.OracleUserName = dbinfo.USERNAME;
            this.CacheKey = dbinfo.USERNAME;
            this.OraclePassword = dbinfo.PASSWORD;
            this.Privilege = string.Empty;
            this.ConnectionString = dbinfo.CONNECT_STRING;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="DbContextBase"/> class.
        /// </summary>
        /// <param name="connectionString">数据库名称或连接字符串。</param>
        public DbContextBase(string connectionString)
        {
            this.DbLog = new StringBuilder();
            this.ConnectionString = connectionString;
        }

        #endregion

        #region Properties

        /// <summary>
        /// Gets or sets the CacheKey
        /// Gets or sets or sets 缓存KEY
        /// </summary>
        public string CacheKey { get; set; }

        /// <summary>
        /// Gets or sets the ConnectionString
        /// Gets or sets NameOrConnectionString
        /// </summary>
        public string ConnectionString { get; set; }

        /// <summary>
        /// Gets or sets a value indicating whether ContextOwnsConnection
        /// Gets or sets ContextOwnsConnection
        /// </summary>
        public bool ContextOwnsConnection { get; set; }

        /// <summary>
        /// Gets or sets the DbConnection
        /// Gets or sets DbConnection
        /// </summary>
        public DbConnection DbConnection { get; set; }

        /// <summary>
        /// Gets the DBCont
        /// DbContext
        /// </summary>
        public DbContext DBCont { get; private set; }

        /// <summary>
        /// Gets or sets the DbLog
        /// Gets or sets or sets 数据库日志
        /// </summary>
        public StringBuilder DbLog { get; set; }

        /// <summary>
        /// Gets or sets the Host
        /// Gets or sets 数据库 IP
        /// </summary>
        public string Host { get; protected set; }

        /// <summary>
        /// Gets or sets the OraclePassword
        /// Gets or sets 数据库 密码
        /// </summary>
        public string OraclePassword { get; protected set; }

        /// <summary>
        /// Gets or sets the OracleUserName
        /// Gets or sets 数据库名
        /// </summary>
        public string OracleUserName { get; protected set; }

        /// <summary>
        /// Gets or sets the Port
        /// Gets or sets 数据库端口
        /// </summary>
        public decimal Port { get; protected set; }

        /// <summary>
        /// Gets or sets the Privilege
        /// Gets or sets 数据库 DBA 权限
        /// </summary>
        public string Privilege { get; protected set; }

        /// <summary>
        /// Gets or sets the ProjectDbInfoId
        /// Gets or sets 数据库 Id
        /// </summary>
        public decimal? ProjectDbInfoId { get; set; }

        /// <summary>
        /// Gets or sets the ProjectId
        /// Gets or sets 项目ID
        /// </summary>
        public decimal? ProjectId { get; set; }

        /// <summary>
        /// Gets or sets the ServiceName
        /// Gets or sets 数据库 Service Name
        /// </summary>
        public string ServiceName { get; protected set; }

        #endregion

        #region Methods

        /// <summary>
        /// 释放
        /// </summary>
        public void ExDispose()
        {
            try
            {
                if (this.Database != null)
                {
                    this.Database.CloseConnection();
                }

                this.Dispose();
            }
            catch (System.Exception)
            {
            }
        }

        /// <summary>
        /// 重新创建数据库连接
        /// </summary>
        /// <returns>DbConnection</returns>
        protected virtual DbConnection CreateDBConn()
        {
            return null;
        }

        /// <summary>
        /// Override this method to configure the database (and other options) to be used
        /// for this context. This method is called for each instance of the context that
        /// is created. The base implementation does nothing.
        /// In situations where an instance of Microsoft.EntityFrameworkCore.DbContextOptions
        /// may or may not have been passed to the constructor, you can use Microsoft.EntityFrameworkCore.DbContextOptionsBuilder.IsConfigured
        /// to determine if the options have already been set, and skip some or all of the
        /// logic in Microsoft.EntityFrameworkCore.DbContext.OnConfiguring(Microsoft.EntityFrameworkCore.DbContextOptionsBuilder).
        /// </summary>
        /// <param name="optionsBuilder">A builder used to create or modify options for this context. Databases (and other extensions) typically define extension methods on this object that allow you to configure the context.</param>
        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            base.OnConfiguring(optionsBuilder);
        }

        /// <summary>
        /// Override this method to configure the database (and other options) to be used
        /// for this context. This method is called for each instance of the context that
        /// is created. The base implementation does nothing.
        /// In situations where an instance of Microsoft.EntityFrameworkCore.DbContextOptions
        /// may or may not have been passed to the constructor, you can use Microsoft.EntityFrameworkCore.DbContextOptionsBuilder.IsConfigured
        /// to determine if the options have already been set, and skip some or all of the
        /// logic in Microsoft.EntityFrameworkCore.DbContext.OnConfiguring(Microsoft.EntityFrameworkCore.DbContextOptionsBuilder).
        /// </summary>
        /// <param name="modelBuilder">A builder used to create or modify options for this context. Databases (and other extensions) typically define extension methods on this object that allow you to configure the context.</param>
        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            base.OnModelCreating(modelBuilder);
        }

        #endregion
    }

    #endregion
}
`

**Comment by JasonDevStudio** [comment]
`using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using HisiCAD.EFCore.DataAccess;
using HisiCAD.EFCore.DataAccess.Entities;
using Microsoft.EntityFrameworkCore;
using Oracle.EntityFrameworkCore.Infrastructure;

namespace Tests
{
    public class JobContext : DbContextBase
    {
        public JobContext() { }

        /// <summary>
        /// Initializes a new instance of the <see cref="LdsRawDbContext"/> class.
        /// </summary>
        /// <param name="info">项目数据库配置对象</param>
        public JobContext(ProjectDbInfo info) : base(info)
        { 

        }

        public JobContext(DbContextOptions<JobContext> options) : base(options) { }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            //配置mariadb连接字符串
            if (this.DbConnection != null)
            {
                optionsBuilder.UseOracle(this.DbConnection);
            }
            else if (!string.IsNullOrWhiteSpace(this.ConnectionString))
            {
                if (this.ConnectionString.StartsWith("DATA SOURCE="))
                {
                    optionsBuilder.UseOracle(this.ConnectionString);
                }
                else
                {
                    optionsBuilder.UseOracle($"DATA SOURCE= {this.ConnectionString};User Id={this.OracleUserName};Password={this.OraclePassword};Connection Lifetime=15;Max Pool Size=3000;Min Pool Size=20;Pooling=true;Enlist=true;");
                }
            }
            else if (!string.IsNullOrWhiteSpace(this.Host) && this.Port > 0 && !string.IsNullOrWhiteSpace(this.ServiceName) && !string.IsNullOrWhiteSpace(this.OracleUserName) && !string.IsNullOrWhiteSpace(this.OraclePassword))
            {
                optionsBuilder.UseOracle($"DATA SOURCE=(DESCRIPTION=(ADDRESS_LIST=(ADDRESS=(PROTOCOL=TCP)(HOST={this.Host})(PORT={this.Port}))(ADDRESS=(PROTOCOL=TCP)(HOST={this.Host})(PORT={this.Port})))(CONNECT_DATA=(SERVICE_NAME={this.ServiceName})));User Id={this.OracleUserName};Password={this.OraclePassword};Connection Lifetime=15;Max Pool Size=3000;Min Pool Size=20;Pooling=true;Enlist=true;");
            }

            base.OnConfiguring(optionsBuilder);
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<ProjectDbInfo>().ToTable("PRO_DBINFO", "LDSJOB_DEV").HasKey(m => m.ID);
            base.OnModelCreating(modelBuilder);
        }
    }
}
`

**Comment by JasonDevStudio** [comment]
`namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Linq.Expressions;
    using System.Reflection;
    using System.Text;
    using System.Threading.Tasks; 
    using Microsoft.EntityFrameworkCore;
    using Z.BulkOperations;

    #region Classes

    /// <summary>
    /// Defines the <see cref="EFCoreHelper{T}" />
    /// </summary>
    /// <typeparam name="T">T : DbContextBase</typeparam>
    public class EFCoreHelper<T> : IDisposable
        where T : DbContextBase, new()
    {
        #region Constructors

        /// <summary>
        /// Initializes a new instance of the <see cref="EFCoreHelper{T}"/> class.
        /// </summary>
        public EFCoreHelper()
        {
            this.DbContext = this.CreateInstance();
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="EFCoreHelper{T}"/> class.
        /// </summary>
        /// <param name="dbinfo">数据库配置对象</param>
        public EFCoreHelper(IDbInfo dbinfo)
        {
            this.DbContext = this.CreateInstance(dbinfo);
        }

        #endregion

        #region Properties

        /// <summary>
        /// Gets or sets the BulkOption
        /// </summary>
        public BulkOperation BulkOption { get; set; }

        /// <summary>
        /// Gets the DbContext
        /// </summary>
        public DbContextBase DbContext { get; private set; }

        #endregion

        #region Static
         
        #endregion

        #region Bulk
          
        /// <summary>
        /// 批量更新操作
        /// </summary>
        /// <typeparam name="TEntity">实体类型</typeparam>
        /// <param name="entities">实体集合</param> 
        /// <param name="keyExp">主键表达式</param>
        /// <param name="inputExp">输入表达式</param>
        /// <param name="ignoreExp">忽略更新字段表达式</param>
        /// <param name="provider">ProviderType</param>
        /// <returns>state:执行结果 msg:返回信息</returns>
        public (bool state, string msg) BulkUpdate<TEntity>(List<TEntity> entities, Expression<Func<TEntity, object>> keyExp = null, Expression<Func<TEntity, object>> inputExp = null, Expression<Func<TEntity, object>> ignoreExp = null, ProviderType provider = ProviderType.OracleManaged)
            where TEntity : class
        {
            this.DbContext.BulkUpdate(
                entities,
                opt =>
                {
                    opt.UseLogDump = true;
                    opt.Provider = provider;

                    if (keyExp != null)
                    {
                        opt.ColumnPrimaryKeyExpression = keyExp;
                    }

                    if (inputExp != null)
                    {
                        opt.ColumnInputExpression = inputExp;
                    }

                    if (ignoreExp != null)
                    {
                        opt.IgnoreOnUpdateExpression = ignoreExp;
                    }

                    opt.BulkOperationExecuted = bulkOperation =>
                    {
                        this.DbContext.DbLog = bulkOperation.LogDump ?? new StringBuilder();
                    };
                });

            return (state: true, msg: string.Empty);
        }
         
        #endregion

        #region Query
         
        /// <summary>
        /// 获取所有数据
        /// </summary>
        /// <typeparam name="TEntity">数据源中数据的类型。</typeparam>
        /// <returns>IQueryable</returns>
        public IQueryable<TEntity> QueryAll<TEntity>()
            where TEntity : class
        {
            return this.DbContext.Set<TEntity>();
        }
          
        #endregion

        #region OtherMethods

        /// <summary>
        /// 创建类型实例
        /// </summary>
        /// <returns>T 类型实例</returns>
        public T CreateInstance()
        {
            var tvalType = typeof(T);
            return (T)tvalType.Assembly.CreateInstance(tvalType.FullName);
        }

        /// <summary>
        /// 创建类型实例
        /// </summary>
        /// <typeparam name="TR">数据库配置对象类型</typeparam>
        /// <param name="dbinfo">数据库配置对象</param>
        /// <returns>DBCONTEXT</returns>
        public T CreateInstance<TR>(TR dbinfo)
        {
            var tvalType = typeof(T);
            var parameters = new object[] { dbinfo };
            return (T)tvalType.Assembly.CreateInstance(tvalType.FullName, true, System.Reflection.BindingFlags.Default, null, parameters, null, null);
        }

        /// <summary>
        /// The Dispose
        /// </summary>
        public void Dispose()
        {
            try
            {
                this.DbContext.Dispose();
            }
            catch (Exception ex)
            {
            }
        }
         
        #endregion
    }

    #endregion
}
`

**Comment by JasonDevStudio** [comment]
class Program
    {
        static void Main(string[] args)
        {
            var dbinfo = new ProjectDbInfo()
            {
                CONNECT_STRING = "(DESCRIPTION=(ADDRESS_LIST=(ADDRESS=(PROTOCOL=TCP)(HOST=*.*.*.*)(PORT=1521)))(CONNECT_DATA=(SERVICE_NAME=orcl)))",
                HOST = "*.*.*.*",
                PORT = 1521,
                PASSWORD = "ldsowner",
                USERNAME = "LDSJOB_DEV",
                SNAME = "orcl",
                SID = "orcl"
            };

            try
            {
                

                using (var cont = new EFCoreHelper<JobContext>(dbinfo))
                {
                    var data = cont.QueryAll<ProjectDbInfo>().ToList();
                    var data1 = data;

                    var fdata = data.FirstOrDefault();
                    fdata.KAFKA_ADDR = "192.192.192.192"; 
                    cont.BulkUpdate(new List<ProjectDbInfo> { fdata });
                }
            }
            catch (Exception ex)
            {
                var sss = ex.ToString();
                Console.WriteLine(ex);
            }

            Console.ReadLine();
            Console.ReadLine();
            Console.ReadLine();
        }
    }

**Comment by JasonDevStudio** [comment]
以上是我自己编写的Demo, 因为一些原因,我只能这么提供给你, 具体原因我目前尚未定位到, 我期望你们在收到我消息之后,删除以上代码. 谢谢

**Comment by JasonDevStudio** [comment]
protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            //配置mariadb连接字符串
            if (this.DbConnection != null)
            {
                optionsBuilder.UseOracle(this.DbConnection);
            }
            else if (!string.IsNullOrWhiteSpace(this.ConnectionString))
            {
                if (this.ConnectionString.StartsWith("DATA SOURCE="))
                {
                    optionsBuilder.UseOracle(this.ConnectionString);
                }
                else
                {
                    optionsBuilder.UseOracle($"DATA SOURCE= {this.ConnectionString};User Id={this.OracleUserName};Password={this.OraclePassword};Connection Lifetime=15;Max Pool Size=3000;Min Pool Size=20;Pooling=true;Enlist=true;");
                }
            }
            else if (!string.IsNullOrWhiteSpace(this.Host) && this.Port > 0 && !string.IsNullOrWhiteSpace(this.ServiceName) && !string.IsNullOrWhiteSpace(this.OracleUserName) && !string.IsNullOrWhiteSpace(this.OraclePassword))
            {
                optionsBuilder.UseOracle($"DATA SOURCE=(DESCRIPTION=(ADDRESS_LIST=(ADDRESS=(PROTOCOL=TCP)(HOST={this.Host})(PORT={this.Port}))(ADDRESS=(PROTOCOL=TCP)(HOST={this.Host})(PORT={this.Port})))(CONNECT_DATA=(SERVICE_NAME={this.ServiceName})));User Id={this.OracleUserName};Password={this.OraclePassword};Connection Lifetime=15;Max Pool Size=3000;Min Pool Size=20;Pooling=true;Enlist=true;");
            }

            base.OnConfiguring(optionsBuilder);
        }


我在子类中重写 OnConfiguring 函数,我发现一个BulkInsert操作,在调试过程中,会两次进入这里,第二次进入这里的时候,我所有的自定义属性都是null 获益这里没有进入任何一个判断体,导致报错

**Comment by JonathanMagnan** [comment]
Hello @JasonDevStudio ,

We believe the issue is due to how you set up your context.

Could you try to set a `ContextFactory`. It will let our library know how to create a context for internal logic purpose

See: https://entityframework-extensions.net/context-factory

```csharp
// Using a constructor that requires a connection string
EntityFrameworkManager.ContextFactory = context => new CurrentContext(My.ConnectionString);

EntityFrameworkManager.ContextFactory = context =>
{
	var optionsBuilder = new DbContextOptionsBuilder<EntityContext>();
	optionsBuilder.UseSqlServer(My.ConnectionString);
	return new EntityContext(optionsBuilder.Options);
};
```

**Comment by JasonDevStudio** [comment]
opt.ContextFactory = context => context;

**Comment by JonathanMagnan** [comment]
你好@JasonDevStudio，

你不能使用这样的方法。这是一个工厂，预计会有新的背景。我们在您当前的上下文中不想做的一些内部逻辑可能会完成。

您必须指定一个新的上下文，而不是作为参数提供的上下文。

**Comment by JasonDevStudio** [comment]
public T CreateInstance<R>(R dbinfo)
        {
            var tvalType = typeof(T);
            var parameters = new object[] { dbinfo };
            return (T)tvalType.Assembly.CreateInstance(tvalType.FullName, true, System.Reflection.BindingFlags.Default, null, parameters, null, null);
        }


请问下,我是使用反射方式创建dbcontext,  我如果使用 opt.ContextFactory = context => this.CreateInstance(this.Dbinfo); 来执行,  会不会很影响执行效率?

**Comment by JonathanMagnan** [comment]
应该没问题。这是一种只通过批量操作调用一次的方法。所以这不是性能问题
