### ISSUE TITLE
No release notes for v2.6.5 (EF Core)

### ISSUE THREAD

**Issue by AStove** [zzzprojects/EntityFramework-Extensions#253]
The release notes for v2.6.5 (EF Core) are missing.
https://github.com/zzzprojects/EntityFramework-Extensions/releases/tag/v2.6.5

**Comment by JonathanMagnan** [comment]
Thank you for letting us know.

The release note has been added: https://github.com/zzzprojects/EntityFramework-Extensions/releases/tag/v2.6.5

Best Regards,

Jonathan
