### ISSUE TITLE
BulkSaveChanges cannot save entity with NetTopologySuite (GeoApi) property (Ef Core)

### ISSUE THREAD

**Issue by zap93** [zzzprojects/EntityFramework-Extensions#254]
### Description
I am using Ef Core 3 with NetTopologySuite and GeoApi geometries

I've got an entity with a property named Location of type IPolygon.
Trying to add the specified entity to the database throws the following exception on BulkSaveChanges:
"Could not find Relational:TypeMapping for property 'Location'."

Maybe the issue is related to the preview version of EF Core?
Everything works as expected with every other operation that Ef.Extensions provides.
Using the defaut DbContext.SaveChanges does not raise any exception

### Further technical details
- EF version: 3.0.0-preview5.19227.1
- EF Extensions version: Z.EntityFramework.Extensions.EFCore 2.6.5
- Database Provider: Sql Server 3.0.0-preview5.19227.1

If you need some other info I would be glad to help!
Thanks in advance

**Comment by JonathanMagnan** [comment]
Hello @zap93 ,

Thank you for reporting,

A fix should be ready for next Monday. 

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment]
Hello @zap93 ,

The v2.6.6 has been released.

Could you try it again with the preview5 and let us know if that's working?

**Comment by zap93** [comment]
Now everything works well without any kind of exception.

Thank you for your quick response and have a good day!
