### ISSUE TITLE
FutureAction is missing

### ISSUE THREAD

**Issue by ahmettahasakar** [zzzprojects/EntityFramework-Extensions#256]
Based on the example at https://entityframework-extensions.net/bulk-insert#insert-with-future-action I'm trying to use FutureAction, but it doesn't seem to be a valid method for Dotnet core 2.2. Is it in a separate package? What am I missing here?

**Comment by JonathanMagnan** [comment]
Hello @ahmettahasakar ,

I checked very fast, it looks `FutureAction` exists in the `EF6` version but we forget to add it in the `EF Core` version.

We will look at it today.

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment]
Hello @ahmettahasakar ,

The v2.6.9 has been released.

`FutureAction` has been added to the .NET Core package.

Let me know if that work as expected.

Best Regards,

Jonathan
