### ISSUE TITLE
UpdateFromQuery does not work with nullable types

### ISSUE THREAD

**Issue by MUlfers** [zzzprojects/EntityFramework-Extensions#257]
### Description
We are trying to use UpdateFromQuery() to set a nullable integer property to null.
Because the setters on the entity are private we are using the dictionary approach.

```
var dictionary = new Dictionary<string, object>
{
  {"SomeOptionalInt", null}
};
context.Customers.UpdateFromQuery(dictionary);
```
When executing this throws an exception. We assume that there might be a Expression.Constant() at some place that is missing the target type information as second parameter. Hence the code tries to assign type int to a property of type int?.

### Exception
```
[System.ArgumentException: Argument types do not match]
   at System.Linq.Expressions.Expression.Bind(MemberInfo member, Expression expression)
   at DbContextExtensions.UpdateFromQuery[TEntity](IQueryable`1 query, IDictionary`2 dictionary, Action`1 bulkOperationFactory)
   at DbContextExtensions.UpdateFromQuery[TEntity](IQueryable`1 query, IDictionary`2 dictionary)
   at Program.Main() :line 31
```

### Fiddle
https://dotnetfiddle.net/AgAbO5

### Further technical details
- EF version: 6.2.0
- EF Extensions version: 3.21.9
- Database Provider: MSSQL

**Comment by JonathanMagnan** [comment]
Hello @MUlfers ,

Our library currently only works with the entity type (`Customer`). You cannot use a dictionary or anonymous type but that's something we are currently working on.

We will investigate this week if we can push faster the development for this request and I will let you know.

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment]
Hello @MUlfers ,

Sorry for the late answer, it looks we forget about this request for a while.

This issue has been finally fixed, your fiddle is now working as expected: https://dotnetfiddle.net/AgAbO5

If you have the chance to try it, could you confirm us that everything is working?

Best Regards,

Jon

**Comment by MUlfers** [comment]
Hello @JonathanMagnan ,

thank you for the update.
I was able to try it out and it works as expected.

Thank you,
Best Regards,
Malte
