### ISSUE TITLE
UpdateFromQuery: Incorrect syntax near ';'.

### ISSUE THREAD

**Issue by rlenders** [zzzprojects/EntityFramework-Extensions#26]
Are one-to-many relationships, EF's navigation properties, and aggregate functions, supported? I'm currently trying something like this:

    Context.Users.UpdateFromQuery(u => new User {
        RoleCount = u.Roles.Count()
    });

But this throws an `SqlException` with the following message:

> UpdateFromQuery: Incorrect syntax near ';'.

**Comment by JonathanMagnan** [comment]
Hello @rlenders ,

Thank you for reporting this issue.

We successfully reproduced it and found out why it's happening. Aggregate functions were not supported.

We did some test and we believe it will be possible to support it. We will start the implementation of the solution tomorrow.

Best Regards,

Jonathan

**Comment by rlenders** [comment]
Would you be able to support more complex queries? E.g.:

    Context.Users.UpdateFromQuery(p => new Person {
        ColleagueCount = p.Employments
            .SelectMany(e => e.Departments.Select(d => d.EmployeeCount))
            .DefaultIfEmpty()
            .Sum()
    });

**Comment by JonathanMagnan** [comment]
Hello @rlenders ,

The v3.10.46 has been released:
https://www.nuget.org/packages/Z.EntityFramework.Extensions/

It should now support aggregate functions and a lot more.

Let us know if it's working.

## Complex Queries
We tried some complex queries and they have all worked correctly. As long as it's a valid IQueryable, it should be now supported.

If you have an issue, let us know and we will investigate it.

**Comment by rlenders** [comment]
Thanks! A lot seems to be working that didn't work for me yesterday.

However, using `DefaultIfEmpty` like my previous example throws an `SqlException` with the following message:

> No column name was specified for column 1 of 'Project1'.

**Comment by JonathanMagnan** [comment]
The v3.10.47 has been released:
https://www.nuget.org/packages/Z.EntityFramework.Extensions/3.10.47

Let me know if this query is now working.

Best Regards,

Jonathan

**Comment by rlenders** [comment]
Thanks, works great.
