### ISSUE TITLE
UpdateFromQuery broken in 3.21.10

### ISSUE THREAD

**Issue by chrfin** [zzzprojects/EntityFramework-Extensions#263]
After updating to version 3.21.10 the following query does not work anymore:

    await db.Customers.Where(c => c.Id == order.Customer.Id).UpdateFromQueryAsync(c => new Customer { ExternalCustomerId = order.Customer.ExternalCustomerId });

I get the following exception:

 > System.Exception: The destination column could not be found:ExternalCustomerId  
 >  at .[](IQueryable`1 , Expression`1 , SchemaEntityType`1 )  
 >  at .Execute[T](IQueryable`1 query, Expression`1 updateFactory)  
 >  at DbContextExtensions.UpdateFromQuery[TEntity](IQueryable`1 query, Expression`1 updateExpression, Action`1 bulkOperationFactory)  

After downgrading to version 3.21.9 the query is working again.

**Comment by JonathanMagnan** [comment]
Hello @chrfin ,

Thank you for reporting,

We will look at what has been modified that could cause this issue.

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment]
Hello @chrfin ,

The v3.21.11 has been released.

Could you try it and let us know if everything is fixed?

The issue has been caused due to a compilation directive added in a wrong place.

**Comment by chrfin** [comment]
Seems to be working again, thanks for the quick fix :-)
