### ISSUE TITLE
Object reference not set to an instance of an object

### ISSUE THREAD

**Issue by 786744873** [zzzprojects/EntityFramework-Extensions#264]
### Description
when I use Z.EntityFramework.Extensions.EFCore,I can use EF to inset or other operation,but when I make bulk operation.It throw exception.

```
try
{
    var opt= ServiceHelper.CurrentServiceProvider.GetRequiredService<DbContextOptions<EFDbContext>>();
    using (var ctx=new EFDbContext(opt))
    {
        EntityFrameworkManager.ContextFactory = c => ctx;
        bool ixit = ctx.FooBarEF.Any();  //true
        ctx.BulkInsert(fooBarEfList);  //error
    }
}
catch (Exception e)
{
    Console.WriteLine(e);
}

``` 

### Exception
If you are seeing an exception, include the full exceptions details (message and stack trace).
![image](https://user-images.githubusercontent.com/24601648/62529083-8c3a7500-b870-11e9-8a99-6dc6aa878d21.png)

```
System.NullReferenceException: Object reference not set to an instance of an object.
   at .( , DbCommand )
   at .Execute(List`1 actions)
   at Z.BulkOperations.BulkOperation.Execute()
   at .[](DbContext this, IEnumerable`1 , Action`1 )
   at Techsel.DataCenter.FrontServer.Controllers.ValuesController.Get() in F:\SVN\DataCenter\trunk\DataCenterV2\前置机\Techsel.DataCenter.FrontServer\Controllers\ValuesController.cs:line 94
```

**Comment by JonathanMagnan** [comment]
Hello @786744873 ,

Is it possible for you to provide a runnable solution with this issue? You can send it in private here info@zzzprojects.com

We checked it but unfortunately, we currently don't have enough information to find the cause and fix it.

Best Regards,

Jonathan

**Comment by 786744873** [comment]
Thans for your review.I have send my code to you email.You should change `appsettings.json` file to config `MysqlConnectStr`.And it can auto create databse on MySql,you can also down load my code [here](https://send.firefox.com/download/9bbb0cb7fc3ebf96/#d0cnDQpDS7Xyg3-TCXjypg). The error place is `Startup.cs` file line 90. hi brother. Thanks a alot.

**Comment by 786744873** [comment]
And I admire remove `EntityFrameworkManager.ContextFactory`. If without this,our context and repository can be pure more and more.

**Comment by JonathanMagnan** [comment]
Hello @786744873 ,

Just to let you know, we have made a great progression today. We were very close to release a fix.

However, we will only be able to resume the work and try to release the fix on next Monday due to vacancy.

**Comment by 786744873** [comment]
It's greate!  brother. Next Monday,I will make a test for the newest update. Thanks a lot.
Please forgive my poor English writing ability.

**Comment by 786744873** [comment]
Hello,I'd like to know when you will update it.

**Comment by JonathanMagnan** [comment]
Hello @786744873 ,

The v2.6.12 has been released today.

Our library should now work with a table without an identity for MySQL.

However, we didn't success to make it fully work with your project due to how DateTime is handled in your project.

The following code:

```csharp
[Timestamp]
public byte[] Timestamp { get; set; }
```

still cause us a lot of trouble since you use a `byte[]` and store it like a `DateTime.
