### ISSUE TITLE
UpdateFromQuery and DeleteFromQuery do not work with custom IQueryable

### ISSUE THREAD

**Issue by davidnemeti** [zzzprojects/EntityFramework-Extensions#268]
### Description
We have just bought EntityFramework.Extensions, and we are trying to migrate from EntityFramework.Plus to EntityFramework.Extensions. We are using an own 2nd-level caching mechanism which needs us to use a custom `IQueryable` implementation:

``` C#
    public class CacherQueryable<TElement> : IQueryable<TElement>, IOrderedQueryable<TElement>, IDbAsyncEnumerable<TElement>
    {
        private readonly IQueryable<TElement> _underlyingQueryable; // NOTE: do not use auto property, because InnerQuery is just a workaround

        // EntityFramework.Extended and EntityFramework.Plus need this private property to exist
        // ReSharper disable once UnusedMember.Local
        private IQueryable<TElement> InnerQuery => _underlyingQueryable;

        // ...
    }
```

Currently we are using **EntityFramework.Plus which works properly** with the above `InnerQuery` private property which exist only to serve EntityFramework.Plus.

The problem is that upon calling either `UpdateFromQuery` or `DeleteFromQuery` method **EntityFramework.Extensions throws an exception** with the message "Could not find the context from the IQueryable expression. Are you sure this is coming from an Entity Framework Context?".

This is because **EntityFramework.Extensions lacks this flexible "underlying queryable finding" mechanism** (which EntityFramework.Plus does have), and it forces the custom `IQueryable` implementation to be either an `ObjectQuery<TEntity>` or a `DbQuery<TEntity>`, which is not an options for us.

### Exception
```
System.Exception : Could not find the context from the IQueryable expression. Are you sure this is coming from an Entity Framework Context?
   at DbContextExtensions.GetContext[TEntity](IQueryable`1 query)
   at DbContextExtensions.[](IQueryable`1 , Action`1 , CancellationToken )
   at DbContextExtensions.DeleteFromQuery[TEntity](IQueryable`1 query, Action`1 bulkOperationFactory)
```

### Fiddle or Project (Optional)
A full, working project with a custom `IQueryable` would be a little bit difficult to serve; however, the solution - I hope - is as easy as doing the same thing as EntityFramework.Plus does here:

https://github.com/zzzprojects/EntityFramework-Plus/blob/afda5ce3d1a8de089a356ae8357ba13578fe0629/src/shared/Z.EF.Plus._Core.Shared/EF5_EF6/IQueryable/IQueryable.GetObjectQuery.cs

### Further technical details
- EF version: 6.2.0
- EF Extensions version: 3.21.11
- Database Provider: SQL Server

**Comment by JonathanMagnan** [comment]
Hello @davidnemeti ,

Thank you for reporting. We will look at it. I believe the fix will be as easy as just importing the code from EF Plus.

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment]
Hello @davidnemeti ,

The v3.21.13 has been released.

Could you try it and let me know if everything now works fine in EFE?

Have a great weekend ;)

Best Regards,

Jonathan

**Comment by davidnemeti** [comment]
Thanks, @JonathanMagnan, that was a really quick fix! Less than 24 hours, which is amazing! :-)

I have tried v3.21.13, and it works flawlessly with our `InnerQuery` private property.

Thanks,
David

**Comment by JonathanMagnan** [comment]
Awesome ;)
