### ISSUE TITLE
UpdateFromQueryAsync, DeleteFromQueryAsync and BulkInsertAsync are not "really" async

### ISSUE THREAD

**Issue by davidnemeti** [zzzprojects/EntityFramework-Extensions#269]
### Description
`UpdateFromQueryAsync`, `DeleteFromQueryAsync` and `BulkInsertAsync` are not "really" **asynchronous**. What I mean by that is that their _asynchronicity is not being **propagated** to the lowest possible level_ (the "communication with the database" level). Rather, these method calls are essentially just simply being **forwarded** to their synchronous corresponding counterparts (`UpdateFromQuery`, `DeleteFromQuery` and `BulkInsert`) and being **wrapped** by a `Task.Run` call.

Wrapping an actually **synchronous** operation by `Task.Run` to convert it into an **asynchronous** operation is not a good practice in **libraries**, because it suggests that the operation is "really" asynchronous, but it is actually not. _A library should only define an asynchronous operation if it is really asynchronous._

If the user of the library wants to call an synchronous operation asynchronously (e.g. to _avoid UI blocking_ in a **WPF application**) then _they can wrap it in a `Task.Run` call themselves_. However, this kind of `Task.Run` wrapping _makes no sense_ e.g. in the case of a **web application**.

In case of a **web application** _there are no UI blocking issues_; however it is still a good idea to use asynchronous operations in order to _release the current thread_ (so the released thread can be used to _serve other web requests_ in the meantime) until the asynchronous operation finishes. The problem with the `Task.Run` solution is that although it releases the current thread, however, it immediately **acquires another thread** from the `ThreadPool` for the synchronous "execution of its `Action` / evaluation of its `Func`" parameter, which acquired thread will be **blocked** and will **wait** for the synchronous operation (inside `Task.Run`) to finish.

In contrast to Entity Framework Extensions' "not really asynchronous" methods, **Entity Framework**'s asynchronous methods are _really asynchronous_ (they do not use `Task.Run` wrapping). It means that their asynchronicity is being propagated to the lowest possible level (the "communication with the database" level), thus, these really asynchronous methods _do not block any thread_ while _awaiting_ for the asynchronous database operations to finish.

### Proposed Solution
The behavior of **Entity Framework Extensions**' `UpdateFromQueryAsync`, `DeleteFromQueryAsync` and `BulkInsertAsync` methods should be changed to behave like **real asynchronous methods**.

### Further technical details
- EF version: 6.2.0
- EF Extensions version: 3.21.11
- Database Provider: SQL Server

**Comment by JonathanMagnan** [comment]
Hello @davidnemeti ,

You are right about it. 

We made it correctly for `BatchSaveChangesAsync` or new method such as `DeleteByKeyAsync` we recently added.

We already started the code for `UpdateFromQueryAsync` and `DeleteFromQueryAsync`. However, I believe it will take more time for other methods such as `BulkInsertAsync` due to how they have been made.

The problem with making it right is all the code and method that are duplicated. It's really not a simple task ;(

So we work on it, but that's not that simple.

**Comment by davidnemeti** [comment]
Hi @JonathanMagnan ,

Yes, maintaining a sync and an async version for these methods would mean code duplication, unless you use a smart trick so you can reuse the common logic and avoid redundancy.

E.g. let us say that we want to override the `DbContext`'s `SaveChanges` and `SaveChangesAsync` methods (i.e. both the sync and the async methods), so they would do some pre- and post-processing while calling the original (`base`) `SaveChanges` and `SaveChangesAsync` methods.

At first sight, it would require us to duplicate the common logic for our `SaveChanges` and `SaveChangesAsync` methods, just because in the deep we want to call the original `base` methods, which, of course, depends on the outer calling context: we want to call the sync one from the sync method, and the async one from the async method.

However, by applying the trick below we can share and reuse the common logic:

``` C#
public override int SaveChanges()
{
	// NOTE: It is completely legitimate to use the "Result" property here, because this SaveChangesAsync call will be synchronous.
	// For explanation see the "SaveChangesAsync(CancellationToken cancellationToken, bool async)" method.
	return SaveChangesAsync(CancellationToken.None, async: false).GetAwaiter().GetResult();   // use this instead of simply calling Result in order to avoid AggregateException
}

public override Task<int> SaveChangesAsync()
{
	return SaveChangesAsync(CancellationToken.None);
}

public override Task<int> SaveChangesAsync(CancellationToken cancellationToken)
{
	// This SaveChangesAsync call will be asynchronous, so we could await for its result here.
	// However, we do not need to do anything after the call, so we just return its return value (which is a Task).
	// For explanation see the "SaveChangesAsync(CancellationToken cancellationToken, bool async)" method.
	return SaveChangesAsync(cancellationToken, async: true);
}

/// <summary>
/// Hybrid method for handling the synchronous SaveChanges and the asynchronous SaveChangesAsync cases.
/// </summary>
/// <param name="cancellationToken">
/// The cancellation token.
/// </param>
/// <param name="async">
/// <para>
/// If <c>true</c> then this method calls asynchronous methods (where they exist), so it behaves asynchronously, therefore its return value is a
/// real asynchronous <see cref="Task"/> which should be awaited asynchronously somewhere in the code (use the <c>await</c> keyword).
/// </para>
/// <para>
/// If <c>false</c> then this method calls only synchronous methods, so it behaves synchronously, therefore its return value is a <see cref="Task"/>
/// which has already been completed, thus it can be waited synchronously (use the <see cref="Task.Wait()"/> method) or its result can be get
/// synchronously (use the <see cref="Task{TResult}.Result"/> property).
/// </para>
/// </param>
/// <returns>
/// The number of state entries written to the underlying database.
/// </returns>
/// <remarks>
/// <para>
/// The goal of this method is to eliminate the redundancy which would be introduced if we were to implement two separate
/// SaveChanges/SaveChangesAsync methods with almost identical logic (code duplication). The only difference between the two methods would be
/// that SaveChanges would call synchronous methods (e.g. base.SaveChanges), while SaveChangesAsync would call asynchronous methods
/// where there exist the corresponding asynchronous versions of the synchronous methods (e.g. base.SaveChangesAsync).
/// </para>
/// </remarks>
private async Task<int> SaveChangesAsync(CancellationToken cancellationToken, bool async)
{
	// Do common stuff here.
	
	int result;

	if (async)
	{
		result = await base.SaveChangesAsync(cancellationToken);
	}
	else
	{
		result = base.SaveChanges();
	}

	// Do other common stuff here.
	
	return result;
}
````

If your problem is the same, then I think you could also apply this trick.

**Comment by JonathanMagnan** [comment]
Yup, we can for sure use this trick in many places

Unfortunately for us, that's way harder ;(

Our library requires to use A LOT of reflection everywhere since we don't force a reference to the latest Entity Framework version, we don't have any dependencies on any of the supported provider beside SQL Server.

The problem is not only making a change in our library to support async but also, we need to change a lot of code everywhere that use reflection and make sure it works with any provider version since some provider has a lot of breaking changes from a version to another.

Let be honest, besides some method such as `DeleteFromQuery` and `UpdateFromQuery`, I don't think that's something that will be done soon due to the complexity to make it right. Doing it will for sure bring a lot of issues. Even if we have thousands of unit test, that's way too dangerous at this moment unless for finish the side project that allows us to use most providers method without referencing them.
