### ISSUE TITLE
Expose generated SQL for profiling purposes.

### ISSUE THREAD

**Issue by rlenders** [zzzprojects/EntityFramework-Extensions#27]
In vanilla Entity Framework you can call `ToString` to view the SELECT statement that Entity Framework generates behind the scenes. Entity Framework also allows logging SQL statements through `context.Database.Log`. This can be useful when refactoring LINQ queries, to see how your changes impact the generated SQL statement.

With this library's extensions, such as `BulkUpdate` and `UpdateFromQuery`, this does not appear to be possible.

**Comment by rlenders** [comment]
One way to expose the generated XML is to just cal `context.Database.Log` manually. This is probably the most EF-like solution to this problem. Profilers that depends on the `Log` function will then also be able to profile bulk operations!

The only challenge here is to log SQL statements in the exact same way as Entity Framework does. This is what a typical update log looks like:

> Opened connection at 09-Feb-17 19:37:21 +01:00
>
> Started transaction at 09-Feb-17 19:37:21 +01:00
> 
> UPDATE [dbo].[AspNetUsers]
> SET [UserName] = @0
> WHERE ([Id] = @1)
>
> -- @0: 'Example' (Type = String, Size = 256)
>
> -- @1: '6e34b669-b1e0-41d9-a6e3-e0de0864e91b' (Type = String, Size = 128)
>
> -- Executing at 09-Feb-17 19:37:21 +01:00
>
> -- Completed in 48 ms with result: 1
>
>
>
> Committed transaction at 09-Feb-17 19:37:21 +01:00
> 
> Closed connection at 09-Feb-17 19:37:21 +01:00
> _\n_

Maybe there is a way to call Entity Framework's internal function that generates this log message?

**Comment by JonathanMagnan** [comment]
Hello @rlenders ,

You can already log query in our library: 

```csharp
using (var ctx = new CurrentContext())
{
    StringBuilder sb = new StringBuilder();

    ctx.Lefts.UpdateFromQuery(x => new Left {EmployeID = x.Rights.Select(y => y.ID).DefaultIfEmpty().Sum()},
        operation => operation.Log = s => sb.AppendLine(s));


    var log = sb.ToString();
}
```

Output:
```
-- Executing Command:
SELECT TOP (1) 
    [c].[ID] AS [ID]
    FROM [dbo].[Z_EntityFramework_Extensions_Lab_Form_Request_UpdateFromQuery_Left] AS [c]
-- CommandTimeout:180
-- Executing at 2017-02-09 2:14:02 PM

-- Completed at 2017-02-09 2:14:02 PM
-- Result: 1 rows



-- Executing Command:
MERGE INTO [dbo].[Z_EntityFramework_Extensions_Lab_Form_Request_UpdateFromQuery_Left] AS DestinationTable
USING
(
SELECT 
    [Extent1].[ID] AS [ID]
    FROM [dbo].[Z_EntityFramework_Extensions_Lab_Form_Request_UpdateFromQuery_Left] AS [Extent1]
) AS StagingTable
ON StagingTable.ID = DestinationTable.ID
WHEN MATCHED THEN
    UPDATE
    SET     [EmployeID] = (SELECT 
        SUM([Join1].[A1]) AS [A1]
        FROM ( SELECT 
            CASE WHEN ([Project1].[C1] IS NULL) THEN 0 ELSE [Project1].[ID] END AS [A1]
            FROM   ( SELECT 1 AS X ) AS [SingleRowTable1]
            LEFT OUTER JOIN  (SELECT 
                [Extent2].[ID] AS [ID], 
                cast(1 as tinyint) AS [C1]
                FROM [dbo].[Z_EntityFramework_Extensions_Lab_Form_Request_UpdateFromQuery_Right] AS [Extent2]
                WHERE DestinationTable.[ID] = [Extent2].[Left_ID] ) AS [Project1] ON 1 = 1
        )  AS [Join1])
;
-- CommandTimeout:180
-- Executing at 2017-02-09 2:14:02 PM

-- Completed at 2017-02-09 2:14:02 PM
-- Result: 5
```

However, it doesn't log yet query exactly like EF do. Still pretty similar...

Let me know if that solve your requirement, otherwise what you would like.

Best Regards,

Jonathan

**Comment by rlenders** [comment]
This is what I needed, thanks!
