### ISSUE TITLE
类型“System.Decimal”的对象无法转换为类型“System.Nullable`1[System.Int32]”。

### ISSUE THREAD

**Issue by JasonDevStudio** [zzzprojects/EntityFramework-Extensions#271]
### Description
Hi, 我在调用 DatabaseExtensions.ExecuteEntities[T](Database this, String cmdText) 函数的时候,出现以下错误, 我们的数据实体类属性确实需要  int? 类型, 请问我们改如何解决?

### Exception
System.ArgumentException: 类型“System.Decimal”的对象无法转换为类型“System.Nullable`1[System.Int32]”。

```
Exception message:
Stack trace:
   在 System.RuntimeType.TryChangeType(Object value, Binder binder, CultureInfo culture, Boolean needsSpecialCast)
   在 System.Reflection.MethodBase.CheckArguments(Object[] parameters, Binder binder, BindingFlags invokeAttr, CultureInfo culture, Signature sig)
   在 System.Reflection.RuntimeMethodInfo.InvokeArgumentsCheck(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   在 System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   在 System.Reflection.RuntimePropertyInfo.SetValue(Object obj, Object value, Object[] index)
   在 .[](IDataReader this)
   在 DatabaseExtensions.ExecuteEntities[T](Database this, Action`1 commandFactory)
   在 DatabaseExtensions.ExecuteEntities[T](Database this, String cmdText)

### Fiddle or Project (Optional)
If you are able, 
 
### Further technical details
- EF version: 6.2
- EF Extensions version: 3.16.14
- Database Provider: Oracle.ManagedDataAccess.4.122.18.3

**Comment by JonathanMagnan** [comment]
Hello @JasonDevStudio ,

Thank you for reporting, we will try to reproduce it.

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment]
Hello @JasonDevStudio ,

Sorry for the delay, probably too late to answer but anyway...

It's possible that the column in your database is of type Decimal?

My developer successfully created a similar issue last month by using a decimal column type in the database and a nullable column int in the entity:

```csharp
public class EntitySimple
{
	public int ID { get; set; }
	public int? ColumnInt { get; set; }
	public String ColumnString { get; set; }
}
```

Obviously, both types are not compatible.

If you believe your mapping should work, please let us know what's the type in your database and the only in your entity. We will look at it.

**Comment by JasonDevStudio** [comment]
HI ,非常抱歉， 中国国庆期间，中国内陆，访问全球互联网有些问题， 我在节后详细看看Github上面的问题， 因为时间有点久了，我有限忘记了。




在2019年10月2日 04:12，Jonathan Magnan<notifications@github.com> 写道：

Hello @JasonDevStudio ,

Sorry for the delay, probably too late to answer but anyway...

It's possible that the column in your database is of type Decimal?

My developer successfully created a similar issue last month by using a decimal column type in the database and a nullable column int in the entity:

publicclassEntitySimple
{
	publicintID { get; set; }
	publicint? ColumnInt { get; set; }
	publicStringColumnString { get; set; }
}

Obviously, both types are not compatible.

If you believe your mapping should work, please let us know what's the type in your database and the only in your entity. We will look at it.
