### ISSUE TITLE
BatchSaveChangesAsync is much slower than BatchSaveChanges

### ISSUE THREAD

**Issue by davidnemeti** [zzzprojects/EntityFramework-Extensions#274]
### Description
The asynchronous `BatchSaveChangesAsync` is **much slower** (takes more than 3x as much time) than its synchronous counterpart `BatchSaveChanges`.

The performance measurement has been taken by **running a Fiddle**. The results were:

Action | Entities | Performance
-- | -- | --
SaveChanges (Entity Framework) | 1000 | 1369 ms
BatchSaveChanges | 1000 | 302 ms
BatchSaveChangesAsync | 1000 | 1101 ms

### Fiddle

The performance issue can be reproduced by running the following Fiddle:
https://dotnetfiddle.net/yC90m0

### Further technical details
- EF version: 6.2.0
- EF Extensions version: ? 3.22.3 ? (I assume Fiddle uses the latest version, and this was the latest at that time)
- Database Provider: ? SQL Server ? (I assume Fiddle uses SQL Server)

**Comment by JonathanMagnan** [comment]
Hello @davidnemeti ,

Are you able to reproduce this issue outside of Fiddle? On our side, without Fiddle, we always get similar or better issue with the async method.

.NET Fiddle has his own limitations so perhaps there is some performance issue inside it.

I tried to create you an example on Fiddle using SaveChanges but it looks that we are also limited about some security accessibility (you probably tried on your side).

Let me know if you also get the same performance issue in a real project.

**Comment by davidnemeti** [comment]
Well, indeed, the **culprit was Fiddle, not `BatchSaveChangesAsync`**. I have tried the same code in LINQPad and it turned out that **`BatchSaveChangesAsync` is as fast as `BatchSaveChanges`**.

However, it has also turned out that `BatchSaveChanges` does not have _that much_ advantage over the traditional `SaveChanges` as it seemed when running the code in Fiddle. It is still _significantly faster_, though

My measurements when running the LINQPad script were:

EFE - High-performance batch operations
--

Action | Entities | Performance
-- | -- | --
SaveChanges (Entity Framework) | 1000 | 391 ms
BatchSaveChanges | 1000 | 271 ms
BatchSaveChangesAsync | 1000 | 271 ms

The LINQPad script itself can be downloaded from here:
http://share.linqpad.net/3aj7pj.linq

**Comment by JonathanMagnan** [comment]
The advantage of `BatchSaveChanges` highly depends on where the SQL Server is located depending on the application.

If both are on the same machine, the `SaveChanges` is still VERY fast (all developers probably have now SSD by now!). However, this case rarely happens in a production environment.

**Comment by davidnemeti** [comment]
Indeed, you are right, I was using my local SQL Server and I also have SSD. :-)

I have also tried it on a _non-local_ SQL Server, and the difference was _much more significant_:

Action | Entities | Performance
-- | -- | --
SaveChanges (Entity Framework) | 1000 | 836 ms
BatchSaveChanges | 1000 | 375 ms
BatchSaveChangesAsync | 1000 | 325 ms
