### ISSUE TITLE
BulkInsert not adding related/child entities with IncludeGraph = true when using InMemoryDatabase

### ISSUE THREAD

**Issue by sergiosaint** [zzzprojects/EntityFramework-Extensions#278]
### Description
BulkInsert not adding related/child entities with IncludeGraph = true when using InMemoryDatabase

This is related with issue #109 but its only happening if the provider is in memory.

(not sure if this is a bug or a wanted feature)
My issue is that because i decided to use Bulkinsert to improve performance a few unit tests that rely on using InMemoryDatabase are now failing.

### Further technical details
- EF version: 2.2.6
- EF Extensions version: v2.6.15
- Database Provider: InMemoryDatabase

**Comment by JonathanMagnan** [comment]
Hello @sergiosaint ,

Thank you for reporting, we will look at it.

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment]
Hello @sergiosaint ,

My developer made a basic test: https://dotnetfiddle.net/opnIHE

And everything seems to work,

Do you have an example that causes an error?

**Comment by JonathanMagnan** [comment]
Hello @sergiosaint ,

Did you succeed to re-create this issue?

**Comment by sergiosaint** [comment]
You example does work, so I need to figure out what am i doing differently not to work.
You probably can close this issue, and ill come when i can pin point what im doing wrong. (if its cause by your library.
