### ISSUE TITLE
Make version 2.x compatible with .NET Standard 2.1

### ISSUE THREAD

**Issue by virzak** [zzzprojects/EntityFramework-Extensions#281]
### Description
Hello,

Our .NET Standard library is multi-targeted to netstandard2.1 and netstandard2.0.

Because version 3, which uses EF core cannot be made compatible with netstandard2.0, we cannot upgrade to version 3 at that time. However, just like older efcore is still expected to be compatible with .NET Standard 2.1, the same should apply to this library.

### Compile-time error
```
The type 'IAsyncEnumerator<T>' exists in both 'System.Interactive.Async, Version=3.0.3000.0, Culture=neutral, PublicKeyToken=94bc3704cddfc263' and 'netstandard, Version=2.1.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'	TryOutIAsyncEnumerable (netstandard2.1)	
```

### Further technical details
- EF version: N/A
- EF Extensions version: 2.6.11
- Database Provider: N/A

**Comment by JonathanMagnan** [comment]
Hello @virzak ,

Like EF Core which has 2 versions:
- One for v2.x
- One for v3.x,

Our library has the same behavior:
- One for v2.x: https://www.nuget.org/packages/Z.EntityFramework.Extensions.EFCore/2.6.16
- One for V3.x: https://www.nuget.org/packages/Z.EntityFramework.Extensions.EFCore/3.0.0-preview8-03

We do not support yet the latest preview-9 that has been released today but the support should be coming very soon (we hope during the weekend).

Or perhaps, I didn't understand correctly this request with those numbers ;) Are you aying that you use EF Core 2.x in .NET Standard 2.1? And our library is not compatible?

Best Regards,

Jonathan

**Comment by virzak** [comment]
> Or perhaps, I didn't understand correctly this request with those numbers ;) Are you aying that you use EF Core 2.x in .NET Standard 2.1? And our library is not compatible?

Hi Jonathan,

Yes, that's what I'm saying. Since IAsyncEnumerator was introduced in .NET Standard 2.1, there is now a collision with IAsyncEnumerator from System.Interactive.Async. We can't currently drop .NET Standard 2.0, since the library is consumed by .NET Framework based project (hence can't upgrade to version 3 of your library). But we also can't multi-target, since 2.6.11 doesn't work with .NET Standard 2.1.

**Comment by JonathanMagnan** [comment]
Great thank,

We will look at it ;)

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment]
Hello @virzak ,

Sorry for the delay,

Unfortunately, we are not able to reproduce it with our library. We made our tests with the latest version (v2.6.17) and everything seem to work fine.

We also created a dll that target specifically .NET Standard 2.1 but again, everything looks to work fine.

Do you think you could provide us a runnable project with this issue? That will help us to solve this problem as we are not sure how to reproduce it at this moment.

Perhaps we are missing something to get this error.

Best Regards,

Jonathan

**Comment by virzak** [comment]
See if you get a compilation error in this minimal example

https://github.com/virzak/EntityFramework-Extensions-281

**Comment by JonathanMagnan** [comment]
Thank you,

But this is where I believe I'm missing you.

I can have the same exact behavior without our library. By simply adding the reference to `Microsoft.EntityFrameworkCore.SqlServer` instead.

```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>netstandard2.0;netstandard2.1</TargetFrameworks>
    <RootNamespace>EntityFramework_Extensions_281</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="2.2.6" />
  </ItemGroup>

</Project>
```

There is currently no reference on `IAsyncEnumerator` in our library.

However, by looking on many thread about this subject in the EF Core repository, it looks they use it on their side.

I'm wrong when saying that EF Core 2.x is still not compatible with it?

**Comment by virzak** [comment]
You're right.

And they have a bunch of issues there where this compilation error is raised.
