### ISSUE TITLE
BatchSaveChanges sometimes throws the "Oops! the SqlCommand could not be found" exception

### ISSUE THREAD

**Issue by davidnemeti** [zzzprojects/EntityFramework-Extensions#282]
### Description
In some rare cases `BatchSaveChanges` throws the "_Oops! the `SqlCommand` could not be found_" exception. We are also using EntityFramework.Cache 1.0.0 nuget package, and EntityFramework.DbContextScope 1.0.0.

### Exception

The exception says that it cannot find the `SqlCommand`, probably because it cannot cope with `EFCache.CachingCommand`.

```
System.Data.Entity.Core.UpdateException : An error occurred while updating the entries. See the inner exception for details.
  ----> System.Exception : Oops! the SqlCommand could not be found. Please report to info@zzzprojects.com the current command: EFCache.CachingCommand
   at .()
   at DbContextExtensions.BatchSaveChanges(DbContext this)
   at MyDbContext.SaveChanges() in D:\SVN\MyProject\MyDbContext.cs:line 191
   at Mehdime.Entity.DbContextCollection.Commit()
--- End of stack trace from previous location where exception was thrown ---
   at Mehdime.Entity.DbContextCollection.Commit()
   at Mehdime.Entity.DbContextScope.SaveChanges()
   at MyDbContextTests.CreateAccount() in D:\SVN\MyProject\MyDbContextTests.cs:line 209
   at MyDbContextTests.AccountCanBeSaved() in D:\SVN\MyProject\MyDbContextTests.cs:line 58
--Exception
   at Z.EntityFramework.Extensions.PolyCommandSet.GetBaseCommand(DbCommand command)
   at .()
```

### Fiddle or Project
Unfortunately, **I cannot reproduce** the problem in a Fiddle or a separated project, because the use case is as simple as the following, however, the following **does not reproduce** the problem (obviously, something is still missing, but I cannot figure out what is it):

https://dotnetfiddle.net/MhPEWT

### Further technical details
- EF version: 6.2.0
- EF Extensions version: 3.22.4
- Database Provider: SQL Server

**Comment by JonathanMagnan** [comment]
Hello @davidnemeti ,

Thank you for reporting,

We will look at it as soon as possible.

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment]
Hello @davidnemeti ,

The v3.22.5 has been released.

Could you let me know if you have some additional issues? If yes, let me know which packages.

Best Regards,

Jonathan

**Comment by davidnemeti** [comment]
Thanks, it seems that by using v3.22.5 the "Oops! the SqlCommand could not be found" exception has gone.
