### ISSUE TITLE
Long query raises error in evaluation mode

### ISSUE THREAD

**Issue by mdelgadov** [zzzprojects/EntityFramework-Extensions#285]
### Description
When passing a string for a Where that can be complicated, like

.where(x => c. x.appointment.appointment_date.date.tostring() == "dateVar" and ... "

When the expression is short, it works
But as soon as it grows it throws the error
No applicable member has been found for the expression

in full:

{"Oops! No applicable member has been found for the expression. The error occurred for expression \".\" at position 3 near \".Where(x =>  x.Appointmen\"."}

We are evaulating to purchase and this doesn't help

EF core 2.1
 Z.EntityFramework.Extensions.EFCore -Version 2.6.18

**Comment by JonathanMagnan** [comment]
Hello @mdelgadov ,

There are no limitations on the string. In fact, you are probably using `DeleteFromQuery` or `UpdateFromQuery` which are free features in EF Extensions.

Do you think you could provide us an example of this issue? You can send it in private here info@zzzprojects.com
