### ISSUE TITLE
sqlconnection does not support parallel transactions error

### ISSUE THREAD

**Issue by rasimcetin** [zzzprojects/EntityFramework-Extensions#286]
I have a context class (MyContext) that has no default constructor. I have to create my context with a connection. For this I am using your context factory like this

SqlConnection newConnection = new SqlConnection();
EntityFrameworkManager.ContextFactory = context => new MyContext(connection);
using (MyContext context = new MyContext(connection));
{
...
}

Also I have a MyContext object (myContext) that comes with Dependecy Injection.
So far so good. 
But when I run the code below I am getting the error “sqlconnection does not support parallel transactions”.
The code like this: 

SqlConnection newConnection = new SqlConnection();
EntityFrameworkManager.ContextFactory = context => new MyContext(connection);
using (MyContext context = new MyContext(connection));
{
    using (var transaction = context.Database.BeginTransaction())
    {
        context.BulkInsert(mylist,options => options.IncludeGraph = true)
    }
}

And I tried the code like this.

EntityFrameworkManager.ContextFactory = context => new MyContext(myContext.Connection);
using (MyContext context = new MyContext(myContext.Connection));
{
    using (var transaction = context.Database.BeginTransaction())
    {
        context.BulkInsert(mylist,options => options.IncludeGraph = true)
    }
}

But all the time I am getting same error “sqlconnection does not support parallel transactions”.

You say in your tutorial BulkInsert, BulkDelete vs, does not use default transaction That’s the link https://entityframework-extensions.net/transaction 
When I analyze the exception stack trace there is a row like
  at Microsoft.EntityFrameworkCore.Infrastructure.DatabaseFacade.BeginTransaction().

As I understand after my transaction is initialized then another transation is also being initialized.
So there are two transaction at the time.

### Further technical details
- EF version: 2.2.4.0
- EF Extensions version: 2.6.16.0
- Database Provider: SQL Server 2014

**Comment by JonathanMagnan** [comment]
Hello @rasimcetin ,

It's possible for you to keep a reference of the current connection in the context?

Something similar to this:

```csharp
public class MyContext
{
	public SqlConnection InnerConnection { get ; set; }
	
	public MyContext(SqlConnection connection) : base(/*code*/)
	{
		InnerConnection = connection;
	}
}

EntityFrameworkManager.ContextFactory = context => {
	if(context is MyContext myContext)
	{
		return new MyContext(myContext.InnerConnection);
	}
};
```

So the same connection will be re-used which should fix the issue.

Best Regards,

Jonathan

**Comment by rasimcetin** [comment]
Hi Jonathan
this is my code last state and I got the same error again.

```
// this is my Context class
public class MyContext
{
    public Connection MyConnection {get; set;}
    
    public MyContext(Connection connection)
    {
        this.MyConnection = connection;
    }
}

// this my MyRepository
public class MyRepository
{
    public MyContext MyContext {get; set;}
    
    public MyRepository(MyContext myContext)
    {
        this.MyContext = myContext;
    }
    
    public void Save(List<MyEntity> list)
    {
        EntityFrameworkManager.ContextFactory = context =>
        {
            if (context is MyContext)
            {
                return new MyContext(this.MyContext.Connection);
            }
        }
        
        using (var context = new MyContext(this.MyContext.Connection))
        {
            using (var transaction = context.Database.BeginTransaction())
            {
                try
                {
                    context.BulkInsert(list, options => options.IncludeGraph = true);
                }
                catch (Exception ex)
                {
                    // get the same error
                    logger.Error(ex.Message);
                }
            }
        }
    }
}
```

Best regards,

**Comment by JonathanMagnan** [comment]
Make this small changes and try again

```csharp
 EntityFrameworkManager.ContextFactory = context =>
        {
            if (context is MyContext)
            {
                return new MyContext(((MyContext)context).Connection);
            }
        }
```

You currently use the `this.MyContext` which might be different of the context passed in parameter.

**Comment by rasimcetin** [comment]
Hello,

I have changed the code like below 

`// this my MyRepository
public class MyRepository
{
    public MyContext MyContext {get; set;}
    
    public MyRepository(MyContext myContext)
    {
        this.MyContext = myContext;
    }
    
    public void Save(List<MyEntity> list)
    {
        EntityFrameworkManager.ContextFactory = context =>
        {
            if (context is MyContext)
            {
                return new MyContext(new SqlConnection(this.MyContext.Connection.ConnectionString));
            }
        }
        
        using (var context = new MyContext(new SqlConnection(this.MyContext.Connection.ConnectionString))
        {
            using (var transaction = context.Database.BeginTransaction())
            {
                try
                {
                    if (list != null)
                    {
                        context.BulkInsert(list, options => options.IncludeGraph = true);
                        throw new Exception();
                    }
                    
                    transaction.Commit();
                    
                }
                catch (Exception ex)
                {
                    // Rollback does not work
                    transaction.Rollback();
                }
            }
        }
    }
}`

BulkInsert operation is done in this case but there is another problem.
When I throw an exception after insert, it does not make rollback.
The inserted data still exists in database.

**Comment by JonathanMagnan** [comment]
The `ContextFactory` must be set only once. For example in a static constructor, otherwise, you will have concurrency issue if you have multiple context type.

As for the transaction issue, it looks to work as expected: https://dotnetfiddle.net/jzU1XZ

**Comment by rasimcetin** [comment]
Your example is working in my side when I change the code like that
`if (list != null)
                    {
                        context.BulkInsert(list);
                        throw new Exception();
                    }
`

But if I want to insert entities which have child entity then it does not work.

**Comment by JonathanMagnan** [comment]
Hello @rasimcetin ,

My developer looked at it today. We were not able to reproduce it.

Here is a Fiddle with Child Entity that work: https://dotnetfiddle.net/w4yiiv

Do you think you could provide us a Fiddle or runnable solution with the issue? It will help us to go faster in the resolution if we have a way to reproduce it.

**Comment by rasimcetin** [comment]
Hello,
Actually the problem is just like your example at  [ https://dotnetfiddle.net/w4yiiv ].
It is working at Fiddle. And I found solution using TransactionScope.
So it is working in my code.

Thanks for your help.
