### ISSUE TITLE
error while inserting to a table with guid as an id. Provider: Pomelo.Mysql

### ISSUE THREAD

**Issue by markocska** [zzzprojects/EntityFramework-Extensions#289]
Hi,

I get the following Exception when I try to bulkinsert into an Amazon Aurora Mysql table, where the Id is a guid. I use Pomelo.EntityFrameworkCore.MySql 2.2: 
Unable to cast object of type "System.String" to type "System.Guid"

EntityFrameworkCore version: 2.2.6
Z.EntityFramework.Extensions.EFCore version: 2.6.18

**Comment by markocska** [comment]
Same issue with version Z.EntityFramework.Extensions.EFCore 2.7.2

**Comment by JonathanMagnan** [comment]
Hello @markocska ,

Thank you for reporting. We will look at it.

Do you have the same issue when you are not on Amazon?

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment]
Hello @markocska ,

The v2.7.3 has been released.

Could you test it and let us know if everything works as expected for `Guid` type?

Best Regards,

Jonathan

**Comment by markocska** [comment]
It works perfectly now, thank you :-) 

Best Regards, Mark

**Comment by JonathanMagnan** [comment]
Awesome,

Have a great week ;)

Best Regards,

Jonathan
