### ISSUE TITLE
Using both Z.EntityFramework.Extensions and Z.EntityFramework.Extensions.EFCore in the same project

### ISSUE THREAD

**Issue by Douuuglas** [zzzprojects/EntityFramework-Extensions#293]
### Description
I use EF Core and EF 6 in the same project. We are migrating things when we get some time. We already use "BulkInsert" from "Z.EntityFramework". I'm trying to use both Z.EntityFramework.Extensions and Z.EntityFramework.Extensions.EFCore in the same project but i'm having problems with the namespaces, because they are the same in both libraries. Is there a way i can use both together?

### Exception
![image](https://user-images.githubusercontent.com/17178270/66314173-09727c80-e8ea-11e9-855e-a2776a6cd996.png)

```
Exception message:
Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0433	The type 'LicenseManager' exists in both 'Z.EntityFramework.Extensions.EFCore, Version=2.7.5.0, Culture=neutral, PublicKeyToken=59b66d028979105b' and 'Z.EntityFramework.Extensions, Version=3.19.0.0, Culture=neutral, PublicKeyToken=59b66d028979105b'	Quirius.SuiteFiscal.DWService	C:\Git\PORTAL-QUIRIUS-EF6\PortalQuirius\Quirius.SuiteFiscal.DWService\Quirius.DWService\DWService.cs	22	N/A
```

### Further technical details
- EF Extensions version: 4.0.6.0
- EF Core Extensions version: 2.7.5.0

**Comment by JonathanMagnan** [comment]
Hello @Douuuglas ,

Thank you for reporting.

We already coded previously a workaround for the license. We will apply the same logic for all options.

We should be able to look at it today.

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment]
Hello @Douuuglas ,

A new version has been released.

It's now possible to access all options via `EF6Config` and `EFCoreConfig`. In your case, you should never use anymore the `EntityFrameworkManager` and `LicenseManager`

For example:

```csharp
EF6Config.AddLicense("name", "key");
EFCoreConfig.AddLicense("name", "key");
```

Let me know if everything works as expected.

Best Regards,

Jonathan

**Comment by Douuuglas** [comment]
Hello @JonathanMagnan ,
Thanks for the fast reply!

I upgraded the packages and did the changes you suggested.
The license seems to be OK, but the ContextFactory didn't work.

My repository looks like these (using Z.EntityFramework.Extensions.EFCore):
`public void BulkInsert(IEnumerable<ApuracaoImpostos> apuracoes)
        {
            _context.BulkInsert(apuracoes);
        }
`

My application startup do this:
`EFCoreConfig.ContextFactory = context =>
                {
                    return new ConciliadorContext(optionsBuilder.Options, defaultSchema);
                };
`
But the execution of the method still throwns an exception:
![image](https://user-images.githubusercontent.com/17178270/66924992-09692f80-f002-11e9-95bd-59761a9ea8f6.png)

Message: A default DbContext context must exist, or a context factory must be provided (EntityFrameworkManager.ContextFactory). This setting is required for some additional features. Read more: http://entityframework-extensions.net/context-factory

Stacktrace:    at Z.EntityFramework.Extensions.EntityFrameworkManager.(DbContext , BulkOperation )
   at .[](BulkOperation`1 this, DbContext , IEntityType , List`1 )
   at .[](BulkOperation`1 this, DbContext , IEntityType , List`1 , BulkOperationActionType )
   at .[](DbContext this, IEntityType , List`1 , Action`1 , Boolean )
   at .[](DbContext this, IEnumerable`1 , Action`1 )
   at DbContextExtensions.BulkInsert[T](DbContext this, IEnumerable`1 entities, Action`1 options)
   at DbContextExtensions.BulkInsert[T](DbContext this, IEnumerable`1 entities)
   at Quirius.Portal.Infra.Database.Repositories.ApuracaoImpostosRepository.BulkInsert(IEnumerable`1 apuracoes) in C:\Git\PORTAL-QUIRIUS-EF6\PortalQuirius\Quirius.Portal.Infra.Database\Repositories\Conciliacao\ApuracaoImpostosRepository.cs:line 17
   at Quirius.SuiteFiscal.Application.KPI.CommandHandlers.VisaoGerencialCommandHandler.Handle(ExecuteVisaoGerencialCommand message, CancellationToken cancellationToken) in C:\Git\PORTAL-QUIRIUS-EF6\PortalQuirius\Quirius.SuiteFiscal.Application\KPI\CommandHandlers\VisaoGerencialCommandHandler.cs:line 103

- Z.EntityFramework.Extensions.EFCore 2.7.9
- .EntityFramework.Extensions 4.0.9

**Comment by Douuuglas** [comment]
Hello @JonathanMagnan ,
I updated the packages and did the changes you suggested, everything is working fine now!
Thank you!
