### ISSUE TITLE
BulkSaveChanges in Teradata Database not working

### ISSUE THREAD

**Issue by hamiltonolivsi** [zzzprojects/EntityFramework-Extensions#297]
I'm trying to use BulkSaveChanges to insert a large entity into a Teradata database. After I call this method i get the following message: "Oops! The destination table name could not be found. That typically happens for an unsupported provider. If you use a custom connection, contact us to learn how to set it up within our library. Please report the issue to our support team : info@zzzprojects.com".

I'm using EF5 (since there's no support for Teradata in EF6) with Teradata .Net Provider 16.20.7.

FullName Connection: Teradata.Client.Provider.TdConnection.

**Comment by JonathanMagnan** [comment]
Hello @hamiltonolivsi ,

Unfortunately, we do not support Teradata either.

We have no plan at this moment to support it.

Best Regards,

Jonathan
