### ISSUE TITLE
EntityFrameworkExtensions.BulkMerge: FormulaUpdate not working in ORACLE

### ISSUE THREAD

**Issue by mentadev** [zzzprojects/EntityFramework-Extensions#298]
### Description
The BulkMerge is not working for Oracle provider. 
It does the INSERT for the new elements but it doesn't do the UPDATE for the existing elements. The FormulaUpdate does not work either.

The same code does works for Sql Server 2017. For SQL Server it does the merge but for Oracle it only does the INSERT.

### Exception
No exceptions thrown but the update does not takes place.

```
Exception message:
Stack trace:
```

### Fiddle or Project (Optional)
https://dotnetfiddle.net/RYEL08

### Further technical details
- EF version: EntityFramework Version="6.3.0" & Microsoft.EntityFrameworkCore Version="2.2.6
- EF Extensions version: Z.EntityFramework.Extensions.EFCore Version="2.7.9
- Database Provider: Oracle.EntityFrameworkCore Version="2.19.30
- Oracle: 18c XE

**Comment by JonathanMagnan** [comment]
Thank you @mentadev  for reporting,

We will look at it.

Best Regards,

Jon

**Comment by JonathanMagnan** [comment]
Hello @mentadev ,

We tried a few environments and the `UPDATE` is always working. It is possible for you to monitor the query that's executed by our library and report it?

**Comment by mentadev** [comment]
Hello @JonathanMagnan. You are right the UPDATE is working my mistake but the FormulaUpdate isn't. 
Here I have more detailed information.

The code is quite simple, merging the values of a simple table named "LOCATOR_NUMBERS" with two columns: 
- LOCATOR_NUMBERS_PK: string field which is the primary key
- LAST_LOCATOR_NUMBER: numeric field. 

In the following funcion I just retrieve the current values, I assign a hardcoded "50" number to the numeric field and my intention is that after doing the Merge the with the FormulaUpdate the final value of each record will be current value + 50 but the SUM operation is not executed.
Perhaps the FormulaUpdate is not defined properly:

> FormulaUpdate = "DestinationTable.LastLocatorNumber + StagingTable.LastLocatorNumber" 
Here I want to do a numeric SUM operation

`public async Task MergeLocators()
        {                        
            using (var context = new OracleDbContext())
            {
                var existingLocators = await context.LocatorNumbers.ToListAsync();
                foreach (var locator in existingLocators)
                {
                    locator.LastLocatorNumber = 50;                    
                }

                await context.BulkMergeAsync(existingLocators, options => {
                    options.PostConfiguration = bulk => {
                        bulk.ColumnMappings.Single(x => x.SourceName == "LastLocatorNumber").FormulaUpdate = "DestinationTable.LastLocatorNumber + StagingTable.LastLocatorNumber";
                    };
                    options.Log += s => Console.WriteLine(s);
                });
            }
        }`

Here you have the options.Log output:

-- Executing Command:
SELECT * FROM "INT"."LOCATOR_NUMBERS" WHERE 1 = 0
-- CommandTimeout:0
-- Executing at 24-10-2019 13:12:19

-- Completed at 24-10-2019 13:12:20
-- Result: SqlDataReader

-- Executing Command:
UPDATE "INT"."LOCATOR_NUMBERS" SET "LAST_LOCATOR_NUMBER" = :P_1 WHERE "LOCATOR_NUMBERS_PK" = :P_0 RETURNING 1 INTO :ZZZ_IS_UPDATED
--INSERT  INTO "INT"."LOCATOR_NUMBERS" ("LOCATOR_NUMBERS_PK", "LAST_LOCATOR_NUMBER") VALUES(:P_0, :P_1)
-- :P_1: System.Object[] (Type = Decimal, Size = 22)
-- :P_0: System.Object[] (Type = StringFixedLength, Size = 100)
-- :ZZZ_IS_UPDATED: System.Object[] (Type = Int32, Size = 0)
-- CommandTimeout:120
-- Executing at 24-10-2019 13:12:22

-- Completed at 24-10-2019 13:12:22
-- Result: 3

**Comment by JonathanMagnan** [comment]
Thank, we will look at it ;)

We were focused first on the `UPDATE` as we already know some options are not yet implemented on Oracle.

**Comment by mentadev** [comment]
Good, now I undertand.
I ran the same code but with another provider and the UPDATE does includes the FormulaUpdate.
So as you are saying the FormulaUpdate is not implemented for Oracle.

Here is the log:

`-- Executing Command:

UPDATE  "int"."locator_numbers" AS DestinationTable
SET     "last_locator_number" = DestinationTable.LastLocatorNumber + StagingTable.LastLocatorNumber
FROM (
SELECT @0_0 AS "locator_numbers_pk", @0_1 AS "last_locator_number", @0_2 AS ZZZ_Index
UNION ALL SELECT @1_0 AS "locator_numbers_pk", @1_1 AS "last_locator_number", @1_2 AS ZZZ_Index
UNION ALL SELECT @2_0 AS "locator_numbers_pk", @2_1 AS "last_locator_number", @2_2 AS ZZZ_Index
) AS StagingTable
WHERE DestinationTable."locator_numbers_pk" = StagingTable."locator_numbers_pk" ;`

**Comment by JonathanMagnan** [comment]
Hello @mentadev ,

We finally released a version that enables the `FormulaUpdate` and `FormulaInsert` for Oracle.

It took us more time than expected to make it works but could you confirm that everything works as expected?

Best Regards,

Jon

**Comment by JonathanMagnan** [comment]
Hello @mentadev 

A simple follow up to see if you got the time to try the new version.

Don't hesitate to contact us for questions, issues or feedback!

Best regards, 

Jon

**Comment by mentadev** [comment]
Hi Jonathan, I will try it this week. Thanks for the update.
I'll keep you posted.

Cheers
Menta

**Comment by JonathanMagnan** [comment]
Awesome @mentadev 

I'm looking forward to hearing from you! 

best regards, 

Jon

**Comment by mentadev** [comment]
Hi Jonathan, FormulaUpdate is working for ORA, thank you, I'll close the issue now.
