### ISSUE TITLE
instance was not detached if BulkUpdateAsync fails

### ISSUE THREAD

**Issue by kinch-tech** [zzzprojects/EntityFramework-Extensions#299]
if BulkUpdateAsync fails(say,exception throws), instance can not be detached. then not more further actions can be executed on this instance.

The instance of entity type 'xxxx' cannot be tracked because another instance with the same key value for {'ID'} is already being tracked. When attaching existing entities, ensure that only one entity instance with a given key value is attached. Consider using 'DbContextOptionsBuilder.EnableSensitiveDataLogging' to see the conflicting key values.

**Comment by JonathanMagnan** [comment]
Hello @kinch-tech ,

Which version of `EntityFramework` are you using? EF6 or EF Core?

Do you use `BulkUpdateAsync` with some special options?

**Comment by JonathanMagnan** [comment]
Hello @kinch-tech,

Since our last conversation, we haven't heard from you. 

Don't hesitate to provide us information so that we could answer your issue correctly!

Looking forward to hearing from you, 

Jon

**Comment by JonathanMagnan** [comment]
Hello @kinch-tech,

A quick reminder that we are here to assist you. 

Don't hesitate to provide us information. 

Best regards, 

Jon

**Comment by JonathanMagnan** [comment]
Hello @kinch-tech,

Since we haven't heard back, we will close this issue. 

Feel free to contact us once you can provide more information.

Best regards,

Jon
