### ISSUE TITLE
Error with enums in relational entity into UpdateFromQuery

### ISSUE THREAD

**Issue by nebre** [zzzprojects/EntityFramework-Extensions#30]
Hi,

When I try to filter from a relational enum, like this:

```
unitOfWork.Set<ClientContact>()
                    .Where(x => x.Client.Status == ClientsClientStatusEnum.Pending)
                    .UpdateFromQuery<ClientContact>(x => new ClientContact() { Code = "something" });
```

This try to update the Entity with this query:

```
exec sp_executesql N'MERGE INTO [Clients].[ClientContacts] AS DestinationTable
USING
(
SELECT 
    [Extent2].[StatusValue] AS [StatusValue], 
    [Extent1].[Id] AS [Id]
    FROM  [Clients].[ClientContacts] AS [Extent1]
    INNER JOIN [Clients].[Clients] AS [Extent2] ON [Extent1].[ClientId] = [Extent2].[Id]
    WHERE ([Extent2].[StatusValue] IN (3, 4))
) AS StagingTable
ON StagingTable.StatusValue = DestinationTable.StatusValue AND StagingTable.Id = DestinationTable.Id
WHEN MATCHED THEN
    UPDATE
    SET     [Code] = @zzzupdate_1
;',N',@zzzupdate_1 nvarchar(4)',@zzzupdate_1=N'something'
```

As you could show, it try to compare this enum into two different entities, because on stagingTable is from Clients and try to filter into ClientContacts

**Comment by JonathanMagnan** [comment]
Hello @nebre ,

Thank you for reporting this issue.

We will try to look at it and release a fix today.

More information will be available soon.

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment]
Hello @nebre ,

The v3.11.3 has been released
https://www.nuget.org/packages/Z.EntityFramework.Extensions/

Could you try it and let us know if the issue is fixed?

Best Regards,

Jonathan

**Comment by nebre** [comment]
Hi again,

I try with this new version but I still have the problem, nothing different, sorry.

```
exec sp_executesql N'MERGE INTO [Clients].[ClientContacts] AS DestinationTable
USING
(
SELECT 
    [Extent2].[StatusValue] AS [StatusValue], 
    [Extent1].[Id] AS [Id]
    FROM  [Clients].[ClientContacts] AS [Extent1]
    INNER JOIN [Clients].[Clients] AS [Extent2] ON [Extent1].[ClientId] = [Extent2].[Id]
    WHERE (3 = [Extent2].[StatusValue])
) AS StagingTable
ON StagingTable.StatusValue = DestinationTable.StatusValue AND StagingTable.Id = DestinationTable.Id
WHEN MATCHED THEN
    UPDATE
    SET     [Code] = @zzzupdate_1
;',N'@zzzupdate_1 nvarchar(9)',@zzzupdate_1=N'something'
```

Could I check anything else?

**Comment by JonathanMagnan** [comment]
Hello @nebre ,

You are right, we did a small (major) mistake in our fix.

The v3.11.6 has been released
https://www.nuget.org/packages/Z.EntityFramework.Extensions/

Could you try it and let us know if the issue is fixed this time ;) ?

Best Regards,

Jonathan

**Comment by nebre** [comment]
Perfect, works fine now, thanks a lot
