### ISSUE TITLE
Is it possible to turn the foreign key constraints off while using Bulk Insert?

### ISSUE THREAD

**Issue by g-dsouza** [zzzprojects/EntityFramework-Extensions#305]
Trying to use BulkInsert for data with a foreign key which contains a value not yet inserted in the primary table. 
Currently getting a Foreign key constraint Exception.
Is there a property which will turn the foreign key check off or is it possible to put in such an option?

- Database: SQL Azure
- EF version: 6.2.0
- EF Extensions version: 4.0.12

**Comment by JonathanMagnan** [comment]
Hello @g-dsouza ,

We will look at it. There is some circumstance that could be possible without altering the table.

Best Regards,

Jon

**Comment by g-dsouza** [comment]
Hi @JonathanMagnan,
Is there a time frame that we can look at by when this can be resolved?

Thanks

**Comment by JonathanMagnan** [comment]
Hello @g-dsouza ,

My developer investigated it.

There are two solutions

## Solution 1
Unlike the `SET IDENTITY_INSERT`, there is no option to turn off the foreign key constaints for the connection only. It needs to be done on the table: https://docs.microsoft.com/en-us/sql/relational-databases/tables/disable-foreign-key-constraints-with-insert-and-update-statements

So on your side, it could be possible to turn off temporary and turn it on back after.

We **don't recommend** doing it. 

## Solution 2
The `SqlBulkCopy` lets you insert without checking constraint (we currently check it at this moment)

So it could be possible for us to add an option named for example `DisableForeignKeyConstaint`. However, adding this option have some "side" impact when enabled:
- A `SqlBulkCopy` will always be performed even with 1 row
- Nothing can be returned, so the identity value will not be returned
- It will work only with BulkInsert, not with BulkMerge
- A lot of options such as `InsertFormula` will not be compatible

Is it something fine with you? If yes, then we will start to code this option. I do not believe it will be very long so it should be available at the start of next week.

**Comment by g-dsouza** [comment]
Hi @JonathanMagnan,
It will be great if you can implement Solution 2.

Thanks

**Comment by JonathanMagnan** [comment]
Awesome,

The task has been assigned to one of our developers.

**Comment by JonathanMagnan** [comment]
Hello @g-dsouza ,

A new version is now available with the option `IsCheckConstraintOnInsertDisabled`.

As specified, a `SqlBulkCopy` will be forced and almost **ALL** other options will be incompatible with this one.

```csharp
context.BulkInsert(list, option => option.IsCheckConstraintOnInsertDisabled = true);
```

Could you confirm that it works as you wanted?

**Comment by g-dsouza** [comment]
Hi @JonathanMagnan,

Thank you for the quick response!!!
I have been tied up with some other work and haven't had the time to test this new functionality.
Will let you know at the earliest

Thanks

**Comment by JonathanMagnan** [comment]
Hello @g-dsouza, 

we will be waiting for your feedback once you try it!

Best regards 

Jon

**Comment by JonathanMagnan** [comment]
Hello @g-dsouza 

A simple follow up to see if you got the chance to try the provided solution.

Looking forward to hearing from you

Jon
