### ISSUE TITLE
EntityFrameworkExtensions.BulkInsert: InsertIfNotExists is not working for PostgreSQL

### ISSUE THREAD

**Issue by skynet2** [zzzprojects/EntityFramework-Extensions#306]
The BulkInsert with the InsertIfNotExists is not working for PostgreSQL.
The SQL Sentence generated only includes the INSERT without checking for existing records using the primary key (or the defined with the ColumnPrimaryKeyExpression option).

Same as https://github.com/zzzprojects/EntityFramework-Extensions/issues/302

Thanks,
Stas

**Comment by JonathanMagnan** [comment]
Hello @skynet2 ,

A new version has been released. We added the support for `InsertIfNotExists` for `PostgreSQL`.

Could you try it and confirm that if everything works as expected?

Best Regards,

Jon

**Comment by JonathanMagnan** [comment]
Hello @skynet2,

Since our last conversation, we haven't heard from you. 

Did you get the time to try the latest version?

Looking forward to hearing from you,

Jon

**Comment by skynet2** [comment]
Hi @JonathanMagnan ,

The fix is working perfectly, thanks!

p.s. we contacted through email
