### ISSUE TITLE
SqlFileStream support

### ISSUE THREAD

**Issue by emdadgar2** [zzzprojects/EntityFramework-Extensions#310]
Hi,

Is theer any plan to support implement SqlFileStream and
make EF streaming?

Thanks

**Comment by JonathanMagnan** [comment]
Hello @emdadgar2 ,

Thank you for reporting.

We will look at it and see if that's possible.

Best Regards,

Jon

**Comment by JonathanMagnan** [comment]
Hello @emdadgar2 ,

We investigated this request, we learned a lot from it but unfortunately, we choose to don't support `SqlFileStream` at this moment.

The syntax required to support it is VERY different from what we currently use and we don't think we will be able to optimize the performance enough to make the time invested worth.
