### ISSUE TITLE
An error occured while resolving mapping by name. See the inner exception for details ---> System.Exception: Missing Colum

### ISSUE THREAD

**Issue by meeper34** [zzzprojects/EntityFramework-Extensions#313]
### Description
I have a windows service that is always running, and I am using the bulk insert functionality within this service.  If I add a new column to a table which has already had data bulk inserted (without restarting the service), I get the below error.  It seems like the library is caching previous mappings internally.  If there any way to turn off this caching?  If it is possible, will there be performance ramifications?

### Exception

System.Exception: An error occured while resolving mapping by name. See the inner exception for details ---> System.Exception: Missing Colum : MappedCodeTest
On Table : [TestMapping]
   at Z.BulkOperations.BulkOperation.?(String ?, Boolean ?, Boolean ?, Boolean ?)
   at Z.BulkOperations.BulkOperation.?()

### Further technical details
Entity Framework 6.2
Z.EntityFramework.Extensions 3.15.17

**Comment by JonathanMagnan** [comment]
Hello @meeper34 ,

Turning off the caching has huge performance impact (We will need to check the table every time a bulk operation is performed).

While I understand why removing a column could cause this issue (a mapped property with not any destination), there is certainly something we can do on our side when a new column is added to don't throw the error.

We will look at it.

Best Regards,

Jon

**Comment by JonathanMagnan** [comment]
Hello @meeper34 ,

We have some test and simply adding a column doesn't throw this error.

However, if a column is added and your `Entity Framework` model is modified, then our library can cause the error since the model has not been refreshed.

Is it possible that your mapping/model is modified on the fly when your table is modified? If that's the case, it's possible to refresh our model with the following method:

```csharp
context.RefreshModel();
```

If that's not the case, let me know more about your scenario and we will try to support it.

Best Regards,

Jon

**Comment by JonathanMagnan** [comment]
hello @meeper34 ,

Since our previous conversation, we haven't heard from you. 

Are you still encountering the error?

Don't hesitate to contact us with further information so that we can assist you better.

Best regards, 

Jon

**Comment by JonathanMagnan** [comment]
hello @meeper34 

A quick reminder that we are here to assist you.

don't hesitate to contact us if you are still encountering the error. 

Looking forward to hearing from you, 

Jon

**Comment by meeper34** [comment]
Sorry about the lack of reply.  I am handling this by catching the exception (System.Exception: Missing Colum) and then refreshing the model like you suggested.  Thanks!

**Comment by JonathanMagnan** [comment]
awesome this issue is reopened!

Feel free to contact us, we are here to assist you. 

Jon

**Comment by JonathanMagnan** [comment]
Hello again @meeper34,

Since our last conversation, we haven't heard from you. 

Did you get the time to work on the issue?

Looking forward to hearing from you, 

Jon

**Comment by shubhamkwn** [comment]
Hey @JonathanMagnan , 
I am using the dapperplus manager but I also encounter the same error and I am trying to use context.RefreshModels() but unable to use.

My senario is that the primary key of a table is trying to map with other primary key of table using Map fun but it is throwing the error as Mising Column .

**Comment by JonathanMagnan** [comment]
Hello @shubhamkwn ,

Could you open an issue here: https://github.com/zzzprojects/Dapper-Plus/issues

We will be happy to look at it. Opening a new issue and referencing in your text this closing issue will makes it easier for us to follow.
