### ISSUE TITLE
EF Core - Concurrent modification of an entity does not throw DbUpdateConcurrencyException when BulkSaveChanges() is called

### ISSUE THREAD

**Issue by estyfen** [zzzprojects/EntityFramework-Extensions#317]
### Description
When calling the BulkSaveChanges method it does not detect concurrency conflicts.

I expect that when conflict is detected then DbUpdateConcurrencyException should be thrown. However, BulkSaveChanges() does not throw an exception, it just silently ignores a conflicting update.

### Exception

**EF Core Native** : SaveChanges  passing test
**Z Extension EF Core** : BulkSaveChanges  failed test

    ```
    Dim saveFailed As Boolean = False
        Do
            Try
                saveFailed = False
                DC.BulkSaveChanges()
            Catch exC As DbUpdateConcurrencyException
                saveFailed = True
                For Each entry In exC.Entries
                    entry.OriginalValues.SetValues(entry.GetDatabaseValues())
                Next
            Catch ex As Exception
                Throw ex
            End Try
        Loop While saveFailed
```

### Further technical details
- EF version: Core 3.1
- EF Extensions version: 3.0.36
- Database Provider: SQL Server 2016

Thank you for your help.
Estyfen

**Comment by JonathanMagnan** [comment]
Hello @estyfen ,

Thank you for reporting.

We will look at it.

Best Regards,

Jon

**Comment by JonathanMagnan** [comment]
Hello @estyfen ,

I'm very sorry, we forget to answer you.

Our library doesn't throw a `DbUpdateConcurrencyException` since there is multiple rows that could be implicated. It instead throws a `DbBulkOperationConcurrencyException`.

Here is an example:

```csharp
try
{

    contextA.BulkSaveChanges();
}
catch (DbBulkOperationConcurrencyException ex)
{
    var list = ex.Entries.ToList();
}
```
