### ISSUE TITLE
Using FromCache causes inserts

### ISSUE THREAD

**Issue by joshmouch** [zzzprojects/EntityFramework-Extensions#319]
I'm using the latest EF Core and EntityFramework Extensions.

If I add FromCache() to a certain query in our application then the next time I try to save the DbContext, I get an error about inserting a duplicate row.  This duplicate row is one of the rows that was returned by the FromCache() method.  So for some reason, the entity is probably getting added to the DbContext, but is being put in an "added" state instead of an "unmodified" or something along those lines.

Is this a known issue?  We do have some interesting things going on with our IQueryable's (for example, using LinqKit in some places).  Does that matter?

```
Cannot insert duplicate key row in object '...' with unique index '..'. The duplicate key value is ...
The statement has been terminated.
```

**Comment by JonathanMagnan** [comment]
Hello @joshmouch ,

The `FromCache` method from `Entity Framework Plus` should return a list using `AsNoTracking()`.

So this case should not normally happen but maybe the `LinqKit` interfere with it as you specified.

Do you think you could provide us a small runnable project with this issue? It will be easier for us to investigate it as perhaps another third-party library you are using causes it.

Best Regards,

Jon

**Comment by joshmouch** [comment]
Maybe what's happening is I later attach a new entity to this "AsNoTracking" entity (via navigation property), which then causes the cached entity to think it needs to be added.

**Comment by JonathanMagnan** [comment]
Yup, that's definitively something that could cause it.

Entity coming from the Cache is shared, so usually, you should not modify them.
