### ISSUE TITLE
Better explanation of versions

### ISSUE THREAD

**Issue by maleet** [zzzprojects/EntityFramework-Extensions#32]
It would be nice to have more information about fixes what have been applied to new version.

Like:
FIXED: Issue with Database First && One to One Relationship

Good fix my current case. Sure there is internal project management behind and links to bug descriptions with fixes are not possible, but maybe little more than just one sentence? 

By the way, good job with this extension. I use it for bulk operations and it makes my application usable.

**Comment by JonathanMagnan** [comment]
Thank you for sharing your comment.

You are right. We need for sure to improve how we write the release note

We will for sure take more time to explain in detail the issue unless it's impossible.

Feel free to re-open this issue if you think we still we don't provide enough information next time

Best Regards,

Jonathan
