### ISSUE TITLE
BulkInsert + Table-separated entity by fluent API doesn`t work properly

### ISSUE THREAD

**Issue by KDaau** [zzzprojects/EntityFramework-Extensions#320]
Hello, my issue is next:
I have an entity, which is separated physically by 2 tables via FluentAPI Map command. When I try to insert a batch of objects into the DB with BulkInsert commant, I only get records inserted into the main table, but there are no approriate ones inserted into related second table, which causes then an impossibility to work with current record (current object becomes invisible for Entity Framework fetching).
Db Profiler showed me that only 1 INSERT statment was generated for 1 table during BulkInsert.

No exceptions are thrown.

Here`s the link to my Demo project, please, check it out: https://github.com/KDaau/z_EF_demo

I am using EF v 6.4.0.

**Comment by JonathanMagnan** [comment]
Hello @KDaau ,

Thank you for the project, my developer will look at it.

Best Regards,

Jon

**Comment by JonathanMagnan** [comment]
Hello @KDaau ,

We support TPC, TPH, and TPT: https://weblogs.asp.net/manavi/inheritance-mapping-strategies-with-entity-framework-code-first-ctp5-part-2-table-per-type-tpt

But unfortunately, we do not support table splitting like the way you did it.

Is it possible for you to create a TPT inheritance which is what I believe you want to do?

**Comment by JonathanMagnan** [comment]
Hello @KDaau,

Since our last conversation, we haven't heard from you. 

Is it possible for you to create a TPT inheritance which is what I believe you want to do?

Looking forward to hearing from you,

Jon

**Comment by JonathanMagnan** [comment]
Hello @KDaau 

A quick reminder that we are here to assist you. 

Is it possible for you to create a TPT inheritance which is what I believe you want to do?

Looking forward to hearing from you,

Jon

**Comment by JonathanMagnan** [comment]
Hello @KDaau,

Since we haven't heard back, we will close this issue. 

Feel free to contact us once you can provide more information.

Best regards,

Jon
