### ISSUE TITLE
EF6 BatchSaveChanges Timeout

### ISSUE THREAD

**Issue by Greg-Hitchon** [zzzprojects/EntityFramework-Extensions#321]
### Description
BatchSaveChanges seems to be ignoring the context.Database.CommandTimeout and using 30 s as a default. This can be fixed somewhat by using the options.BatchSize but would prefer to be able to extend the timeout as in the Bulk operations.

### Further technical details
- EF version: 6.2.0
- EF Extensions version: 4.0.39
- Database Provider: SQL Server

**Comment by JonathanMagnan** [comment]
Hello @Greg-Hitchon ,

Thank you for reporting.

We will look at it.

Best Regards,

Jon

**Comment by JonathanMagnan** [comment]
Hello @Greg-Hitchon ,

The v3.0.43 has been released.

The `BatchSaveChanges` should now honor the `CommandTimeout`.

Please let me know if everything is now working as expected.

Best Regards,

Jon

**Comment by Greg-Hitchon** [comment]
Great thanks!
