### ISSUE TITLE
DatabaseGeneratedOption.Identity Property isn't populated if not the Key

### ISSUE THREAD

**Issue by PTC-JoshuaMatthews** [zzzprojects/EntityFramework-Extensions#323]
### Description
```
`public class MyEntity
{
    [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
    [Required]
    public int Id { get; set; } // Id

    [Required]
    [Key]
    public System.Guid GUID { get; set; }
}`
```

The Id property is not populated after BulkSaveChanges. If I switch to standard EF SaveChanges it is populated. 

### Exception
If you are seeing an exception, include the full exceptions details (message and stack trace).

```
Exception message:
Stack trace:
```

### Fiddle or Project (Optional)
If you are able, 

Provide a Fiddle that reproduces the issue: https://dotnetfiddle.net/Uqe9sf

Or provide a project/solution that we can run to reproduce the issue.
- Make sure the project compile
- Make sure to provide only the code that is required to reproduce the issue, not the whole project
- You can send private code here: info@zzzprojects.com

Otherwise, make sure to include as much information as possible to help our team to reproduce the issue.

_Note: More information you provide, faster we can implement a solution._

### Further technical details
- EF version: 6
- EF Extensions version:
 `  <package id="Z.EntityFramework.Extensions" version="3.16.30" targetFramework="net452" />
  <package id="Z.EntityFramework.Plus.EF6" version="1.8.21" targetFramework="net452" />`
- Database Provider: SQL Server 2016

**Comment by JonathanMagnan** [comment]
Hello @PTC-JoshuaMatthews ,

Thank you for reporting, we will look at it.

We might indeed miss this case.

Best Regards,

Jon

**Comment by JonathanMagnan** [comment]
Hello @PTC-JoshuaMatthews ,

A new version has been released.

The latest version should now support this case when the `Identity` is not the key.

Let me know if everything works as expected.

**Comment by PTC-JoshuaMatthews** [comment]
@JonathanMagnan I tried to upgrade it but the new version won't accept my old license key. Do I need a new key?

**Comment by PTC-JoshuaMatthews** [comment]
I've tested it without a key and it is working as expected! Thanks for the fast turnaround!

**Comment by JonathanMagnan** [comment]
Awesome ;)

If your support & upgrades is expired, you might indeed need to renew it to get access to latest version.

Make sure to contact us for renewal discount.
