### ISSUE TITLE
Missing Column Error on BulkInsert using IncludeGraph = true on entities with properties not in Database

### ISSUE THREAD

**Issue by SteffenGammelgaard** [zzzprojects/EntityFramework-Extensions#324]
### Description
I have an entity with a one to many relationship (a collection) of nested entities, like an order with orderlines.
My orderline has a property that is not stored in the database.
The two top classes are generated by a tool as we have used database first, which is also why I added the property in a partial class

I use BulkInsert with the `IncludeGraph = true` option.
Below I have tried to add in the option to ignore the column, but I get the exact same result if I completely omit the `IncludeGraphOperationBuilder`.

I am able to get this to work by using the `ColumnInputExpression`, but that is clearly not what I want.

### Exception

```
Exception message:
An error occured while resolving mapping by name. See the inner exception for details

Inner Exception message:
Missing Colum : SomeColumn
On entity : OrderLine
On Table : [OrderLine]

This exception was originally thrown at this call stack:
	Z.BulkOperations.BulkOperation.(string, bool, bool, bool)
	Z.BulkOperations.BulkOperation.()
```

### Code
```
_dbContext.BulkInsert(orders, options => 
{ 
	options.IncludeGraph = true;
	options.IncludeGraphOperationBuilder = operation =>
	{
		if (operation is BulkOperation<OrderLine>)
		{
			var bulk = (BulkOperation<OrderLine>)operation;
			bulk.IgnoreOnInsertExpression = e => new { e.SomeColumn};
		}
	};
});

public partial class Order
{
	public Order()
	{
		OrderLines= new HashSet<OrderLine>();
	}

	public int Id { get; set; }

	public virtual ICollection<OrderLine> OrderLines { get; set; }
}

public partial class OrderLine
{
	public int Id { get; set; }

	public virtual Order { get; set; }
}

public partial class OrderLine
{
	public string SomeColumn { get; set; }
}
```

### Further technical details
- EF version: Core 3.1.1
- EF Extensions version: 3.0.39
- Database Provider: MS SQL

**Comment by JonathanMagnan** [comment]
Hello @SteffenGammelgaard ,

Thank you for reporting.

I asked my developer to look at it. That's definitively a scenario that we want our library to support.

Best Regards,

Jon

**Comment by JonathanMagnan** [comment]
Hello @SteffenGammelgaard ,

It is working with `SaveChanges`?

We currently try to reproduce the issue but we are not able to make it work even with `SaveChanges`. So we currently wonder if we forget something after the code has been generated in database first that you might have added.

**Comment by SteffenGammelgaard** [comment]
It turns out I was looking in the wrong place.

My `SomeColumn` was not part of the database table, so when I used `SaveChanges` it became obvious that I was missing a `[NotMapped]` attribute.

With that attribute the bulk stuff works perfectly, and clearly the `IgnoreOnInsertExpression` was meant for a scenario where the column exists in both the database and the entity, but should not be set.

Thank you for your help!
