### ISSUE TITLE
BulkInsertAsync not working as expected

### ISSUE THREAD

**Issue by Hariharankross** [zzzprojects/EntityFramework-Extensions#327]
**Description**
Hello, 
I am using Z.EntityFramework.Extensions.EFCore (Version 2.7.56.0) for EF Core with MySql database. I have used BulkUpdateAsync which is working fine, but when i use BulkInsertAsync the code has been executed successfully, but no entry has been made in database and also no exception has been thrown. Can you please check this issue and let me now

**Exception**
No Exception has been thrown.

**Further technical details**
- EF Core version: 2.1.2
- EF Extensions version: 2.7.56.0
- Database Provider: MySql

**Comment by JonathanMagnan** [comment]
Hello @Hariharankross ,

Are you sure the `Async` version has been executed? This is a common mistake to check the data but the task has not yet started.

Could you provide a runnable project with the issue? I don't think my developer will be able to reproduce it with the current description.

Best Regards,

Jon

**Comment by Hariharankross** [comment]
Thanks for your response. We tried to verify it using await but it throws below exception.

Exception:
'A default DbContext context must exist, or a context factory must be provided (EntityFrameworkManager.ContextFactory). This setting is required for some additional features. Read more: http://entityframework-extensions.net/context-factory'.

Also want to let you know that bulk update async version is working fine but we are facing this issue only for bulk insert async. Could you help us or suggest ways to overcome this issue meanwhile if you have runnable project then i will make and let you know.

**Comment by Hariharankross** [comment]
Hello @JonathanMagnan ,
Actually i found the missing part that u have already mentioned this type of issue from github. Now BulkInsertAsync is working fine after adding a line "EntityFrameworkManager.ContextFactory = container => new FBREMBaseDataContext(builder.Options);" in my startup.cs file. Thankyou for your response.

Below code is the solution for me.

Before: 
container.Register(() =>
            {
                var builder = new DbContextOptionsBuilder<MYBaseDataContext>();
                var connection = Configuration["ConnectionStrings:MySqlConnection"];
                builder.UseLoggerFactory(EFLoggerFactory).EnableSensitiveDataLogging();
                builder.UseMySQL(connection);                
                return new MYBaseDataContext(builder.Options);
            }, Lifestyle.Scoped);
After: 
container.Register(() =>
            {
                var builder = new DbContextOptionsBuilder<MYBaseDataContext>();
                var connection = Configuration["ConnectionStrings:MySqlConnection"];
                builder.UseLoggerFactory(EFLoggerFactory).EnableSensitiveDataLogging();
                builder.UseMySQL(connection);
                EntityFrameworkManager.ContextFactory = container => new MYBaseDataContext(builder.Options);
                return new MYBaseDataContext(builder.Options);
            }, Lifestyle.Scoped);

Solution:
EntityFrameworkManager.ContextFactory = container => new FBREMBaseDataContext(builder.Options);
