### ISSUE TITLE
EntityFrameworkManager BulkInsert Memory

### ISSUE THREAD

**Issue by npbenjohnson** [zzzprojects/EntityFramework-Extensions#329]
### Description
The contexts generated to perform BulkInsert operations appear to remain in-memory

### Exception
Out of memory after a number of large bulk inserts, despite using AutoMapOutputDirection = false. I have tracked the issue down to the Contexts being created by EntityFrameworkManager.ContextFactory never being released. Each call to BulkInsert runs the factory, which creates a dbcontext that is used for the insert operation, then never reused, which is not available for garbage collection.

### Further technical details
- EF version: 3.1.3
- EF Extensions version: 3.0.46
- Database Provider: SqlServer

**Comment by JonathanMagnan** [comment]
Hello @npbenjohnson ,

Could you provide a standalone project that shows this issue? It will help my developer to investigate this issue faster as many time when this kind of issue is reported, this is usually because of a bad usage of the `ContextFactory`.

Best Regards,

Jon

**Comment by npbenjohnson** [comment]
[UnitTestProject1.zip](https://github.com/zzzprojects/EntityFramework-Extensions/files/4477072/UnitTestProject1.zip)

**Comment by JonathanMagnan** [comment]
Thank you,

I believe you give us enough information to get us started to investigate it ;)

**Comment by JonathanMagnan** [comment]
Hello @npbenjohnson ,

We investigated a lot the issue. At this moment, we don't think that's caused by our library.

Why? In both case, without using our library you will still have `leak` in your unit test with `SaveChanges`

```csharp
public void DbOnlyProperty_BulkInserted_LeaksMemory_ChildScope()
{
	using (var db = InitDb(GetDbContextOptions().Options))
	{
		db.CtxUndeclaredAutoDateTimeEntities.AddRange(Enumerable.Range(0, 1000)
			.Select(x => new CtxUndeclaredAutoDateTimeEntity { }));
		db.SaveChanges();
		db.CtxUndeclaredAutoDateTimeEntities.AddRange(Enumerable.Range(0, 1000)
			.Select(x => new CtxUndeclaredAutoDateTimeEntity { }));
		db.SaveChanges();
		db.CtxUndeclaredAutoDateTimeEntities.AddRange(Enumerable.Range(0, 1000)
			.Select(x => new CtxUndeclaredAutoDateTimeEntity { }));
		db.SaveChanges();
	}
}
public void EntityProperty_BulkInserted_DoesNotLeakMemory_ChildScope()
{
	using (var db = InitDb(GetDbContextOptions().Options))
	{
		db.CtxDeclaredAutoDateTimeEntities.AddRange(Enumerable.Range(0, 1000)
			.Select(x => new CtxDeclaredAutoDateTimeEntity { }));
		db.SaveChanges();
		db.CtxDeclaredAutoDateTimeEntities.AddRange(Enumerable.Range(0, 1000)
			.Select(x => new CtxDeclaredAutoDateTimeEntity { }));
		db.SaveChanges();
		db.CtxDeclaredAutoDateTimeEntities.AddRange(Enumerable.Range(0, 1000)
			.Select(x => new CtxDeclaredAutoDateTimeEntity { }));
		db.SaveChanges();
	}
}

// EntityFrameworkManager.ContextFactory = (o) => new Ctx(options); (also commenting this line)
```

One difference is within our library, the `EntityProperty_BulkInserted_DoesNotLeakMemory` work slightly differently and might skip some logic about the `ValueGeneratedOnAdd` which we cannot skip with the `UndeclaredAutoDateTimeEntity` since that's a shadow property.

Can you also reproduce the same issue without our library with only `SaveChanges`? Just to make sure we both get the same behavior

**Comment by JonathanMagnan** [comment]
Hello @npbenjohnson 

Since our last conversation, we haven't heard from you.

Did you get the time to reproduce the same issue without our library with only SaveChanges?

Looking forward to hearing from you, 

Jon

**Comment by npbenjohnson** [comment]
Thanks for looking into this, if there is logic with the shadow properties that can't be worked around, this does seem like an efcore issue. When using the aspnetcore pooling, I think ResetState gets called quite a bit in the background so this would only end up being an issue with a series of very large operations. We moved our heavy db operations into a separate service so it gets reset more often without affecting our hosting and that has been an acceptable workaround.
