### ISSUE TITLE
BulkSaveChanges inconsistent behavior when saving value that exceeds max field length

### ISSUE THREAD

**Issue by ibootbg** [zzzprojects/EntityFramework-Extensions#333]
### Description
BulkSaveChanges behaves inconsistently depending on the number of updated records. When I set a value that exceeds the field's size I expect BulkSaveChanges to fail. This is consistent with SaveChanges. However if I only change a few records the update succeeds and the values in the table are truncated. When I update many records (e.g. 1000) the update correctly fails. Please see this [example](https://github.com/ibootbg/ZExtensionsTest/tree/issue/BulkSaveChanges_inconsistent_behavior_when_saving_value_that_exceeds_max_field_length-333).

### Further technical details
- EF version: 6.4.0
- EF Extensions version: 4.0.69
- Database Provider: SQL Server

**Comment by JonathanMagnan** [comment]
Hello @ibootbg ,

You are 100% right.

This behavior is depending on if a `SqlCommand` or `SqlBulkCopy` is executed. The `SqlCommand` auto truncate varchar while the `SqlBulkCopy` will throw an error.

It is possible to always truncate using the `options.AutoTruncate = true` options.

Unfortunately, for backward compatibility reason, we never fixed this issue (and we don't know which one should be the default behavior either!)

Let me know if that answers correctly to your question.

Best Regards,

Jon

**Comment by ibootbg** [comment]
Hi Jon,
My problem is that BulkSaveChanges truncates the string and I couldn't find a way to disable this behavior. Setting options.AutoTruncate = false did not help. Do you have any other suggestions?

**Comment by JonathanMagnan** [comment]
> My problem is that BulkSaveChanges truncates the string

You would like it to throw an error? I'm correct?

**Comment by ibootbg** [comment]
I would like it to not truncate the string. And then when it executes the SQL command, the DB will raise an error. This is how SaveChanges behaves.

**Comment by christophpre** [comment]
@JonathanMagnan Any updates on this?

We are facing the same issue and would like to have the option to always throw an error, if the string size exceeds the column length. Regardless of SqlCommand or SqlBulkCopy being used internally.

**Comment by rizi** [comment]
> @JonathanMagnan Any updates on this?
> 
> We are facing the same issue and would like to have the option to always throw an error, if the string size exceeds the column length. Regardless of SqlCommand or SqlBulkCopy being used internally.

+1 for an option to configure this behaviour.
Br

**Comment by JonathanMagnan** [comment]
Hello @christophpre , @rizi ,

We are currently looking at it with option (we need to keep the default behavior for backward compatibility).

The major difference between `SaveChanges` and our library is that we specify the `varchar` size while `SaveChanges` use `varchar(max)` which is why the full string is passed and the SQL error is thrown. So when that option will be enabled, for all kinds of char/varchar types, we will no longer specify the size.

Best Regards,

Jon

**Comment by rizi** [comment]
> Hello @christophpre , @rizi ,
> 
> We are currently looking at it with option (we need to keep the default behavior for backward compatibility).
> 
> The major difference between `SaveChanges` and our library is that we specify the `varchar` size while `SaveChanges` use `varchar(max)` which is why the full string is passed and the SQL error is thrown. So when that option will be enabled, for all kinds of char/varchar types, we will no longer specify the size.
> 
> Best Regards,
> 
> Jon

Thank you very much !

**Comment by JonathanMagnan** [comment]
Hello all,

The v6.13.10 has been released with a fix for the `AutoTruncate` option.

The default value for `AutoTruncate` is null (no value). so when nothing is specified:
- The `SqlCommand` will always work
- The `SqlBulkCopy` will throw an error when the length is greater than the one in the database

When `AutoTruncate = true`:
- If the length is invalid, **no error** will be thrown  (`SqlCommand` and `SqlBulkCopy`). The value is automatically truncated.

When `AutoTruncate = false`:
- If the length is invalid, **an error** should always be thrown  (`SqlCommand` and `SqlBulkCopy`) 

As said, we currently cannot change the current behavior for backward compatibility. But you can choose which kind of behavior you want.

You can always change the current behavior by default for all operations:

```csharp
EntityFrameworkManager.BulkOperationBuilder = builder => AutoTruncate = false;
```

**Comment by d-57u3ndl** [comment]
> 

Thanks for the quick implementation.

The `AutoTruncate` option behaves as described and solves my problem!

**Comment by JonathanMagnan** [comment]
Great to hear! 

Don't hesitate to contact us if you need further assistance. 

BEst regards, 

Jon
