### ISSUE TITLE
BulkUpdate with the ColumnInputExpression is not working for ORACLE

### ISSUE THREAD

**Issue by arielunanueAtKTC** [zzzprojects/EntityFramework-Extensions#336]
Description
The BulkUpdate with the ColumnInputExpression is not working for ORACLE.
The SQL Sentence generated is not considering to update only the columns specified with the "ColumnInputExpression" options.
Currently the error risen is that "the IDENTITY cannot be set because it is configured to be ALWAYS" but the problem is that the library is trying to update fields that were not specified in the "ColumnInputExpression" options
Below the "log" generated. As you can see it is including the TransitForManualValidationId field in the update but is it wrong, It is the primary key (and defined as primary key in the mapping) but also it was not added to the ColumnInputExpression therefore it should not update that field.
Exception

```txt
-- Executing Command:
SELECT * FROM "ETRX"."TRANSITS_FOR_MANUAL_VALIDATION" WHERE 1 = 0
-- CommandTimeout:0
-- Executing at 18/5/2020 18:13:57

-- Completed at 18/5/2020 18:13:57
-- Result: SqlDataReader



-- Executing Command:
UPDATE "ETRX"."TRANSITS_FOR_MANUAL_VALIDATION" SET "FILTERS_FOR_MANUAL_VALIDATION_ID" = :P_0, "STATUS_FOR_VALIDATION_ID" = :P_1, "TRANSITS_FOR_MANUAL_VALIDATION_ID" = :P_2 WHERE "TRANSITS_FOR_MANUAL_VALIDATION_ID" = :P_2
-- :P_0: System.Object[] (Type = Decimal, Size = 22)
-- :P_1: System.Object[] (Type = Int64, Size = 22)
-- :P_2: System.Object[] (Type = Decimal, Size = 22)
-- :P_2:  (Type = Decimal, Size = 22)
-- CommandTimeout:120
-- Executing at 18/5/2020 18:13:58

-- Failed with error: ORA-32796: no se puede actualizar una columna de identidad siempre generada
```

Fiddle or Project (Optional)
Attached the definicions for the table and the c# class.
Below the code which is quite simple. A class with only 3 fields, we set the values to the three fields but only want to update two of it. The update generated does the UPDATE for the three fields.

```csharp
EntityFrameworkManager.ContextFactory = cnxt => new DbContext();
            using (var dbContext = new DbContext())
            {
                var trxsToLock = new List<TransitForManualValidation>();                
                trxsToLock.Add(new TransitForManualValidation
                {
                    TransitForManualValidationId = 1,
                    FilterForManualValidationId = 362,
                    StatusForValidationId = ValidationStatuses.BLOCKED
                });

                dbContext.BulkUpdate(trxsToLock, options =>
                {
                    options.ColumnInputExpression = c => new { c.FilterForManualValidationId, c.StatusForValidationId };
                    options.Log = s => Console.WriteLine(s);
                });
                
                Assert.IsTrue(true);
            }
```

Further technical details
EF version: EntityFramework Version="6.3.0" & Microsoft.EntityFrameworkCore Version="2.2.6
EF Extensions version: Z.EntityFramework.Plus.EFCore Version="2.0.50
Database Provider: Oracle.EntityFrameworkCore Version="2.19.70
Oracle: 18c XE

**Comment by JonathanMagnan** [comment]
Thank you for reporting,

We will try it and provide you a project if we cannot reproduce.

Best Regards,

Jon

**Comment by JonathanMagnan** [comment]
Hello @arielunanueAtKTC ,

Could you show us how your mapping is done? We made a few tests which they all worked but I believe the issue happens due to the mapping.

Here is a short example we tried:

```csharp
{
	// CLEAR 
	using (var context = new EntityContext())
	{
		context.TRANSITS_FOR_MANUAL_VALIDATIONS.RemoveRange(context.TRANSITS_FOR_MANUAL_VALIDATIONS);
	}

	// SEED  
	using (var context = new EntityContext())
	{
		for (int i = 0; i < 1; i++)
		{
			context.TRANSITS_FOR_MANUAL_VALIDATIONS.Add(new TRANSITS_FOR_MANUAL_VALIDATION() { StatusForValidationId = i, FilterForManualValidationId = i});
		}

		context.SaveChanges();
	}

	StringBuilder sb = new StringBuilder();

	// TEST  
	using (var context = new EntityContext())
	{
		var toUpdate = context.TRANSITS_FOR_MANUAL_VALIDATIONS.ToList();
		toUpdate.ForEach(x => x.StatusForValidationId += 1);

		context.BulkUpdate(toUpdate, options =>
		{
			options.ColumnInputExpression = c => new { c.FilterForManualValidationId, c.StatusForValidationId };
			options.Log = s => sb.AppendLine(s);
		});
	}

	var log = sb.ToString();
}

public class EntityContext : DbContext
{
	public EntityContext() : base("CodeFirstEntities")
	{
		Database.SetInitializer(new NullDatabaseInitializer<Form_Request_DeleteFormula.EntityContext>());
	}

	public DbSet<TRANSITS_FOR_MANUAL_VALIDATION> TRANSITS_FOR_MANUAL_VALIDATIONS { get; set; }

	protected override void OnModelCreating(DbModelBuilder modelBuilder)
	{
		modelBuilder.HasDefaultSchema("SYSTEM");

		base.OnModelCreating(modelBuilder);
	}
}

[Table("TRANSITS_FOR_MANUAL_VALIDATION")]
public class TRANSITS_FOR_MANUAL_VALIDATION
{
	[Key]
	[DatabaseGenerated(DatabaseGeneratedOption.Identity)]
	[Column("TRANSITS_FOR_MANUAL_VALIDATION_ID")]
	public decimal TransitsForManualValidationId { get; set; }
	
	[Column("STATUS_FOR_VALIDATION_ID")]
	public long StatusForValidationId { get; set; }
	
	[Column("FILTERS_FOR_MANUAL_VALIDATION_ID")]
	public decimal FilterForManualValidationId { get; set; }
	}
}
```

We made some tests with and without specifying the column is an identity.

Could you help us to get started with this issue?

**Comment by arielunanueAtKTC** [comment]
Hello Jonathan,
I’m sending you the TransitsForManualValidation class, the Mapper class (we use fluent API) for the mapping. Also the DDL for the ORA table.
Please note that there are many other fields in the class that I excluded in the original post because those are not important, can be ignored.


  *   TransitForManualValidation.cs: entity class
  *   TransitForManualValidationMap.cs: mapper class using Fluent API.
  *   TransisForManualValidation_DLL: DLL for the ORA TABLE

Then we have the dbcontext class
public class SmartTollEtrxDbContextBase : DbContext
{
       protected override void OnModelCreating(ModelBuilder modelBuilder)
{
             modelBuilder.ApplyConfiguration(new Models.Configuration.Oracle.TransitForManualValidationMap());
}
}

Ariel

**Comment by JonathanMagnan** [comment]
Could you answer it by email: info@zzzprojects.com?

I believe you attached some files and unfortunately, replying to GitHub doesn't include those files so you need to send it directly to us.

**Comment by arielunanueAtKTC** [comment]
Hello Jonathan,
I’m sending you the TransitsForManualValidation class, the Mapper class (we use fluent API) for the mapping. Also the DDL for the ORA table.
Please note that there are many other fields in the class that I excluded in the original post because those are not important, can be ignored.


  *   TransitForManualValidation.cs: entity class
  *   TransitForManualValidationMap.cs: mapper class using Fluent API.
  *   TransisForManualValidation_DLL: DLL for the ORA TABLE

Then we have the dbcontext class
public class SmartTollEtrxDbContextBase : DbContext
{
       protected override void OnModelCreating(ModelBuilder modelBuilder)
{
             modelBuilder.ApplyConfiguration(new Models.Configuration.Oracle.TransitForManualValidationMap());
}
}

Ariel

**Comment by JonathanMagnan** [comment]
Hello @arielunanueAtKTC ,

Just to let you know that we successfully reproduced the issue and one of my developers is currently working on it.

**Comment by arielunanueAtKTC** [comment]
Great! looking forward for the fix.
Cheers

**Comment by JonathanMagnan** [comment]
Hello @arielunanueAtKTC ,

A new version has been released for `EF6` and `EF Core`.

Both versions should now honor correctly the `ColumnInputExpression` and stop adding the primary key.

Let us know if everything now works as well as expected on your side.

Best Regards,

Jon

**Comment by arielunanueAtKTC** [comment]
Hi Jon, I don't see the new version.
https://www.nuget.org/packages/Z.EntityFramework.Plus.EFCore

The latest is 2.0.50 and that is the version for which I have reported the bug. I was expecting the 2.0.52/3.0.52 and so on.

**Comment by JonathanMagnan** [comment]
Hello @arielunanueAtKTC ,

The bug was in the EF Extensions library.

So you need to update this dependency: https://www.nuget.org/packages/Z.EntityFramework.Extensions.EFCore/2.7.75

We only update the reference of EF Plus from time to time. Not every time a new version of EF Extensions is released.

Let me know if that answer correctly.

Best Regards,

Jon

**Comment by arielunanueAtKTC** [comment]
Hi Jon,
**issue solved! thanks!!!**

However the BulkInsert for ORA is behaving in a similar way, do you want me to create a new ticket?
I think there is an issue with the Fluent API mapping and the ORA Identity fields.

If you use the same code I sent you, the bulk Insert for ORA fails because it is trying to insert a value for an "IDENTITY ALWAYS GENERATED" field.

This code fails
`
var trxsToLock = new List<TransitForManualValidation>();                
                trxsToLock.Add(new TransitForManualValidation
                {                   
                    FilterForManualValidationId = 362,
                    StatusForValidationId = ValidationStatuses.BLOCKED
                });
await smartTollDb.BulkInsertAsync(trxsToLock);
`

So I have to use this for ORA
`
await smartTollDb.BulkInsertAsync(trxsToLock,
                        options => options.IgnoreOnInsertExpression = t => new { t.TransitForManualValidationId}));
`

**Comment by JonathanMagnan** [comment]
Awesome @arielunanueAtKTC !

Don't hesitate to contact us for questions, issues or feedback.

Best regards,

Jon

**Comment by arielunanueAtKTC** [comment]
I'm closing this issue and opening a new one for the BulkInsertAsync problem for ORA with identity fields
