### ISSUE TITLE
Error starting with 4.0.50 for table with always-encrypt

### ISSUE THREAD

**Issue by careLearning** [zzzprojects/EntityFramework-Extensions#338]
### Description
We recently upgraded from 3.x to the latest and immediately get an error when we run bulk insert statements.  We have tracked it down to first being broken in 4.0.50.  Did something change during that release that might be a breaking change?  We can't find any release notes not documentation per release.  This database uses encryption as some sensitive data is stored there.  We have followed the MS docs to set that up (https://docs.microsoft.com/en-us/sql/relational-databases/security/encryption/always-encrypted-database-engine?view=sql-server-ver15).  Do you have any idea as to what could have changed with this version to cause an error with encrypted tables?

### Exception
anyName.AbpZeroTemplate.Provider.Program - System.Exception: An error occurred while updating the entries. See the inner exception for details. ---> System.Data.SqlClient.SqlException: Operand type clash: varchar is incompatible with varchar(15) encrypted with (encryption_type = 'DETERMINISTIC', encryption_algorithm_name = 'AEAD_AES_256_CBC_HMAC_SHA_256', column_encryption_key_name = '***OMITTED*****', column_encryption_key_database_name = '*****OMITTED*****') collation_name = 'Latin1_General_BIN2'
Statement(s) could not be prepared.
at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action1 wrapCloseInAction) at System.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action1 wrapCloseInAction)
at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
at System.Data.SqlClient.SqlDataReader.TryConsumeMetaData()
at System.Data.SqlClient.SqlDataReader.get_MetaData()
at System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString, Boolean isInternal, Boolean forDescribeParameterEncryption, Boolean shouldCacheForAlwaysEncrypted)

### Further Details:

version | outcome
-- | --
starting point | works.
4.0.75 | error
latest 3.x | works
4.0.0 | works
4.0.73 | error
4.0.35 | works
4.0.54 | error
4.0.45 | worked
4.0.50 | error <--earliest error
4.0.47 | worked
4.0.48 | works
4.0.49 | works <-- latest working state

**Comment by JonathanMagnan** [comment]
Hello @careLearning ,

Thank you for reporting.

We will look at it and see what has been modified and make the fix.

We will also make sure to add some additional unit tests to make sure that the backward compatibility issues never happens again.

Best Regards,

Jon

**Comment by JonathanMagnan** [comment]
Hello @careLearning ,

We indeed made a modification that is returning a column in some cases that were not returned before (which should have been).

However, I believe you are missing an option that you were not needed on your side before. When using column encryption, you need to let our library know that your table have an encrypted column. Either for a specific operation or globally like the example below:

```csharp
EntityFrameworkManager.BulkOperationBuilder = builder =>
{
    builder.HasColumnEncrypted = true;
};
```

You only need to set this builder once if you do it globally.

When doing it, our library will have different behavior to support the column encrypted.

Could you try it and let me know if that fix it?

**Comment by JonathanMagnan** [comment]
Hello @careLearning ,

Since our previous conversation, we haven't heard from you. 

Did you get the chance to try the provided solution?

Let us know if you have any questions, feedback, or issues.

Looking forward to hearing from you,

Jon

**Comment by careLearning** [comment]
Hi Jon,

We have had some emergencies to attend to but hope to test this very soon and get back to you.    We were not using the "builder.HasColumnEncrypted = true" and are excited the the solution could be so simple.  We appreciate the follow-up and will reply soon.

Thanks again.

**Comment by JonathanMagnan** [comment]
Awesome @careLearning 

Don't hesitate to contact us once you give it a try!

Have a great week, 

Jon

**Comment by careLearning** [comment]
Hi Jon,

I tested the solution above and it did resolve the specific error we first reported.  I put the code in startup.cs in the web project of the solution at the end of the Configuration method where we are configuring other settings.

However, now we are getting this error instead, 

_"Store update, insert, or delete statement affected an unexpected number of rows (0). Entities may have been modified or deleted since entities were loaded. See http://go.microsoft.com/fwlink/?LinkId=472540 for information on understanding and handling optimistic concurrency exceptions."_  

This error does not exist if I run the deletes as single deletes in a loop.  It only happens when we use the BulkDelete functionality.  

Would you have any advice on how to troubleshoot this?

**Comment by JonathanMagnan** [comment]
Hello @careLearning ,

It is possible for you to reproduce it in a standalone project?

It might be caused by us due to a mistake when handling concurrency and the option `HasColumnEncrypted = true`.

I asked my developer to try it but I'm not sure if he will be able or not yet to reproduce it.

**Comment by JonathanMagnan** [comment]
Hello @careLearning ,

Unfortunately, we didn't succeed to reproduce it.

Could you provide more information, for example, the SQL generated and execute for when it works and when it doesn't work. You can get this SQL from SQL Profiler or by using the Entity Framework logger.

Obviously, having a runnable example with the issue will be even better.

Best Regards,

Jon

**Comment by careLearning** [comment]
Hi Jon,

We are still trying to produce a project that is small enough to send you, but large enough to replicate the issue.  We have spent hours on this.  I have the trace file.  Is there a private way I can send it to you?

Thank you.

**Comment by JonathanMagnan** [comment]
Hello @careLearning ,

Thank you for getting back to me!

You can send us the project at our mailbox info@zzzprojects.com

Looking forward to hearing from you, 

Jon

**Comment by careLearning** [comment]
The email is on the way.  Thanks.

**Comment by careLearning** [comment]
We were able to track down the issue.  It was not with your bulk tools.  We were pulling data that was being tracked by entity framework and then bulk deleting that data.  When we use the “.AsNoTracking” method or set the state to be “Detached” then the error goes away.  Thank you for your help.

**Comment by JonathanMagnan** [comment]
Awesome ;)

Thank for letting us know.

Have a great day

Best Regards,

Jon
