### ISSUE TITLE
Error on IgnoreOrMergeUpdateExpression

### ISSUE THREAD

**Issue by ilushka85** [zzzprojects/EntityFramework-Extensions#340]
I receive an invalid expression when including ignoreonmergeupdateexpression

 public class HubSpotContact
    {
        public Guid CompanyId { get; set; }
        public long HubspotId { get; set; }
        public string PhoneNumber { get; set; }
        public string Email { get; set; }
    }  

await _dbContext.SingleMergeAsync(contact, options =>
                        {
                            options.IgnoreOnMergeUpdateExpression =
                                c => new {contact.Email};
                        }
                    );

**Comment by JonathanMagnan** [comment]
Hello @ilushka85 ,

It should be

```csharp
await _dbContext.SingleMergeAsync(contact, options =>
{
options.IgnoreOnMergeUpdateExpression =
c => new {c.Email};
}
);
```

`contact` doesn't exist in the context, you named it `c`.

Let me know if that solves correctly your issue.

Best Regards,

Jon
