### ISSUE TITLE
InsertFromQuery Error when combined with select

### ISSUE THREAD

**Issue by npbenjohnson** [zzzprojects/EntityFramework-Extensions#341]
### Description
It's not clear from the docs if InsertFromQuery shouldn't or shouldn't support this situation, but chaining InsertFromQuery onto the end of a select statement errors out.

### Exception
If you are seeing an exception, include the full exceptions details (message and stack trace).

```
Unhandled exception. System.Exception: Oops! An attempt to create an anonymous in a no MemberInitExpression occured.
   at .[](Expression`1 )
   at `1.()
   at `1.Execute(IQueryable`1 query, String databaseName, String schemaName, String tableName, Expression`1 selectFieldsExpression, Type tableType)
   at DbContextExtensions.[](IQueryable`1 , String , String , String , Expression`1 , Type )
   at DbContextExtensions.InsertFromQuery[TEntity](IQueryable`1 query, Expression`1 selectFieldsExpression)
   at Program.Main()
Command terminated by signal 6
```

### Fiddle or Project (Optional)
https://dotnetfiddle.net/jDOzVg

### Further technical details
- EF version: Core 3.1
- EF Extensions version: 3.0.51
- Database Provider: SqlServer

**Comment by JonathanMagnan** [comment]
Hello @npbenjohnson ,

We will look at it.

I think we should indeed support the following syntax `c=>c` as this seem pretty valid for me.

Best Regards,

Jon

**Comment by alxocity** [comment]
I'm running into this as well. Any updates?

**Comment by JonathanMagnan** [comment]
Hello @alxocity ,

I fix should be available soon I hope.

I currently need to review the fix provided by my developer.

**Comment by klinckag** [comment]
Running into the same problem.
Any news on this?

**Comment by JonathanMagnan** [comment]
Hello all,

It has been a while since this request was created but we finally did it.

Starting from the v5.1.18 it should finally support this syntax.

When doing `InsertFromQuery(x => x)`, all properties will be automatically selected beside those marked as "generated" such an identity.

More improvements are coming including `EF6` support.

**Comment by JonathanMagnan** [comment]
Hello all,

Just to let you know that starting from v5.1.20, this syntax is also supported for EF6.
