### ISSUE TITLE
StackOverflowException occurred while calling Database.ExecuteDataSet

### ISSUE THREAD

**Issue by andywu188** [zzzprojects/EntityFramework-Extensions#343]
### Description

I tried to get a DataSet from the database, but there was a StackOverflowException exception. Copy the ExecuteDataSet related code from the Z.EntityFramework.Extensions source code and execute it independently. There is no problem. I think it is the assembly that confuses some public methods to cause this exception.

### Exception

System.StackOverflowException:“Exception_WasThrown”

Exception message:
Stack trace:

System.StackOverflowException
  HResult=0x800703E9
  Message=Exception_WasThrown

### Fiddle or Project (Optional)

var ds = Database.ExecuteDataSet("SELECT NEWID()", null, CommandType.Text);

### Further technical details
- EF version:6.2.0
- EF Extensions version:4.0.79
- Database Provider:MS SQL Server 2008 R2

**Comment by JonathanMagnan** [comment]
Hello @andywu188 ,

Thank you for reporting.

You are right, we are missing a parameter so the same method is called again and again.

We will review all our execute methods to make sure we didn't make any similar mistakes.

Best Regards,

Jon

**Comment by JonathanMagnan** [comment]
Hello @andywu188 ,

The v4.0.80 has been released.

Let me know if now everything is working as expected.

Best Regards,

Jon
