### ISSUE TITLE
The properties of the DataTable column obtained by calling Database.ExecuteDataTable are incorrect.

### ISSUE THREAD

**Issue by andywu188** [zzzprojects/EntityFramework-Extensions#345]
### Description
The properties of the DataTable column obtained by calling Database.ExecuteDataTable are incorrect. At present, four property values ​​have been found to be incorrect. For details, please see the following sample code. The following code demonstrates the use of Z.EntityFramework.Extensions and System.Data.SqlClient Get DataTable, and output the attributes of the column

### Fiddle or Project (Optional)
**DEMO1:**

            var dt = Database.ExecuteDataTable("SELECT *  FROM [dbo].[Book]"，null，CommandType.Text);
            foreach (DataColumn c in dt.Columns)
            {
                Console.WriteLine($"ColumnName = {c.ColumnName}, AllowDBNull = {c.AllowDBNull},  ReadOnly = {c.ReadOnly}, MaxLength = {c.MaxLength}, Unique = {c.Unique}");
            }
//The result obtained by this demo, ReadOnly may be true, MaxLength is greater than 0

**DEMO2:**

            var cmd = Database.Connection.CreateCommand();
            cmd.Transaction = Database.CurrentTransaction?.UnderlyingTransaction;
            cmd.CommandType = CommandType.Text;
            cmd.CommandText = "SELECT *  FROM [dbo].[Book]";
            //cmd.Parameters.AddRange(parameters);
            var dt = new DataTable();
            if (Database.Connection.State != ConnectionState.Open)
            {
                Database.Connection.Open();
            }
            using (var sdr = new System.Data.SqlClient.SqlDataAdapter(cmd as System.Data.SqlClient.SqlCommand))
            {
                sdr.Fill(dt);
            }

            foreach (DataColumn c in dt.Columns)
            {
                Console.WriteLine($"ColumnName = {c.ColumnName}, AllowDBNull = {c.AllowDBNull},  ReadOnly = {c.ReadOnly}, MaxLength = {c.MaxLength}, Unique = {c.Unique}");
            }
//The result obtained by this demo, ReadOnly is false, and MaxLength is -1

### Further technical details
- EF version:6.2.0
- EF Extensions version:4.0.79
- Database Provider:MS SQL Server 2008 R2

**Comment by JonathanMagnan** [comment]
Hello @andywu188 ,

Thank you for reporting, we will try it on our side.

Our library also uses the `SqlDataAdapter` so it's a little bit weird.

```csharp
using (adapter)
{
	adapter.SelectCommand = command;
	adapter.Fill(dt);
}
```

Best Regards,

Jon

**Comment by JonathanMagnan** [comment]
Hello @andywu188 ,

My developer investigates it but in fact, our library return the right information.

You don't fill the schema in your demo2 which means it doesn't populate some attributes such as ReadOnly and MaxLength.

If you fill the schema:

```csharp
using (var sdr = new System.Data.SqlClient.SqlDataAdapter(cmd as System.Data.SqlClient.SqlCommand))
                    {
                        sdr.FillSchema(dt, SchemaType.Mapped);
                        sdr.Fill(dt);
                    }
```

You will get the same result.

So unless I misunderstood something, there is no bug here.

Best Regards,

Jon
