### ISSUE TITLE
error A `GUID` has been provided, but the property

### ISSUE THREAD

**Issue by mahdisky** [zzzprojects/EntityFramework-Extensions#346]
hi 
i used this articel [https://entityframework-extensions.net/context-factory](https://entityframework-extensions.net/context-factory)

` EntityFrameworkManager.ContextFactory = _context => {
                    var optionsBuilder = new DbContextOptionsBuilder<ApplicationDbContext>();
                    optionsBuilder.UseSqlServer(connection);
                    return new ApplicationDbContext(optionsBuilder.Options);
                };`

for IncludeGraph
but after running error: 
Exception: Oops! A `GUID` has been provided, but the property: 'Id' is currently specified to be database generated. Is it intended? Please report the issue to our support team if you believe this error should not appear: info@zzzprojects.com

**Comment by JonathanMagnan** [comment]
Hello @mahdisky ,

Unfortunately, our library still doesn't support to provide `Guid` value when the database is set to generate it.

We are currently working on a new version (for EF Core 5) which already allow it but unfortunately, this version is not ready yet and it involves way too many changes to put it in older version of EF Core.

So while that's currently possible to set a `Guid` value in EF Core 5 on a database generated column, that's currently impossible with our library for the moment but we are working on it.

Let me know if that answers the current exception.

Best Regards,

Jon
