### ISSUE TITLE
EntityFrameworkExtensions.BulkInsert: InsertIfNotExists is not working for ORACLE >= 18 

### ISSUE THREAD

**Issue by arielunanueAtKTC** [zzzprojects/EntityFramework-Extensions#349]
**Description**
InsertIfNotExists it is not working for ORA 18C. A temp table is created for being able to detect if records should be inserted only 
if not exists but the temp table declaration is missing the data type for some fields.

**Exception**
2020-07-21 09: 25: 31.918 -03: 00 [INF] BulkInsert -> - Failed with error: ORA-02263: You must specify the data type for this column

**Fiddle or Project (Optional)**
This code fails
`smartTollDb.BulkInsert(transitsToInsert,
                                            options =>
                                            {
                                                options.InsertIfNotExists = true;
                                                options.AutoMapOutputDirection = false;
                                                options.Log = l => logger.LogInformation("BulkInsert->" + l);
                                            });`

As you can see in the LOG the TEMP table is defined but many fields lacks the type definition. 
@JonathanMagnan I can send you the source code via email as before for the Model and the Mapping using fluent API.

**Error log**
SELECT * FROM "ETRX"."TRANSITS_FOR_VALIDATION" WHERE 1 = 0
-- CommandTimeout:0
-- Executing at 21/7/2020 09:25:31

2020-07-21 09:25:31.124 -03:00 [INF] BulkInsert->-- Completed at 21/7/2020 09:25:31
-- Result: SqlDataReader
2020-07-21 09:25:31.749 -03:00 [INF] BulkInsert->-- Executing Command:

create private temporary table ORA$PTT_ZA3CD98C4590A4853AB656B83764768EA (
"CPY_CODE" VARCHAR2(2),
"NODE_TYPE" ,
"NODE_CODE" VARCHAR2(15),
"LOCATOR" ,
"AVC_CLASS" ,
"AVC_DATA" VARCHAR2(70),
"DATE_TIME_CREATED" TIMESTAMP(6),
"FARE_TYPE" ,
"FARE_VERSION" ,
"INITIAL_FARE_AMOUNT" NUMBER(19,2),
"INITIAL_ISO_CODE" VARCHAR2(3),
"INITIAL_ITEM_ID" VARCHAR2(50),
"INITIAL_MOMENT" TIMESTAMP(6),
"INITIAL_PLATE" VARCHAR2(70),
"INITIAL_TAG_NUMBER" VARCHAR2(50),
"INITIAL_TITLE_TYPE" VARCHAR2(4),
"INITIAL_TITLE_USE" VARCHAR2(2),
"LAST_TRANSIT_HISTORY_ID" NUMBER(19,0),
"MESSAGE_VERSION" ,
"MVC_DATA" VARCHAR2(70),
"N_NODE_CODE" VARCHAR2(15),
"N_NODE_TYPE" ,
"OPERATOR_ID" ,
"PERIOD" ,
"REAL_PASS" ,
"SHIFT_ID" ,
"SHIFT_MOMENT" DATE,
"SHIFT_NODE_CODE" VARCHAR2(15),
"SHIFT_NODE_TYPE" ,
"SIMULATION" ,
"SPLIT" ,
"TAB_CLASS" ,
"TRANS_NUMBER" ,
"VALIDATED" ,
"VH_PLATE" VARCHAR2(70),
"VIOLATION" 
)
ON COMMIT PRESERVE DEFINITION
-- CommandTimeout:0
-- Executing at 21/7/2020 09:25:31

**Further technical details**
EF version: EntityFramework Version="6.3.0" & Microsoft.EntityFrameworkCore Version="2.2.6"
EFCore version: Z.EntityFramework.Plus.EFCore Version="2.0.50"
EF Extensions Core version: Z.EntityFramework.Plus.EFCore Version="2.7.75"
Database Provider: Oracle.EntityFrameworkCore Version="2.19.70"
Oracle: 18c XE

**Comment by JonathanMagnan** [comment]
Hello @arielunanueAtKTC ,

Could you try the latest version? A few weeks ago we fixed a similar issue.

If you still have it, could you provide your table creation script? So we will know which field is missing. You can send it in private here if you wish: info@zzzprojects.com

I'm not sure what this change has happened but it looks that some column is returned differently than before when we check for the column type which leads to this error.

Best Regards,

Jon

**Comment by arielunanueAtKTC** [comment]
Hi Jon, I confirm that with the latest version the problem is gone. Good work

- Z.EntityFramework.Extensions.EFCore" Version="2.7.84
- Z.EntityFramework.Plus.EFCore" Version="2.0.55"

Ariel
