### ISSUE TITLE
How to let Entityframework-Extensions log out sql statement executed

### ISSUE THREAD

**Issue by alexander9999** [zzzprojects/EntityFramework-Extensions#35]
@JonathanMagnan ,

i use the Bulk delete method, and that functions good, is it possible that the generated SQL Statement for the bulk Operation is Outputted. i have tried to use following code:
`MyContext.Database.Log = Console.Write;`
but i could see nothing.

thanks

**Comment by JonathanMagnan** [comment]
Hello @alexander9999 ,

Our library has his own logger. You can find an example here: http://entityframework-extensions.net/log

```csharp
StringBuilder logger = new StringBuilder();
using (var ctx = new EntitiesContext())
{
    ctx.BulkSaveChanges(operation =>
    {
        operation.Log += s => logger.AppendLine(s);
    });
}
```

Let me know if that helped you or you need more information.

Best Regards,

Jonathan

**Comment by alexander9999** [comment]
Hello @JonathanMagnan ,

sorry, late to reply. 
one another question to entityframework.plus, has it also the same or similar usage?

thanks,

**Comment by JonathanMagnan** [comment]
Hello @alexander9999 ,

No, Entity Framework Plus has no logger features but that might may a good idea to add in the future.

I added this request to our list.

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment]
Hello @alexander9999 ,

I will close this request since I believe I have answered your question and the asking features are about EF+.

Feel free to re-open it if something is missing.

Best Regards,

Jonathan
