### ISSUE TITLE
BulkDelete throw Cannot access a disposed object. Object name: 'MainDbContext'.

### ISSUE THREAD

**Issue by thononv** [zzzprojects/EntityFramework-Extensions#350]
Hello, 
I’m currently having an issue using BulkDelete when running multiple job in scoped context.
The error received is : 
   at Microsoft.EntityFrameworkCore.DbContext.CheckDisposed()
   at Microsoft.EntityFrameworkCore.DbContext.get_Database()
   at .[](BulkOperation`1 this, DbContext , IEntityType , IEnumerable`1 )
   at .[](BulkOperation`1 this, DbContext , IEntityType , IEnumerable`1 , BulkOperationActionType )
   at .BulkDelete[T](DbContext this, IEntityType entityType, IEnumerable`1 list, Action`1 options, Boolean forceSpecificTypeMapping)
   at DbContextExtensions.BulkDelete[T](DbContext this, IEnumerable`1 entities)
   at Be.Corilus.Pharmacy.Tarification.DataAccess.UnitOfWork.BulkDelete[T](IEnumerable`1 entities) in C:\git\Tarification 2.0\DataAccess\UnitOfWork.cs:line 362
   at Be.Corilus.Pharmacy.Tarification.BusinessLogic.JobRecordingsHandler.CleanUp(DateTime referenceDate) in C:\git\Tarification 2.0\BusinessLogic\JobRecordingsHandler.cs:line 94
   at Be.Corilus.Pharmacy.Tarification.BusinessLogic.Facades.JobFacade.CleanUpRecordings() in C:\git\Tarification 2.0\BusinessLogic.Facades\JobFacade.cs:line 107
   at Be.Corilus.Pharmacy.Tarification.Scheduler.Jobs.CleanLogsJob.<Execute>z__OriginalMethod(IJobExecutionContext context) in C:\git\Tarification 2.0\Scheduler.Jobs\CleanLogsJob.cs:line 48
   at Be.Corilus.Pharmacy.Tarification.Scheduler.Jobs.CleanLogsJob.<Execute>z__TargetMethod(IJobExecutionContext context)
   at Be.Corilus.Pharmacy.Tarification.Scheduler.Jobs.CleanLogsJob.Execute(IJobExecutionContext context)

Cannot access a disposed object. A common cause of this error is disposing a context that was resolved from dependency injection and then later trying to use the same context instance elsewhere in your application. This may occur if you are calling Dispose() on the context, or wrapping the context in a using statement. If you are using dependency injection, you should let the dependency injection container take care of disposing context instances.
Object name: 'MainDbContext'.

It only occurs when running multiple IJob .
Other jobs (not using Bulk operation) run well.

Here is the simplified code : 

```csharp
public class Startup
    {
        public Startup(IConfiguration configuration)
            => this.Configuration = configuration;

        public void ConfigureServices(IServiceCollection services)
        {
            services.AddDbContext<MainDbContext>()
                .AddTransient<IUnitOfWork, UnitOfWork>();

            services.UseBusinessLogic(new List<string> { "BusinessLogic", "BusinessLogic.Facades" })
                    .UseSwagger()
                    .UseAutoMapper(new List<string> { "Scheduler.Core", "BusinessLogic" })
                    .UseMvc()
                    .UseQuartzHostedService()
                    .UseJobs(new CrontabProvider(services))
                    .UseOptions(this.Configuration)
                    .UseCors();
        }

public static IServiceCollection UseQuartzHostedService(this IServiceCollection services)
        {
            services.AddSingleton<IJobFactory, QuartzScopedJobFactory>();
            services.AddSingleton<ISchedulerFactory, StdSchedulerFactory>();
 
            services.AddHostedService<QuartzHostedService>();
 
            return services;
        }


public class QuartzScopedJob : IJob, IDisposable
   { 
       public QuartzScopedJob(IServiceScope scope, IJob quartzJob)
       {
           this.scope = scope ?? throw new ArgumentNullException(nameof(scope));
           this.quartzJob = quartzJob ?? throw new ArgumentNullException(nameof(quartzJob));
       }
 
       public Task Execute(IJobExecutionContext context)
           => this.quartzJob.Execute(context);


public class QuartzScopedJob : IJob, IDisposable
   {
       public QuartzScopedJob(IServiceScope scope, IJob quartzJob)
       {
           this.scope = scope ?? throw new ArgumentNullException(nameof(scope));
           this.quartzJob = quartzJob ?? throw new ArgumentNullException(nameof(quartzJob));
       }
 
       public Task Execute(IJobExecutionContext context)
           => this.quartzJob.Execute(context);


[DisallowConcurrentExecution]
   public class CleanLogsJob : IJob
   {
       public CleanLogsJob(IJobFacade jobFacade)
           => this.jobFacade = jobFacade;
 
       [JobRecorder]
       public Task Execute(IJobExecutionContext context)
       { 
           this.jobFacade.CleanUpRecordings();
 
           return Task.CompletedTask;
       }
   }

        public JobFacade(IUnitOfWork uow, IJobHandler jobHandler, IJobRecordingsHandler jobRecordingsHandler, IOptions<JobSettings> jobOptions)
            : base(uow)
        {
            this.jobRecordingsHandler = jobRecordingsHandler;
        }
 
        public int CleanUpRecordings()
            => this.jobRecordingsHandler.CleanUp(new DateTimeProvider().Now().AddDays);
    }


public class JobRecordingsHandler : Handler, IJobRecordingsHandler, IAutomaticDependencyInjectorMarker
    {
        public JobRecordingsHandler(IUnitOfWork uow, IAutoMapperAdapter mapper)
            : base(uow, mapper)
        {
        }
        
        public void CleanUp(DateTime referenceDate)
        {
            IEnumerable<JobRecordingsEntity> recordings = this.Uow.Read<JobRecordingsEntity>().Where(e => e.CreatedAt <= referenceDate);
 
            this.Uow.BulkDelete(recordings.ToList());
        }
    }

public class MainDbContext : DbContext
    {
        public MainDbContext()
        {
        }

        public MainDbContext(DbContextOptions<MainDbContext> options, IConfiguration configuration)
            : base(options)
                => this.configuration = configuration;
        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.LoadEntityConfigurations();
            modelBuilder.ConfigureShadowEntities();
            modelBuilder.ApplyEntityConfigurations();

            base.OnModelCreating(modelBuilder);

            DataSeederHelper.Seed(modelBuilder);
        }


public class UnitOfWork : IUnitOfWork
   {
       /// <summary>
       /// Initializes a new instance of the <see cref="UnitOfWork"/> class.
       /// </summary>
       /// <param name="context">The context.</param>
       public UnitOfWork(MainDbContext context)
       {
           this.Context = context;
 
           EntityFrameworkManager.ContextFactory = ctx => context;
       }
       
       public void BulkDelete<T>(IEnumerable<T> entities)
           where T : class
       {
           this.Context.BulkDelete(entities);
       }
}
```

Then solution I found is setting the contextFactory  with the option, but as the context is set at the instantiation of the class ,I do not understand why I have to force this option.

 this.Context.BulkDelete(entities, o => o.ContextFactory = ctx => this.Context);

What do I do wrong ? Do you have an explanation ?

**Comment by JonathanMagnan** [comment]
Hello @thononv ,

The `EntityFrameworkManager.ContextFactory` is a global property. The property is expecting to receive a new context, not the one you are currently using since the library try to use some internal code from Entity Framework and we do not affect your current context (ContextFactory will not be longer required soon for EF Core 5 and perhaps for EF Core 3 as well)

So in a concurrency scenario:

```csharp
EntityFrameworkManager.ContextFactory = ctx => context;
```

This line gets overridden every time a new UnitOfWork is created. So if `thread B` is the latest to set this property and is completed and `thread A` use this property, it will lead exactly to this issue since the context from `thread B` is disposed of.

So the `ContextFactory` needs to be set only once. For example, in your `ConfigureServices` method or any other place that will be called only once.

Let me know if that explains correctly why this issue happen and how to solve it.

Best Regards,

Jon

**Comment by JonathanMagnan** [comment]
Hello @thononv ,

Since our last conversation, I haven't heard from you. 

feel free to contact us for further assistance. 

Best regards, 

Jon

**Comment by thononv** [comment]
Hello,
I juste finished correcting my code,
It works not with correct implementation.
Thank you for your help !
Regards
Virginie Thonon

De : Jonathan Magnan <notifications@github.com>
Envoyé : vendredi 24 juillet 2020 14:57
À : zzzprojects/EntityFramework-Extensions <EntityFramework-Extensions@noreply.github.com>
Cc : Virginie Thonon <virginie.thonon@corilus.be>; Mention <mention@noreply.github.com>
Objet : Newsletter/marketing: Re: [zzzprojects/EntityFramework-Extensions] BulkDelete throw Cannot access a disposed object. Object name: 'MainDbContext'. (#350)

CAUTION: This email originated from outside of the organization. Do not click links or open attachments unless you recognize the sender and know the content is safe.


Hello @thononv<https://github.com/thononv> ,

Since our last conversation, I haven't heard from you.

feel free to contact us for further assistance.

Best regards,

Jon

**Comment by JonathanMagnan** [comment]
Awesome @thononv !

We are glad everything is working out for you!

Don't hesitate to contact us for questions, issues or feedback!

Have a great weekend, 

Jon
