### ISSUE TITLE
UpdateFromQueryAsync with anonymous object does not work when the entity being updated has private constructor

### ISSUE THREAD

**Issue by luciniga** [zzzprojects/EntityFramework-Extensions#351]
### Description
```
public Entity 
{
   private Entity() { }

   public string Name { get; private set; }
}

async Task MyMethod(CancellationToken cancellationToken) 
{
  var dbContext = new DbContext();
  await dbContext.entities.UpdateFromQueryAsync(e => new { Name = "test" }, cancellationToken);
}
```
### Exception
```
System.ArgumentNullException: Value cannot be null. (Parameter 'constructor')
at System.Linq.Expressions.Expression.New(ConstructorInfo constructor, IEnumerable`1 arguments)
at BatchUpdateExtensions.UpdateFromQuery[T](IQueryable`1 query, Expression`1 updateExpression, Action`1 batchUpdateBuilde)
at BatchUpdateExtensions.UpdateFromQuery[T](IQueryable`1 query, Expression`1 updateExpression)
at BatchUpdateExtensions.`1.()
```

### Further technical details
- EF version: 3.1.3
- EF Extensions version: 3.0.79
- Database Provider: SqlServer

**Comment by JonathanMagnan** [comment]
Hello @luciniga ,

Thank you for reporting, we will look at it.

Best Regards,

Jon

**Comment by JonathanMagnan** [comment]
Hello @luciniga ,

The v3.0.87 has been released.

Private constructor should now be supported.

Let me know if everything is working,

Best Regards,

Jon

**Comment by luciniga** [comment]
@JonathanMagnan I've tested with v3.0.88 and it works like a charm. Thank you for the fix!

**Comment by JonathanMagnan** [comment]
Awesome @luciniga ,

we are glad to hear that everything is working out for you!

don't hesitate to contact us for any questions, issues or feedback.

Have a good day, 

Jon
