### ISSUE TITLE
More control over update

### ISSUE THREAD

**Issue by atkulp** [zzzprojects/EntityFramework-Extensions#354]
I'm trying to use the bulk merge feature, but running into a limitation due to an update that requires an expression for one column.  The requirement is to update a date stamp when a given field is true, and clear it when it's not.  Unfortunately, the data is coming from a CSV import, so I don't have the date as it is on the entity, and don't want to overwrite if it's already set.  At first glance, it sounds like a simple coalesce, except that fails to clear the destination value on false.

Details:

From CSV: ID, Active flag
If any row has flag == true, I stamp the current date in the entity that I create.

Upon update, if the ID already exists, it might already be active, and date would then be in the past.  In that case, I wouldn't want to replace the past date with the current one.  Here's what I need:

CSV › Copied to entities › Passed to BulkMerge
I would like the MERGE to update like this:

Destination.ActiveDate = IIF( Staging.IsActive = 0, NULL, ISNULL ( Destination. ActiveDate, Staging.ActiveDate))

As far as I can tell, I can't specify something like this in the current config. Would it be possible to specify an exact update expression for a given field?

Thanks for your help!

**Comment by JonathanMagnan** [comment]
Hello @atkulp ,

I might have missed something on your question but I believe the following Fiddle has everything you need to get you started to complete it: https://dotnetfiddle.net/sRAC9R

```csharp
context.BulkMerge(list, options => {
	options.PostConfiguration = config => {
		var activeDateColumn = config.ColumnMappings.Single(x => x.SourceName == "ActiveDate");
		// Destination.ActiveDate = IIF( Staging.IsActive = 0, NULL, ISNULL ( Destination. ActiveDate, Staging.ActiveDate))
		activeDateColumn.FormulaUpdate = "CASE WHEN StagingTable.IsActive = 0 THEN NULL ELSE ISNULL(DestinationTable.ActiveDate, StagingTable.ActiveDate) END";
	};
});
```

If you need more help, let me know.

Best Regards,

Jon

**Comment by atkulp** [comment]
That is exactly what I needed!  I didn't understand that feature from the docs. Thank you so much for the clear example!

**Comment by JonathanMagnan** [comment]
Hello @atkulp 

Glad we could help ;)

Don't hesitate to contact us for any questions, issues or feedback!

Best regards,

Jon
