### ISSUE TITLE
Multiple BulkOperationExecuted listeners

### ISSUE THREAD

**Issue by JesseKlaasse** [zzzprojects/EntityFramework-Extensions#356]
### Description
I have a project in which I would like to do some global stuff in the BulkOperationExecuted listener. Like this:

```csharp
EntityFrameworkManager.BulkOperationBuilder = operation =>
{
    operation.UseAudit = true;
    operation.BulkOperationExecuted = bulkOperation =>
    {
        // some global logic
    };
};
```

Apart from that, I have some specific bulk calls where I would like do so some things _in addition to_ the global stuff, like this:

```csharp
await context.BulkMergeAsync(entities, operation =>
{
    operation.UseAudit = true;
    operation.BulkOperationExecuted = bulkOperation =>
    {
        // I would like the global logic to be executed here, but it isn't.
        // some specific logic here...
    };
    
}, cancellationToken);
```

At the moment, this seems to be impossible, except by doing something like this:

```csharp
await context.BulkMergeAsync(entities, operation =>
{
    operation.UseAudit = true;
    
    var oldBulkOperationExecuted = operation.BulkOperationExecuted;
    operation.BulkOperationExecuted = bulkOperation =>
    {
        oldBulkOperationExecuted.Invoke(operation);

        // some specific logic here...
    };
    
}, cancellationToken);
```

However, this isn't an elegant solution, since it requires an adaptation of all specific Bulk-calls, and it would be error-prone for future Bulk-calls.

I would like to see an option to attach more than one listener to the BulkOperationExecuted event (and of course for all other events). Or maybe there is another way to achieve this?

**Comment by JonathanMagnan** [comment]
Hello @JesseKlaasse ,

I believe you are looking for the `+=` operator. Instead of overriding the current event, you will append it to existing events:

```csharp
await context.BulkMergeAsync(entities, operation =>
{
    operation.UseAudit = true;
    operation.BulkOperationExecuted += bulkOperation =>
    {
        // I would like the global logic to be executed here, but it isn't.
        // some specific logic here...
    };
    
}, cancellationToken);
```

(See this part: `operation.BulkOperationExecuted += bulkOperation`)

Let me know if that answers correctly to your question.

Best Regards,

Jon

**Comment by JesseKlaasse** [comment]
Wow, I didn't even realize that this was possible! Thanks.
