### ISSUE TITLE
Bulk insert is not working with 500k of 4 list

### ISSUE THREAD

**Issue by arpitaw** [zzzprojects/EntityFramework-Extensions#362]
I am trying to insert 500k records with Bulkinsert extension. Basically i am 4 list using 4 bulkinsert. but it is only inserting one for this amount of data.
I am not able to find the root cause of it

context.bulkinsert(list1);
**context.bulkinsert(list2);**
context.bulkinsert(list3);
context.bulkinsert(list4);

**Comment by JonathanMagnan** [comment]
Hello @arpitaw ,

Are you able to provide more information? What's the error? A runnable project?

With the current information, there is nothing we can really do.

If you need to send something in private, you can send it here: info@zzzprojects.com

Best Regards,

Jon

**Comment by arpitaw** [comment]
Sure.I have sent you the code snippet.
