### ISSUE TITLE
Oracle: SchemaName missing in generated SQL Command

### ISSUE THREAD

**Issue by alexanderwieland** [zzzprojects/EntityFramework-Extensions#372]
### Description
We're currently trying your software, but we have encountered a problem.
When I do some inserts and save the DbContext with BulkSaveChanges(), I get the following exception:

### Exception
```
Exception message:
System.Exception: An error occurred while updating the entries. See the inner exception for details.
System.Exception: An error occured while retrieving the InformationSchemaTable information. See the inner exception for details.
Oracle.ManagedDataAccess.Client.OracleException: ORA-01741: Unzulässige ID mit Länge Null (invalid id with length null)
Stack trace:
bei OracleInternal.ServiceObjects.OracleConnectionImpl.VerifyExecution(Int32& cursorId, Boolean bThrowArrayBindRelatedErrors, SqlStatementType sqlStatementType, Int32 arrayBindCount, OracleException& exceptionForArrayBindDML, Boolean& hasMoreRowsInDB, Boolean bFirstIterationDone)
   bei OracleInternal.ServiceObjects.OracleCommandImpl.ExecuteReader(String commandText, OracleParameterCollection paramColl, CommandType commandType, OracleConnectionImpl connectionImpl, OracleDataReaderImpl& rdrImpl, Int32 longFetchSize, Int64 clientInitialLOBFS, OracleDependencyImpl orclDependencyImpl, Int64[] scnForExecution, Int64[]& scnFromExecution, OracleParameterCollection& bindByPositionParamColl, Boolean& bBindParamPresent, Int64& internalInitialLOBFS, OracleException& exceptionForArrayBindDML, OracleConnection connection, OracleLogicalTransaction& oracleLogicalTransaction, IEnumerable`1 adrianParsedStmt, Boolean isDescribeOnly, Boolean isFromEF)
   bei Oracle.ManagedDataAccess.Client.OracleCommand.ExecuteReader(Boolean requery, Boolean fillRequest, CommandBehavior behavior)
   bei Oracle.ManagedDataAccess.Client.OracleCommand.ExecuteDbDataReader(CommandBehavior behavior)
   bei System.Data.Common.DbCommand.ExecuteReader(CommandBehavior behavior)
   bei ?.?(DbCommand ?, CommandBehavior ?, BulkOperation ?, Int32 ?)
   bei ?.?(? ?, String[] ?)
   bei ?.?(Boolean ?, String[] ?)
   bei ?.?()
   bei Z.BulkOperations.BulkOperation.?()
   --- Ende der internen Ausnahmestapelüberwachung ---
   bei Z.BulkOperations.BulkOperation.?()
   bei Z.BulkOperations.BulkOperation.Execute()
   bei Z.BulkOperations.BulkOperation.BulkInsert()
   bei ?.?(List`1 ?, Object ?, Dictionary`2 ?)
   bei ?.Execute()
   --- Ende der internen Ausnahmestapelüberwachung ---
   bei ?.Execute()
   bei DbContextExtensions.?(DbContext this, Boolean ?, Action`1 ?, Boolean ?)
   bei DbContextExtensions.BulkSaveChanges(DbContext this, Action`1 bulkOperationFactory)
```

On SqlServer everything works fine.

I enabled some logging via Context.Database.Log => seems like the schemaname is not found:
`Executing Command: SELECT * FROM ""."TableName" WHERE 1 = 0`
I somehow can't figure out why it isn't set.
When I use the default EF SaveChanges, it works. And it doesn't even try to add a schema name:
`Executing Command: SELECT * FROM "TableName" WHERE 1 = 0`
I tried to intercept the command (`IDbCommandInterceptor`) and change the commandtext, but somehow the `IDbCommandInterceptor` methods are not called.
I also tried setting the default schema with `modelBuilder.HasDefaultSchema("Schemaname");` but somehow the `OnModelCreating` is never called. Would that be the correct way?
I'm out of ideas... any recommendations?

### Further technical details
- EF version: 6.4.x (A fork)
- EF Extensions version: 4.0.105
- Database Provider: Oracle.ManagedDataAccess.Client
- Oracle.ManagedDataAccess.EntityFramework version: 19.7.0

**Comment by JonathanMagnan** [comment]
Hello @alexanderwieland ,

Do you think you could send us a private runnable project here info@zzzprojects.com with the issue?

We cannot currently reproduce it and since you use a fork and we might miss an important configuration that you do, having a runnable project will make it way easier to find out what is happening.

Best Regards,

Jon

**Comment by alexanderwieland** [comment]
Hi @JonathanMagnan ,

I sent you an email :)

**Comment by alexanderwieland** [comment]
Maybe there is an option not to use the schema name at all? We are always logged on to the correct schema by default.

**Comment by mp2apw** [comment]
Any news?

**Comment by JonathanMagnan** [comment]
Hello @alexanderwieland , @mp2apw ,

The version 5.1 has been released (https://github.com/zzzprojects/EntityFramework-Extensions/releases/tag/5.1.0)

_(Nothing major from the v4.0.105, we just upgraded the major version to match EF Core 5)_

Could you try it and let us know if everything is fixed?

Best Regards,

Jon

**Comment by alexanderwieland** [comment]
It seems like the bug is fixed, thank you. 

The normal inserts are insanely fast, as expected :) 

However, BulkInserts with NCLOBs (size ~100 bytes) still seem to be slow (~1000 objects, only ~10% faster compared to the normal SaveChanges) 
Are there options / tips to further improve the performance there?

**Comment by JonathanMagnan** [comment]
Hello @alexanderwieland ,

We are currently improving some internal code that currently slows down the bulk operations (should be available later this month).

However, Oracle is slower when the table has types such as NCLOB and there is nothing we can do about that. One problem is `ORACLE` needs first to store data on the disk before performing the statement, so the `USER_IO_WAIT_TIME` is way longer and we never found any solution for that.

Best Regards,

Jon

**Comment by alexanderwieland** [comment]
Hi, thanks for the infos.
