### ISSUE TITLE
InMemory Provider throws ArgumentOutOfRangeException on BulkInsert

### ISSUE THREAD

**Issue by meinsiedler** [zzzprojects/EntityFramework-Extensions#378]
### Description
When using the InMemory database provider, the `BulkInsert()` method throws an `ArgumentOutOfRangeException`.
This issue is reproducible with the instructions provided here: https://entityframework-extensions.net/efcore-inmemory-provider

### Exception

```
Unhandled exception. System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')
   at Z.EntityFramework.Extensions.EntityTypeZInfo..ctor(IEntityType entityType)
   at PublicExtensions..(IEntityType )
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at PublicExtensions.ToZInfo(IEntityType entityType)
   at .BulkInsert[T](DbContext this, IEnumerable`1 entities, Action`1 options, Boolean isBulkSaveChanges)
   at DbContextExtensions.BulkInsert[T](DbContext this, IEnumerable`1 entities, Action`1 options)
   at EfExtensionsTest.Program.Main(String[] args)
```

### Fiddle or Project (Optional)

I've added the code from https://entityframework-extensions.net/efcore-inmemory-provider in this Fiddle: https://dotnetfiddle.net/Dtyg8C

### Further technical details
- EF version: `Microsoft.EntityFrameworkCore.InMemory`: 5.0.0
- EF Extensions version: 5.1.4
- Database Provider: In-Memory

**Comment by kdvtrifork** [comment]
I have same problem with `BulkMergeAsync` and `BulkDeleteAsync`

**Comment by JonathanMagnan** [comment]
Hello @meinsiedler ,  @kdvtrifork ,

Thank you for reporting, we will look at it.

Best Regards,

Jon

**Comment by JonathanMagnan** [comment]
Hello @meinsiedler , @kdvtrifork ,

The v5.1.5 has been released.

It should now correctly work with `InMemory`. However, we still don't support `IncludeGraph` with `InMemory`.

Let me know if, for the rest, everything is working as expected.

Best Regards,

Jon

**Comment by meinsiedler** [comment]
Hello @JonathanMagnan,

the `BulkInsert` is now working as expected. Thanks!

**Comment by kdvtrifork** [comment]
That fixed that problem but i got a new

```
Message: 
    System.TypeInitializationException : The type initializer for '' threw an exception.
    ---- System.Reflection.AmbiguousMatchException : Ambiguous match found.
  Stack Trace: 
    .GetAllByPrimaryKeys( action, DbContext inMemoryContext, Type entityType, Object entity)
    .( , DbCommand )
    .( , DbCommand )
    .Execute(List`1 actions)
    .(List`1 )
    BulkOperation.Execute()
    .BulkDelete[T](DbContext this, IEntityType entityType, IEnumerable`1 list, Action`1 options, SavingSelector savingSelector, Boolean forceSpecificTypeMapping)
    .BulkDelete[T](DbContext this, IEnumerable`1 entities, Action`1 options, Boolean isBulkSaveChanges)
    DbContextExtensions.BulkDelete[T](DbContext this, IEnumerable`1 entities, Action`1 options)
    `1.()
    Task.InnerInvoke()
    <.cctor>b__277_0(Object obj)
    ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
    --- End of stack trace from previous location ---
    ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
    Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
    --- End of stack trace from previous location ---
    DbContextExtensions.BulkDeleteAsync[T](DbContext this, IEnumerable`1 entities, Action`1 options, CancellationToken cancellationToken)
    DeleteableGenericRepository`3.DeleteAsync(IEnumerable`1 entities, CancellationToken cancellationToken) line 23
    LogsRepositoryUnitTest.TestDeleteLogs() line 123
    --- End of stack trace from previous location ---
    ----- Inner Stack Trace -----
    RuntimeType.GetMethodImplCommon(String name, Int32 genericParameterCount, BindingFlags bindingAttr, Binder binder, CallingConventions callConv, Type[] types, ParameterModifier[] modifiers)
    RuntimeType.GetMethodImpl(String name, BindingFlags bindingAttr, Binder binder, CallingConventions callConv, Type[] types, ParameterModifier[] modifiers)
    Type.GetMethod(String name, BindingFlags bindingAttr)
    Type.GetMethod(String name)
    .cctor()
```
The unit test worked before with EF 3.1.

**Comment by JonathanMagnan** [comment]
Hello @kdvtrifork 

Are you using EF Core 3.x? If yes, you must use the major version of our library matching your EF Core version.

In this case, it would have been be: v3.1.5

**Comment by kdvtrifork** [comment]
Hi @JonathanMagnan, 

We use DotNet Core 5 and 5.0.0 packages too.

**Comment by JonathanMagnan** [comment]
Thank, I was not sure with your previous message.

I think we have found the issue. My developer will test it, if I'm right, the fix will be deployed later today.

**Comment by kdvtrifork** [comment]
That is awesome! 🚀

Sorry for not being clear!

**Comment by JonathanMagnan** [comment]
Hello @kdvtrifork ,

The v5,1,8 has been released.

Could you try it and let us know if everything is working as expected?

**Comment by kdvtrifork** [comment]
Hi @JonathanMagnan , 

Yes it looks like that it works now!

**Comment by JonathanMagnan** [comment]
Awesome @kdvtrifork !

We are glad to hear that everything is working out!

Don't hesitate to contact us with any questions, issues or feedback :)

Best regards,

Jon
