### ISSUE TITLE
BulkUpdate  Error

### ISSUE THREAD

**Issue by a985951420** [zzzprojects/EntityFramework-Extensions#382]
### Description
There is no column  LastModifiedByUserId   LastModifiedTime
dbTable column :  Id   Status   LastModifiedByUserId   LastModifiedTime
Why
### Exception
Exception: Missing Colum : Operator_LastModifiedByUserId
On entity : Package
On Table : [dbo].[Packages]
Exception message:
Stack trace:
```

### Fiddle or Project (Optional)
public class Package
    {
        public Package()
        {

        }

        public Package(long id)
        {
            Id = id;
        }
        public long Id { get; set; }
        public int Status { get; set; }

        public Operator Operator { get; protected set; }
        public static Package CreateReleaseInventory(long id, long userid)
        {
            var package = new Package(id);
            package.SetPackageCancelSectionOrder(userid);
            return package;
        }
        public void SetPackageCancelSectionOrder(long userId)
        {
            Status = 400;
            Operator = new Operator(userId);
        }
    }`
`    public class Operator
    {
        public Operator(long userid)
        {
            LastModifiedByUserId = userid;
            LastModifiedTime = DateTimeOffset.Now;
        }
        public long CreatedByUserId { get; set; }

        public DateTimeOffset CreatedTime { get; set; }

        public long? LastModifiedByUserId { get; set; }
        public DateTimeOffset? LastModifiedTime { get; set; }
    }

     using (var context = new TestContext())
            {
                var pack = Package.CreateReleaseInventory(791912420112187392, 110);
                var listpackage = new List<Package>()
                {
                    pack
                };
                context.BulkUpdate(listpackage, options => options.ColumnInputExpression = c => new
                {
                    c.Operator.LastModifiedByUserId,
                    c.Operator.LastModifiedTime,
                    c.Status,
                });
                context.SaveChanges();
            };

```

**Comment by JonathanMagnan** [comment]
Hello @a985951420 ,

Which version of Entity Framework are you using? (EF6, EF Core 3.x, EF Core 5.x)

In EF6, by default when using complex type, the property name `Operator` of your main entity is added as prefix to all complex type properties. I don't see any special configuration in your example, so perhaps we are missing something to reproduce it.

If you are able to create a standalone project that contains only this issue, you can attach it here or send it in private to info@zzzprojects.com

Best Regards,

Jon

**Comment by a985951420** [comment]
dear&nbsp;Jon
&nbsp; &nbsp; &nbsp; &nbsp;At present, I found errors in the project, and there was no error in rebuilding a new project.&nbsp;I don't know what went wrong and I can't simulate this situation!&nbsp;There will be errors in the original project, but there will be no errors in a new project.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "zzzprojects/EntityFramework-Extensions"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年12月29日(星期二) 晚上9:50
收件人:&nbsp;"zzzprojects/EntityFramework-Extensions"<EntityFramework-Extensions@noreply.github.com&gt;;
抄送:&nbsp;"985951420"<985951420@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [zzzprojects/EntityFramework-Extensions] BulkUpdate  Error (#382)





 
Hello @a985951420 ,
 
Which version of Entity Framework are you using? (EF6, EF Core 3.x, EF Core 5.x)
 
In EF6, by default when using complex type, the property name Operator of your main entity is added as prefix to all complex type properties. I don't see any special configuration in your example, so perhaps we are missing something to reproduce it.
 
If you are able to create a standalone project that contains only this issue, you can attach it here or send it in private to info@zzzprojects.com
 
Best Regards,
 
Jon

**Comment by JonathanMagnan** [comment]
No problem,

If you can reproduce it and provide us a project, just let us know and we will re-open this issue.

Best Regards,

Jon
