### ISSUE TITLE
Setup License from appsettings.json

### ISSUE THREAD

**Issue by klinckag** [zzzprojects/EntityFramework-Extensions#384]
### Description
When we setup the license from the appsettings.json file, for development purposes we use the secrets.json file so that secrets like the license key are never checked in to source control.
In appsettings.json we do:
{
  "Z.EntityFramework.Extensions": {
    "LicenseName": "[licenseName]",
    "LicenseKey": "[licenseKey]"
  }
}
The actual vaules are entered in the secrets.json file
{
  "Z.EntityFramework.Extensions": {
    "LicenseName": "actualLicenseName",
    "LicenseKey": "actualLicenseKey"
  }
}

It seems like the call to Z.EntityFramework.Extensions.LicenseManager.ValidateLicense(out licenseErrorMessage) is picking up the values from the appsettings.json file directly because we get an error: 
The type initializer for 'Z.BulkOperations.LicenseManager' threw an exception. ---> System.Exception: The License name cannot be the placeholder '[licenseName].

_When deploy to azure we want to get the actual values from KeyVault_

**Comment by JonathanMagnan** [comment]
Hello @klinckag ,

Unfortunately, I believe there is nothing we can do on our side about it since the only file we try to read is the default `appsettings.json`. We are not aware of other files as those files can have pretty much any names.

What we suggest is that you keep the license information in your json file (with another name so our library doesn't try to read it) but manually add it in your project before the first use of our library:

```csharp
Z.EntityFramework.Extensions.LicenseManager.AddLicense([licenseNameFromJsonFile], [licenseKeyFromJsonFile]);
```

https://entityframework-extensions.net/licensing

So license information will keep being hidden in the `secrets.json` file but since you manually add it, the right value will now be added.

Let me know if that answer correctly to your issue.

Best Regards,

Jon

**Comment by klinckag** [comment]
We now add the license manually which works fine.

But I think you should be using the classes/interfaces in the Microsoft.Extensions.Configuration ( like IConfigurationRoot ) instead of reading/parsing the appsettings.json file directly.
IConfigurationRoot fi can be used to read configuration values config["Z.EntityFramework.Extensions:LicenseKey"] no matter where the actual values come from ( appsettings.json, azure keyVault, .... ) because during configuration all those possible configuration sources are merged together.

**Comment by JonathanMagnan** [comment]
Thank you for your feedback,

We will look if there is a reason why we didn't take it.

It has been a lot of years since we coded this solution so perhaps it's time we move to `Microsoft.Extensions.Configuration` as you recommended.

**Comment by JonathanMagnan** [comment]
Hello @klinckag ,

We checked your alternative solution and finally choose to don't doing it for now.

The major problem is about having a solution which works for all our libraries. One of the biggest probably is that we are not able to choose which version all our projects should reference! Should it be the latest? but in this case, some older projects will need to update their reference which is unlikely what they want to do. We cannot either choose a different version depending on the project such as EFE Core and C# Eval as both work well together. Reference a very old version seem weird for people who use EF Core 5.

While that will be without a doubt the best solution for a situation like yours, we are just too much undecided about how it should work. In that case, we simply choose of doing nothing for now which is the easiest solution.
