### ISSUE TITLE
Z.BulkOperations.DbBulkOperationConcurrencyException: A concurrency exception has occured. Entities may have been modified or deleted since entities were loaded  

### ISSUE THREAD

**Issue by tersonly** [zzzprojects/EntityFramework-Extensions#385]
How do I troubleshoot the problem？ Thank you

**Comment by JonathanMagnan** [comment]
Hello @tersonly ,

You can have the list of entries of the current batch this way:

```csharp
var entries = concurrencyException.Entries.ToList();
```

In EF6, you can disable the concurrency column this way:

```csharp
ctx.BulkUpdate(list, options => options.AllowConcurrency = false);
```

You can also find a small article here about how you can handle it: https://entityframework-extensions.net/concurrency#solution-bulkupdate

Let me know if that successfully answer your question.

Best Regards,

Jon

**Comment by tersonly** [comment]
Thank you very much  ! it solve  my  problem

**Comment by JonathanMagnan** [comment]
Awesome @tersonly 

Don't hesitate to contact us with any questions or further assistance!

Best regards,

Jon
