### ISSUE TITLE
Bulk Insert creates NULL discriminator in Mixed TPC/TPCH hierarchy

### ISSUE THREAD

**Issue by jehhynes** [zzzprojects/EntityFramework-Extensions#386]
### Description
Take the following class hierarchy:

```csharp
abstract class BaseFoo

class SomeFooSubType : BaseFoo

class AnotherFooSubType : BaseFoo

[Table("AnotherTable")]
class SeparateTableFooSubType : BaseFoo
```

In this hierarchy, there would be 2 tables, [BaseFoo] and [AnotherTable]. The [BaseFoo] Table would have a Discriminator column. When EF saves records via SaveChanges(), it saves the class name into the Discriminator column of the [BaseFoo] table.

However, in this scenario, BulkInsert() does not save the class name into the Discriminator column.

### Fiddle or Project (Optional)
https://dotnetfiddle.net/E9S79y

### Further technical details
- EF version: Latest
- EF Extensions version: Latest
- Database Provider: SQL Server

**Comment by JonathanMagnan** [comment]
Hello @jehhynes ,

Unfortunately, we do not support mixed inheritance. Is either `TPC`, `TPH`, or `TPT` inheritance but mixing two together is usually asking for problems.

Honestly, I'm even surprised that Entity Framework works well with a mixed inheritance.

I do not think anything will be done here since trying to support it will be too hard and will change way too much code in our library.

Best Regards,

Jon

**Comment by jehhynes** [comment]
We used EF to map to a pre-existing database, and the "mixed" inheritance strategy was the best fit for certain pre-existing tables. I was also surprised by how well EF was able to adapt to this "mixed" TPC/TPH mode. Actually, the EF designer does have a "mixed" mode (https://huagati.blogspot.com/2010/10/mixing-inheritance-strategies-in-entity.html) so I guess it is well supported.

Do you have a workaround for this? For instance, can I supply additional columns to be included in the insert statement, and manually specify the discriminator value?

**Comment by JonathanMagnan** [comment]
Thank @jehhynes ,

My developer told me that he finally will try to look at it. If the issue is only the discriminator column, perhaps there is something we can do.

So perhaps the change will be less big than we thought to support this.

**Comment by JonathanMagnan** [comment]
Hello @jehhynes ,

My developer tried your scenario but didn't succeed to reproduce it. Even the code in the Fiddle doesn't work either directly with `SaveChanges`.

Do you think you could share a small runnable project with the minimum code that reproduces the issue (and work with SaveChanges). We want to make sure we will work on exactly the same scenario as you to try to support it. You can send your project in private here: info@zzzprojects.com

**Comment by jehhynes** [comment]
Jonathan,

Thanks so much for looking into this. I've updated the Fiddle to test the same scenario using SaveChanges(), and you are right it also appears to be inserting "(Undefined)" in the discriminator.

I will let you know if I can reproduce it, but in the meantime this ticket can be closed. Looks like perhaps EF doesn't support the mixed inheritance mode the way I thought it did.
