### ISSUE TITLE
 ISaveChangesInterceptor execution for BulkSaveChanges

### ISSUE THREAD

**Issue by alexb5dh** [zzzprojects/EntityFramework-Extensions#391]
Would it be possible to execute registered [ISaveChangesInterceptor](https://docs.microsoft.com/en-us/ef/core/logging-events-diagnostics/interceptors#savechanges-interception)'s for Bulk methods or `BulkSaveChanges` at least?

In my case this is needed for:
- updating entity `CreatedAt`, `UpdatedAt` dates
- preventing any database modification operations in some situations

**Comment by JonathanMagnan** [comment]
Hello @alexb5dh ,

We will look at it.

I don't think it will be implemented on methods such as `BulkInsert` and `BulkMerge`

However, as you requested, we will check what is the difficulty of this feature for `BulkSaveChanges`.

Best Regards,

Jon

**Comment by JonathanMagnan** [comment]
Hello @alexb5dh ,

Unfortunately, we didn't succeed to implement this solution correctly. After reviewing your requirement, I don't think this would be very compatible with the way our library has been created.

Something you could do is create your own method, adding your logic and calling `BulkSaveChanges` or any method you want after such as:

```csharp
public class EntityContext : DbContext
{
	public EntityContext()
	{
	}

	public DbSet<EntitySimple> EntitySimples { get; set; }

	protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
	{
		optionsBuilder.UseSqlServer(new SqlConnection(My.ConnectionString));

		base.OnConfiguring(optionsBuilder);
	}

	public void CustomBulkSaveSaveChanges()
	{
		var entries = this.ChangeTracker.Entries<IAudit>().Where(x => x.State == EntityState.Added).ToList();
		
		foreach(var entry in entries)
		{
			entry.Entity.CreatedDate = DateTime.Now;
		}

		this.BulkSaveChanges();
	}
}
```

Is an alternative solution that could work for you?
