### ISSUE TITLE
Bulk.SaveChangesAsync does not use defined converter from UInt64 to byte[]

### ISSUE THREAD

**Issue by soniachikh** [zzzprojects/EntityFramework-Extensions#395]
We convert RowVersion from ulong to byte[] and we provide the converter with HasConversion.
We get this error : 

>  Failed with error: Failed to convert parameter value from a UInt64 to a Byte[].
> ystem.InvalidCastException: Invalid cast from 'System.UInt64' to 'System.Byte[]'.
>    at System.Convert.DefaultToType(IConvertible value, Type targetType, IFormatProvider provider)
>    at System.Data.SqlClient.SqlParameter.CoerceValue(Object value, MetaType destinationType, Boolean& coercedToDataFeed, Boolean& typeChanged, Boolean allowStreaming)
>    --- End of inner exception stack trace ---
>    at System.Data.SqlClient.SqlParameter.CoerceValue(Object value, MetaType destinationType, Boolean& coercedToDataFeed, Boolean& typeChanged, Boolean allowStreaming)
>    at System.Data.SqlClient.SqlParameter.GetCoercedValue()
>    at System.Data.SqlClient.SqlParameter.Validate(Int32 index, Boolean isCommandProc)
>    at System.Data.SqlClient.SqlCommand.BuildParamList(TdsParser parser, SqlParameterCollection parameters)
>    at System.Data.SqlClient.SqlCommand.BuildExecuteSql(CommandBehavior behavior, String commandText, SqlParameterCollection parameters, _SqlRPC& rpc)
>    at System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 timeout, Task& task, Boolean asyncWrite, SqlDataReader ds)
>    at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean asyncWrite, String method)
>    at System.Data.SqlClient.SqlCommand.ExecuteReader(CommandBehavior behavior)
>    at System.Data.SqlClient.SqlCommand.ExecuteDbDataReader(CommandBehavior behavior)
>    at System.Data.Common.DbCommand.System.Data.IDbCommand.ExecuteReader(CommandBehavior behavior)
>    at System.Data.Common.DbDataAdapter.FillInternal(DataSet dataset, DataTable[] datatables, Int32 startRecord, Int32 maxRecords, String srcTable, IDbCommand command, CommandBehavior behavior)
>    at System.Data.Common.DbDataAdapter.Fill(DataSet dataSet, Int32 startRecord, Int32 maxRecords, String srcTable, IDbCommand command, CommandBehavior behavior)
>    at System.Data.Common.DbDataAdapter.Fill(DataSet dataSet)
>    at .(DbCommand , BulkOperation , Int32 )
>    at .( , DbCommand )
>    at .Execute(List`1 actions)
>    at Z.BulkOperations.BulkOperation.Execute()
>    at .BulkUpdate[T](DbContext this, IEntityType entityType, IEnumerable`1 list, Action`1 options, Boolean forceSpecificTypeMapping)
>    at .BulkUpdate[T](DbContext this, IEnumerable`1 entities, Action`1 options, Boolean isBulkSaveChanges)
>    at .(DbContext this, List`1 , Action`1 )
>    at .(DbContext this, StateManager , IReadOnlyList`1 , Action`1 )
>    at .(DbContext this, StateManager , IReadOnlyList`1 , Action`1 )
>    at .(DbContext this, Action`1 , DbContext )

I enabled the logs when calling the SaveChanges and I get this : 

```
MERGE INTO [Batchs]  AS DestinationTable
USING
(
SELECT TOP 100 PERCENT * FROM (SELECT @0_0 AS [Id], @0_1 AS [AutodetectName], @0_2 AS [Autopublish], @0_3 AS [CreatedOn], @0_4 AS [DeletedBy], @0_5 AS [DeletedOn], @0_6 AS [FolderId], @0_7 AS [IsActive], @0_8 AS [IsDrawing], @0_9 AS [IsSplit], @0_10 AS [ModifiedOn], @0_11 AS [PartialUri], @0_12 AS [ProjectId], @0_13 AS [PublishState], @0_14 AS [RasterQuality], @0_15 AS [RemoveAfterDot], @0_16 AS [SkipHyperlinkingForDrawing], @0_17 AS [UploadedBy], @0_18 AS [VersionDate], @0_19 AS [VersionId], @0_20 AS [VersionName], @0_21 AS ZZZPredicate_6b41990a8da644379eda5722d78901bc, @0_22 AS ZZZ_Index) AS StagingTable ORDER BY ZZZ_Index
) AS StagingTable
ON DestinationTable.[Id] = StagingTable.[Id]
WHEN MATCHED   AND ( (DestinationTable.[RowVersion] = StagingTable.ZZZPredicate_6b41990a8da644379eda5722d78901bc OR (DestinationTable.[RowVersion] IS NULL AND StagingTable.ZZZPredicate_6b41990a8da644379eda5722d78901bc IS NULL)) )  THEN
    UPDATE
    SET     [AutodetectName] = StagingTable.[AutodetectName], [Autopublish] = StagingTable.[Autopublish], [CreatedOn] = StagingTable.[CreatedOn], [DeletedBy] = StagingTable.[DeletedBy], [DeletedOn] = StagingTable.[DeletedOn], [FolderId] = StagingTable.[FolderId], [IsActive] = StagingTable.[IsActive], [IsDrawing] = StagingTable.[IsDrawing], [IsSplit] = StagingTable.[IsSplit], [ModifiedOn] = StagingTable.[ModifiedOn], [PartialUri] = StagingTable.[PartialUri], [ProjectId] = StagingTable.[ProjectId], [PublishState] = StagingTable.[PublishState], [RasterQuality] = StagingTable.[RasterQuality], [RemoveAfterDot] = StagingTable.[RemoveAfterDot], [SkipHyperlinkingForDrawing] = StagingTable.[SkipHyperlinkingForDrawing], [UploadedBy] = StagingTable.[UploadedBy], [VersionDate] = StagingTable.[VersionDate], [VersionId] = StagingTable.[VersionId], [VersionName] = StagingTable.[VersionName]
OUTPUT
    $action,
    StagingTable.ZZZ_Index,
    1,
    INSERTED.[RowVersion] AS [RowVersion_zzzinserted]
;
-- @0_0: 09606634-a6b4-4d23-9d99-122b4b11320e (Type = Guid, Size = 16)
-- @0_1: True (Type = Boolean, Size = 1)
-- @0_2: False (Type = Boolean, Size = 1)
-- @0_3: 2/16/2021 9:43:18 PM +00:00 (Type = DateTimeOffset, Size = 10)
-- @0_4:  (Type = Guid, Size = 16)
-- @0_5:  (Type = DateTimeOffset, Size = 10)
-- @0_6: b53038ad-5312-4281-82a4-4e1a45f992be (Type = Guid, Size = 16)
-- @0_7: True (Type = Boolean, Size = 1)
-- @0_8: True (Type = Boolean, Size = 1)
-- @0_9: False (Type = Boolean, Size = 1)
-- @0_10: 2/17/2021 3:29:25 PM -05:00 (Type = DateTimeOffset, Size = 10)
-- @0_11: https://devstoragecanadaeast.blob.core.windows.net/pdf/09606634-a6b4-4d23-9d99-122b4b11320e/ (Type = String, Size = -1)
-- @0_12: f76a7e44-ebb0-40cb-9cca-2037d705b058 (Type = Guid, Size = 16)
-- @0_13: 1 (Type = Int32, Size = 4)
-- @0_14: 0 (Type = Int32, Size = 4)
-- @0_15: False (Type = Boolean, Size = 1)
-- @0_16: False (Type = Boolean, Size = 1)
-- @0_17: cf572101-a0fe-4859-c311-08d795fcb996 (Type = Guid, Size = 16)
-- @0_18: 2/16/2021 8:57:00 PM +00:00 (Type = DateTimeOffset, Size = 10)
-- @0_19: 68de2940-d8e3-4959-9a17-2dd821998c3e (Type = Guid, Size = 16)
-- @0_20: test5 (Type = String, Size = -1)
-- @0_21: 1591002 (Type = Binary, Size = 8)
-- @0_22: 0 (Type = Int32, Size = 0)
```

from the looks of it, RowVersion has the ulong value and not the binary value
### Further technical details
- EF Core  version: 2.2.6
- EF Core Extensions version: 2.8.19
- Database Provider: SQL Azure

Any suggestions are welcome

**Comment by JonathanMagnan** [comment]
Hello @soniachikh ,

Thank you for reporting, we will look at it.

The logic to handle `ValueConverter` still use the old logic for backward compatibility in EF Core 2.x

We greatly improved it in EF Core 3.x and 5.x

We will look at what is possible to do for the 2.x version.

Best Regards,

Jon

**Comment by soniachikh** [comment]
Hi Jon,
Thank you for your reply,
We are in the process of upgading to .net 5 and we tested it and we got the same failure.

Is there some thing we have to do?

Thank you

**Comment by JonathanMagnan** [comment]
Hello @soniachikh ,

Just to let you know that we successfully reproduced it.

One of my developers is currently looking to fix it.

**Comment by JonathanMagnan** [comment]
Hello @soniachikh ,

You were right, we indeed have an issue with the concurrency column. The `ValueConverter` logic was missed when we were retrieving this value.

The v5.1.21 has been released.

Could you test it and let us know if everything has been fixed correctly?

Best Regards,

Jon

**Comment by soniachikh** [comment]
Hi Jon,
Thank you, i will get back to you as soon as we test it.

**Comment by soniachikh** [comment]
hi Jon,
It works for our application! many thanks !
Merci beaucoup!

Sonia

**Comment by soniachikh** [comment]
Hi Jon,
Do you think this fix can be added to the former versions of ef core?

**Comment by JonathanMagnan** [comment]
Bonjour Sonia,

What do you mean by "former versions of ef core"? You mean for EF Core 2?

If so, this is already available, you simply need to match the major version of your EF Core version with our library:
- EF Core 5 => v5.1.21
- EF Core 3 => v3.1.21
- EF Core 2 => v2.8.21

We already support all these 3 EF Core versions.

Let me know if that answer your question

Cordialement,

Jon

**Comment by JonathanMagnan** [comment]
Hello Sonia,

Since our last conversation, we haven't heard from you. 

As mentioned in my previous message, we support all 3 EF Core versions. 

Don't hesitate to contact us for further information or assistance. 

Best regards,

Jon

**Comment by JonathanMagnan** [comment]
Hello @soniachikh 

A simple reminder that we are here to assist you. 

As mentioned in my previous message, we support all 3 EF Core versions.

Don't hesitate to contact us for further information or assistance.

Best regards,

Jon

**Comment by soniachikh** [comment]
I apologize !!!
Thank you Jon it works !
