### ISSUE TITLE
IgnoreOnMergeUpdateExpression is not work in BulkUpdate

### ISSUE THREAD

**Issue by shengyu-kmust** [zzzprojects/EntityFramework-Extensions#397]
### Description
  when i use BulkUpdate method and set IgnoreOnMergeUpdateExpression  to update entity with ignored fields,got exception.
but when i change BulkUpdate to BulkMerge,it works.But i don't want to use merge,because it will insert data.following is the details.thanks!
* dll version Z.EntityFramework.Extensions, Version=3.12.19.0
* .net framework 4.7.2
* sqlserver 2016，following is table script
```
CREATE TABLE [dbo].[Mng_OfferPreVesting](
	                    [Id] [int] IDENTITY(1,1) NOT NULL,
	                    [OfferResultId] [int] NOT NULL,
	                    [OfferDetailInfoCode] [nvarchar](100) NOT NULL,
	                    [Tag] [int] NOT NULL,
	                    [DealKind] [int] NOT NULL,
	                    [DealStatus] [int] NOT NULL,
	                    [DealTime] [datetime] NULL
                    ) ON [PRIMARY]
                    GO
```
* code
```
  [TestMethod]

        public void Test()
        {
            try
            {
                using (MngContext ctx = new MngContext())
                {
                    /*
                    create table script:
                    CREATE TABLE [dbo].[Mng_OfferPreVesting](
	                    [Id] [int] IDENTITY(1,1) NOT NULL,
	                    [OfferResultId] [int] NOT NULL,
	                    [OfferDetailInfoCode] [nvarchar](100) NOT NULL,
	                    [Tag] [int] NOT NULL,
	                    [DealKind] [int] NOT NULL,
	                    [DealStatus] [int] NOT NULL,
	                    [DealTime] [datetime] NULL
                    ) ON [PRIMARY]
                    GO
                    
                    database version:Microsoft SQL Server 2016 (SP2) (KB4052908) - 13.0.5026.0 (X64)   Mar 18 2018 09:11:49   Copyright (c) Microsoft Corporation  Enterprise Edition (64-bit) on Windows Server 2012 R2 Standard 6.3 <X64> (Build 9600: ) (Hypervisor) 
                     */
                    #region method1, following will throw exception
                    ctx.BulkUpdate(new List<MngOfferPreVesting>
                    {
                        new MngOfferPreVesting
                        {
                            Id=1,
                            DealTime=DateTime.Now
                        }
                    }, opt => { opt.IgnoreOnMergeUpdateExpression = a => new { a.Id, a.OfferDetailInfoCode, a.OfferResultId }; });
                    #endregion

                    #region method2, following is right
                    ctx.BulkMerge(new List<MngOfferPreVesting>
                    {
                        new MngOfferPreVesting
                        {
                            Id=1,
                            DealTime=DateTime.Now
                        }
                    }, opt => { opt.IgnoreOnMergeUpdateExpression = a => new { a.Id, a.OfferDetailInfoCode, a.OfferResultId }; });
                    #endregion

                }
            }
            catch (Exception ex)
            {
                var a = ex;
            }
        }

```

### Exception
   在 System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   在 System.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   在 System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   在 System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   在 System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString, Boolean isInternal, Boolean forDescribeParameterEncryption, Boolean shouldCacheForAlwaysEncrypted)
   在 System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 timeout, Task& task, Boolean asyncWrite, Boolean inRetry, SqlDataReader ds, Boolean describeParameterEncryptionRequest)
   在 System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry)
   在 System.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource`1 completion, String methodName, Boolean sendToPipe, Int32 timeout, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry)
   在 System.Data.SqlClient.SqlCommand.ExecuteNonQuery()
   在 Z.BulkOperations.SqlActionExecutor.(SqlCommand , BulkOperation , Int32 )
   在 Z.BulkOperations.SqlActionExecutor.(DbCommand , BulkOperation , Int32 )
   在 Z.BulkOperations.SqlActionExecutor.(ExecuteAction , DbCommand )
   在 Z.BulkOperations.DbActionExecutor.(List`1 )
   在 Z.BulkOperations.SqlProvider.(List`1 )
   在 ..(BulkOperation )
   在 Z.BulkOperations.BulkOperation.BulkUpdate()
   在 Z.EntityFramework.Extensions.EntityBulkOperation`1.BulkUpdate()
   在 Z.EntityFramework.Extensions.InternalBulkOperationManager.[](BulkOperation`1 , DbContext , List`1 , Boolean , Type , String )
   在 Z.EntityFramework.Extensions.InternalBulkOperationManager..(SchemaEntityType )
   在 System.Collections.Generic.List`1.ForEach(Action`1 action)
   在 Z.EntityFramework.Extensions.InternalBulkOperationManager.[](DbContext , BulkOperation`1 , IEnumerable`1 )
   在 Z.EntityFramework.Extensions.InternalBulkOperationManager.[](BulkOperation`1 , DbContext , IEnumerable`1 )
   在 DbContextExtensions.BulkUpdate[T](DbContext this, IEnumerable`1 entities, Action`1 bulkOperationFactory)
   在 DevTest.MngFacadeTest.Test() 在 D:\LTI\hally\source\DevTest\MngFacadeTest.cs 中: 第 124 行
```
### Further technical details
- EF version:6.0.0
- EF Extensions version:3.12.19.0
- Database Provider:entityframework.sqlserver 6.0.0.0

**Comment by JonathanMagnan** [comment]
Hello @shengyu-kmust ,

The `IgnoreOnMergeUpdateExpression` is only for the `BulkMerge` method.

For the `BulkUpdate` method, you should use the `IgnoreOnUpdateExpression` options.

Let me know if everything works once you use the right options.

Best Regards,

Jon

**Comment by JonathanMagnan** [comment]
Hello @shengyu-kmust ,

Since our last conversation, we haven't heard from you.

Did you get the chance to try the right options?

Don't hesitate to contact us with any questions or further assistance, 

Jon

**Comment by shengyu-kmust** [comment]
> Hello @shengyu-kmust ,
> 
there is no IgnoreOnUpdateExpression in  bulkOperationFactory of 
![20210302123121](https://user-images.githubusercontent.com/9101211/109598056-7461ca80-7b53-11eb-92de-70f808bdb14d.png)
![QQ截图20210302123155](https://user-images.githubusercontent.com/9101211/109598064-77f55180-7b53-11eb-96fe-dda720def450.png)

BulkUpdate method。
```
public static void BulkUpdate<T>(this DbContext @this, IEnumerable<T> entities, Action<EntityBulkOperation<T>> bulkOperationFactory) where T : class;
```

**Comment by JonathanMagnan** [comment]
Hello @shengyu-kmust ,

Your version is very very very old. So yes, it was probably not existing in 2017.

I'm not sure exactly when this has been added but as you that online example:
- https://dotnetfiddle.net/rKFA73 (from https://entityframework-extensions.net/ignore-on-update-expression)

It sure now part of the library.

We highly recommend you to update to a more recent version as there is nothing we can do for an older version.

Let me know if that answers correctly to your question.

Best Regards,

Jon

**Comment by shengyu-kmust** [comment]
thanks,but we can't update the version.
And there is another question in this issues ,why "InsertIfNotExists=false " is not work. Some data not exists in the database inserted when i set InsertIfNotExists=false.following is my code.
```
  this.BulkMerge<T>(entities, opt => { opt.InsertIfNotExists = false; opt.IgnoreOnMergeUpdateExpression = ignoreOnMergeUpdateExpression; });
```

**Comment by JonathanMagnan** [comment]
Hello @shengyu-kmust ,

The option `InsertIfNotExists` is for the `BulkInsert`.

The `BulkMerge` always inserts if the entities don't exist. It doesn't make sense this option for this method, since why not use `BulkUpdate` if you just want to update?
