### ISSUE TITLE
Constructors with optional parameters...

### ISSUE THREAD

**Issue by jsobell** [zzzprojects/EntityFramework-Extensions#40]
Just experimenting with this, and I imported the "MomentSharp" NuGet package to experiment with date manipulation.
Any call to `new Moment()` raises the exception 
```text
Value cannot be null.
Parameter name: constructor
```
The signature is simply
`public Moment(bool zero = false)`
Providing `false` avoids the problem.

Are optional parameters not implemented, or am I missing something?

Thanks, Jason

**Comment by JonathanMagnan** [comment]
Hello Jason,

Could you provide more information?

I'm currently unsure how this issue is related to Entity Framework Extensions.

Could you give us a small example or anything to let us get started with this issue?

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment]
Hello Jason,

We tested it with our library Eval.Expressions.NET which seem to be the right library.

We successfully reproduced the issue and are currently investigating it.

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment]
Hello Jason,

The v2.1.2 has been released to fix this issue:
https://www.nuget.org/packages/Z.Expressions.Eval/

Please note that's only a quick fix, more work will be done by our team in following week to provide more support to constructor overload as we did with method.

Make sure to also use the right issue tracker: https://github.com/zzzprojects/Eval-Expression.NET/issues

Best Regards,

Jonathan

**Comment by jsobell** [comment]
D'oh! Sorry, I followed the 'Issues' link on the webpage and was brought here.
I've just checked, and it turns out I'm not a complete idiot (just `partial`):

The link in the documentation requires updating: http://eval-expression.net/issue-tracker

Thanks for the speedy response, I'll give it a go.

Cheers,
 Jason

**Comment by jsobell** [comment]
Initial tests look good, so I'll close this.
Many thanks.

**Comment by JonathanMagnan** [comment]
Oh thank you Jason,

I have fixed this link. That explain why you landed here! Our fault.

Best Regards,

Jonathan
