### ISSUE TITLE
UseHiLo EF Core 5 setting value to previous one

### ISSUE THREAD

**Issue by rshivarkar** [zzzprojects/EntityFramework-Extensions#408]
```
modelBuilder.HasSequence("SEQ_TEST").IncrementsBy(1);

entity.Property(e => e.TestId) 
  .HasPrecision(10) .
  HasColumnName("TEST_ID") 
  .ValueGeneratedOnAdd() .
  UseHiLo("SEQ_TEST", "SCHEMA_NAME");
```

I can add 10 rows but for 11th row, its again reverting back to previous TEST_ID resulting in PK violation. Is there anything that I am missing here ?  I am using oracle DB.

**Comment by JonathanMagnan** [comment]
Hello @rshivarkar ,

Unfortunately, we still do not support the `UseHiLo`.

Perhaps the following answer could help you with an alternative solution: https://github.com/zzzprojects/EntityFramework-Extensions/issues/315#issuecomment-707764965

Best Regards,

Jon
