### ISSUE TITLE
how to use ternary operator in UpdateFromQuery

### ISSUE THREAD

**Issue by ainuo5213** [zzzprojects/EntityFramework-Extensions#409]
### Description
there has an error when I use ternary operator in UpdateFromQuery, just like
``` C#
bool isValid = 1 == 1;
context.Entities.Where(r => r.ID == 1).UpdateFromQuery(r => new Entities() { Time = isValid ? DateTime.Now : r.Time });
````

### Exception
and here are some exception messages

```
System.NullReferenceException:“Object reference not set to an instance of an object.”
```

### Fiddle or Project (Optional)
fiddle : https://dotnetfiddle.net/bjSs1f
if here has errors, maybe you can copy it to a temp project, and just run

Otherwise, make sure to include as much information as possible to help our team to reproduce the issue.

_Note: More information you provide, faster we can implement a solution._

### Further technical details
- EF version: 5.0.5
- EF Extensions version: 5.1.31
- Database Provider: sql server

**Comment by ainuo5213** [comment]
sorry, fiidle url at: `https://dotnetfiddle.net/bjSs1f`

**Comment by JonathanMagnan** [comment]
Hello @ainuo5213 ,

We will try to eventually improve it but at this moment, some part of expression such as `DateTime.Now` must be declared outside:

```csharp
int count = 1;
bool isValid = count == 1;
var date = DateTime.Now;
context.Customers.Where(x => x.CustomerID == 1).UpdateFromQuery(x => new Customer { Time = isValid ? date : x.Time });
```

Online example: https://dotnetfiddle.net/PJzAVP

Let me know if that solved your current issue

Best Regards,

Jon

---
**Sponsorship**
[Help us improve this library](https://github.com/sponsors/zzzprojects)

**Performance Libraries**
`context.BulkInsert(list, options => options.BatchSize = 1000);  `
[Entity Framework Extensions](https://entityframework-extensions.net/) • [Bulk Operations](https://bulk-operations.net/) •  [Dapper Plus](https://dapper-plus.net/)

**Runtime Evaluation**
`Eval.Execute("x + y", new {x = 1, y = 2}); // return 3`
[C# Eval Function](https://eval-expression.net/) • [SQL Eval Function](https://eval-sql.net/)

**Comment by ainuo5213** [comment]
@JonathanMagnan but here some other errors when I use the operator:
```
convert 'string' to 'datetime' has an error
```
and this is the entity:
![image](https://user-images.githubusercontent.com/50324300/115977256-d31e5000-a5a8-11eb-976c-07107081da5c.png)

**Comment by JonathanMagnan** [comment]
Hello @ainuo5213 ,

Please provide us a project or runtime example.

This is hard for us to understand what is the error when your entity doesn't contain the column `Time` as your first question and that we are not exactly sure what is the code that throws this new error.

Best Regards,

Jon
