### ISSUE TITLE
'DBContext' does not contain a definition for 'BulkSaveChanges'

### ISSUE THREAD

**Issue by henrikib** [zzzprojects/EntityFramework-Extensions#41]
I previously had:
base.SaveChanges();

where base is System.Data.Entity.DBContext.
When switching to 
base.BulkSaveChanges();

I get the error: 'DBContext' does not contain a definition for 'BulkSaveChanges'
Can You help me?

**Comment by henrikib** [comment]
I solved this by writing this.BulkSaveChanges() :)

**Comment by JonathanMagnan** [comment]
Hello @henrikib ,

Exactly, since the BulkSaveChanges doesn't exist in the base class, you must do what you have did ;)

Best Regards,

Jonathan
