### ISSUE TITLE
ForceUpdateUnmodifiedValues is no longer available

### ISSUE THREAD

**Issue by akamud** [zzzprojects/EntityFramework-Extensions#411]
### Description
[This section](https://entityframework-extensions.net/bulk-savechanges#why-bulksavechanges-update-all-columns-by-default) states that we can disable the update on `BulkSaveChanges` trying to update all the columns by using `ForceUpdateUnmodifiedValues`, but on versoin 3.1.33, the property is not available.

### Further technical details
- EF version: Microsoft.EntityFrameworkCore.SqlServer/3.1.3
- EF Extensions version: Z.EntityFramework.Extensions.EFCore/3.1.33
- Database Provider: SQLServer

**Comment by JonathanMagnan** [comment]
Hello @akamud ,

This option is for `EF6` only.

In `EF Core`, the `BulkSaveChanges` already currently try to update only the column that it has to update.

(The doc has been updated and will be available the next time we release it)

Let me know if that answers your question.

Best Regards,

Jon

**Comment by akamud** [comment]
Thanks, I guess I was using the `BulkSaveChanges` wrong. If I pass the `IncludeGraph` and the `InsertIfNotExists` options to it, it was trying to update a computed column and throwing an exception. I still find it a bit weird that passing these options breaks the `BulkSaveChanges`, though.

I removed these options from the `BulkSaveChanges` since it already inserts the whole graph because my entities are already in the ChangeTracker. 

Does that make sense?

**Comment by JonathanMagnan** [comment]
Yes, it makes 100% sense ;)

I agree, that's a little bit weird. We will eventually have to check what we can do for this, but adding an exception on our side might be even worse for backward compatibility as we might break some code already running in production.

**Comment by akamud** [comment]
Awesome, thanks for the great support. Feel free to close this since you explained why the property is missing and the documentation is getting updated.
