### ISSUE TITLE
Oops! A permanent key will be generated, but no property getter was found (6.0.0-preview.3.21201.2-09)

### ISSUE THREAD

**Issue by tuyndv** [zzzprojects/EntityFramework-Extensions#416]
Dear Team,

In the version update : 6.0.0-preview.3.21201.2-**09** , BulkUpdateAsync or BulkMergeAsync got an exception

**_Oops! A permanent key will be generated, but no property getter was found (6.0.0-preview.3.21201.2-09)_**

Note : 6.0.0-preview.3.21201.2-**08** working.

Table Info :
```SQL
 create table XXX_Queue
(
    Id                uniqueidentifier not null
        constraint PK_XXX_Queue
            primary key,
    TraceParent       nvarchar(60),
    IPAddress         varchar(20),
    UserAgent         nvarchar(512),
    Payload           ntext,
    Status            int              not null,
    CreatedDate       datetime2        not null,
    LastModified      datetime2,
    PushDate          datetime2,
    PushException     ntext,
    PushTimes         int,
    PushResponse      ntext
)
```

Code :
```C#
await _dbContext.BulkMergeAsync(payloadQueues, p =>
                {
                    p.ColumnPrimaryKeyExpression = c => c.Id;
                    p.ColumnInputExpression = c => new
                    {
                        c.Status,
                        c.PushDate,
                        c.PushResponse,
                        c.PushException,
                        c.PushTimes,
                        c.LastModified
                    };
                });
```

Thanks

**Comment by JonathanMagnan** [comment]
Hello @tuyndv ,

This is indeed a new error we added in this version to better support identity that's generated by Entity Framework.

We will look at it.

Best Regards,

Jon

**Comment by tuyndv** [comment]
Dear @JonathanMagnan 

Id is Guid Type
```C#
 [Table("Harawork_Queue")]
    public partial class HaraworkQueue
    {
        public HaraworkQueue()
        {
            #region Generated Constructor

            #endregion
        }

        #region Generated Properties
        [Key]
        public Guid Id { get; set; }
        [Column(TypeName = "varchar")]
        [StringLength(50)]
        public string HaravanId { get; set; }
        [Column(TypeName = "varchar")]
        [StringLength(100)]
        public string HaravanTopic { get; set; }
        [Column(TypeName = "varchar")]
        [StringLength(50)]
        public string HaravanOrgId { get; set; }
        [Column(TypeName = "nvarchar")]
        [StringLength(225)]
        public string HaravanHmacSha256 { get; set; }
        [Column(TypeName = "nvarchar")]
        [StringLength(60)]
        public string TraceParent { get; set; }
        [Column(TypeName = "varchar")]
        [StringLength(20)]
        public string IPAddress { get; set; }
        [Column(TypeName = "nvarchar")]
        [StringLength(512)]
        public string UserAgent { get; set; }
        [Column(TypeName = "ntext")]
        [MaxLength]
        public string Payload { get; set; }
        [Column(TypeName = "int")]
        public QueueStatus Status { get; set; }
        [Column(TypeName = "datetime2")]
        public DateTime CreatedDate { get; set; }
        [Column(TypeName = "datetime2")]
        public DateTime? LastModified { get; set; }
        [Column(TypeName = "datetime2")]
        public DateTime? PushDate { get; set; }
        [Column(TypeName = "ntext")]
        public string PushException { get; set; }
        [Column(TypeName = "ntext")]
        public string PushResponse { get; set; }
        [Column(TypeName = "int")]
        public int? PushTimes { get; set; }
        #endregion

        #region Generated Relationships


        #endregion

    }
```

**Comment by JonathanMagnan** [comment]
Hello @tuyndv ,

Here is a Fiddle that shows this case is working: https://dotnetfiddle.net/foiSWs

However, I believe we definitely missing something as you are not the first to tell us the code we added doesn't fully work.

Is it possible for you to tell us the version of EF Core you are using? For example `6.0.0-preview.3.21201.2`

Also, do you think you could reproduce the issue in this Fiddle or a standalone project? That will greatly help us to focus on the resolution instead of trying to understand how to get the error.

**Comment by tuyndv** [comment]
Dear JonathanMagnan,

I change Id field to :
[Column(TypeName = "bigint")]
[DatabaseGenerated(DatabaseGeneratedOption.Identity)]

=> Work done.

This PackageReference  : 
<PackageReference Include="Microsoft.EntityFrameworkCore" Version="6.0.0-preview.4.21253.1" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="6.0.0-preview.4.21253.1">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="6.0.0-preview.4.21253.1" />

**Comment by JonathanMagnan** [comment]
Hello @tuyndv ,

Our library doesn't support the `preview4`, we find out an issue in `EF Core` that makes it incompatible with our library. We are still unsure if that's an issue only on this preview or they heavily modified their logic for complex owned types. We currently waiting for preview 5.

As for the error for the `identity`, we will look at it.

We currently have a branch that improves all this logic but it will takes several day to merge it as a lot of core code has been modified to rework all this `identity`/generation logic

**Comment by JonathanMagnan** [comment]
Hello @tuyndv ,

Just to let you know that our library now supports the latest `preview`.

The `identity` issue should also be fixed in the latest version.

If you have the chance, could you test it and let us know if everything is now working as expected?

Best Regards,

Jon
