### ISSUE TITLE
Z.EntityFramework.Plus.AuditEntry vs Z.BulkOperations.AuditEntry

### ISSUE THREAD

**Issue by Phibee** [zzzprojects/EntityFramework-Extensions#417]
why is it Z.EntityFramework.Plus.AuditEntry different from Z.BulkOperations.AuditEntry?

coz I'm using AuditManager Z.EntityFramework.Plus.AuditEntry and for Bulk Operations it's different
https://entityframework-extensions.net/audit.

**Comment by JonathanMagnan** [comment]
Hello @Phibee ,

Both audits are completely different.

To make is very simple:
- The `Z.EntityFramework.Plus.AuditEntry` is created using the ChangeTracker. It doesn't care about what is the actual value in the database, it only cares about what's in the ChangeTracker.
- The `Z.BulkOperations.AuditEntry` is created using database values. It doesn't care about what is the actual value in the change tracker, it only cares about what's in the Database.

Both have the pros and cons. Unfortunately, they have the same name which is probably a mistake on our side even if they have a different namespace.

Let me know if that answers correctly to your question or you need more information.

Best Regards,

Jon

**Comment by Phibee** [comment]
Thanks very much @JonathanMagnan for quick response,

Yeah, they have different values as well. Like for example on the `Z.EntityFramework.Plus.AuditEntry` returns Entity Name, while on `Z.BulkOperations.AuditEntry` is the actual Table Name. As well as the AuditActionType vs AuditEntryState. It's just that we're trying to store Audit in one database table which we want it to almost similar values.  Even using AuditManager which is good. but for bulk operations you need to have different way.

All in all both good library.

**Comment by JonathanMagnan** [comment]
Thank you for the feedback.

In the short term, I don't think anything will be done but you are right, it would be good if the `Z.BulkOperations.AuditEntry` return some similar value that EF Plus does. However, that will cause some breaking changes which we really always try to advoid and even more, the `Z.BulkOperations` library can be used without EF, so additional field when you are not in EF will be weird.
