### ISSUE TITLE
Compatibility question

### ISSUE THREAD

**Issue by james1o4timothy** [zzzprojects/EntityFramework-Extensions#418]
This is a question and not a feature request or issue.
Is it possible to make this compatible with 
[Info carrier](https://github.com/azabluda/InfoCarrier.Core)

**Comment by JonathanMagnan** [comment]
Hello @james1o4timothy ,

Unfortunately, as we answer you here https://github.com/zzzprojects/EntityFramework-Plus/issues/686, it depends what is not compatible with our library.

If you can give us more information about what doesn't work, it will be already a good start.

Best Regards,

Jon
