### ISSUE TITLE
WhereBulkContains for Postgres returns all existing entities in table

### ISSUE THREAD

**Issue by DmitriyMarov** [zzzprojects/EntityFramework-Extensions#423]
### Description
When I use WhereBulkContains for specified entities, it returns all existing entities in table. Similar MS SQL implementation works fine.

### Fiddle or Project (Optional)
I created simple reproduce demo: https://github.com/DmitriyMarov/BulkDemo. Don't forget to change connection string in app.config and run createtables.sql script on your postgres db.

### Further technical details

- EF version: 6.4.0
- EF Extensions version: 5.1.41
- Database Provider: Devart.Data.PostgreSql 7.20.1905.0

**Comment by JonathanMagnan** [comment]
Hello @DmitriyMarov ,

Unfortunately, at this moment this feature only supports `SQL Server`.

We might try to support more providers after the summer but there is currently no short-term plan of adding it right now (we currently have way too many requests to close first before adding more).

Still, my developer will look to check if at least we can still add a message when this case happens to an unsupported provider.

Best Regards,

Jon

**Comment by JonathanMagnan** [comment]
Hello @DmitriyMarov ,

The error message should now be fixed. Thank again for letting us know about this.

As said, we will try to look at that features after the summer to support more provider

Best Regards,

Jon
