### ISSUE TITLE
Possible memory leak with BulkInsert

### ISSUE THREAD

**Issue by aldinei-sampaio** [zzzprojects/EntityFramework-Extensions#424]
When using BulkInsert to save 10k-50k rows to a table, we noticed a severe memory consumption in our app. And that memory is not freed after bulkinsert ends (a memory leak, perhaps?).

We have a table with a VARCHAR(MAX) field. And for this field we are saving a big text (around 34k characters).

On the bulkinsert for 10k rows, the test app consumes 1,288MB of memory if we use MySql provider and 764MB if we use SQL Server or Sqlite. If we try to save 50k rows, the memory consumption increases up to 7GB (that are NOT freed after the bulkinsert).

Here is our test project (note: the connectionstrings must be defined on the context classes):

[BulkCopyTest.zip](https://github.com/zzzprojects/EntityFramework-Extensions/files/6818997/BulkCopyTest.zip)

**Comment by JonathanMagnan** [comment]
Hello @aldinei-sampaio ,

## Memory Consumption 
`Faker.Data` seem the library that consume A LOT of memory.

We did a small test without our library, and by using a simple "RandomString" method found on internet, the memory go from over 800MB to around only 40MB.

```csharp
private static async Task RunAsync<T>() where T : DataContext, new()
{
	using (var context = new T())
	{
		await context.Database.MigrateAsync();
		await context.SaveChangesAsync();
	}

	using (var context = new T())
	{
		var document = GetDocuments().ToList();
		//await context.Document.BulkInsertAsync(
		//    document, 
		//    i => i.AutoMapOutputDirection = false
		//);
	}
}

private static IEnumerable<Document> GetDocuments()
{
	for (var n = 0; n < NumberOfRecords; n++)
	{
		yield return new Document
		{
			//Code = Faker.User.Password(),
			//Contents = Faker.Lorem.Paragraph(500)
			Code = RandomString(20),
			Contents = RandomString(500)
		};
	}
}

private static Random random = new Random();
public static string RandomString(int length)
{
	const string chars = "ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789";
	return new string(Enumerable.Repeat(chars, length)
	  .Select(s => s[random.Next(s.Length)]).ToArray());
}
```

Obviously, the `RandomString` method doesn't have all advantage that `Faker.Data` has but the high memory consumption is not made by our library but this third party library.

When uncommenting the `BulkInsert`, a few more MB of memory but nothing really anormal.

## Memory Leak

At my surprise, even when we comment the `BulkInsert`, use the `RandomString` method and call the garbage collector, it seems the 10k entities generated is still in the memory due to the async Main.

We did a test by using a non-async Main and no memory leak happened.

```csharp
public static void Main(string[] args)
{
	var opt = '2';

	Console.WriteLine();
	Console.WriteLine();
	Console.WriteLine("Running...");

	var sw = new Stopwatch();
	sw.Start();

	switch(opt)
	{
		case '2':
			var task2 = RunAsync<SqlServerDataContext>();
			Task.WaitAll(task2);
			break;
	}

	sw.Stop();

	Console.WriteLine("Done.");
	Console.WriteLine();
	Console.WriteLine($"Elapsed time: {sw.ElapsedMilliseconds:N0}ms");

	Console.ReadKey();
}

private static async Task RunAsync<T>() where T : DataContext, new()
{
	using (var context = new T())
	{
		await context.Database.MigrateAsync();
		await context.SaveChangesAsync();
	}

	using (var context = new T())
	{
		var document = GetDocuments().ToList();
		//await context.Document.BulkInsertAsync(
		//    document, 
		//    i => i.AutoMapOutputDirection = false
		//);
	}
}
```

I cannot explain why the `async Main` retain some local variable, but there is definitely something and you are not the first one to report this: https://github.com/dotnet/roslyn/issues/40420

Again, the code has been executed without our library and we got the same behavior, so this is not related to us but how `async` method work.

## Conclusion

Obviously if you think I'm wrong, please let me know but after our research, it looks that both issues is not related to our library.

Best Regards,

Jon

**Comment by aldinei-sampaio** [comment]
Thank you for your kind and fast response.

I think there was a little misinterpretation of what "Faker.Lorem.Paragraph(500)" does. It returns a string with 500 paragraphs of text (between 33000 and 35000 characters). Your test used a let less memory just because it was using an incredibly smaller string. Using your RandomString function with the value 34000 as argument uses rougly the same memory than Faker.Lorem.Paragraph(500).

```
for (var n = 0; n < NumberOfRecords; n++)
{
    yield return new Document
    {
        Code = Faker.User.Password(),
        Contents = RandomString(34000)
    };
}
```

Another think I want to talk about is your use of the ToList() method. My code purpose was just to avoid that at all costs. We can't affort to use it because the ammount of data our production app uses is just too big to create the complete list of data in memory that way.

In your example, is the ToList() method that generates the memory leak; if you just iterate through the enumerator (which is what I think the bulkinsert should be doing), the memory consumption does not go up at all.

```
foreach (var document in GetDocuments())
{
    if (document.Contents == null) // just for doing something with the object and prevent compiler optimizations
        throw new Exception();
}
```

Obs: if you use the ToList() approach, does not matter if you use async/await or not: the memory leak occurs anyways. A call to GC.Collect() after the list went out of scope frees most of the memory used but not all. Anyways, I think the ToList() method should not be called at all.

**Comment by JonathanMagnan** [comment]
Hello @aldinei-sampaio ,

My bad, I sure did a big mistake for `Faker.Data`. 

I better understand your issue.

At this moment, there is no way to enable "streaming" within our library for `Entity Framework`. Unfortunately, we need to transform it to a `List` and cannot use purely an IEnumerable (However, we support streaming when you use a `BulkOperation` but then you need to specify your mapping).

One solution for you at this moment would be to use a `Batch` method: https://github.com/morelinq/MoreLINQ/blob/master/MoreLinq/Batch.cs

So the code will look probably something similar to this:

```csharp
var batches = GetDocuments().Batch(1000);

foreach (var batch in batches)
{
	await context.Document.BulkInsertAsync(
		batch,
		i => i.AutoMapOutputDirection = false
	);
}
```

We made the test and indeed, a lot of less memory was used.

I will speak with my developer about how we could integrate this kind of solution into our library. The solution is not as good as a 100% pure streaming but way easier to implement for now.

**Comment by aldinei-sampaio** [comment]
Ok, that explains a lot. My previous experience was with the BulkCopy class from System.Data.SqlServer (and its NpgSql equivalent for PostgreSql), where we always used streaming, so I wrongly assumed the BulkInsert method did something similar.

Can you give more details about that BulkOperation you talked about? We don't mind to specify the mapping. Actually, that sounds even better, because it give us more fine control over the whole operation.

**Comment by JonathanMagnan** [comment]
Sure, I will create you an online example tomorrow.

**Comment by JonathanMagnan** [comment]
Hello @aldinei-sampaio ,

Here is an online example: https://dotnetfiddle.net/dlk4HV

To make it easier, on our side we usually use a `BaseDataReader` that we can override with the minimum code required to make it works:

```csharp
public class DocumentDataReader : BaseDataReader<Document>
{
	public DocumentDataReader(IEnumerable<Document> enumerables)
	{
		this.Enumerator = enumerables.GetEnumerator();

		Tuples.Add(new Tuple<string, int>("Id", 0));
		Tuples.Add(new Tuple<string, int>("Code", 1));
		Tuples.Add(new Tuple<string, int>("Contents", 2));
	}

	public override object this[string name]
	{
		get
		{
			if(name == "Id")
			{
				return Enumerator.Current.Id;
			}
			else if(name == "Code")
			{
				return Enumerator.Current.Code;
			}
			else if(name == "Contents")
			{
				return Enumerator.Current.Contents;
			}

			throw new Exception("Invalid name");
		}
	}
}

public class BaseDataReader<T> : IDataReader
{
	protected IEnumerator<T> Enumerator { get; set; }

	public List<Tuple<string, int>> Tuples = new List<Tuple<string, int>>();

	public int FieldCount
	{
		get { return Tuples.Count; }
	}

	public virtual object this[string name]
	{
		get
		{
			throw new NotImplementedException();
		}
	}

	public string GetName(int i)
	{
		return Tuples.Single(x => x.Item2 == i).Item1;
	}
	public int GetOrdinal(string name)
	{
		return Tuples.Single(x => x.Item1 == name).Item2;
	}

	public object GetValue(int i)
	{
		var name = GetName(i);
		return this[name];
	}

	public void Close()
	{
	}
	public void Dispose()
	{

	}

	public bool Read()
	{
		return Enumerator.MoveNext();
	}

	#region Default Interface Implementation

	public string GetDataTypeName(int i)
	{
		throw new NotImplementedException();
	}

	public Type GetFieldType(int i)
	{
		throw new NotImplementedException();
	}

	public int GetValues(object[] values)
	{
		throw new NotImplementedException();
	}

	public bool GetBoolean(int i)
	{
		throw new NotImplementedException();
	}

	public byte GetByte(int i)
	{
		throw new NotImplementedException();
	}

	public long GetBytes(int i, long fieldOffset, byte[] buffer, int bufferoffset, int length)
	{
		throw new NotImplementedException();
	}

	public char GetChar(int i)
	{
		throw new NotImplementedException();
	}

	public long GetChars(int i, long fieldoffset, char[] buffer, int bufferoffset, int length)
	{
		throw new NotImplementedException();
	}

	public Guid GetGuid(int i)
	{
		throw new NotImplementedException();
	}

	public short GetInt16(int i)
	{
		throw new NotImplementedException();
	}

	public int GetInt32(int i)
	{
		throw new NotImplementedException();
	}

	public long GetInt64(int i)
	{
		throw new NotImplementedException();
	}

	public float GetFloat(int i)
	{
		throw new NotImplementedException();
	}

	public double GetDouble(int i)
	{
		throw new NotImplementedException();
	}

	public string GetString(int i)
	{
		throw new NotImplementedException();
	}

	public decimal GetDecimal(int i)
	{
		throw new NotImplementedException();
	}

	public DateTime GetDateTime(int i)
	{
		throw new NotImplementedException();
	}

	public IDataReader GetData(int i)
	{
		throw new NotImplementedException();
	}

	public bool IsDBNull(int i)
	{
		throw new NotImplementedException();
	}

	public object this[int i] => throw new NotImplementedException();

	public DataTable GetSchemaTable()
	{
		throw new NotImplementedException();
	}

	public bool NextResult()
	{
		throw new NotImplementedException();
	}

	public int Depth { get; }
	public bool IsClosed { get; }
	public int RecordsAffected { get; }

	#endregion
}
```

Then you can use directly the `BulkOperation` class and pass this reader:

```csharp
var reader = new DocumentDataReader(GetDocuments());

var bulkOperation = new BulkOperation();
bulkOperation.Connection = new SqlConnection(FiddleHelper.GetConnectionStringSqlServer());
bulkOperation.Connection.Open();
bulkOperation.DestinationTableName = "Document";

// if you wish to make some custom mapping
// bulkOperation.ColumnMappings.Add("Id");

bulkOperation.BulkInsert(reader);
```

When testing it with `Faker` in your project, only 75MB was consumed which was pretty stable during all the `BulkInsert`.

Let me know if that solution worked for you and about your memory consumption.

**Comment by aldinei-sampaio** [comment]
Hello, and thank you very much for your example.

Your code works like a charm for SQL Server.

Unfortunatelly, it does not work for MySql of Sqlite. For those providers seems that the library is calling some of the non implemented methods of the base class, resulting in a NotImplementedException.

First it called "RecordsAffected". I implemented it returning 0 and then it called "GetValues". I implemented it to put the values on the array and then it called "GetSchemaTable". That method I could not figure out how to implement it. Just creating a DataTable with all the columns being saved seems not to be enough as I keep receiving an ArgumentException with the message "Input array is longer than the number of columns in this table."

**Comment by JonathanMagnan** [comment]
Hello @aldinei-sampaio ,

We successfully make the reader work for `MySql` and `Sqlite`, However, there is a memory issue we want to investigate first as those 2 providers seem to have a way higher memory consumption than `SQL Server`.

I should be able to give you another update tomorrow.

**Comment by JonathanMagnan** [comment]
Finally, we don't have any high memory consumption

Here is the code we used that's compatible with `MySql`, `Sqlite` and `SQL Server`:

```csharp
public class DocumentDataReader : BaseDataReader<Document>
{
	public DocumentDataReader(IEnumerable<Document> enumerables)
	{
		this.Enumerator = enumerables.GetEnumerator();

		Tuples.Add(new Tuple<string, int>("Id", 0));
		Tuples.Add(new Tuple<string, int>("Code", 1));
		Tuples.Add(new Tuple<string, int>("Contents", 2));
	}

	public override DataTable GetSchemaTable()
	{
		var dt = new DataTable();

		dt.Columns.Add("ColumnName", typeof(string));
		dt.Columns.Add("DataType", typeof(Type));

		dt.Rows.Add("Id", typeof(Int64));
		dt.Rows.Add("Code", typeof(string));
		dt.Rows.Add("Contents", typeof(string));

		return dt;
	}

	public override int GetValues(object[] values)
	{
		values[0] = this["Id"];
		values[1] = this["Code"];
		values[2] = this["Contents"];
		return values.Length;
	}

	public override object this[string name]
	{
		get
		{
			if(name == "Id")
			{
				return Enumerator.Current.Id;
			}
			else if(name == "Code")
			{
				return Enumerator.Current.Code;
			}
			else if(name == "Contents")
			{
				return Enumerator.Current.Contents;
			}

			throw new Exception("Invalid name");
		}
	}
}
	
public class BaseDataReader<T> : IDataReader
{
	protected IEnumerator<T> Enumerator { get; set; }

	public List<Tuple<string, int>> Tuples = new List<Tuple<string, int>>();

	public int FieldCount
	{
		get { return Tuples.Count; }
	}

	public virtual object this[string name]
	{
		get
		{
			throw new NotImplementedException();
		}
	}

	public string GetName(int i)
	{
		return Tuples.Single(x => x.Item2 == i).Item1;
	}
	public int GetOrdinal(string name)
	{
		return Tuples.Single(x => x.Item1 == name).Item2;
	}

	public object GetValue(int i)
	{
		var name = GetName(i);
		return this[name];
	}

	public void Close()
	{
	}
	public void Dispose()
	{

	}

	public bool Read()
	{
		return Enumerator.MoveNext();
	}

	#region Default Interface Implementation

	public string GetDataTypeName(int i)
	{
		throw new NotImplementedException();
	}

	public Type GetFieldType(int i)
	{
		throw new NotImplementedException();
	}

	public virtual int GetValues(object[] values)
	{
		throw new NotImplementedException();
	}

	public bool GetBoolean(int i)
	{
		throw new NotImplementedException();
	}

	public byte GetByte(int i)
	{
		throw new NotImplementedException();
	}

	public long GetBytes(int i, long fieldOffset, byte[] buffer, int bufferoffset, int length)
	{
		throw new NotImplementedException();
	}

	public char GetChar(int i)
	{
		throw new NotImplementedException();
	}

	public long GetChars(int i, long fieldoffset, char[] buffer, int bufferoffset, int length)
	{
		throw new NotImplementedException();
	}

	public Guid GetGuid(int i)
	{
		throw new NotImplementedException();
	}

	public short GetInt16(int i)
	{
		throw new NotImplementedException();
	}

	public int GetInt32(int i)
	{
		throw new NotImplementedException();
	}

	public long GetInt64(int i)
	{
		throw new NotImplementedException();
	}

	public float GetFloat(int i)
	{
		throw new NotImplementedException();
	}

	public double GetDouble(int i)
	{
		throw new NotImplementedException();
	}

	public string GetString(int i)
	{
		throw new NotImplementedException();
	}

	public decimal GetDecimal(int i)
	{
		throw new NotImplementedException();
	}

	public DateTime GetDateTime(int i)
	{
		throw new NotImplementedException();
	}

	public IDataReader GetData(int i)
	{
		throw new NotImplementedException();
	}

	public bool IsDBNull(int i)
	{
		throw new NotImplementedException();
	}

	public object this[int i] => throw new NotImplementedException();

	public virtual DataTable GetSchemaTable()
	{
		throw new NotImplementedException();
	}

	public bool NextResult()
	{
		throw new NotImplementedException();
	}

	public int Depth { get; }
	public bool IsClosed { get; }
	public int RecordsAffected { get; }

	#endregion
}
```

Let me know if that worked for you or you still have an issue here.

**Comment by aldinei-sampaio** [comment]
Thank you very much. That worked perfectly. :-)
