### ISSUE TITLE
Why I can't Use BulkMerge with identity column when I update from V.3.1.41 To 3.2.X

### ISSUE THREAD

**Issue by Nutgangza2** [zzzprojects/EntityFramework-Extensions#425]
I got an error When I Update to version3.2.X when I use BulkMerge with Identity column But I can use this function on version 3.1.41 

ErrorMessage : Explicit value must be specified for identity column in table 'TBM_GOODS' either when IDENTITY_INSERT is set to ON or when a replication user is inserting into a NOT FOR REPLICATION identity column. Microsoft.Data.SqlClient.SqlException (0x80131904): Explicit value must be specified for identity column in table 'TBM_GOODS' either when IDENTITY_INSERT is set to ON or when a replication user is inserting into a NOT FOR REPLICATION identity column. at Microsoft.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action1 wrapCloseInAction) at Microsoft.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action1 wrapCloseInAction) at Microsoft.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose) at Microsoft.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady) at Microsoft.Data.SqlClient.SqlDataReader.TryHasMoreRows(Boolean& moreRows) at Microsoft.Data.SqlClient.SqlDataReader.TryReadInternal(Boolean setTimeout, Boolean& more) at Microsoft.Data.SqlClient.SqlDataReader.Read() at System.Data.Common.DataAdapter.FillLoadDataRow(SchemaMapping mapping) at System.Data.Common.DataAdapter.FillFromReader(DataSet dataset, DataTable datatable, String srcTable, DataReaderContainer dataReader, Int32 startRecord, Int32 maxRecords, DataColumn parentChapterColumn, Object parentChapterValue) at System.Data.Common.DataAdapter.Fill(DataSet dataSet, String srcTable, IDataReader dataReader, Int32 startRecord, Int32 maxRecords) at System.Data.Common.DbDataAdapter.FillInternal(DataSet dataset, DataTable[] datatables, Int32 startRecord, Int32 maxRecords, String srcTable, IDbCommand command, CommandBehavior behavior) at System.Data.Common.DbDataAdapter.Fill(DataSet dataSet, Int32 startRecord, Int32 maxRecords, String srcTable, IDbCommand command, CommandBehavior behavior) at System.Data.Common.DbDataAdapter.Fill(DataSet dataSet) at .(DbCommand , BulkOperation , Int32 ) at .(DbCommand , BulkOperation , Int32 ) at .( , DbCommand ) at .Execute(List1 actions) at .(List1 ) at Z.BulkOperations.BulkOperation.Execute() at Z.BulkOperations.BulkOperation.BulkMerge() at .BulkMerge[T](DbContext this, IEntityType entityType, IEnumerable1 list, Action1 options, SavingSelector savingSelector, Boolean forceSpecificTypeMapping) at .BulkMerge[T](DbContext this, IEnumerable1 entities, Action1 options, Boolean isBulkSaveChanges) at DbContextExtensions.BulkMerge[T](DbContext this, IEnumerable1 entities, Action1 options)

**Comment by JonathanMagnan** [comment]
Hello @Nutgangza2 ,

Thank you for reporting, I will ask my developer to look at it. 

The v3.2.x was indeed a pretty major change for us exactly for that kind of mapping.

Is it possible to provide us your table script, entity definition, and how you are doing your mapping for this entity? You can remove anything sensible that you believe is not required to reproduce this issue.

If you can provide us a project that reproduces the issue, that will be indeed even better (you can send it in private here info@zzzproject.com if you wish)

Best Regards,

Jon

**Comment by Nutgangza2** [comment]
I already sent an email please check.

**Comment by JonathanMagnan** [comment]
Hello @Nutgangza2 ,

we checked our emails, and we haven't received the email. 

Could you please provide the project again?

Looking forward to hearing from you, 

Jon

**Comment by Nutgangza2** [comment]
I have sent again can you receive my e-mail?

**Comment by JonathanMagnan** [comment]
That's strange, we normally don't have any problem receiving any email

However, we will make a release tomorrow which will likely fix this issue. So might be better to wait and see first if we fixed it correctly.

**Comment by JonathanMagnan** [comment]
Hello @Nutgangza2 ,

The v3.2.4 has been released. Could you try it and let us know if your issue has been fixed?

Best Regards,

Jon

**Comment by Nutgangza2** [comment]
I already test and it's work! Thank you ^^
