### ISSUE TITLE
BulkMerge doesn't include PK from Derived class

### ISSUE THREAD

**Issue by MisterOzzy** [zzzprojects/EntityFramework-Extensions#426]
Hi guys, I found a bug. I have Base and Derived classes.

```
public abstract class Base
 {
        public string B1 { get; set; }
        public string B2 { get; set; }
        public string B3 { get; set; }
 }
 public class Derived: Base
 {
        public Guid D1 { get; set; }
 }
```

I configured EF model in the following way:
```
 builder.HasKey(x => x.D1);
 builder.Property(x => x.D1).ValueGeneratedOnAdd();
 builder.Property(x => x.B1).HasMaxLength(15);
 builder.Property(x => x.B2).HasMaxLength(15);
 builder.Property(x => x.B3).HasMaxLength(15);
 builder.HasIndex(x => new { x.B1, x.B2, x.B3 }).IsUnique();
```

I call BulkMergeAsync in the following way:
```
await _dbContext.Set<Derived>().BulkMergeAsync(items.Cast<Derived>(),
options =>
{
        options.AutoMapOutputDirection = false;
        options.ColumnPrimaryKeyExpression = entity => new { x.B1, x.B2, x.B3 };
        options.IgnoreOnMergeUpdate = true;
        options.BatchSize = 1500;
        options.BatchTimeout = 300;
        options.RetryCount = 3;
});
```

I get error like 'Npgsql.PostgresException (0x80004005): 23502: null value in column "D1" violates not-null constraint'

And it's logically because if you look at generated query you will figure out that there is no "D1" column presents
```
INSERT INTO "Derived"
("B1", "B2", "B3")
SELECT "B1", "B2", "B3"
FROM (
SELECT * FROM ZZZProjects_58f4fe7b_c700_419d_984c_01ee744c9e39
WHERE ZZZ_Index >= @IndexStart AND ZZZ_Index <= @IndexEnd
) AS StagingTable
WHERE NOT EXISTS (SELECT 1 FROM "Derived" AS DestinationTable WHERE (DestinationTable."B1" =
StagingTable."B1" OR (DestinationTable."B1" IS NULL AND StagingTable."B1" IS NULL)) AND (Desti
nationTable."B2" = StagingTable."B2" OR (DestinationTable."B2" IS NULL AND StagingTable."B2" IS NULL)) AND
(DestinationTable."B3" = StagingTable."B3" OR (DestinationTable."B3" IS NULL AND
```

I added handler for `PostConfiguration` and I realized that `ColumnMapping` for `Derived.D1` has `Direction =
ColumnMappingDirectionType.None` but other column mappings have `ColumnMappingDirectionType.Input`
I made a dirty hack and changed this to `ColumnMappingDirectionType.Input` and it works but it's hack, not pretty code.
Note: in version 3.0.66 I didn't have such a problem. I saw that in 3.0.68 you made a breaking change related to bulk
operations and maybe you changed behavior for creating column mapping. I think It can be the root of the problem.

### Further technical details
- EF version: 5.0.8
- EF Extensions version: 5.2.3
- Database Provider: PostgreSQL

**Comment by MisterOzzy** [comment]
Fixed

**Comment by JonathanMagnan** [comment]
Awesome ;)

Have a good day

Best Regards,

Jon
