### ISSUE TITLE
Type not supported yet (LazyType): xmltype

### ISSUE THREAD

**Issue by aliciadavis** [zzzprojects/EntityFramework-Extensions#434]
### Description
I am trying to perform update from LINQ Query without loading entities in the context. After reading through a previously closed issue :
Type not supported yet: ınt32 #4

I found that temporarily removing the property from the STATUS model below allows the Update function to work. This is a temporary fix as the property for that model is required. 

### Exception
Type not supported yet (LazyType): xmltype

```
return context.Photos.Where(x => x.photoId == id).Update(x => new Photo { default_pic = "Y"});
```

### Code First Model causing error

```
[Table("STATUS")]
public partial class STATUS
{
 [Key]
public int Id { get; set; }

[Column(TypeName = "xmltype")]
[Required]
public string Status_Check { get; set; }
}
```

### Further technical details
- EF version: 6.4.4
- EF Extensions version: 5.2.6
- Database Provider: Oracle

**Comment by JonathanMagnan** [comment]
Hello @aliciadavis ,

Thank you for reporting, we will look to add the support to `xmltype`  before the release next week.

Best Regards,

Jon

**Comment by JonathanMagnan** [comment]
Hello @aliciadavis ,

Sorry for the delay, we missed it for last week's release.

Could you try the v5.2.8 and let us know if we fixed it correctly?

Best Regards,

Jon
