### ISSUE TITLE
EF Extensions BulkDelete method EntryState issue

### ISSUE THREAD

**Issue by shahinjabbar** [zzzprojects/EntityFramework-Extensions#435]
I was using classic EF to delete entities and detaching entity before calling SaveChanges method. I switched to EF extensions and now it is not working. I know that it doesn't use ChangeTracker for performance. My entity has some relations with other tables. Example code EF : 
 
       `_dbContext.Entry(this).State = EntityState.Detached;
       /// some remove logic 
       _dbContext.SaveChanges();
       /// further remove logic( remove related entities from other tables )`

New code EF extensions :

       ` _dbContext.Entry(this).State = EntityState.Detached;
       ///some remove logic 
       _dbContext.BulkDelete(entities, opt => opt.AllowConcurrency = false);
       /// further remove logic( remove related entities from other tables )`

I should detach entity for further remove logic but in my case I am getting an exception **The MERGE statement conflicted with the REFERENCE constraint "FK_XXX.** I am not getting any exception with old EF code and after SaveChanges method I can go on and trig "further remove logic" which is basically is stored procedure. How I can make it work with EF Extensions BulkDelete method? Thanks!

**Comment by JonathanMagnan** [comment]
Hello @shahinjabbar ,

Since our last conversation, we haven't heard from you!

As mentioned, our library cannot delete FK automatically, you need to specify explicitly the delete order.

Let us know if you used `BulkSaveChanges` instead of `SaveChanges` .

Looking forward to hearing from you,

Jon

**Comment by JonathanMagnan** [comment]
Hello @shahinjabbar,

A simple reminder that we are here to assist you. 

Could you let us know if you used BulkSaveChanges instead of SaveChanges?

Don't hesitate to contact us if you have any questions. 

Best regards, 

Jon

**Comment by JonathanMagnan** [comment]
Hello again, 

Dont hesitate to contact us if your issue is not resolved. 

Please let us know if you have any questions. 

Best regards,

Jon
