### ISSUE TITLE
BulkInsertAsync rounding 100 to 99.99.

### ISSUE THREAD

**Issue by hgc10120** [zzzprojects/EntityFramework-Extensions#437]
### Description
Describe the issue or proposed feature.
Hi guys, I have a very weird issue, for which I've been struggling to identity the root cause. I'm using the bulk insert operation to insert data in a MYSQL database. Everything runs fine, without any errors, but when I quality check the results, I find that values that were 100 are rounded to 99.99 in some cases. Initially, I thought that it was a coding error on my part so I checked my code, added some break line prior to reaching the bulk insert operation to see if the value was being switched beforehand but that isn't the case. It seems to happen during the bulk insert operation. To further confirm, I removed the entity framework extensions package and use the entity framework core add range and save changes methods instead and the values are correctly inserted in the database then.

### Exception
If you are seeing an exception, include the full exceptions details (message and stack trace).
No exception.
```
Exception message:
Stack trace:
No stack trace.
```

### Fiddle or Project (Optional)
If you are able, 
Unable to do so.
Provide a Fiddle that reproduces the issue: https://dotnetfiddle.net/Uqe9sf

Or provide a project/solution that we can run to reproduce the issue.
- Make sure the project compile
- Make sure to provide only the code that is required to reproduce the issue, not the whole project
- You can send private code here: info@zzzprojects.com

Otherwise, make sure to include as much information as possible to help our team to reproduce the issue.
It could be related to a casting issue. The values that are being inserted in the MYSQL database are of double types, where as the database properties are of decimal(8,2) type.
_Note: More information you provide, faster we can implement a solution._

### Further technical details
- EF version:
- 5.0
- EF Extensions version:
- 5.28
- Database Provider:
- MySql

**Comment by JonathanMagnan** [comment]
Hello @hgc10120 ,

Thank you for reporting, this issue looks indeed very strange.

I will ask my developer to try it., I will let you know if we have a problem reproducing it.

Best Regards,

Jon

**Comment by JonathanMagnan** [comment]
Hello @hgc10120 ,

My developer did a few tests but cannot reproduce it.

In fact, we are not really sure of this part of your sentence `in some cases` as we don't know those cases.

Is it possible to provide a runnable project with this issue? That will sure help us to discover what is happening.

Here is one of the test my developer did:

```csharp
using Microsoft.EntityFrameworkCore;
using MySqlConnector;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Text;

namespace Lab.EFCore50.MySqlPomelo
{
	class Request_BulkInsert100To99
	{
		public static void Execute()
		{
			// Create BD 
			using (var context = new EntityContext())
			{
				context.Database.EnsureDeleted();
				context.Database.EnsureCreated();
			}

			// CLEAN  
			using (var context = new EntityContext())
			{
				context.EntitySimples.RemoveRange(context.EntitySimples);

				context.SaveChanges();
			}

			// TEST  
			using (var context = new EntityContext())
			{
				List<EntitySimple> list = new List<EntitySimple>();
				list.Add(new EntitySimple { ColumnDouble = 100 });
				list.Add(new EntitySimple { ColumnDouble = 100 });
				list.Add(new EntitySimple { ColumnDouble = 100 });

				context.BulkInsert(list);

				var listToCheck = context.EntitySimples.ToList();
			}

			// TEST  
			using (var context = new EntityContext())
			{
				List<EntitySimple> list = new List<EntitySimple>();

				for (int i = 0; i < 100; i++)
				{
					list.Add(new EntitySimple { ColumnDouble = 100 });
				}

				context.BulkInsert(list);

				var listToCheck = context.EntitySimples.ToList();
				var listToCheckNot100 = context.EntitySimples.Where(x => x.ColumnDouble != 100).ToList();
			}
		}

		public class EntityContext : DbContext
		{
			public EntityContext()
			{
			}

			public DbSet<EntitySimple> EntitySimples { get; set; }

			protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
			{
				optionsBuilder.UseMySql(new MySqlConnection(My.Connection), new MySqlServerVersion(new Version(5, 7, 19)));

				base.OnConfiguring(optionsBuilder);
			}
		}

		public class EntitySimple
		{
			public int ID { get; set; }
			[Column("ColumnDouble", TypeName = "decimal(8,2)")]
			public Double ColumnDouble { get; set; }
			public string ColumnString { get; set; }
		}
	}
}
```

Best Regards,

Jon

**Comment by hgc10120** [comment]
Hi Jon,

Thanks for getting back to me so quickly and sorry for the delayed response. I spent most of today trying to identify a pattern for the cases, which the rounding happens but it's been unsuccessful so far. It seems to be happening randomly. Some 100 values are correctly inserted in the database, whereas some other ones don't. I'll see if I can provide a running project tomorrow to help with the debugging. My code looks very similar to that of your developer with the exception that I'm using the bulk async method and mysql server version 8. I'm not sure if either one of those things will help. 

Best,

**Comment by JonathanMagnan** [comment]
Hello @hgc10120 ,

Since our last conversation, we haven't heard from you. 

Did you get the chance to create a running project for us to be able to solve your issue?

Don't hesitate to contact us if you have any questions. 

Best regards, 

Jon

**Comment by hgc10120** [comment]
Hey,

Sorry for the lack of response. At this point, after researching, we believe that the issue might be related to the buffer size of our my sql server. I’ll be doing some additional testing on that front this week and will know more about that then. 

Thanks for reaching out.

**Comment by JonathanMagnan** [comment]
Hello @hgc10120 ,

Since we haven't heard back, we will close this issue. 

Feel free to contact us once you can provide more information. 

Best regards,

Jon
