### ISSUE TITLE
Z.EntityFramework.Extensions with ASP.Net Core

### ISSUE THREAD

**Issue by guan919** [zzzprojects/EntityFramework-Extensions#44]
I was Installed Z.EntityFramework.Extensions.EFCore -Pre

 Install-Package Z.EntityFramework.Extensions.EFCore -Pre

bulkUpdate is fine but bulkInsert is not working

`

 List<VehicleStockLot> lvs = new List<VehicleStockLot>();

            for (var i = 0; i < 100; i++)
            {
                VehicleStockLot vs = new VehicleStockLot();
                vs.lotNumber = i.ToString();
                vs.status = 1;
                vs.finishCount = 0;
                vs.totalCount = 100;
                vs.vehicleSupplierId = 8 + i;
                vs.vehicleSupplierId = 1;
                vs.addTime = DateTime.Now;
                lvs.Add(vs);
            }
            _ctx.BulkInsert(lvs);
`

**Comment by JonathanMagnan** [comment]
Hello @guan919 ,

Could you report the error message?

On our side, this kind of example is working very fine. In addition, let us know the EF Core version used.

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment]
Hello @guan919 ,

We will close this issue since we received no answer.

Please reopen it if you can add some information.

Best Regards,

Jonathan
