### ISSUE TITLE
BulkInsert with ComputedColumn throws ArgumentException

### ISSUE THREAD

**Issue by cspitzwieser** [zzzprojects/EntityFramework-Extensions#444]
### Description
We're having a problem using BulkInsert on a Table containing a ComputedColumn-Property (`ComputedName`).
Whenever BulkInsert tries to insert the Table in question, an ArgumentException is thrown.:

`ArgumentException: Expression must be writeable (Parameter 'left')`

We have already tried to use `IgnoreOnInsertNames `and `ForceSelectOutput`, like it has been suggested in a similar ticket, but unfortunately we have had no success so far.

```
await targetDbContext.BulkInsertAsync(entities, o => 
{ 
  o.IncludeGraph = true;
  o.IncludeGraphOperationBuilder = operation =>
  {
      if (operation is BulkOperation<Person> bulk)
      {
          bulk.IgnoreOnInsertNames = new List<string>() { "ComputedName" };
          bulk.ForceSelectOutput = true;
      }
  };
 }).ConfigureAwait(false);
```
After removing the ComputedColumn from the Entity, BulkInsert works fine again.

I should also mention, that the ComputedName has a private Setter, and we would ideally like to keep it that way, but when changing it to public, BulkInsert also works fine. ^^

### Further technical details
- EF version: 2.2.6
- EF Extensions.EFCore version: 2.7.83.0
- Database Provider: SQL Server

**Comment by JonathanMagnan** [comment]
Hello @cspitzwieser ,

We are still looking for the original issue but since the v2.12.17, you can use the following options to ignore some columns to output: `IgnoreColumnOutputExpression` and `IgnoreColumnOutputNames`

I know you currently use a generic class but perhaps the column to ignore is the same which will let you use the `IgnoreColumnOutputNames` option.

**Comment by JonathanMagnan** [comment]
Hello @cspitzwieser ,

The v2.13.1 has been released.

The original problem should now be fixed.

Could you try the latest version and let us know if everything is now working fine?

Best Regards,

Jon
