### ISSUE TITLE
Type not supported yet (LazyType): uint

### ISSUE THREAD

**Issue by 007gzs** [zzzprojects/EntityFramework-Extensions#45]
table is 

> CREATE TABLE `ly_itemcode` (
  `id` int(11) unsigned NOT NULL,
  `xxx` int(11) unsigned NOT NULL,
  PRIMARY KEY (`id`),
) ENGINE=InnoDB DEFAULT CHARSET=utf8

**Comment by JonathanMagnan** [comment]
Hello @007gzs ,

For my knowledge, Entity Framework doesn't support LazyType at all?

By example, using the following code, Entity Framework will skip the `LazyColumnInt` property

```csharp
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Windows.Forms;

namespace Z.EntityFramework.Extensions.Lab
{
    public partial class Form_Request_LazyType : Form
    {
        public Form_Request_LazyType()
        {
            InitializeComponent();

            // CLEAN
            using (var ctx = new CurrentContext())
            {
                ctx.Parents.RemoveRange(ctx.Parents);
                ctx.SaveChanges();
            }

            // SEED

            // TEST
            using (var ctx = new CurrentContext())
            {
                var list = new List<Parent>();
                for (var i = 0; i < 10; i++)
                {
                    var i2 = i;
                    list.Add(new Parent { ID = 1 + i * 3, ColumnInt = i, LazyColumnInt = new Lazy<int>(() => i2)});
                }

                ctx.Parents.AddRange(list);
                ctx.SaveChanges();
            }
        }

        public class CurrentContext : DbContext
        {
            public CurrentContext()
                : base("CodeFirstEntities")
            {
            }

            public DbSet<Parent> Parents { get; set; }


            protected override void OnModelCreating(DbModelBuilder modelBuilder)
            {
                modelBuilder.Types().Configure(x => x.ToTable(GetType().DeclaringType != null ? GetType().DeclaringType.FullName.Replace(".", "_") + "_" + x.ClrType.Name : ""));

                base.OnModelCreating(modelBuilder);
            }
        }

        public class Parent
        {
            public int ID { get; set; }
            public int ColumnInt { get; set; }
            public Lazy<int> LazyColumnInt { get; set; }
        }
    }
}
```

Do you think you could provide us a working example using `SaveChanges` to let us investigate this issue?

Best Regards,

Jonathan

**Comment by serifreedom** [comment]
![zzz](https://user-images.githubusercontent.com/1667960/28927312-7108bf44-7894-11e7-9cb2-21211b3d7c3b.png)

It's not problem in method _SaveChanges(Tested work fine)_ , which is default DbContext method.
It's error in "**BulkInsert**" extension method while using EntityFramwork + your EntityFramework-Extensions + MySql, Database First Models on Table

> CREATE TABLE `sales` (
>   **`entity_id` int(11) NOT NULL AUTO_INCREMENT,**
>   `type` varchar(32) DEFAULT NULL,
>   `account` varchar(32) CHARACTER SET latin1 DEFAULT NULL,
>   `pay_date` date DEFAULT NULL,
>   `merch_number` varchar(32) DEFAULT NULL,
>   `order_sl` varchar(50) DEFAULT NULL,
>   `trans_code` varchar(32) DEFAULT NULL,
>   `trans_date` date DEFAULT NULL,
>   `amount` decimal(12,2) DEFAULT NULL,
>   `store_name` varchar(255) DEFAULT NULL,
>   `shot_code` varchar(32) DEFAULT NULL,
>   `gold_code` varchar(24) DEFAULT NULL,
>   `batch_export` varchar(24) DEFAULT NULL,
>   PRIMARY KEY (`entity_id`),
>   UNIQUE KEY `entity_id_UNIQUE` (`entity_id`),
>   KEY `IDX_SALES_ORDER_SL` (`order_sl`)
> ) ENGINE=InnoDB AUTO_INCREMENT=0 DEFAULT CHARSET=utf8

I guess the error because  it's miss match datatype `entity_id` int(11) between EF-Ex and MySql

Please Help ASAP!.

**Comment by JonathanMagnan** [comment]
Hello @serifreedom ,

Thank you, we misread this issue the first time.

We will investigate this issue today and probably release a fix this night.

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment]
Hello @007gzs , @serifreedom ,

The v3.12.16 has been released.
https://www.nuget.org/packages/Z.EntityFramework.Extensions/

We added the support to column type `uint`. As Entity Framework do, we bind it to type `long`

Let me know if the new version has fixed this issue on your side.

Best Regards,

Jonathan

**Comment by serifreedom** [comment]
@JonathanMagnan , Unfortunately, It's still error! but with another type! or did i do anything wrong?
```
CREATE TABLE `sales_interface_order_tmp3` (
  `entity_id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `type` varchar(32) DEFAULT NULL,
  `bank_account` varchar(32) CHARACTER SET latin1 DEFAULT NULL,
  `mer_number` varchar(32) DEFAULT NULL,
  `order_sl` varchar(50) DEFAULT NULL,
  `trans_code` varchar(32) DEFAULT NULL,
  `store_name` varchar(255) DEFAULT NULL,
  `shot_code` varchar(32) DEFAULT NULL,
  `gold_code` varchar(24) DEFAULT NULL,
  `batch` varchar(24) DEFAULT NULL,
  PRIMARY KEY (`entity_id`),
  KEY `IDX_SALES_INTERFACE_ORDER_TMP3_ORDER_SL` (`shopee_order_sl`)
) ENGINE=InnoDB AUTO_INCREMENT=0 DEFAULT CHARSET=utf8
```
![zzz2](https://user-images.githubusercontent.com/1667960/28992829-4dd327ba-79d1-11e7-98c6-7e7199e3549f.png)

Thank you.

**Comment by JonathanMagnan** [comment]
Hello @serifreedom ,

Thank you, we made sure this time all unsigned type is supported!

The v3.12.16 has been released.
https://www.nuget.org/packages/Z.EntityFramework.Extensions/

Let me know if all type issue is fixed.

Best Regards,

Jonathan

**Comment by serifreedom** [comment]
@JonathanMagnan ,Thank  you for quick release. But!
Again...,What is this error? not data type mapping anymore,Now I guess EF-Ex confusing connection between MS SQL and MySQL, I'm using both Db server in  the same project with separate connections/DbContext/Models.

![zzz3](https://user-images.githubusercontent.com/1667960/29032673-7a103128-7bbc-11e7-8680-a417a110f31a.png)

Any Idea?

**Comment by JonathanMagnan** [comment]
Hello @serifreedom ,

I just tried in a project (MySQL + SQL Server) and it works fine on my side.

Do you believe you could create a project that has this error and send it to us (info@zzzprojects.com)? Or give us a hint to reproduce it.

Best Regards,

Jonathan

**Comment by serifreedom** [comment]
I will try create project for you to reproduce error later, What's different between default `SaveChanges` and `BulkInsert`? `SaveChanges ` always complete!, It's the same Dbcontext/Connection. Is EF-Ex require any special/full permission to Db?
FYI,exception thrown access denied for 'user@[my LAN ip]' instead of [server ip] from connection string!?

**Comment by JonathanMagnan** [comment]
Hello @serifreedom ,

I'm not sure yet was is causing this issue since we cannot reproduce it. I believe it may be caused by something we cache in the library and the unique key (with the context added) is the same for both context.

I believe it will be very easy to find once we receive the project.

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment]
Hello @serifreedom ,

Did you succeed to create the project?

Best Regards,

Jonathan

**Comment by serifreedom** [comment]
Hello @JonathanMagnan,
Found the problem, No need sample project. Like I have asked you before, EF-Ex required ALL PRIVILEGES permission on Database for LOCK TABLES, if use BulkInsert :

`LOCK TABLES TableA WRITE, TableA AS DestinationTable READ;`

But  BulkSaveChanges no need to LOCK TABLES. Wondering why...

I think this issue might be solved.

**Comment by JonathanMagnan** [comment]
Hello @serifreedom ,

I have looked at it today. `BulkSaveChanges` also require `LOCK TABLES` on insert if the table has an identity value.

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment]
Hello @serifreedom ,

Feel free to reopen if you have more question.

Best Regards,

Jonathan
