### ISSUE TITLE
Oops! Unsupported types : ARRAY _text

### ISSUE THREAD

**Issue by Aloento** [zzzprojects/EntityFramework-Extensions#452]
### Description
Do you not support PostgreSQL's Array type?

### Exception
```
      System.Exception: An error occured while retrieving the InformationSchemaTable information. See the inner exception for details.
       ---> System.Exception: Oops! Unsupported types : ARRAY _text
       ---> System.Exception: Oops! Unsupported types : system.collections.generic.dictionary`2[system.string,system.string]
```

### Further technical details
- EF version: EF Core 6
- EF Extensions version: Neweset
- Database Provider: Npgsql

**Comment by Aloento** [comment]
`Oops! The following provider 'Npgsql.NpgsqlConnection is not yet supported by the method DeleteByKey and DeleteRangeByKey. We add provider on demand, so if you wish we support it, report this message to 'info@zzzprojects.com'`

**Comment by JonathanMagnan** [comment]
Hello @Aloento ,

I will ask my developer if that's possible to support it for this feature.

Best Regards,

Jon

**Comment by Aloento** [comment]
I think it should be relatively easy to implement it, and Npgsql already provides full support. 
Thank you very much for considering this important feature!

**Comment by Aloento** [comment]
I will prepare a demo as soon as possible and follow up here.

**Comment by JonathanMagnan** [comment]
Thank you Aloento, 

In the meantime, don't hesitate to contact us if you need further assistance. 

Best regards, 

Jon
