### ISSUE TITLE
EF Core 6.0.1 and EF Extensions 6.13.4 throws TargetException on BulkInsert with in-memory provider

### ISSUE THREAD

**Issue by meinsiedler** [zzzprojects/EntityFramework-Extensions#458]
### Description
After upgrading to EF 6.0.1 and EF Extensions 6.13.4, the `BulkInsert` throws a `TargetException` when using the in-memory provider. The issue is easily reproducible with the simple program below.

### Exception
`System.Reflection.TargetException`: Object does not match target type.

```
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.RuntimePropertyInfo.GetValue(Object obj, BindingFlags invokeAttr, Binder binder, Object[] index, CultureInfo culture)
   at System.Reflection.RuntimePropertyInfo.GetValue(Object obj, Object[] index)
   at .[](IQueryable`1 )
   at DbSetExtensions.BulkInsert[T](DbSet`1 this, IEnumerable`1 entities)
   at Program.<Main>$(String[] args) in ...\Program.cs:line 12
```

### Fiddle or Project (Optional)
```
using Microsoft.EntityFrameworkCore;

using var context = new BookStore();

var books = new List<Book>()
{
    new Book { Id = new Guid("00000000-0000-0000-0000-000000000001"), Title = "Book 1" },
    new Book { Id = new Guid("00000000-0000-0000-0000-000000000002"), Title = "Book 2" },
    new Book { Id = new Guid("00000000-0000-0000-0000-000000000003"), Title = "Book 3" }
};

context.Books.BulkInsert(books);

public class Book
{
    public Guid Id { get; set; }
    public string Title { get; set; }
}

public class BookStore : DbContext
{
    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    {
        optionsBuilder.UseInMemoryDatabase(databaseName: "BookStoreDb");
    }

    public DbSet<Book> Books { get; set; }
}

```

### Side note

Additionally to the above described exception, the NuGet package `Microsoft.EntityFrameworkCore.Relational` must now be added. Otherwise, a `FileNotFoundException` (Could not load file or assembly 'Microsoft.EntityFrameworkCore.Relational, Version=6.0.0.0) is thrown. This behavior has changed to a prior version, where this dependency was not needed when using only the in-memory provider.

### Further technical details
- EF version: `Microsoft.EntityFrameworkCore.InMemory` 6.0.1
- EF Extensions version: `Z.EntityFramework.Extensions.EFCore` 6.13.4
- Database Provider: in-memory

**Comment by JonathanMagnan** [comment]
Hello @meinsiedler ,

Thank you for reporting, we will look at it.

Best Regards,

Jon

**Comment by JonathanMagnan** [comment]
Hello @meinsiedler ,

Is this an issue for you if we add it to our dependencies list?

Our library have a dependency on the `Microsoft.EntityFrameworkCore.Relational` since the beginning but it was not always required as the error is only thrown if something from the DLL (in this case `ITableMapping`) is used in the code execution.

We are afraid that even if we fix this specific case, we will for sure eventually do the same mistake from time to time.

So the easiest/safest way to fix it for us is to simply add this dependency.

Best Regards,

Jon

**Comment by meinsiedler** [comment]
Adding the dependency wouldn't be an issue since we have this dependency in our production code anyway.

I just pointed out the changed behavior as it occurred to us while reproducing the issue in the sample program.

**Comment by meinsiedler** [comment]
Hi @JonathanMagnan,

do you have any update on the above described `System.Reflection.TargetException`?

**Comment by JonathanMagnan** [comment]
We did the mistake last week to forget to add this dependency. It should be released tomorrow

**Comment by JonathanMagnan** [comment]
Hello @meinsiedler ,

The v6.13.6 has been released. We added the right dependency (the relational).

Everything should now be fixed.

If you still have an issue, let us know.

Best Regards,

Jon

**Comment by meinsiedler** [comment]
Hello @JonathanMagnan ,

do you have any update on the reported `TargetException` which still occurs with the latest version 6.13.6?

Thank you!

**Comment by JonathanMagnan** [comment]
Hello @meinsiedler ,

The v6.13.7 has been released which includes the fix for it.

Could you try this latest version and let me know if everything is now working?

Best Regards,

Jon

**Comment by meinsiedler** [comment]
Hello @JonathanMagnan ,

everything is working as expected now. Thank you for your efforts!
