### ISSUE TITLE
BulkMerge triggers EF events with incorrect state

### ISSUE THREAD

**Issue by oresttkachukd** [zzzprojects/EntityFramework-Extensions#459]
### Description
BulkMergeAsync with IncludeGraph option enabled triggers ChangeTracker.Tracked and ChangeTracker.StateChanged EF events with  State set to Added for each entity, even in case they were updated.

As an option I tried to add AutoDetectChangesEnabled set false/AsNoTracking in the get query that is run before the update, but it did not help. It seems that tracking was called manually inside of this method. 

Stack Trace: 
`at Microsoft.EntityFrameworkCore.DbContext.AddRange(IEnumerable`1 entities)
   at Z.EntityFramework.Extensions.EntityFrameworkManager.(DbContext , BulkOperation , IEnumerable`1 )
   at .BulkMerge[T](DbContext this, IEntityType entityType, IEnumerable`1 list, Action`1 options, SavingSelector savingSelector, Boolean forceSpecificTypeMapping)
   at .BulkMerge[T](DbContext this, IEnumerable`1 entities, Action`1 options, Boolean isBulkSaveChanges)
   at DbContextExtensions.BulkMerge[T](DbContext this, IEnumerable`1 entities, Action`1 options)
`

I'm aware that some libraries allow configuring TrackingEntities property, so we can control such behavior. 
Also I found an issue where opposite behavior described in: https://github.com/zzzprojects/EntityFramework-Extensions/issues/391

Could you please share what is the expected behaviour there? Would it be possible to add additional option to control it?

### Further technical details
- EF version: 3.1.13 (Core)
- EF Extensions version: 3.13.5
- Database Provider: SQL Server

**Comment by JonathanMagnan** [comment]
Hello @oresttkachukd ,

The `IncludeGraph` option indeed call the `AddRange` from the context returned by the [ContextFactory](https://entityframework-extensions.net/context-factory).

Even if there are in added state, we later know if we should `insert`, `update`, or `merge` those entities.

Unfortunately, at this moment there is no workaround to this.

Best Regards,

Jon
