### ISSUE TITLE
DeleteFromQuery on Oracle and DevArt

### ISSUE THREAD

**Issue by rhgs** [zzzprojects/EntityFramework-Extensions#46]
Hi!

I'm trying to use DeleteFromQuery with Oracle and DevArt, but the exception is thrown.
I understand this occurred because the schema is not included in SQL command.
It's is possible to include?

Thanks

**Comment by JonathanMagnan** [comment]
Hello @rhgs ,

Thank you for letting us know.

Oracle is not yet supported for `DeleteFromQuery`, we will add the support today.

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment]
Hello @rhgs ,

The v3.12.19 has been released ([Release Note](https://github.com/zzzprojects/EntityFramework-Extensions/releases/tag/v3.12.19))

`DeleteFromQuery` and `UpdateFromQuery` should now work with Oracle DevArt.

Let me know if this new version has fixed your issue.

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment]
Hello @rhgs ,

Did you success to check if these features were working correctly for your cases?

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment]
Closing comment: Fix added
