### ISSUE TITLE
BulkInsert 60x slower than BulkSaveChanges

### ISSUE THREAD

**Issue by Bouke** [zzzprojects/EntityFramework-Extensions#462]
### Description
I have a model like this:

```c#
public class Entity
{
    public Guid Id { get; set; }

    public string OtherId { get; set; }

    public string Name { get; set; }

    public string[] Aliases { get; set; }

    internal class Configuration : IEntityTypeConfiguration<Entity>
    {
        public void Configure(EntityTypeBuilder<Entity> builder)
        {
            builder.HasKey(x => x.Id);

            builder.HasIndex(x => x.OtherId).IsUnique();
            builder.Property(x => x.OtherId).IsRequired();

            builder.HasIndex(x => x.Name);
            builder.Property(x => x.Name).IsRequired();

            builder.Property(x => x.Aliases)
                   .HasColumnType("jsonb");
        }
    }
}
```

I'm inserting around 250k items in an empty table (following a TRUNCATE). Using `BulkInsert` it takes approx 2 minutes. `BulkSaveChanges` around 2 seconds. The Npgsql logs print the following, with the 2 minutes being taken up by "Start user action".

> DEBUG [4478] Starting binary import
TRACE [4478] Start user action
DEBUG [4478] COPY operation ended
TRACE [4478] End user action
TRACE [4478] Closing connection...
DEBUG [4478] Connection closed

`BulkInsert` is supposed to be faster than `BulkSaveChanges`, however I'm seeing a 60x performance decrease.

### Fiddle or Project (Optional)
```
            context.Entities.BulkInsert(entities,
                                               x =>
                                               {
                                                   x.AutoMapOutputDirection = false;
                                                   x.InsertKeepIdentity = true;
                                               });
```

### Further technical details
- EF version: 3.1.12
- EF Extensions version: 3.13.7
- Database Provider: Npgsql 4.1.9, Npgsql.EntityFrameworkCore.PostgreSQL 3.1.18

**Comment by Bouke** [comment]
Ah nevermind, I got the baseline wrong. I was doing a TRUNCATE in the case of BulkInsert, whereas with BulkSaveChanges I used the change tracker.

**Comment by JonathanMagnan** [comment]
Hello Bouke, 

No problem, don't hesitate to contact us if you need help with anything. 

Best regards, 

Jon
