### ISSUE TITLE
ORA-00932: inconsistent datatypes: expected - got CLOB when process UpdateFromQuery

### ISSUE THREAD

**Issue by aaa646123** [zzzprojects/EntityFramework-Extensions#464]
### Description
I have a table that contains CLOB field.
I found it would occur error when I execute script below.

```c#
Var updateAddress = DbContext.MyTable(x=>x.Name == "Test").Select(s=>s.Address).FirstOrDefalt(); //search result was null

DbContext.MyTable.Where(x=>x.Address== updateAddress ).UpdateFromQuery(x=>new MyTable{ STATUS = "0" }); // it would occur error

DbContext.MyTable.Where(x=>x.Address == null).UpdateFromQuery(x=>new MyTable{ STATUS = "0" }); // it works fine

```
Here are my model.
```c#
[Table("MyTable")]
public partial class MyTable
{
   [Key]
    [Column(Order = 0)]
    public string NAME{ get; set; }
    
    public string ADDRESS{ get; set; }

    public string STATUS { get; set; }

    public string LOCATION { get; set; } // CLOB In Oracle
}
```

### Exception
```
Exception message: ORA-00932: inconsistent datatypes: expected - got CLOB 
Stack trace:
```

### Further technical details
- EF version: EntityFramework 6.0.0.0
- EF Extensions version: Z.EntityFramework.Extensions 6.13.6
- Database Provider: Oracle

**Comment by JonathanMagnan** [comment]
Hello @aaa646123 ,

Thank you for reporting.

We will look at this.

Best Regards,

Jon

**Comment by JonathanMagnan** [comment]
Hello @aaa646123 ,

Do this simple LINQ that doesn't use our library work on your side?

```csharp
var list1 = DbContext.MyTable.Where(x=>x.Address== updateAddress).ToList();
```

My developer tried some scenarios:

- Whenever this LINQ  was falling, the `UpdateFromQuery` in your example was not also working
- Whenever this LINQ was working (by modifying column type in the database), the `UpdateFromQuery` was also working

Under the hood, our library uses the same parameter at this LINQ, so we have the same limitations as Entity Framework.

Let me know if you get different behavior on your side.

Best Regards,

Jon

**Comment by aaa646123** [comment]
Hi @JonathanMagnan 

I try the code as below, it won't occur exception.

Var nullAddress = DbContext.MyTable(x=>x.Name == "Test").Select(s=>s.Address).FirstOrDefalt(); //search result was null

DbContext.MyTable.Where(x=>x.Address== updateAddress ).ToList(x=>x.STATUS = "0");

DbContext.SaveChanges(); // Although it won't update any record but it won't occur exception, either.

DbContext.MyTable.Where(x=>x.Address== updateAddress ).UpdateFromQuery(x=>new MyTable{ STATUS = "0" }); //it would occur error.

**Comment by JonathanMagnan** [comment]
Hello @aaa646123 ,

Do you think you could provide a runnable project with the table creation? It doesn’t need to be your project, just a new solution with the minimum code to reproduce the issue. You can send it in private here: info@zzzprojects.com

It will be easier for my developer as we currently don't get the same behavior as you.

It currently either both fails (`ToList` and `UpdateFromQuery`) or both works depending on how we change things but not one work and one fail

Best Regards,

Jon

**Comment by aaa646123** [comment]
Hi @JonathanMagnan 

I already send you a project to reproduce the issue.

Please check, thanks.
