### ISSUE TITLE
Support Microsoft.Data.SqlClient for EF 6

### ISSUE THREAD

**Issue by ErikEJ** [zzzprojects/EntityFramework-Extensions#467]
I have published an EF6 provider that uses Microsoft.Data.SqlClient iso System.Data.SqlClient.

This causes some issues, see https://github.com/ErikEJ/EntityFramework6PowerTools/issues/82#issuecomment-1028462408

**Comment by JonathanMagnan** [comment]
Thank you @ErikEJ for reporting.

We will look at your fork and see what we can do.

Best Regards,

Jon

**Comment by eolamisan** [comment]
We are getting the message: 
> Oops! Only SQL Server is currently supported for BatchSaveChanges. More provider is coming soon.

If it is important the Environment is
- Azure SQL Server and LocalDb and SQL Server
- EF 6.4, .Net Framework 4.8
- EntityFrameworkExtensions 5.1.2 

Would any other information be help?

**Comment by JonathanMagnan** [comment]
Hello @eolamisan , is this for the same issue as @ErikEJ ?

If yes, I don't think we need more information. We just need to create another version of our library compatible with the one released by @ErikEJ .

Best Regards,

Jon

**Comment by eolamisan** [comment]
> Hello @eolamisan , is this for the same issue as @ErikEJ ?
> 
> If yes, I don't think we need more information. We just need to create another version of our library compatible with the one released by @ErikEJ .
> 
> Best Regards,
> 
> Jon

Yes, it is the same issue.

**Comment by eolamisan** [comment]
Hello @JonathanMagnan ,

Any updates on this issue?

Best,
Ed

**Comment by JonathanMagnan** [comment]
Hello @eolamisan ,

Unfortunately, it was harder than we thought when we tried due to some hardcoded references to `System.Data.SqlClient`.

We never expected EF6 to be compatible with `Microsoft.Data.SqlClient` when we created our code.

Unless the `ErikEJ.EntityFramework.SqlServer` package start to be really used/recommended, I do not believe it will happen as we already passed a few days trying to support it but we have to postpone it due to some most important development in `EF Core` for us.

**Comment by ktand** [comment]
We're also having the same problem and would very much appreciate a solution!

**Comment by peterno** [comment]
We would really need a solution to this problem.

We are using SqlServer in Azure, Always Encrypted and Z.EntityFramwork in many places in our .net 4.8 code, for e.g. Filter, IncludeFilter, BatchSaveChanges, UpdateFromQueryAsync and DeleteFromQueryAsync.

As a company that have invested heavily in .net 4.8 and EF6 the only path for us is to migrate to multi targeting projects and migrate step by step to .net 6. But we need to have EF6 working for a long time as we see it.

We see the ErikEJ.EntityFramework.SqlServer package as a way to bridge the EF6 with Always Encrypted migration but we also need Z.EntityFramwork to get the performance benefits of that library.

Any update would be really appreciated.

**Comment by JonathanMagnan** [comment]
Hello @ktand , @peterno ,

I cannot guarantee yet anything but we re-opened the issue as it looks like more people than we thought are using it.

At this moment we hope to release a version next week but with some features that will not work for this provider:

- BatchSaveChanges (However `BulkSaveChanges work fine)
- DeleteByKey
- DeleteRangeByKey
- Spatial Type (We will try to fix this one)
- Other? We will see soon

That's probably the only trade-off we can do to with the time we currently have

**Comment by ErikEJ** [comment]
@JonathanMagnan Known issues with the provider are listed here: https://github.com/ErikEJ/EntityFramework6PowerTools/tree/community/src/ErikEJ.EntityFramework.SqlServer#known-issues

Let me know if I can help in any way.

**Comment by JonathanMagnan** [comment]
Great to hear! 

Don't hesitate to contact us if you need further assistance. 

Best regards, 

Jon
