### ISSUE TITLE
Owned entities with Unique Index throws exception

### ISSUE THREAD

**Issue by virzak** [zzzprojects/EntityFramework-Extensions#469]
### Description
Owned entity with a unique index works (with a workaround) in EF Core. See https://github.com/dotnet/efcore/issues/11336

However it throws with EntityFramework-Extensions

### Exception
If you are seeing an exception, include the full exceptions details (message and stack trace).

```
System.Exception
  HResult=0x80131500
  Message=One of your column have a destination mapped more than once. See the inner exception for details.
  Source=Z.EntityFramework.Extensions.EFCore
  StackTrace:
   at Z.BulkOperations.BulkOperation.()
   at Z.BulkOperations.BulkOperation.Execute()
   at Z.BulkOperations.BulkOperation.BulkInsert()
   at .BulkInsert[T](DbContext this, IEntityType entityType, IEnumerable`1 list, Action`1 options, SavingSelector savingSelector, Boolean forceSpecificTypeMapping)
   at .BulkInsert[T](DbContext this, IEnumerable`1 entities, Action`1 options, Boolean isBulkSaveChanges)
   at DbContextExtensions.BulkInsert[T](DbContext this, IEnumerable`1 entities, Action`1 options)
   at DbContextExtensions.BulkInsert[T](DbContext this, IEnumerable`1 entities)
   at Program.<Main>$(String[] args) in Q:\Code\Sandbox\OwnedEntityWithUniqueIndex\OwnedEntityWithUniqueIndex\Program.cs:line 26

  This exception was originally thrown at this call stack:
    Z.BulkOperations.BulkOperation.()

Inner Exception 1:
Exception: The following destination column is mapped more than once: 'ParentId'.
```

### Project
This [commit](https://github.com/virzak/EntityFramework-Extensions-469/commit/182eb190cf09c2a4b84e547b0c5db0c6e9f8832f) throws an exception

### Further technical details
- EF version: 6
- EF Extensions version: 6.13.9
- Database Provider: SqlServer

**Comment by JonathanMagnan** [comment]
Hello @virzak ,

The v6.13.10 has been released.

Could you try it and let us know if everything is working with the latest release?

Best Regards,

Jon

**Comment by virzak** [comment]
@JonathanMagnan thanks, it passes, but `UpdateFromQuery` it also an issue.

Here is a breaking commit:

https://github.com/virzak/EntityFramework-Extensions-469/commit/0580263c37557d86b5c52f5be9cded798525fe79

**Comment by virzak** [comment]
`DeleteFromQuery` seems to work just fine.

**Comment by JonathanMagnan** [comment]
Great to hear! 

Don't hesitate to contact us if you need anything.

Best regards, 

Jon

**Comment by virzak** [comment]
@JonathanMagnan, sorry, `UpdateFromQuery` is still not working.

**Comment by virzak** [comment]
@JonathanMagnan, would be great if you could look into it. I also believe that `InsertFromQuery` crashes in this scenario.

**Comment by JonathanMagnan** [comment]
Thank for reporting,

My developer pushed a fix early this week, I should be able to review it Friday and check if the `InsertFromQuery` would be fixed at the same time.

**Comment by virzak** [comment]
@JonathanMagnan Thanks so much for the update.

**Comment by JonathanMagnan** [comment]
Hello @virzak ,

As promised, since we're not able to complete the full fix, we added an option that will work with this scenario:

```csharp
EntityFrameworkManager.TmpUseDistinctTableLogic = true;
```

This option is temporary and will be removed as soon as my developer provides a complete fix (I will give you an update when it happens).

**Comment by virzak** [comment]
Thank you, @JonathanMagnan
