### ISSUE TITLE
BulkMerge breaking change #421 Follow-up

### ISSUE THREAD

**Issue by david-garcia-garcia** [zzzprojects/EntityFramework-Extensions#470]
### Description
In version 4.0.82 (from nuget) a regression/behaviour change was introduced where MERGE will not output keys if nothing has been merged.

I incorretly diagnosed this as something else in #421, I have now prepared a reproducible test case project:

https://github.com/david-garcia-garcia/zzzbrokenmerge

To run the tests make sure to properly adjust both the license and the connection string.

The test passes in 4.0.81 but fails in 4.0.82. (And last release also fails)

### Fiddle or Project (Optional)
https://github.com/david-garcia-garcia/zzzbrokenmerge

### Further technical details
- EF version: 6.4.4
- EF Extensions version: 4.0.82
- Database Provider: System.Data.SqlClient

**Comment by JonathanMagnan** [comment]
Hello @david-garcia-garcia ,

Thank you for reporting, we will look at it.

Best Regards,

Jon

**Comment by david-garcia-garcia** [comment]
Setting the option ` op.ForceOutputFromUnmodifiedRow = true` does restore the previous default behaviour. I guess this was changed for performance reasons.

**Comment by david-garcia-garcia** [comment]
Looks like the change was introduced here:

https://github.com/zzzprojects/EntityFramework-Extensions/issues/393#issuecomment-783918558

But this is a breaking change...
