### ISSUE TITLE
BatchSaveChanges throws DbUpdateException instead of removing entity that eagerly loads related entities

### ISSUE THREAD

**Issue by pierluca** [zzzprojects/EntityFramework-Extensions#471]
### Description
In a given scenario, detailed below, `BatchSaveChanges` generates a `DbUpdateException` due to a `PRIMARY KEY` violation, whereas both `SaveChanges` and `BulkSaveChanges` would work.

Scenario:
1. Create a database with an entity (key=1) and 2 related entities
2. Load (eagerly) all at the same time ( `ctx.MyEntities.Include(e=> e.MySubEntities).First(e => e.Id == 1)`)
3. Remove the entity ( `ctx.MyEntities.Remove` )
4. Add a new entity, with the same key
5. `BatchSaveChanges`

Further information:
- This doesn't break with `ctx.MyEntities.First(e=> e.Id == 1)` instead of eager loading
- This doesn't break if `BatchSaveChanges` were also executed before adding a new entity.

### Generated SQL

```
DELETE [dbo].[MySubEntities]
WHERE ([Id] = @zzz_0)
SELECT @@ROWCOUNT

DELETE [dbo].[MySubEntities]
WHERE ([Id] = @zzz_1)
SELECT @@ROWCOUNT

--
-- This is where we would be expecting a DELETE [dbo].[MyEntities] WHERE ([Id] = @zzz_2)
--

INSERT [dbo].[MyEntities]([Id], [Name])
VALUES (@zzz_2, @zzz_3)

-- @zzz_0: '1' (Type = Int32)
-- @zzz_1: '2' (Type = Int32)
-- @zzz_2: '1' (Type = Int32)
-- @zzz_3: 'MyEntity' (Type = String, Size = -1)
```

### Exception
Clearly, the entity had not been deleted as it was trying to insert a new one, causing a `DbUpdateException` due to a `Violation of PRIMARY KEY constraint` violation.

### Minimal reproduction
The following repository provides a minimal reproduction of the problem 
https://github.com/pierluca/batchsavechanges-bug

### Further technical details
- EF version: 6.4.4
- EF Extensions version: 6.13.12
- Database Provider: SQL Server

**Comment by JonathanMagnan** [comment]
Hello @pierluca 

Thank you for reporting, we will look at it.

Best Regards,

Jon

**Comment by pierluca** [comment]
Hi Jon,

Thank you for your prompt support, it's always much appreciated.
As you can imagine, this is quite blocking 😅 

Yours sincerely,

Pierluca

**Comment by pierluca** [comment]
Hi Jon,

Any news ?

Are we looking at something that could be fixed in a short time frame or do we need to start looking into workarounds?

Thank you.

**Comment by JonathanMagnan** [comment]
Hello @pierluca ,

I will be able to give a better update around next Tuesday.

We probably know now exactly why it happens and where in our code. One of my developers is currently trying to fix it.

Best Regards,

Jon

**Comment by JonathanMagnan** [comment]
Hello @pierluca ,

The fix has been done but it takes A LOT of time (a few days) to run the tests for these changes.

If there are no fails, it should be released next Tuesday.

Best Regards,

Jon

**Comment by pierluca** [comment]
Hi Jon,

Thanks for the update and the hard work on fixing this and ensuring no regressions arise !

Yours sincerely,

Pierluca

**Comment by pierluca** [comment]
Hi @JonathanMagnan ,

Just to clarify: was this issue forgotten from the release notes or did the test results warrant further investigation ? 

If there's anything I can do to help, let me know.

Yours sincerely,

Pierluca

**Comment by JonathanMagnan** [comment]
Hello @pierluca ,

I passed a lot of time this weekend trying to include this one in the last release but unfortunately, we found some cases that failed with the new logic.

I should be able to investigate more tomorrow to better understand what is not working.

Best Regards,

Jon

**Comment by pierluca** [comment]
Hi Jon,

Understood, thank you for your effort !

The release on my customer's side had to go ahead anyways without the switch to `BatchSaveChanges`, thereby (relatively) lowering the urgency of this fix. We do however still very much hope to be able to make the switch in the next release.

Yours sincerely,

Pierluca

**Comment by JonathanMagnan** [comment]
Hello @pierluca ,

The v6.13.6 has been released.

This issue is now fixed. If you find anything strange when upgrading, let us know.

Best Regards,

Jon

**Comment by pierluca** [comment]
Hi Jon,

Thank you !

The customer's going to look into this, run its internal tests and we'll keep you posted in the coming weeks.

Yours sincerely,

Pierluca
