### ISSUE TITLE
UpdateFromQueryAsync throw ArgumentNullException when the update entity has no parameterless constructors

### ISSUE THREAD

**Issue by mHalo** [zzzprojects/EntityFramework-Extensions#478]
### Description
I had a types don't have parameterless constructors, looks like:
```
        public class Customer
	{
		//private Customer(){}
		public Customer(string name){
			Name = name;
		}
		public int CustomerID { get; set; }
		public string Name { get; set; }
		public Boolean IsActive { get; set; }
	}
```
when i update something like 
```
context.Customers.Where(x => x.Name =="Customer_B").Update(x => new{
	Name = "123"
});
```
the exception was throw out

### Exception
```
Unhandled exception. System.ArgumentNullException: Value cannot be null. (Parameter 'constructor')
   at System.Linq.Expressions.Expression.New(ConstructorInfo constructor, IEnumerable`1 arguments)
   at BatchUpdateExtensions.UpdateFromQuery[T](IQueryable`1 query, Expression`1 updateExpression, Action`1 batchUpdateBuilde)
   at Z.EntityFramework.Plus.BatchUpdateExtensions.Update[T](IQueryable`1 query, Expression`1 updateExpression, Action`1 batchUpdateBuilder)
   at Z.EntityFramework.Plus.BatchUpdateExtensions.Update[T](IQueryable`1 query, Expression`1 updateExpression)
   at Program.Main()
```

I can provide a private  parameterless constructors to solve this problem，but i dont know why.
When I research github`s issue ,I found this ->  https://github.com/zzzprojects/EntityFramework-Extensions/issues/401#issuecomment-809696646
in this issue，it seems ok.
```
========================================

This worked great:
await _db.Stories.Where(x => x.Id == @event.SourceId).UpdateFromQueryAsync(x => new
{
    IsComplete = false
});
========================================
```
I reproduced the bug on  https://dotnetfiddle.net/w7hMnb

I use version:
Z.EntityFramework.Plus.EFCore 6.13.15

**Comment by JonathanMagnan** [comment]
Hello @mHalo ,

Unfortunately, this is the way this feature currently works.

You currently provide an anonymous type in the `Update` method but internally, we transform it into a `new Customer() { Name = "123" }` statement to be able to generate a query to get the value/formula provided (in this case, the simple constant "123").

We might improve it eventually and remove this restriction but there is currently no short-term plan of doing it right now.

As you find out, providing private parameterless constructors solve the problem as we can use it when creating our expression.

Let me know if that explains correctly why this issue happens.

Best Regards,

Jon

**Comment by mHalo** [comment]
Much appreciate for your quick response.
