### ISSUE TITLE
BulkSaveChangesAsync throws SqlException when updating entities with transaction level Snapshot Isolation - Part 2

### ISSUE THREAD

**Issue by d-57u3ndl** [zzzprojects/EntityFramework-Extensions#479]
Hello @JonathanMagnan,
after the fix from Issue #475 I have updated from version 6.13.10 to 6.13.15.
Unfortunately, I determined that the provided example was oversimplified and our explicit edge case is still not supported.
The original exception in relation with transaction level `Snapshot Isolation` and `BulkSaveChangesAsync` from Issue #475 gets still thrown.

Steps to reproduce:
1) Create a `DbConnection` and begin a DbTransaction with transaction level `Snapshot Isolation`
2) Create a `DbContext` with the existing `DbConnection` 
3) Use the `DbTransaction` in the `DbContext` via `Database.UseTransaction(transaction)`
4) Add 100 entities to the `DbContext`
5) Call `BulkSaveChangesAsync` => Exception gets thrown

I have also updated the sample project to reproduce the issue:
https://drive.google.com/file/d/1GPnuQxsLvhpivMqt0uQKsfdC5rxc5dvT/view?usp=sharing

### Exception
The EF ZExtensions are creating this SQL Script:
```
CREATE TABLE #ZZZProjects_679f9295_f4d4_4438_900a_020785b6e883 (
    [Id] [sys].[bigint] NULL,
    [Name] NVARCHAR(50) COLLATE Latin1_General_CI_AS NULL,
    [Age] [sys].[int] NULL,
    ZZZ_Index [INT] NOT NULL
    )

CREATE CLUSTERED INDEX [INDEX_#ZZZProjects_679f9295_f4d4_4438_900a_020785b6e883] ON #ZZZProjects_679f9295_f4d4_4438_900a_020785b6e883 (ZZZ_Index ASC);
```
Which leads to following Exception Message, because of TransactionLevel Snapshot Isolation:
```
System.Data.SqlClient.SqlException: Transaction failed because this DDL statement is not allowed inside a snapshot isolation transaction. Since metadata is not versioned, a metadata change can lead to inconsistency if mixed within snapshot isolation.
```

### Further technical details
- EF Extensions version: 6.13.15
- Database Provider: Microsoft SQL Server 2016 (SP3) (KB5003279) - 13.0.6300.2 (X64)

Please let me know if you need any further technical information.

**Comment by d-57u3ndl** [comment]
@rizi

**Comment by JonathanMagnan** [comment]
Hello @d-57u3ndl ,

My developer looked at it.

The `BulkSaveChanges` will work correctly but not the `BulkSaveChangesAsync` method (or any other async method). That's caused due to how we currently pass the `TransactionScope` on our side.

Unfortunately, fixing it for `async` method is a major development that is currently impossible for us to complete at this moment. So the only solution available is using the `BulkSaveChanges` method or `DisableTemporaryTableClusteredIndex`.

```csharp
// Global
EntityFrameworkManager.BulkOperationBuilder = builder => builder.DisableTemporaryTableClusteredIndex = true;
```

**Comment by d-57u3ndl** [comment]
Thanks for your response and the additional information.

My currently implemented workaround in the `DbContext` looks like this:
```
private void BulkOperationFactory(BulkOperation bulkOperation, Action<BulkOperation> onBulkOperationExecuted)
{
    // Other options...
    bulkOperation.ForceUpdateUnmodifiedValues = false;
    bulkOperation.AutoTruncate = false

    // Required because otherwise the EF-ZExtensions would generate a DDL statement that is not allowed for transaction level snapshot isolation.
    if (Database.CurrentTransaction?.UnderlyingTransaction?.IsolationLevel == IsolationLevel.Snapshot)
    {
        bulkOperation.DisableTemporaryTableClusteredIndex = true;
    }
}
```
