### ISSUE TITLE
WhereBulkContains is case sensitive

### ISSUE THREAD

**Issue by mbendtsen** [zzzprojects/EntityFramework-Extensions#480]
### Description
WhereBulkContains is case sensitive even though database is configured as case insensitive.

The list of items are upper case, but some columns in the database are with lower case number.
Having '04b6488b10582709' in database and '04B6488B10582709' in code, will not match

```sql
INSERT INTO EndpointDevices VALUES (20, '04b6488b10582709')
```

This works:
```sql
SELECT [DevEui]
      ,[EndpointId]
  FROM [dbo].[EndpointDevices]
  WHERE DevEui = '04B6488B10582705'
```

This does not work:
```csharp
List<string> devEuis = new() { "04B6488B10582709" };
List<Database.Model.EndpointDevice> endpointDevices = await context.EndpointDevices
                .Include(x => x.Endpoint).ThenInclude(x => x.Headers)
                .Where(x => x.Endpoint.Enabled && x.Endpoint.Deleted == null)
                .WhereBulkContains(devEuis, x => x.DevEui)
                .ToListAsync(cancellationToken);
```

### Further technical details
- EF version: 6.0.0
- EF Extensions version: 6.13.16
- Database Provider: Azure SQL Database (SQL SERVER)

**Comment by JonathanMagnan** [comment]
Hello @mbendtsen ,

Your database is configured case insensitive but what about your default server collation?

The `WhereBulkContains` use a temporary table, so if the `tempdb` creates a case-sensitive table, this latest collation will be used for the comparison.

Let me know the casing of the table you create in your `tempdb`.

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment]
Hello, 

Since our last conversation, we haven't heard from you. 

As mentioned in my previous message, we need more information about your tempdb casing

Don't hesitate to contact us for more assistance. 

Best regards, 

Jon

**Comment by mbendtsen** [comment]
Hi,

I've been looking around, but a can't find anything about a collation being set to CS. Everywhere I look it is set to CI. Could you point me in the right direction?
According to an article I found, I don't have access to tempdb in Azure SQL.

**Comment by JonathanMagnan** [comment]
Hello @mbendtsen ,

Could you run the following SQL to at least know if the tempdb is case sensitive or not:

```sql
SELECT 'zzz' AS ColumnName INTO #test

SELECT * FROM #test
WHERE ColumnName = 'zzz'

SELECT * FROM #test
WHERE ColumnName = 'ZZZ'

--DROP TABLE #test
```

We normally expect that both select should return something but in your case, I expect only the first one to work if the tempdb is `CS`.

Let's just start by making sure about it. Since we don't have directly access to the tempdb and getting this information, this is the only trick I find out to look at it.

**Comment by mbendtsen** [comment]
Thanks for taking you time to help me.

This is the result:
![image](https://user-images.githubusercontent.com/338354/164067200-151ba42a-1607-4610-ad1d-6d618092e190.png)

Looks to me like it is case insensitive.

**Comment by JonathanMagnan** [comment]
Thank you for the information,

We will make some tests in this case on our side to see if we can find out something. We perhaps indeed are doing something wrong

**Comment by JonathanMagnan** [comment]
Hello @mbendtsen ,

We checked this issue today but unfortunately we find nothing ;(

Is it possible for you to log what is executed and provide us the result with the logger?

```csharp
using (var ctx = new CurrentContext())
{
	var devEuis = new List<string>() { "zZz" };

	StringBuilder sb = new StringBuilder();

	ctx.Database.Log = log => sb.AppendLine(log);
       
        // change for your query here
	var list1 = ctx.EntitySimples.WhereBulkContains(devEuis, x => x.ColumnString).ToList();

	var s = sb.ToString();
}
```

We are particularly interested by the following line:

```txt
CREATE TABLE #ZZZProjects_218ae7dd_67a5_4cfd_8968_19ed65615f15 ( [ColumnString] nvarchar (max)  COLLATE SQL_Latin1_General_CP1_CI_AI NULL, ZZZ_Index [INT] NOT NULL )
```

As you can see, a collation is set when creating the temporary table. Perhaps that will give us an additional hint

Could you also run and provide us the result of the following query:

```sql
-- Change this table for your tableName if different
DECLARE @TableName VARCHAR(255) = 'EndpointDevices'

SELECT  DestinationTable.Name AS DestinationName ,
        C.name AS ColumnName ,
        C.column_id AS ColumnOrder ,
        C.precision AS Precision ,
        C.scale AS Scale ,
        C.max_length AS MaxLength ,
        C.collation_name AS Collation ,
        C.Is_Identity AS IsIdentity ,
        ( CASE WHEN EXISTS ( SELECT 1
                             FROM   sys.index_columns AS X
                             WHERE  X.index_id = B.index_id
                                    AND X.object_id = B.object_id
                                    AND X.column_id = C.column_id ) THEN 1
               ELSE 0
          END ) AS IsPrimaryKey ,
        C.system_type_id AS System_Type_Id ,
        D.Name AS TypeName,
        (CASE WHEN E.base_object_name IS NOT NULL THEN 1 ELSE 0 END) AS IsSynonym,
        D.is_user_defined,
        F.name,
		CASE WHEN C.default_object_id  = 0 THEN 'ZZZ_NO_DEFAULT' ELSE ISNULL(OBJECT_DEFINITION(C.default_object_id), 'ZZZ_ERROR_DEFAULT_ZZZ') END AS DefaultValueSql,
        C.is_nullable
FROM    (SELECT @TableName AS Name) AS DestinationTable
        LEFT JOIN sys.synonyms  AS E ON E.object_id = OBJECT_ID(DestinationTable.Name)
										AND COALESCE(PARSENAME(base_object_name,4), @@SERVERNAME) = @@SERVERNAME
										AND COALESCE(PARSENAME(base_object_name,3), DB_NAME(DB_ID())) = DB_NAME(DB_ID())
        INNER JOIN sys.tables   AS A ON A.object_id = OBJECT_ID(DestinationTable.Name)
                                        OR A.object_id = OBJECT_ID(E.base_object_name)
        LEFT JOIN sys.indexes   AS B ON B.object_id = A.object_id
                                        AND B.is_primary_key = 1
        INNER JOIN sys.columns  AS C ON C.object_id = A.object_id
        INNER JOIN sys.types    AS D ON D.system_type_id = C.system_type_id
                                     AND D.user_type_id = C.user_type_id
        INNER JOIN sys.schemas AS F ON D.schema_id = F.schema_id
ORDER BY DestinationName ,
        ColumnOrder
```

If some information needs to be keep in private, you can send it to info@zzzprojects.com

**Comment by mbendtsen** [comment]
It looks like everything is correct. Weird.... I will look at this from my side.
I'm closing this and reopen it, if I find out that something is wrong.

```sql
CREATE TABLE #ZZZProjects_a2720ac4_f1db_4c86_a1bf_1c9049f71046 ( [DevEUI] nvarchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL, ZZZ_Index [INT] NOT NULL )

CREATE CLUSTERED INDEX [INDEX_#ZZZProjects_a2720ac4_f1db_4c86_a1bf_1c9049f71046] ON #ZZZProjects_a2720ac4_f1db_4c86_a1bf_1c9049f71046 (ZZZ_Index ASC);
```

![image](https://user-images.githubusercontent.com/338354/164414073-99bb0f97-1010-47e4-abb5-4694db16c2c5.png)
