### ISSUE TITLE
Error for BulkUpdate with ColumnInputeExpression and complex type

### ISSUE THREAD

**Issue by wojMark** [zzzprojects/EntityFramework-Extensions#49]
Hello,

We are not able to use BulkUpdate with ColumnInputExpression for Completype properties. Below you can find test which should pass - but code throw exception "Additional information: An error occured while resolving ColumnInput expression. See the inner exception for details.". Please note that if we do not use ColumnInputExpression than everything works.

    public class EFContext : DbContext
    {
        public EFContext(string nameOrConnectionString) : base(nameOrConnectionString)
        {
        }

        public DbSet<TestItem> TestItems { get; set; }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            modelBuilder.ComplexType<OptimisticLock>().Property(a => a.Value).HasColumnName("OptimisticLock");
        }
    }

    public class TestItem
    {
        public TestItem()
        {
            Lock = new OptimisticLock();
        }

        [Key]
        public int Id { get; set; }
        public string Name { get; set; }
        public OptimisticLock Lock { get; set; }
    }

    public class OptimisticLock
    {
        public int Value { get; set; }
    }

    [TestClass]
    public class BatchUploadTests
    {
        string connectionString = "connectionString";

        [TestMethod]
        public void BulkUpdate_ComplexTypePropertyInColumnInputExpression_ShouldPass()
        {
            EFContext context = new EFContext(connectionString);
            List<TestItem> items = GetTestItems(context);
            Action<EntityBulkOperation<TestItem>> bulkOperationFactory = sett =>
            {
                sett.ColumnInputExpression = a => new { a.Id, a.Lock};
            };
            context.BulkUpdate(items, bulkOperationFactory);
        }

        List<TestItem> GetTestItems(EFContext context)
        {
            List<TestItem> result = context.TestItems.Take(5).ToList();
            if (result.Count == 0)
            {
                CreateItems();
                result = context.TestItems.Take(5).ToList();
            }

            return result;
        }

        void CreateItems()
        {
            using (EFContext context = new EFContext(connectionString))
            {
                List<TestItem> tempInsertList = new List<TestItem>();
                for (int i = 0; i < 100; i++)
                {
                    TestItem item = new TestItem()
                    {
                        Name = "Name" + i
                    };
                    tempInsertList.Add(item);
                }
                context.TestItems.AddRange(tempInsertList);
                context.SaveChanges();
            }
        }
    }

**Comment by JonathanMagnan** [comment]
Hello @wojMark ,

The problem is caused because you don't specify the property inside the complex type.

The following expression should work:

```csharp
sett.ColumnInputExpression = a => new { a.Id, a.Lock.Value};
```

We will look if we can add this feature to automatically include all properties from the complex type when an expression like the one you provided is used.

Let me know if the workaround solution works correctly meanwhile.

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment]
Hello @wojMark ,

The v3.12.21 has been released ([Release Note](https://github.com/zzzprojects/EntityFramework-Extensions/releases/tag/v3.12.21))
https://www.nuget.org/packages/Z.EntityFramework.Extensions/

The support to directly map the complex type property has been added.

Let me know if that's our working with your original expression.

Best Regards,

Jonathan

**Comment by wojMark** [comment]
Hello Jonathan,

Thanks for fast relase (4 hours - really??:)). It is working if we use column names which are consistent with EF convention. Unfortunately we got custom column names and in such case exception is thrown ("An error occured while resolving ColumnInput expression. See the inner exception for details.", inner exception "The given key was not present in the dictionary."). We have test it for both cases:
`sett.ColumnInputExpression = a => new { a.Id, a.Lock};`
`sett.ColumnInputExpression = a => new { a.Id, a.Lock.Value};`

To get this error please set in your tests custom column name for complex type property name. For example:
    
```
    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        modelBuilder.ComplexType<OptimisticLock>().Property(a => a.Value).HasColumnName("OptimisticLock");
        //in another test you can uncomment next line
        //modelBuilder.Entity<TestItem>().Property(a => a.Lock.Value).HasColumnName("CustomOptimistickLockName");//this one can be put in another test
    }

**Comment by JonathanMagnan** [comment]
Hello @wojMark ,

Yup ;) We try to release as fast as possible as we understand how important is to get fixed thing fixed in a good delay.

We forget to implement custom column name. We will add the support to it in a few hours.

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment]
Hello @wojMark ,

The v3.12.23 has been released (Release Note)
https://www.nuget.org/packages/Z.EntityFramework.Extensions/

The expression should not try to get the mapping from the Entity Framework model first.

Let me know if that's our working with your original expression.

Best Regards,

Jonathan

**Comment by wojMark** [comment]
Hello Jonathan,

Yes it is working. Once again thanks for so fast support.

Best regards,
Marek
