### ISSUE TITLE
Exception raised when executing Bulk Insert using Azure SQL Warehouse.

### ISSUE THREAD

**Issue by Saldash** [zzzprojects/EntityFramework-Extensions#491]
### Description
Exception is being thrown when calling `context.BulkSaveChangesAsync()`

### Exception
Exception message: `Must declare the scalar variable \"@@SERVERNAME\".`
Stack trace:
```
   at .Execute()
   at DbContextExtensions..()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at DbContextExtensions..MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Project.Services.DataWarehouse.AzureDataWarehouseServices.<UpdateContainerDataWarehouse>d__2.MoveNext() in "Project"\DataWarehouse\AzureDataWarehouseServices.cs:line 509
```

### Further technical details
- _EF version:_
   EntityFramework 6.0
   EntityFramework.SqlServer 6.0
- _EF Extensions version:_
   Z.EntityFramework.Extensions 6.14.2.0
- _Project Targeting Framework_
.Net Framework 4.8
- _Database Provider:_
Azure SQL Data Warehouse (Synapse)

### Implementation Sample
My DB Context;
```c#
using Project.DataAccess.Entities.Reporting;
using System.Data.Entity;

namespace Project.DataAccess.Context
{
    public class AzureDbContext : DbContext
    {
        public AzureDbContext() : base("name=ADW")
        {
            Database.SetInitializer<AzureDbContext>(null);
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
        }

        public virtual DbSet<MyEntity_Container> MyEntityContainers { get; set; }
    }
}
```
Adding new entries from my services;
```c#
// Add new entries
_db.MyEntityContainers.Add(...listOfMyEntityContainer...);

// Save changes and return
await _db.BulkSaveChangesAsync();
```
Please note, I have no ability to upgrade the overall project to higher than the current targeting framework.
Any solutions need to be supported within the current scope of .Net Framework 4.8.2

**Comment by JonathanMagnan** [comment]
Hello @Saldash ,

Unfortunately, we do not support Azure SQL Synapse. When we looked at it, there were way too many limitations on normal SQL syntax.

Best Regards,

Jon
