### ISSUE TITLE
BulkUpdate -> register does not exists

### ISSUE THREAD

**Issue by miguelquiroz** [zzzprojects/EntityFramework-Extensions#5]
Hi, i have a question, i'd like to know if there is a way to know whether a register exists or not when performing a bulk update operation.

**Comment by zzzprojects** [comment]
Unfortunately, there is no way to have this information.

We have added this suggestion to our features to implement list.

I can think of some scenario, but I would like to get your point of view on this suggestion. Why do you need to know which record has is updated? What will you do with it or with records not updated?

**Comment by zzzprojects** [comment]
Hello @miguelquiroz,

We will close this issue.

As we said, this is in our roadmap when the library will be fully re-written but we cannot provide any date yet.
