### ISSUE TITLE
Performance of BatchSaveChanges is worse than EntityFrameworks SaveChanges

### ISSUE THREAD

**Issue by jamesHargreaves12** [zzzprojects/EntityFramework-Extensions#501]
### Description
Running side-by-side comparisons of EntityFramework Extension's BatchSaveChanges and EntityFramework SaveChanges yielded the surprising result that SaveChanges was actually significantly faster in the majority of cases. 

The only cases that we could find that BatchSaveChanges was faster was in the case where the table was very thin (Had a small number of columns) like the provided online benchmark. 

## More detailed analysis:
We have done some profiling on our system for insertions of 50 Entities With AutoDetectChangesEnabled and ValidateOnSaveEnabled both set to false. Using SQL profiler we can find the time for:
- Sql transaction: (compare the time of the BEGIN TRANSACTION  and COMMIT TRANSACTION events)
- Total time spent executing insert commands (End time of last INSERT statement - Start time of first INSERT statement).
We can then compare this data to how long C# recorded that SaveChanges vs BatchSaveChanges method call took. The results are given below:

<html>
<body>

Run | C# time /ms | Sql Transaction time/ms | Sql total Insert time / ms | C#-SQL transaction /ms | SQL Transaction - SQL total insest / ms
-- | -- | -- | -- | -- | --
SaveChanges (1) | 241 | 233 | 214 | 8 | 19
SaveChanges (2) | 328 | 320 | 277 | 8 | 20
BatchSaveChanges (1) | 504 | 474 | 300 | 30 | 197
BatchSaveChanges (2) | 481 | 450 | 257 | 31 | 193

</body>
</html>

So we can see that there is some time lost outside of the SQL transaction but that the majority of the loss comes from time difference between the SQL transaction length and the time spent executing the inserts. This delta grows dramatically as the number of entities increases e.g. The same experiment for 500 entities was 200ms vs 2000ms .

Looking into the (Obfuscated) source code it appears that the only thing going on within the transaction but outside of the inserts is the construction of the SQL commands using reflection so it appears that the delta comes from the fact that the EF Extensions implementation is significantly more inefficient here than the EF implementation.

A Further point of note is that turning on either ValidateOnSaveEnabled or AutoDetectChangesEnabled resulted in the difference between the two methods growing large.
### Fiddle or Project (Optional)
https://dotnetfiddle.net/zU7u2Q (This is a very simple fork of the online benchmark just changed by adding 25 columns)

### Further technical details
- EF version: 6.4.4
- EF Extensions version: 6.14.4 (also tested 6.14.2)
- Database Provider: SQL Server

**Comment by JonathanMagnan** [comment]
Thank you for reporting,

My developer is currently looking at it.

**Comment by JonathanMagnan** [comment]
Hello @jamesHargreaves12 ,

Thank you again for reporting.

Unfortunately for everyone, you are 100% right, and there is nothing we can do to fix this.

## Why BatchSaveChanges is sometimes slower than SaveChanges?

This is all about how long SQL Server will take to compile the query. There is nothing we can do to improve this part.

By default, the maximum command in a batch is 25, reducing this value would increase performance in a scenario like this one, but at one point, it would be just probably better to use `SaveChanges` when this case happens.

The major advantage of `BatchSaveChanges` is to reduce database roundtrip. However, as you just have demonstrated, the major drawback is taking more time to compile a query.

So when only a few columns are involved, the compile time is really quick but becomes longer and longer when more columns start to get involved.

Let me know if that explains the cause correctly.
