### ISSUE TITLE
OptimisticConcurrencyException on BulkSaveChangesAsync

### ISSUE THREAD

**Issue by dilandau2001** [zzzprojects/EntityFramework-Extensions#505]
### Description
When saving multiple changes, sometimes an exception fires preventing saving changes. From this point following calls keep failing.
This class works as a database cache and is in charge all all writes to the database. The context is not closed and entities are kept in memory.

### Exception
System.Data.Entity.Infrastructure.DbUpdateConcurrencyException
  HResult=0x80131501
  Message=Store update, insert, or delete statement affected an unexpected number of rows (0). Entities may have been modified or deleted since entities were loaded. See http://go.microsoft.com/fwlink/?LinkId=472540 for information on understanding and handling optimistic concurrency exceptions.
  Source=Z.EntityFramework.Extensions
  StackTrace:
   at .Execute()
   at DbContextExtensions.(DbContext this, Boolean , Action`1 , Boolean )
   at DbContextExtensions..()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at DbContextExtensions..MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at DataAccess.EFBasicUnitOfWork`1.<BulkSaveChangesAsync>d__9.MoveNext() in DataAccess\EfBasicUnitOfWork.cs:line 100

  This exception was originally thrown at this call stack:
    System.Data.Entity.Core.Mapping.Update.Internal.UpdateTranslator.ValidateRowsAffected(long, System.Data.Entity.Core.Mapping.Update.Internal.UpdateCommand)

Inner Exception 1:
OptimisticConcurrencyException: Store update, insert, or delete statement affected an unexpected number of rows (0). Entities may have been modified or deleted since entities were loaded. See http://go.microsoft.com/fwlink/?LinkId=472540 for information on understanding and handling optimistic concurrency exceptions.

### Further technical details
- EF version: 6.4.4
- EF Extensions version: 6.15.0 (was also happening in previous versions)
- Database Provider: Microsoft SQL Server 

we have try to implement "Client wins" 
/* 
                                 * Solution proposed by Microsoft for client wins
                                 * (ensures original values are from storage, but leaves current values with client values before save changes again).
                                 * See:
                                 * https://learn.microsoft.com/en-us/ef/ef6/saving/concurrency?redirectedfrom=MSDN#resolving-optimistic-concurrency-exceptions-as-client-wins
                                 * 
                                 *  More info about original and currrent values:
                                 *  https://learn.microsoft.com/en-us/ef/ef6/saving/change-tracking/property-values
                                 */
                                entry.OriginalValues.SetValues(entry.GetDatabaseValues());

It did not work because entry.GetDatabaseValues is returning null. The entry that is giving conflict is not yet in the database.

We could see that this entry.Status is "Modified" instead of "Added" so we tried force status to Added but the issue is still happening.

We have run out of ideas.

**Comment by JonathanMagnan** [comment]
Hello @dilandau2001 ,

Do you think you could create a runnable project with the issue? It doesn’t need to be your project, just a new solution with the minimum code to reproduce the issue. You can send it in private here: info@zzzprojects.com

The last part of your message looks really weird: `We could see that this entry.Status is "Modified" instead of "Added"`

Are you having the same issue by using directly `SaveChanges`? 

We will be happy to investigate this issue, but we need a project here as we have no idea how to reprodu ce it.

Best Regards,

Jon

**Comment by dilandau2001** [comment]
Finally we found the culprit. 
There was some other task that could be "Updating" the entity before it was saved, changing the Added state to modify artificially.
And that was causing a DbUpdateConcurrencyException
