### ISSUE TITLE
EF Core 7 RC1

### ISSUE THREAD

**Issue by pleavitt** [zzzprojects/EntityFramework-Extensions#507]
Are you planning to release a version compatible with EF Core 7 RC1?

**Comment by JonathanMagnan** [comment]
Hello @pleavitt ,

The following version should already support it: https://www.nuget.org/packages/Z.EntityFramework.Extensions.EFCore/7.0.0-rc.1.22426.7-01

Let me know if that answers correctly to your question.

Best Regards,

Jon

**Comment by pleavitt** [comment]
Thanks mate
