### ISSUE TITLE
BulkMerge failing on Windows 10 PRO and Azure App Service

### ISSUE THREAD

**Issue by TrevorLinkgreen** [zzzprojects/EntityFramework-Extensions#514]
### Description
We recently started noticing that the BulkSaveChanges functionality from Z.EntityFrameWork.Extensions was failing on one of our development machines, it is also failing in an Azure App Service.   This does not appear to happen in Windows 10 Home.  

When it hit the BulkSaveChanges lines, it would cause the IIS server to actually fault, so no error trapping would allow us to debug or work around the issue.   Eventually, we replaced the BulkSaveChanges with the original SaveChanges(), using the EntityFramework native SaveChanges.

We are now seeing this behaviour while using BulkMerge().  And don't have a simple "fix" that would work for this.   So hoping you have an idea what might be happening

### Exception

We do not have any C# exceptions as when it fails, it casues IIS to fault.     

This is the Windows event log for when IIS faults on the Windows 10 Pro development machine

```
Faulting application name: w3wp.exe, version: 10.0.19041.1, time stamp: 0x58c67bf3
Faulting module name: ntdll.dll, version: 10.0.19041.2130, time stamp: 0xb5ced1c6
Exception code: 0xc0000409
Fault offset: 0x000000000008c67f
Faulting process id: 0x3598
Faulting application start time: 0x01d8f2e99b37fa12
Faulting application path: c:\windows\system32\inetsrv\w3wp.exe
Faulting module path: C:\WINDOWS\SYSTEM32\ntdll.dll
Report Id: a0a9d940-0875-4867-a2cb-cafe66db5107
Faulting package full name:
Faulting package-relative application ID:
```

### Fiddle or Project (Optional)

Below is the BulkMerge command that we are trying to run that causes IIS to fault.

```csharp
  Context.BulkMerge(salesReps, opt =>
                {
                    opt.AllowDuplicateKeys = false;
                    opt.ColumnPrimaryKeyExpression = salesrep => new { salesrep.BuyerId, salesrep.UserId };

                    opt.IgnoreOnMergeUpdateExpression = ignorePrimaryOnUpdate
                        ? (Expression<Func<Salesrep, object>>)(salesrep =>
                            new { salesrep.CreatedBy, salesrep.CreatedDate, salesrep.IsPrimary })
                        : salesrep => new { salesrep.CreatedBy, salesrep.CreatedDate };

                    opt.IgnoreOnMergeInsertExpression = salesrep => new { salesrep.ModifiedBy, salesrep.ModifiedDate };
                });
```

### Further technical details
- EF version: Microsoft.EntityFrameworkCore.SqlServer 6.0.1
- EF Extensions version: Z.EntityFramework.Extensions.EFCore 6.13.4
- Database Provider: Microsoft.EntityFrameworkCore.SqlServer 6.0.1

**Comment by TrevorLinkgreen** [comment]
Jon,

Thanks for replying.

On the development machine, the database is on the same machine as the code.  

In Azure, the site is hosted on an Azure App Service Plan and the database is an Azure SQL database.


In all instances, the users are full administrators of the database.


In my windows 10 HOME machine (which does not encounter the issue), my SQL instance is in a VM, but still a full administrator

**Comment by JonathanMagnan** [comment]
Hello @TrevorLinkgreen ,

If the user is a full administrator, I guess we are wrong, and that's not a missing permission issue.

Does this error happen as soon as you use our library? or from time to time?

If it happens as soon as you use our library, the second guess would be maybe a FIPS problem: https://entityframework-extensions.net/md5-exception

That's the only thing we can think could cause this.

Fortunately, you currently have a development machine that has the error, so if that's not this, you can perhaps find some solution to catch the error from here (or any other way you can find): https://stackify.com/beyond-iis-logs-find-failed-iis-asp-net-requests/

**Comment by TrevorLinkgreen** [comment]
This morning, after patch tuesday, it has started to work on our Windows 10 Pro machine.

A rebuild and redeploy to Azure appears to have fixed the issue in production.

![image](https://user-images.githubusercontent.com/35039527/200874507-da55f128-2c27-4933-97ee-9a1aabd0a7bf.png)


Looks like something in one of those two patches from Microsoft was the fix.

Thank you for your support.
