### ISSUE TITLE
How to send to preserveinsertorder=false in BulkInsertAsync method for ef core?

### ISSUE THREAD

**Issue by P9avel** [zzzprojects/EntityFramework-Extensions#516]
Cannot find preserveinsertorder option in Action. Please help

**Comment by JonathanMagnan** [comment]
Hello @P9avel ,

We do not have an `preserveinsertorder` option. However, it should already be in the same order as the list of entities you passed.

Did you have an issue with the ordering?

Best Regards,

Jon

**Comment by P9avel** [comment]
I am want set false for increase performance

**Comment by P9avel** [comment]
I see you. many thx
