### ISSUE TITLE
Invalid program exception on iOS with .NET 7 and Maui

### ISSUE THREAD

**Issue by jtexter3** [zzzprojects/EntityFramework-Extensions#517]
### Description
I have a project I am porting from Xamarin Forms to Maui. Whenever I attempt to call BulkSaveChanges, I am receiving an InvalidProgramException

### Exception
System.TypeInitializationException: The type initializer for '' threw an exception.\n ---> System.InvalidProgramException\n   --- End of inner exception stack trace ---\n   at DbContextExtensions.BulkSaveChanges(DbContext this, Action`1 options)\n   at DbContextExtensions.BulkSaveChanges(DbContext this)\n

### Further technical details
- EF version: 7.0.0
- EF Extensions version: 7.17.0
- Database Provider: SQLite

**Comment by JonathanMagnan** [comment]
Hello @jtexter3 ,

As answered by email, it seems more like an issue already reported to EF Core itself: https://github.com/dotnet/efcore/issues/29589

If you believe this is caused by our library, let us know and we will re-open the issue to investigate more.

Best Regards,

Jon
