### ISSUE TITLE
The variable name '@isForceOutputFromUnmodifiedRow' has already been declared.

### ISSUE THREAD

**Issue by vindberg** [zzzprojects/EntityFramework-Extensions#518]
### Description
Im suddently getting this kind of error: Microsoft.Data.SqlClient.SqlException (0x80131904): The variable name '@isForceOutputFromUnmodifiedRow' has already been declared. Variable names must be unique within a query batch or stored procedure.

Never seen that error before.
Im doing a BulkMerge:
             
```csharp
await context.BulkMergeAsync(titlesUnique, options =>

                {
                    options.UseAudit = true;
                    options.AuditEntries = auditEntries;
                    options.OnMergeUpdateUseCoalesce = true; 
                    options.ForceOutputFromUnmodifiedRow = true;
                    options.IncludeGraph = true;
                    options.IncludeGraphOperationBuilder = operation =>
```

### Further technical details
- EF version: 6
- EF Extensions version: 6.16.1
- Database Provider: Sql Server

**Comment by JonathanMagnan** [comment]
Hello @vindberg ,

Thank you for reporting. We will look at this scenario.

Meanwhile, you can disable the command `batching`, which causes this error while the following **global option**:

```csharp
Z.EntityFramework.Extensions.EntityFrameworkManager.DisableBulkCommandBatch = true;
```

I should be able to give you an update really soon.

Best Regards,

Jon

**Comment by vindberg** [comment]
Thanks for suggesting a workaround. Does it degrade performance?

**Comment by JonathanMagnan** [comment]
Hello @vindberg ,

Could you try the latest version? The v6.17.1 should have this issue fixed

Let me know if you still have the problem after upgrading to the latest v6.x version.

Best Regards,

Jon

**Comment by vindberg** [comment]
Its working, thanks.
