### ISSUE TITLE
WhereBulkContains Error "Oops! A general error has occurred. Please report the issue including the stack trace to our support team: info@zzzprojects.com"

### ISSUE THREAD

**Issue by fabianleonardog** [zzzprojects/EntityFramework-Extensions#522]
I need to do a Contains to filtered a table by a list of ids, that works fine on EF but creating unit test with Memory db context, because UseInMemoryDatabase has limitations, so i decide to use zzz EF extensions with a WhereBulkContains

simple test 

var test = await _dbContext.MyTable.WhereBulkContains(ids).ToListAsync();

I added the nuget package EntityFramework.Extensions V 7.18.3 i added 

but then a got this error

System.Exception : Oops! A general error has occurred. Please report the issue including the stack trace to our support team: info@zzzprojects.com

  Stack Trace: 
    .[](IQueryable`1 )
    .[](IQueryable`1 )
    QueryHookManager.Hook[T](IQueryable`1 query, BaseQueryHookAction hookAction)
    WhereBulkContainsExtensions.WhereBulkContains[T](IQueryable`1 this, IEnumerable isInList)
    AdvancedSearchHelper.UpdateForwardingStatusAsync(IEnumerable`1 timesheets) line 112
    AdminAdvancedSearchService.GetAdvanceSearchResultAsync(AdvancedSearchRequestDto requestDto, String email) line 31
    AdvancedSearchServiceTest.AdvancedSearchAdminByAdmin(String strStartDate, String strEndDate, Int32 pageSize) line 70
    --- End of stack trace from previous location ---

**Comment by JonathanMagnan** [comment]
Hello @fabianleonardog ,

We will close the issue as currently, we don't plan to support `InMemory` providers.

However, starting from v7.18.5, an explicit error message should be thrown.

Best Regards,

Jon
