### ISSUE TITLE
Merge problem inserting multiple rows with the same id key

### ISSUE THREAD

**Issue by payoff** [zzzprojects/EntityFramework-Extensions#524]
### Description
The way the library is developed by looking at the logs with
```
                operation.MergeKeepIdentity = true;
                operation.UseAudit = true;
                operation.AuditEntries = audits;
                operation.UseLogDump = true;
```
 shows that when you do a bulkmerge with multiple rows with the same Id, only the first one is taken, and not all of them are executed as you would expect.
The problem in Postgres is visible from the sql below

### PG SQL Code

```
Sample:
update
	public.node as tgt set

	"NodeName" = src."NodeName"
from
	(
		select '3d000000-0012-0100-1200-000142707e00'::uuid as "Id", '[m000]' as "NodeName"
		UNION all  select '3d000000-0012-0100-1200-000142707e00'::uuid as "Id", '[m002]' as "NodeName"
		UNION all select '3d000000-0012-0100-1200-000142707e00'::uuid as "Id", '[m005]' as "NodeName"
	) as src
where
	tgt."Id" = src."Id";

```

### Further technical details
- EF version: EF CORE 6
- EF Extensions version:  6.18.2
- Database Provider: PgSQL 14

**Comment by JonathanMagnan** [comment]
Hello @payoff ,

The sql currently shows that all matched rows will be updated and not only the first one unless I miss something.

If you are looking to only matches the last row when you have duplicate keys like in your case, you must use the `AllowDuplicateKeys` option.

I believe I'm missing something, so let me know what I didn't understand correctly.

Best Regards,

Jon
