### ISSUE TITLE
[Help]No provider supported for 'Microsoft.EntityFrameworkCore.Dm', help plz

### ISSUE THREAD

**Issue by ZHAO-SHI-HAO** [zzzprojects/EntityFramework-Extensions#526]
Hello there!

 

I’m a developer from China, and I got a problem here:

 

I got a database named “Dameng”(here is their official site: [达梦数据库管理系统DM8 (dameng.com)](https://www.dameng.com/DM8.html)) and a driver they’ve provided.

 

But when mix them up with ‘Z.EntityFramework.Plus.EFCore’ I got an error described like: “ The provider is not supported yet: 'Microsoft.EntityFrameworkCore.Dm. If you believe it's a mistake, please report this message to our support team: info@zzzprojects.com ”.

![image](https://user-images.githubusercontent.com/43308915/220663628-3f461de3-e2d5-4af4-acfe-faf097c018e9.png)

 

I could not find any help on the internet and I still have these questions.

 

1.     Which provider is not supported? And what can I do for this problem?

2.     If I can override or add something in the driver they provided, which part do you suggest me to start?

 

Really need some help here, help plz.

 

The detailed picture and “Dameng” driver nuget package were attached in the attachments’ list and named “error.png” and “dameng.zip”.

 

Thank you for your help!

**Comment by JonathanMagnan** [comment]
Hello @ZHAO-SHI-HAO ,

Unfortunately, I don't think anything will be done as this provider is not supported and there is no plan to add more providers at this moment.

We only support the most common providers, such as:
- SQL Server
- MySQL
- SQLite
- PostgreSQL
- Oracle

Best Regards,

Jon
