### ISSUE TITLE
EF7 - Concurrency validation is not throwing an exception when calling the 'BulkSaveChanges' method

### ISSUE THREAD

**Issue by tnering** [zzzprojects/EntityFramework-Extensions#527]
### Description
Hello,

During a testing session, I came across a problem with concurrent editing control when using the ``BulkSaveChanges()``.

If an entity is modified by another terminal after it is loaded, we cannot persist the changes made, however, the ``BulkSaveChanges()``  seems to ignore the concurrent editing validation configuration, or am I doing something wrong?

If we use EF's ``SaveChanges()`` method, validation occurs normally.

### Fiddle or Project (Optional)

I have attached a project illustrating the problem.
To run it, it will be necessary to create a table called 'user' with the fields 'id' (int) and 'nickname' (varchar).

I use the 'xmin' column (default in Postgres) to check if the record has been modified after it is loaded, so there is no need to create it as it is maintained by the database.

[TestingBulkSave.zip](https://github.com/zzzprojects/EntityFramework-Extensions/files/11043498/TestingBulkSave.zip)

#### Sample Context

```c#
public class SessionContext : DbContext
{
	private const string CONNECTION_STRING = "?";

	public DbSet<User> Users { get; set; } = null!;

	public SessionContext() {
		InitContext();
	}

	protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder) {
		base.OnConfiguring(optionsBuilder);
		ConfigureDbContext(optionsBuilder);
		optionsBuilder.EnableSensitiveDataLogging();
	}

	public static DbContextOptionsBuilder ConfigureDbContext(DbContextOptionsBuilder optionsBuilder) {
		optionsBuilder.UseQueryTrackingBehavior(QueryTrackingBehavior.NoTrackingWithIdentityResolution);
		optionsBuilder.UseNpgsql(CONNECTION_STRING, builder => { builder.CommandTimeout(90); });

		return optionsBuilder;
	}

	protected override void OnModelCreating(ModelBuilder modelBuilder) {
		base.OnModelCreating(modelBuilder);

		//concurrency settings
		modelBuilder.Entity<User>().Property(p => p.Version).IsRowVersion();
	}

	private void InitContext() {
		ChangeTracker.AutoDetectChangesEnabled = false;
		ChangeTracker.LazyLoadingEnabled = false;
		ChangeTracker.CascadeDeleteTiming = CascadeTiming.Never;
		ChangeTracker.DeleteOrphansTiming = CascadeTiming.Never;
	}
}
``` 

#### Sample Method 
```c#
	public void Run(int id = 1) {
		var user = _ctx.Users.Find(id);

		if (user is not null) {
			user.Name = $"{user.Name} - {DateTime.Now:T}";
		}

		_ctx.Attach(user);

		//force change (ChangeTracker.AutoDetectChangesEnabled = false)
		foreach (var entry in _ctx.ChangeTracker.Entries<User>()) {
			entry.Property(p => p.Name).IsModified = true;
		}

		try {
			//this doesn't work
			_ctx.BulkSaveChanges();

			//this works
			//_ctx.SaveChanges();
		}
		catch (DbBulkOperationConcurrencyException ex) {
			Console.WriteLine(ex);
		}
		catch (DBConcurrencyException ex) {
			Console.WriteLine(ex);
		}
		catch (Exception ex) {
			Console.WriteLine(ex);
		}
	}
``` 

### Further technical details
- EF version: 7.0.4
- EF Extensions version: 7.20.0
- Database Provider: PostgreSQL 14

**Comment by JonathanMagnan** [comment]
Hello @tnering ,

Starting from v7.100.0.0, we now support the `AllowConcurrency` option correctly within our library for PostgreSQL.

Due to backward compatibility, you need to however enable it with the `option.AllowConcurrency = true` option such as:

```csharp
context.BulkSaveChanges(option => option.AllowConcurrency = true);
context.BulkMerge(list, option => option.AllowConcurrency = true);
```

I’m not sure if you will have the chance to test it since you reported this problem 6 months ago, but if you test it, let us know if everything works as expected.

Best Regards,

Jon

**Comment by tnering** [comment]
Hello Jon,

I managed to run the tests, yes. I confess I was looking forward to this improvement, especially in cases where concurrency control is needed. I was still performing updates via EF in those cases.

Anyway, I ran the tests, and everything worked as expected.

Thank you very much.

Best regards.
