### ISSUE TITLE
Is `InsertFromQuery` supported when using Effort?

### ISSUE THREAD

**Issue by tiesont** [zzzprojects/EntityFramework-Extensions#530]
### Description

When attempting to unit test a method which uses `InsertFromQuery`, we always get the error noted below. Same occurs when trying to use `SingleInsert`.

### Exception

```
Exception message:  System.Exception : Stream not found (Conceptual).

Stack trace:

.(DbContext this, String )
.(DbContext this, List`1 , String )
.(DbContext )
.(DbContext )
DbContextExtensions.GetModel(DbContext this)
`1.(IQueryable`1 , Action`1 )
`1.Execute(IQueryable`1 query, Action`1 batchInsertBuilder)
DbContextExtensions.InsertFromQuery[TEntity](IQueryable`1 query, Expression`1 selectExpression)
```

### Fiddle or Project (Optional)

Can't really provide a complete runnable example, but this is how I'm attempting to call either of the methods mentioned above:

```
Context.Diagnosis.InsertFromQuery(m => new Data.Diagnosi
{
    Code = code,
    OrderId = id
});
```

`Diagnosi` maps to this table:

```
Diagnosis
---
[Id] int not null identity(1,1)
[Code] nvarchar(50) null
[OrderId] int not null
```

`Id` is the primary key, and `OrderId` is a foreign key reference to an `Order` table. The Entity Framework model was created as a database-first EDMX model.

_Note: More information you provide, faster we can implement a solution._

### Further technical details
- EF version: 6.4.4
- EF Extensions version: 7.21.1
- Database Provider: SQL Server

**Comment by JonathanMagnan** [comment]
Hello @tiesont ,

Unfortunately, indeed `InsertFromQuery` doesn't work with `Effort`. Support might eventually come but there is currently no short-term plan of doing it at this moment.

Best Regards,

Jon

**Comment by tiesont** [comment]
> Hello @tiesont ,
> 
> Unfortunately, indeed `InsertFromQuery` doesn't work with `Effort`. Support might eventually come but there is currently no short-term plan of doing it at this moment.
> 
> Best Regards,
> 
> Jon

I thought as much. Wanted to ask before I spent a lot of time trying to work around this. Appreciate the quick response.
