### ISSUE TITLE
UpdateMatchedAndOneNotConditionExpression option in BulkUpdateAsync does not work in MySQL

### ISSUE THREAD

**Issue by LEIRONGHUA** [zzzprojects/EntityFramework-Extensions#537]
### Description
The UpdateMatchedAndOneNotConditionExpression option in BulkUpdateAsync does not work in MySQL, but it works in MSSQL, please tell me where I am wrong

### Fiddle or Project (Optional)
Provide a Fiddle that reproduces the issue: https://dotnetfiddle.net/C3wNmy

### Further technical details
- EF version: EntityFrameworkCore 7.0.9
- EF Extensions version: 7.22.4
- Database Provider: MySQL 8.0.31

Thank you for looking into this!

**Comment by JonathanMagnan** [comment]
Hello @LEIRONGHUA ,

You are maybe right. At first sight, it doesn't look to have been added yet to `MySQL`.

I asked my developer to look at it.

Best Regards,

Jon

**Comment by JonathanMagnan** [comment]
Hello @LEIRONGHUA ,

The v7.100.0.0 has been released.

In this version, we added the support to `UpdateMatchedAndOneNotConditionExpression` and a few more similar options that were still missing for `MySQL` provider.

Let us know if everything now works as expected in the latest version.

Best Regards,

Jon

**Comment by LEIRONGHUA** [comment]
Hello @JonathanMagnan 

It is normal to work in the new version, thank you for your great efforts.

By the way, https://github.com/zzzprojects/EntityFramework-Extensions/issues/498 is there any progress on this issue?

Best Regards，

Lei

**Comment by JonathanMagnan** [comment]
Hello @LEIRONGHUA ,

No, we didn't start yet the #498 . However the issue opened in our JIRA this week (we had a reminder to look at it again in September)

As we completed/released our major changes (v7.100.0.0), we will look at it very soon. So feel free to ask for an update at the beginning of October directly in issue #498 if we haven't provided anything yet.

Best Regards,

Jon

**Comment by LEIRONGHUA** [comment]
OK, thank you very much
