### ISSUE TITLE
InsertFromQuery in oracle throw an ArgumentOutOfRangeException exception

### ISSUE THREAD

**Issue by mauricio-andre** [zzzprojects/EntityFramework-Extensions#538]
### Description
When We try to call the function InsertFromQuery to operate a insert function in the oracle database, We get an ArgumentOutOfRangeException, this error does not occur when the function is executed on Sql Server Database. The follow repository was created to simulate the error [ZZZ-ORACLE-EXAMPLE](https://github.com/mauricio-andre/ZZZ-ORACLE-EXAMPLE), it contains more information about the error and instructions for simulating this problem.

### Exception
Exception message: Length cannot be less than zero.
Stack trace:
Exception has occurred: CLR/System.ArgumentOutOfRangeException An unhandled exception of type 'System.ArgumentOutOfRangeException' occurred in System.Private.CoreLib.dll: 'Length cannot be less than zero.' at System.String.ThrowSubstringArgumentOutOfRange(Int32 startIndex, Int32 length) at System.String.Substring(Int32 startIndex, Int32 length) at 1.() at 1.(IQueryable1 , Action1 ) at 1.Execute(IQueryable1 query, Action1 batchInsertBuilder) at DbContextExtensions.[](IQueryable1 , Action1 ) at DbContextExtensions.[](IQueryable1 , String , String , String , Type , Expression1 ) at DbContextExtensions.InsertFromQuery[TEntity](IQueryable1 query, Expression`1 selectExpression) at ZZZOracleExample.Core.Handlers.CreateExampleCmdHandler.d__5.MoveNext() in C:\Users\mauricio.andre\repos\private\ZZZ-ORACLE-EXAMPLE\src\ZZZOracleExample.Core\Examples\Handlers\CreateExampleCmdHandler.cs:line 41 at Program.<$>g__ExemplifyServiceLifetime|0_1(IServiceProvider hostProvider) in C:\Users\mauricio.andre\repos\private\ZZZ-ORACLE-EXAMPLE\src\ZZZOracleExample.App.SomeEventHandlerWorker\Program.cs:line 29 at Program.$(String[] args) in C:\Users\mauricio.andre\repos\private\ZZZ-ORACLE-EXAMPLE\src\ZZZOracleExample.App.SomeEventHandlerWorker\Program.cs:line 22

### Further technical details
- EF version: 7
- EF Extensions version: 7.22.3
- Database Provider: Oracle.EntityFrameworkCore: 7.21.9
- Database: Oracle 19.11.0.0.0

**Comment by JonathanMagnan** [comment]
Hello @mauricio-andre ,

Just to let you know that starting from v7.22.6, this issue has now been fixed.

`InsertFromQuery` should now work correctly with Oracle.

Let us know if you got any problem with the latest version.

Best Regards,

Jon
