### ISSUE TITLE
BulkOperation.RowsAffected always return 0?

### ISSUE THREAD

**Issue by serifreedom** [zzzprojects/EntityFramework-Extensions#54]
![zzz1](https://user-images.githubusercontent.com/1667960/30640014-6f81a994-9e2b-11e7-86a1-7e706fe56e49.png)

Did I do anythings wrong? I need to known, how many transactions have been done?

EF v6.0.0.0, EF-Ex v3.12.17.0, MySql DB First

**Comment by JonathanMagnan** [comment]
Hello @serifreedom ,

Unfortunately due to some restriction, `RowsAffected` is not currently supported for Bulk Operations.
We will add this request to our road map.

Best Regards,

Jonathan

**Comment by serifreedom** [comment]
What are some restriction?  Why It works on free EP-PLus?

BR,

**Comment by JonathanMagnan** [comment]
Hello @serifreedom ,

It work on EF Plus under `BatchDelete` && `BatchUpdate` features. This library also support it for only for `DeleteFromQuery` and `UpdateFromQuery` features (which are the same but with a different name).

Best Regards,

Jonathan
