### ISSUE TITLE
Is is possible to globally set column mappings for shadow properties?

### ISSUE THREAD

**Issue by meinsiedler** [zzzprojects/EntityFramework-Extensions#542]
### Description
We are implementing a change tracking feature where we want to store the ID of the current user who modified an entity. Therefore, we have a marker interface `IChangeTrackedEntity`. When this interface is applied to entity types, we configure a [shadow property](https://learn.microsoft.com/en-us/ef/core/modeling/shadow-properties) `ModifiedByUserId`, which should be filled automatically when saving enties. For the regular EF change tracker, we use [SaveChanges interception](https://learn.microsoft.com/en-us/ef/core/logging-events-diagnostics/interceptors#savechanges-interception) for that.

We now also want to set the `ModifiedByUserId` when using the bulk operations like `BulkInsert` or `BulkMerge`. We want to have a generic solution, which is globally configured, so that we don't need to change the calling code of `BulkInsert` or `BulkMerge`.

We tried to set this up using the `EntityFrameworkManager.BulkOperationBuilder`, the `PostConfiguration` event and configuring the `ColumnMapping` like this:

```csharp
EntityFrameworkManager.BulkOperationBuilder = bulkOperation =>
{
    bulkOperation.PostConfiguration = postConfigurationBulkOperation =>
    {
        var entityType = postConfigurationBulkOperation.GetType().GetGenericArguments().FirstOrDefault();
        if (entityType != null && typeof(IChangeTrackedEntity).IsAssignableFrom(entityType))
        {
            ConfigureModifiedByUserIdColumnMapping(postConfigurationBulkOperation);
        }
    };
};

static void ConfigureModifiedByUserIdColumnMapping(BulkOperation bulkOperation)
{
    var modifiedUserId = Guid.NewGuid(); // assume we have a service here which provides the current user id.

    var modifiedByUserIdColumnMapping = bulkOperation.ColumnMappings.SingleOrDefault(c => c.SourceName == "ModifiedByUserId");
    if (modifiedByUserIdColumnMapping != null)
    {
        // Neither of those settings set the value in the database column.
        modifiedByUserIdColumnMapping.DefaultValue = modifiedUserId;
        modifiedByUserIdColumnMapping.SourceValue = modifiedUserId;
    }
}
```

Unfortunately, this doesn't work. We tried to set the `DefaultValue` or the `SourceValue` to the current user's ID. Neither of those options work and the column in the database stays `null`.

Is is somehow possible to globally set column values for shadow properties for the bulk operations?

### Fiddle or Project (Optional)

[Here](https://dotnetfiddle.net/zGVeN4) is a DotNetFiddle which implements our use case in the sample. Please note that we use a LocalDB for testing, which is not supported in DotNetFiddle, so the fiddle cannot be executed directly.

### Further technical details
- EF version: 7.0.10
- EF Extensions version: 7.22.6
- Database Provider: SqlServer (using LocalDB for testing)

**Comment by JonathanMagnan** [comment]
Hello @meinsiedler ,

Here is an example that my developer provided me: https://dotnetfiddle.net/QLXVum

Let me know if that solves your problem.

Best Regards,

Jon

**Comment by meinsiedler** [comment]
Hello @JonathanMagnan,

thank you your your quick response and for the sample.

We did not want to touch every call to `BulkMergeAsync` or `BulkInsertAsync` in our code base to pass the additional options like in your sample. Therefore, we tried to use the `EntityFrameworkManager.BulkOperationBuilder` to configure the setting of the shadow properties for all calls to the bulk operations in one single place.

I now changed two things based your sample and this works now:

1. I changed the `ColumnMapping` to use the `FormulaInsert` and `FormulaUpdate` (for `BulkMerge`) instead of trying to set the `DefaultValue` or the `SourceValue`:

    ```csharp
    modifiedByUserIdColumnMapping.FormulaInsert = "'" + modifiedUserId.ToString() + "'";
	modifiedByUserIdColumnMapping.FormulaUpdate = "'" + modifiedUserId.ToString() + "'";
    ```

2. I changed the option from `IncludeGraph` to `IncludeGraphBeta`. With that we don't need the `IncludeGraphOperationBuilder`. The `ModifiedByUserId` column gets set for the whole graph (i.e. `InvoiceItems` too). With the regular `IncludeGraph` option we received the following exception:

    ```
	When using `IncludeGraph`, columns related options CANNOT be specified outside the `IncludeGraphOperationBuilder` since they depend on the type (See: https://entityframework-extensions.net/include-graph). The following options must be specified inside `IncludeGraphOperationBuilder`: _postConfiguration
    ```

For reference, here is our updated global config:

```csharp
EntityFrameworkManager.BulkOperationBuilder = bulkOperation =>
{
    bulkOperation.PostConfiguration = postConfigurationBulkOperation =>
    {
        var entityType = postConfigurationBulkOperation.GetType().GetGenericArguments().FirstOrDefault();
        if (entityType != null && typeof(IChangeTrackedEntity).IsAssignableFrom(entityType))
        {
            ConfigureModifiedByUserIdColumnMapping(postConfigurationBulkOperation);
        }
    };
};

void ConfigureModifiedByUserIdColumnMapping(BulkOperation bulkOperation)
{
    var modifiedUserId = Guid.NewGuid(); // assume we have a service here which provides the current user id.

    var modifiedByUserIdColumnMapping = bulkOperation.ColumnMappings.SingleOrDefault(c => c.SourceName == "ModifiedByUserId");
    if (modifiedByUserIdColumnMapping != null)
    {
      modifiedByUserIdColumnMapping.FormulaInsert = "'" + modifiedUserId.ToString() + "'";
      modifiedByUserIdColumnMapping.FormulaUpdate = "'" + modifiedUserId.ToString() + "'";
    }
}
```
