### ISSUE TITLE
[8.0.0-rc.1] BulkMerge, BulkAdd do not update generated Identity values correctly?

### ISSUE THREAD

**Issue by schuettecarsten** [zzzprojects/EntityFramework-Extensions#548]
When `BulkMerge` or `BulkAdd` insert new rows into the database, the generated Identity value is correctly taken from the database. The value changes from a negative number to a positive value was expected. That's fine. But with 8.0.0-rc.1 I get the following exception if I try to use the same entity again with `ChangeManager`, try to get the `EntityEntry` and set the State to `Unchanged`:

```
The property '<propertyname>' has a temporary value while attempting to change the entity's state to 'Unchanged'. Either set a permanent value explicitly, or ensure that the database is configured to generate values for this property.
```

This seems to happen because the property value "bit" is still set to "temporary". I do not use IncludeGraph or LegacyIncludeGraph settings at the moment. I have no idea how to "fix" the entities, whenever I try to modify the state or reload it, I get a similar exception.

This works when I downgrade to 7.0.11.

**Comment by JonathanMagnan** [comment]
Hello @schuettecarsten ,

We tried to reproduce it. but unfortunately, we failed. Either modifying some existing entities/adding some and changing the state after still working. We are missing the model on the configuration about this `bit` property that will help us to reproduce it.

Do you think you could create a runnable project with the issue? It doesn’t need to be your project, just a new solution with the minimum code to reproduce the issue.

Best Regards,

Jon

**Comment by schuettecarsten** [comment]
@JonathanMagnan 

I've created a demo project for the issue. You can download it here, it needs some explanation:
https://1drv.ms/u/s!Ajk93YqKTO5fiJBfRF7Ri67u-YVmpg?e=j06GRG

Please make sure to create the database by running `Update-Database" as migrations are note automatically executed on startup. When you run the project, it will throw an exception in line 69.

The code does the following:
1. Create a simple entity with FirstName value `William`
2. Add the entity to the Change Tracker (line 23) using `context.Add(entity)`
3. Use BulkMerge to add the entity to the database, check if a `William Shakespeare` already exists (lines 32 to 40)
4. Update the entity property FirstName to `Heinz`
5. Update the entity in the Change Tracker by calling `context.Update(entity)`
6. SaveChanges

The code produces the following output and exception:

```
Author.ID before Add: 0

Author.ID after Add: 0
EntityEntry state after Add: Added
Author.ID from EntityEntry values after Add: -2147482647

Author.ID after Merge: 1
EntityEntry state after Merge: Added
Author.ID from EntityEntry values after Merge: 1

Author.ID after State manipulation: 1
EntityEntry state after State manipulation: Added
Author.ID from EntityEntry values after State manipulation: 1

Author.ID after Update: 1
EntityEntry state after Update: Modified
Author.ID from EntityEntry values after Update: 1

Microsoft.EntityFrameworkCore.DbUpdateConcurrencyException:
The database operation was expected to affect 1 row(s), but actually affected 0 row(s); data may have been modified or deleted since entities were loaded. See http://go.microsoft.com/fwlink/?LinkId=527962 for information on understanding and handling optimistic concurrency exceptions.

```

The problem is that the entity state is not updated by `BulkMerge`. The ID is set to the identity value from the database, but the `EntityState` stays on `Added`. Because of this, `context.Update()` does not change the state to `Modified`. `SaveChanges` will try to add the entity again, this fails. So I need to set the `EntityState` to `Unmodified` after `BulkMerge`.

But there is another issue with BulkMerge.
Run the code again on the same database. This time, it will throw an exception in line 60:

```
Author.ID before Add: 0

Author.ID after Add: 0
EntityEntry state after Add: Added
Author.ID from EntityEntry values after Add: -2147482647

Author.ID after Merge: 0
EntityEntry state after Merge: Added
Author.ID from EntityEntry values after Merge: -2147482647

Author.ID after State manipulation: 0
EntityEntry state after State manipulation: Added
Author.ID from EntityEntry values after State manipulation: -2147482647

System.InvalidOperationException:
The property 'Author.AuthorId' has a temporary value while attempting to change the entity's state to 'Unchanged'. Either set a permanent value explicitly, or ensure that the database is configured to generate values for this property.
```

For some reasons, and I have no idea why, the `BulkMerge` call did not read the Author.ID value from the existing entity in the database as it did when the entity was inserted. I was not able to make my test code to update the IDs from the database for existing entities that match die merge key expression. On my other project, this works but I get some other exceptions. So we first need to make the ID update work for existing entities.

**Comment by JonathanMagnan** [comment]
Hello @schuettecarsten ,

Indeed, in your case, you currently use all your properties in your custom key. So the [BulkMerge](https://entityframework-extensions.net/bulk-merge) has nothing to `UPDATE`. It only expected to be able to `INSERT` rows.

In this specific case, you will need to use `ForceOutputFromUnmodifiedRow` such as:

```csharp
context.BulkMerge(entities, operation => {
	operation.ForceOutputFromUnmodifiedRow = true;
});
```

So the `Identity` will be also outputted for existing rows and ensure the value for the `Id` is no longer a temporary value.

Let me know if that explains correctly the cause and solution for this issue.

Best Regards,

Jon
