### ISSUE TITLE
Still missing column after updating database with Migration

### ISSUE THREAD

**Issue by maleet** [zzzprojects/EntityFramework-Extensions#549]
### Description
I have EF 6.4 application where I forgot to update latest Migration. So I updated database, but without application restart I still get same error message as there is missing column. I can confirm that there is now existing column. Is there some internal mapping cache used for BulkInsert and can I reset that without application restart?

```
Exception message:
An error occured while resolving mapping by name. See the inner exception for details
 ---> System.Exception: Missing Column : Res_ResBufferTimeBeforeExpr
On entity : AsprovaResource
On Table : [Asprova].[Resources]

**Comment by JonathanMagnan** [comment]
Hello @maleet ,

There is indeed a `Cache` to cache table information.

You can call the `RefreshModel` method to clear the cache everywhere:

```csharp
context.RefreshModel();
```

So if you have an admin screen or pass a parameter to a hidden page, you will be able to call this method.

Let me know if that answer correctly to your question.

Best Regards,

Jon

**Comment by maleet** [comment]
Thanks, that's exactly what was needed
