### ISSUE TITLE
Delete method is slow

### ISSUE THREAD

**Issue by ora8** [zzzprojects/EntityFramework-Extensions#55]
Hello
The first time delete method is so slow. Why? Following calls are fast.

**Comment by JonathanMagnan** [comment]
Hello @ora8 ,

How slow it's the first time? Do we talk about a few additional ms or a few seconds?

Our library like any library needs to be `JIT` compiled the first time it's used. So it may take up to an additional 100-500ms to get compiled.

Best Regards,

Jonathan

**Comment by ora8** [comment]
not ms, seconds, have of a minute.

**Comment by JonathanMagnan** [comment]
That's for sure VERY slow!!!

- Which provider are you using?
- Are you using code first or database first?
- Do you include the time `Entity Framework` first load also in this time (this one may take up to one minute)?

Is there anything you could think that could help us to reproduce this issue?

Best Regards,

Jonathan

**Comment by ora8** [comment]
- Sqlite
- database first
- How can I force to load the entity framework when starting the programm.

Our experience is, that the entity framework is generally slow. What can we do against.

Regards

Urs

**Comment by JonathanMagnan** [comment]
Hello @ora8 ,

Yes, from what I remember with tests I have done with `Sqlite` is the first `Entity Framework` load is **VERY** slow.

Please make sure to make any call to `Entity Framework` before checking the time taken by our library. By example, taking any value from the database will ensure it.

```csharp
using (var context = new CurrentContext())
{
    var firstLoad = context.Customers.First();
}
```

There is no so much you can do against `Entity Framework` first load. I believe there is some improvement that can be done to save a few seconds in your case, but the performance will still stay unacceptable.

Let me know if that answer successfully to the current problem or you believe there is something in our library that also is part of the performance issue.

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment]
Hello @ora8 ,

Feel free to reopen if you have more question.

Best Regards,

Jonathan
