### ISSUE TITLE
Missing values in target table

### ISSUE THREAD

**Issue by NicoKno** [zzzprojects/EntityFramework-Extensions#550]
### Description
I have this one Entity which behaves quite weird. When i sync my database with a BulkMerge the entities are beeing written, but my last two columns LinesAdded and LinesDeleted keep getting removed from the insert statement. See below. In this case I get the records in the target but only get the DefaultValue of "0" defined for the columns.
Is there some mechanism causing this?
The only option I set on the operation is KeepIdentityOnInsert = true;

Some help would be highly appreciated.

### Exception
No Exception

### Fiddle or Project (Optional)

```sql
SET IDENTITY_INSERT [data].[PartProgramValueChanges] ON;
MERGE INTO [data].[PartProgramValueChanges]  AS DestinationTable
USING
(
SELECT TOP 100 PERCENT * FROM (SELECT @0_0 AS [PartProgramValueChange_Id], @0_1 AS [GitCommitHashValue], @0_2 AS [GitRepository_Id], @0_3 AS [LinesAdded], @0_4 AS [LinesDeleted], @0_5 AS [PartProgram_Id], @0_6 AS [SourceTimestamp], @0_7 AS ZZZ_Index) AS StagingTable ORDER BY ZZZ_Index
) AS StagingTable
ON DestinationTable.[PartProgramValueChange_Id] = StagingTable.[PartProgramValueChange_Id]
WHEN MATCHED   THEN
UPDATE
SET     [GitCommitHashValue] = StagingTable.[GitCommitHashValue], [GitRepository_Id] = StagingTable.[GitRepository_Id], [LinesAdded] = StagingTable.[LinesAdded], [LinesDeleted] = StagingTable.[LinesDeleted], [PartProgram_Id] = StagingTable.[P
artProgram_Id], [SourceTimestamp] = StagingTable.[SourceTimestamp]
WHEN NOT MATCHED THEN
INSERT ( [PartProgramValueChange_Id], [GitCommitHashValue], [GitRepository_Id], [PartProgram_Id], [SourceTimestamp] )
VALUES ( [PartProgramValueChange_Id], [GitCommitHashValue], [GitRepository_Id], [PartProgram_Id], [SourceTimestamp] )
OUTPUT
    $action,
    StagingTable.ZZZ_Index,
    1,
    INSERTED.[LinesAdded] AS [LinesAdded_zzzinserted], INSERTED.[LinesDeleted] AS [LinesDeleted_zzzinserted]
```

### Further technical details
- EF version: 7.0
- EF Extensions version: 7.100.3
- Database Provider: SqlServer

**Comment by JonathanMagnan** [comment]
Hello @NicoKno ,

I'm not sure if I understand the problem correctly. Are you looking to be able to insert values to some properties that you have set a default value to them?

If that's the case, you should look at the [ForceValueGeneratedStrategy option](https://entityframework-extensions.net/forcevaluegeneratedstrategy)

Let me know if that was the cause and solution you were looking for. Otherwise, let me know more about the issue.

Best Regards,

Jon

**Comment by NicoKno** [comment]
Hi Jon,

thanks again for your help. That's actually the feature I was looking for and its nicely documented too. 

Best wishes.
