### ISSUE TITLE
InsertFromQuery ERROR: You currently try to map an entity type directly. You need to specify the property of this entity.

### ISSUE THREAD

**Issue by arnoabraham** [zzzprojects/EntityFramework-Extensions#554]
### Description
Trying to insert entities using InsertFromQuery extension. 
But receiving a System.Exception without much indication to how to resolve it.

### Exception
```
Exception message: System.Exception: Oops! You currently try to map an entity type directly. You need to specify the property of this entity.

Stack trace:
at .(IQueryable )
   at `1.()
   at `1.(IQueryable`1 , Action`1 )
   at `1.Execute(IQueryable`1 query, Action`1 batchInsertBuilder)
   at DbContextExtensions.InsertFromQuery[TEntity](IQueryable`1 query, String schemaName, String tableName, Expression`1 selectExpression)
```

### Fiddle or Project (Optional)
I can make a Fiddle if needed, indication into how possible resolve this error would be great already :)

### Further technical details

- EF version: EF Core v6.0.1
- EF Extensions version: EFE Core v6.13.12

**Comment by JonathanMagnan** [comment]
Hello @arnoabraham ,

Could you provide the code (the full LINQ you use with `InsertFromQuery`) you are using that throws that error.

Best Regards,

Jon

**Comment by arnoabraham** [comment]
Hi,

Figured out it was SQL having trouble with Math.Round in the select of the LINQ query. Removing Math.Round from my select resolved the error.

```C#
from roundPrice in q
select new InsertDto
{
  Price = roundPrice.Price.HasValue ? Math.Round(roundPrice.Price.Value, 12, MidpointRounding.AwayFromZero) : null,
};
```

Kr,

Arno
