### ISSUE TITLE
ExecuteFutureAction (with useTransactions = true) swallows exceptions and can throw "The underlying provider failed on Rollback." exception

### ISSUE THREAD

**Issue by WesleySSmith** [zzzprojects/EntityFramework-Extensions#556]
### Description
The way in which DbContextExtensions.ExecuteFutureAction is implemented can cause an actual database exception to be swallowed, and in some cases a "The underlying provider failed on Rollback." exception thrown instead.

This is not really a bug report, but rather a suggestion that would make the ExecuteFutureAction method better.

### Exception

```
Exception during notification message creation for event '1888e79c-f262-ee11-9935-002248be3e49':
System.Data.Entity.Core.EntityException: The underlying provider failed on Rollback.
   at void System.Data.Entity.Core.EntityClient.EntityTransaction.Rollback()
   at void System.Data.Entity.DbContextTransaction.Rollback()
   at void DbContextExtensions.ExecuteFutureAction<T>(T this, bool useTransaction)
   at <my code> in <my file>
```

### Analysis

In the case where ExecuteFutureAction is called with useTransaction = true, that method contains code similar to this:

```
      DbContextTransaction contextTransaction = @this.Database.BeginTransaction();
      try {
        // call registered actions
        contextTransaction.Commit();
      }
      catch (Exception ex)
      {
        contextTransaction.Rollback();
      }
      finally
      {
        if ((contextTransaction == null ? 1 : 0) == 0)
          contextTransaction.Dispose();
      }
```

If any of the actions throws an exception, then that exception will be caught, the transaction will be rolled back, but the original exception will be lost, and the caller will never know that something went wrong.

In addition, if the exception thrown by the action was a database exception, and that exception was a severe database error, then then call to contextTransaction.Rollback() will actually throw an exception itself, which the caller will see, but that "The underlying provider failed on Rollback." exception will not be useful for the caller, because it's not the actual, underlying exception.

This Entity Framework bug:  https://github.com/dotnet/EntityFramework.Docs/issues/327  provides some interesting background.  According that that bug, the  code in ExecuteFutureAction was probably modeled after some sample code that the Entity Framework team provided, which was later realized was bad advice.  That bug specifically suggests that the documentation be changed to the better approach:

```
    using (var dbContextTransaction = context.Database.BeginTransaction()) 
    { 
        DoSomeWork(context);
        context.SaveChanges(); 
        dbContextTransaction.Commit(); 
    } 
```

I suggest that ExecuteFutureAction might want to follow that suggestion and change to that new approach that will avoid swallowing any exceptions and let the caller see the underlying issue.

### Further technical details

- EF version: [EF 6.4.4]
- EF Extensions version: [EFE v7.100.0.5]
- Database Server version: [multiple]

**Comment by JonathanMagnan** [comment]
Hello @WesleySSmith ,

Thank you for reporting. I discussed this with my developer, and indeed, that's a suggestion we will look to implement very quickly.

Best Regards,

Jon

**Comment by JonathanMagnan** [comment]
Hello @WesleySSmith ,

The v7.101.0.0 has been released today.

Starting from this version, the exception should now be thrown correctly. If an exception also occurs during the rollback, the inner exception will contain the original exception that caused the issue in the first place.

Let me know if everything now works as intended.

Best Regards,

Jon
