### ISSUE TITLE
Npgsql.PostgresException: 23505: duplicate key value violates unique constraint 

### ISSUE THREAD

**Issue by StanlyLife** [zzzprojects/EntityFramework-Extensions#557]
### Exception
If you are seeing an exception, include the full exceptions details (message and stack trace).
![image](https://github.com/zzzprojects/EntityFramework-Extensions/assets/13099896/faf722f0-2929-4ccb-be13-148d8f8eb8f3)

`
Npgsql.PostgresException: '23505: duplicate key value violates unique constraint "IX_CardVehiclesUsed_VehicleOdometerBegin_VehicleRegistrationNu~"
`
`
DETAIL: Key ("VehicleOdometerBegin", "VehicleRegistrationNumber", "DriverCardId")=(222222, XXXXXX, XXXXXX) already exists.'
`
```
Exception message:
Stack trace: Npgsql.PostgresException: '23505: duplicate key value violates unique constraint "IX_CardVehiclesUsed_VehicleOdometerBegin_VehicleRegistrationNu~"
```

### Fiddle or Project (Optional)
Provide a Fiddle that reproduces the issue: https://dotnetfiddle.net/SeU6vJ
The fiddle is untested (and not running) but is a reproduction of similar code as to what's used in the project.
---

I think the main issue lies between the EntityTypeConfiguration:

```cs
        public void Configure(EntityTypeBuilder<CardVehiclesUsedPo> builder)
        {
            builder
                .HasIndex(
                    c =>
                        new
                        {
                            c.VehicleOdometerBegin,
                            c.VehicleRegistrationNumber,
                            c.DriverCardId
                        }
                )
                .IsUnique();
        }
```
and the bulkInsert

```cs
        public void AddRange(List<CardVehiclesUsedPo> cvu)
        {
            db.BulkInsert(
                cvu,
                options =>
                {
                    options.InsertIfNotExists = true;
                    options.ColumnPrimaryKeyExpression = p =>
                        new
                        {
                            p.DriverCardId,
                            p.VehicleOdometerBegin,
                            p.VehicleRegistrationNumber
                        };
                }
            );

            db.SaveChanges();
        }
```

and the fact that; when (trying to) adding duplicate data, instead of overwriting/updating, postgres throws an error.

---

### Further technical details

```xml
<TargetFramework>net7.0</TargetFramework>

<PackageReference Include="Z.EntityFramework.Extensions.EFCore" Version="7.100.0.5" />
<PackageReference Include="Microsoft.EntityFrameworkCore" Version="7.0.13" />
<PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="7.0.11" />
```

**Comment by StanlyLife** [comment]
Added image of error

**Comment by StanlyLife** [comment]
@JonathanMagnan Thank you for the explanation. Is there an option to; say "skip duplicates". E.g. Drop every duplicate in the list?

**Comment by JonathanMagnan** [comment]
Hello @StanlyLife ,

Thank you, we will look at it.

Just for your information, after using a method such as [BulkInsert](https://entityframework-extensions.net/bulk-insert), you do not have to call `SaveChanges`. The `BulkInsert` method is an immediate method that directly insert in the database.

Best Regards,

Jon

**Comment by StanlyLife** [comment]
Thank's @JonathanMagnan! Do you have any workarounds or other suggestions to get around the problem of trying to insert "large" amounts of data with a high likelihood of being duplicate-data into a database? This issue is currently holding us back from continuing the progress on our application.

**Comment by JonathanMagnan** [comment]
Hello @StanlyLife ,

The easiest way and fastest way would be on your side to ensure there is no duplicate, so the `AllowDuplicateKeys = true` will not be required.

Something like this:

```csharp
var toInsert = cvu.GroupBy(x => new
	{
		p.DriverCardId,
		p.VehicleOdometerBegin,
		p.VehicleRegistrationNumber
	}).Select(x => x.Last()).ToList();
```

**Comment by JonathanMagnan** [comment]
Hello @StanlyLife ,

I will close this issue as I believe there is nothing more to do here (we recently also improved some error messages related to when this scenario happened).

If I'm wrong, just let me know and we will re-open it.

Best Regards,

Jon
