### ISSUE TITLE
Trial for EF core 7

### ISSUE THREAD

**Issue by knopa** [zzzprojects/EntityFramework-Extensions#561]
Am I understand properly trial will be available only for latest .net ef core ?

**Comment by JonathanMagnan** [comment]
Hello @knopa,

No, the trial is available for all versions of EF Core, including EF Core 7.

You just need to download the latest version. with the first number corresponding to your EF Core version. In your case, the v7.101.1.0: https://www.nuget.org/packages/Z.EntityFramework.Extensions.EFCore/7.101.1

Let me know if that answers correctly to your question.

_NOTE: EF Extensions uses [EFCore-Pinned Versionning](https://entityframework-extensions.net/efcore-pinned-versioning) conventions_

Best Regards,

Jon

**Comment by knopa** [comment]
Thanks for reply,

Seems i was confused with release/tags versions

![image](https://github.com/zzzprojects/EntityFramework-Extensions/assets/1783681/465b1c17-a948-48e0-a4e6-830f6525c468)

**Comment by JonathanMagnan** [comment]
Yup, that's surely confusing. That's why we now add our [EFCore-Pinned Versionning](https://entityframework-extensions.net/efcore-pinned-versioning) conventions link on every release to try to make it as clear as possible.
