### ISSUE TITLE
BulkInsert taking 20+ min for 80 000 data rows

### ISSUE THREAD

**Issue by Lucian1000** [zzzprojects/EntityFramework-Extensions#562]
### Description
Currently we are experiencing very long importing times due to bulk insert taking 20+ mins for 80 000 data rows.
We are using following command:

```c#
await _dbContext.BulkInsertAsync(
    data,
    options =>
    {
        options.BatchSize = 100_000;
        options.InsertIfNotExists = true;
        options.AutoMapOutputDirection = false;
        options.ColumnPrimaryKeyExpression =
            t => new
                 {
                     // 12 columns here (basically all from table)
                 };
    });
```

Further information:
- Big database; table has more than 100 GB
- Time critical task; we really need fast insert because our users need to access the data asap

My guess is that the merge from temp table to the actual table takes very long due our big ColumnPrimaryKeyExpression. But there is no other way around except making an alternate hash key for it or smth. 

Does anyone have an idea how we can improve our statement here?

### Further technical details

- EF version: [EF Core v7.0.9]
- EF Extensions version: [EFE Core 7.22.4]
- Database Server version: [SQL Server 13.0]

**Comment by JonathanMagnan** [comment]
Hello @Lucian1000 ,

Is there a reason why your custom primary key has 12 columns? Something seems weird here, but it could also be the right way (hard to know without exactly knowing the scenario).

One solution we recently documented for another customer was to use a covering index to improved the performance: https://entityframework-extensions.net/improving-performance-of-bulkmerge-with-wherebulkcontains#solution-1-covering-index 

On the article, the covered index was making a lot of sense but it's not always the right solution either.

Let us know more why you have 12 columns as a key and if the covered index could be a solution or not in your case. If there is some private information, you can send it to us directly at info@zzzprojects.com

Best Regards,

Jon

**Comment by JonathanMagnan** [comment]
Hello @Lucian1000, 

Since our last conversation, we haven't heard from you. 

Let me know if you need more information. 

Best regards, 
Jon

**Comment by JonathanMagnan** [comment]
Hello @Lucian1000 ,

A simple reminder that we are here to assist you. 

Don't hesitate to contact us if you need further help. 

Best regards, 

Jon
