### ISSUE TITLE
WhereBulkContains throwing System.ArgumentNullException: 'Value cannot be null. (Parameter 'name')'

### ISSUE THREAD

**Issue by Wout-M** [zzzprojects/EntityFramework-Extensions#567]
### Description
I have a solution with multiple projects that interface with a database through EF Core (and Extensions) which is setup with a Database-First approach and reverse engineered with[ EF Core Power Tools](https://github.com/ErikEJ/EFCorePowerTools).

In these projects I'm using [WhereBulkContains](https://entityframework-extensions.net/where-bulk-contains) to fetch a set amount of items by Id. However, this seems to work for some projects but breaks for other projects.

From what I can find it seems that projects with a "normal" DbContext, the WhereBulkContains function just works. By normal I mean it has some DbSets, some EntityConfigurations in the OnModelCreation function and that's about it.
However, for projects where EF Core Power Tools generates sets & functions for a stored procedure, WhereBulkContains throws an error on any DbSet/Entity we want to use it on for said context.

For example, with the below Code part we would use WhereBulkContains on the ActiviteitGroupEntity set and without the stored procedures function it works and with the storedprocedure function it throws the above error, even though we don't do anything with the stored procedure during that time.

### Exception
The exception thrown when we try to use WhereBulkContains (and ToList to actually fetch it):

```
Exception message: Value cannot be null. (Parameter 'name')
Stack trace:

   at Microsoft.EntityFrameworkCore.Metadata.StoreObjectIdentifier.Table(String name, String schema)
   at Z.EntityFramework.Extensions.EntityTypeZInfo..ctor(IEntityType entityType)
   at PublicExtensions..(IEntityType )
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Z.EntityFramework.Plus.QueryHookCommandInterceptor.<>c.(IEntityType )
   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source, Func`2 predicate)
   at Z.EntityFramework.Plus.QueryHookCommandInterceptor.InterceptorForAllExecuting(DbCommand command, DbContext context, Boolean isNotCTE)
   at Z.EntityFramework.Plus.QueryHookCommandInterceptor.ReaderExecuting(DbCommand command, DbCommandInterceptionContext`1 interceptionContext)
   at Z.EntityFramework.Extensions.InternalDbCommandInterceptorObserver.OnNext(KeyValuePair`2 value)
   at System.Diagnostics.DiagnosticListener.Write(String name, Object value)
   at Microsoft.EntityFrameworkCore.Diagnostics.IDiagnosticsLogger.DispatchEventData(EventDefinitionBase definition, EventData eventData, Boolean diagnosticSourceEnabled, Boolean simpleLogEnabled)
   at Microsoft.EntityFrameworkCore.Diagnostics.Internal.RelationalCommandDiagnosticsLogger.CommandReaderExecuting(IRelationalConnection connection, DbCommand command, DbContext context, Guid commandId, Guid connectionId, DateTimeOffset startTime, CommandSource commandSource)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReader(RelationalCommandParameterObject parameterObject)
   at Microsoft.EntityFrameworkCore.Query.Internal.SplitQueryingEnumerable`1.Enumerator.InitializeReader(Enumerator enumerator)
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerExecutionStrategy.Execute[TState,TResult](TState state, Func`3 operation, Func`3 verifySucceeded)
   at Microsoft.EntityFrameworkCore.Query.Internal.SplitQueryingEnumerable`1.Enumerator.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at BuildSoftware.BackOffice.DL.Repositories.ExternalLinkWerfRepository.GetWervenLinkAll() in C:\Sources\Build.net (master)\Main\BuildSoftware\BackOffice\BuildSoftware.BackOffice.DL\Repositories\ExternalLinkWerfRepository.cs:line 57
```

### Code
All code is automatically generated by EF Core Power Tools, but simplified for the example.

Calling WhereBulkContains:
```csharp
using var context = new BackOfficeContext();
var entites = context.ActiviteitGroupEntity
    .AsNoTracking()
    .WhereBulkContains(new List<long> { 1, 2, 3 }, x => new { x.ActGroupId })
    .ToList();
```

"Normal" context:
```csharp
 public partial class BackOfficeContext : DbContext
 {
     public DbSet<ActiviteitGroupEntity> ActiviteitGroupEntity { get; set; }

     public BackOfficeContext()
         : base(new DbContextOptionsBuilder<BackOfficeContext>()
             .UseSqlServer(
                 Framework.General.Connection.ConnectionString,
                 o => o.UseQuerySplittingBehavior(QuerySplittingBehavior.SplitQuery))
             .Options)
 {
     Database.SetCommandTimeout(new Framework.DL.Repository.GeneralRepository().GetDomainTimeout(this));
 }

 public BackOfficeContext(DbContextOptions<BackOfficeContext>
     options) : base(options)
     {
     }

     protected override void OnModelCreating(ModelBuilder modelBuilder)
     {
         modelBuilder.UseCollation("Latin1_General_CI_AS");

         modelBuilder.ApplyConfiguration(new Configurations.ActiviteitGroupEntityConfiguration());
         modelBuilder.HasSequence("seqOGMNumber", "Invoice");
         OnModelCreatingPartial(modelBuilder);
     }

     partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
 }
```

Same context, but with stored procedure:
```csharp
public partial class BackOfficeContext : DbContext
{
    public DbSet<ActiviteitGroupEntity> ActiviteitGroupEntity { get; set; }

    public BackOfficeContext()
        : base(new DbContextOptionsBuilder<BackOfficeContext>()
            .UseSqlServer(
                Framework.General.Connection.ConnectionString,
                o => o.UseQuerySplittingBehavior(QuerySplittingBehavior.SplitQuery))
            .Options)
{
Database.SetCommandTimeout(new Framework.DL.Repository.GeneralRepository().GetDomainTimeout(this));
}

public BackOfficeContext(DbContextOptions<BackOfficeContext>
    options) : base(options)
    {
    }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.UseCollation("Latin1_General_CI_AS");

        modelBuilder.ApplyConfiguration(new Configurations.ActiviteitGroupEntityConfiguration());
        modelBuilder.HasSequence("seqOGMNumber", "Invoice");

        OnModelCreatingGeneratedProcedures(modelBuilder);
        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}
```

OnModelCreatingGeneratedProcedures function and other generated functions for it:
```csharp
public partial class BackOfficeContext
{
    private IBackOfficeContextProcedures _procedures;

    public virtual IBackOfficeContextProcedures Procedures
    {
        get
        {
            if (_procedures is null) _procedures = new BackOfficeContextProcedures(this);
            return _procedures;
        }
        set
        {
            _procedures = value;
        }
    }

    public IBackOfficeContextProcedures GetProcedures()
    {
        return Procedures;
    }

    protected void OnModelCreatingGeneratedProcedures(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<spBackOfficeApproveWorkDayResult>().HasNoKey().ToView(null);
    }
}

public partial class BackOfficeContextProcedures : IBackOfficeContextProcedures
{
    private readonly BackOfficeContext _context;

    public BackOfficeContextProcedures(BackOfficeContext context)
    {
        _context = context;
    }

    public virtual List<spBackOfficeApproveWorkDayResult> spBackOfficeApproveWorkDay(int? CompanyID, DateTime? Date, OutputParameter<int> returnValue = null)
    {
        var parameterreturnValue = new SqlParameter
        {
            ParameterName = "returnValue",
            Direction = System.Data.ParameterDirection.Output,
            SqlDbType = System.Data.SqlDbType.Int,
        };

        var sqlParameters = new[]
        {
            new SqlParameter
            {
                ParameterName = "CompanyID",
                Value = CompanyID ?? Convert.DBNull,
                SqlDbType = System.Data.SqlDbType.Int,
            },
            new SqlParameter
            {
                ParameterName = "Date",
                Value = Date ?? Convert.DBNull,
                SqlDbType = System.Data.SqlDbType.Date,
            },
            parameterreturnValue,
        };
        var _ = _context.SqlQuery<spBackOfficeApproveWorkDayResult>("EXEC @returnValue = [dbo].[spBackOfficeApproveWorkDay] @CompanyID, @Date", sqlParameters);

        returnValue?.SetValue(parameterreturnValue.Value);

        return _;
    }
}

public static class DbContextExtensions
{
    public static List<T> SqlQuery<T>(this DbContext db, string sql, object[] parameters = null) where T : class
    {
        if (parameters is null)
        {
            parameters = new object[] { };
        }

        if (typeof(T).GetProperties().Any())
        {
            return db.Set<T>().FromSqlRaw(sql, parameters).ToList();
        }
        else
        {
            db.Database.ExecuteSqlRaw(sql, parameters);
            return default;
        }
    }
}

public class OutputParameter<TValue>
{
    private bool _valueSet = false;

    public TValue _value;

    public TValue Value
    {
        get
        {
            if (!_valueSet)
                throw new InvalidOperationException("Value not set.");

            return _value;
        }
    }

    internal void SetValue(object value)
    {
        _valueSet = true;

        _value = null == value || Convert.IsDBNull(value) ? default(TValue) : (TValue)value;
    }
}
```

The entity & configuration:
```csharp
public partial class ActiviteitGroupEntity
{
    public long ActGroupId { get; set; }
    public string ActGroup { get; set; }
    public string Code { get; set; }
    public int ShowAsMode { get; set; }
    public string ShowAs { get; set; }
}

public partial class ActiviteitGroupEntityConfiguration : IEntityTypeConfiguration<ActiviteitGroupEntity>
{
    public void Configure(EntityTypeBuilder<ActiviteitGroupEntity> entity)
    {
        entity.HasKey(e => e.ActGroupId);

        entity.ToTable("tActiviteitGroup", "Settings");

        entity.Property(e => e.ActGroupId).HasColumnName("ActGroupID");

        entity.Property(e => e.ActGroup)
            .IsRequired()
            .HasMaxLength(150);

        entity.Property(e => e.Code).HasMaxLength(15);

        entity.Property(e => e.ShowAs).HasMaxLength(120);

        entity.Property(e => e.ShowAsMode).HasColumnName("ShowASMode");

        OnConfigurePartial(entity);
    }

    partial void OnConfigurePartial(EntityTypeBuilder<ActiviteitGroupEntity> entity);
}
```

### Further technical details

- EF version: [EF Core v6.0.21]
- EF Extensions version: [EFE Core v6.22.6]
- Database Server version: [SQL Server 2019]
- Database Provider version (NuGet, comes with Microsoft.EntityFrameworkCore.SqlServer): [Microsoft.Data.SqlClient v2.1.4]

**Comment by JonathanMagnan** [comment]
Hello @Wout-M ,

Thank you for reporting. I don't think it will be possible to support it but we will still look at it as I might be wrong

Best Regards,

Jon

**Comment by Wout-M** [comment]
Hi @JonathanMagnan,

What do you mean by supporting it or not?
Do you mean resolving this issue (in the version we're using or a later version) or something else?

**Comment by JonathanMagnan** [comment]
Hello @Wout-M ,

Do you think you could create a runnable project with the issue? It doesn’t need to be your project, just a new solution with the minimum code to reproduce the issue. Include either a backup of the database (only what is required) or the script creation for everything that is needed. You can send it in private here if needed: info@zzzprojects.com

You provided most of the information, but some stuff is still missing on our side to create a runnable project.

The current problem is that our library cannot find the `table` in which the entity is mapped. But if there is indeed no table mapped, there is nothing we can really do as we cannot use the stored procedure to make a join statement.

We see in your code that you still look to have a table mapping set: `entity.ToTable("tActiviteitGroup", "Settings");`

So having a project will help us to find out why we cannot find this table and ensure we work on the right issue.

Best Regards,

Jon

**Comment by Wout-M** [comment]
[test.zip](https://github.com/zzzprojects/EntityFramework-Extensions/files/13939791/test.zip)


Hey @JonathanMagnan , 
I've attached a zip file with a full solution and database backup with the minimum amount of tables & procedures possible. 
You might need to edit the security on the database and/or the connection string in both contexts to make sure you can connect properly, but everything else should work. And of course you'd need to add the license credentials for your extension (I've tested it with ours and then changed it before sending it in the zip).

The result for without stored procedures in the context:
![image](https://github.com/zzzprojects/EntityFramework-Extensions/assets/38492330/eee89ecb-16df-412f-bcbf-c48792158bf2)

The result with stored procedures in the context (which we don't use for the fetching):
![image](https://github.com/zzzprojects/EntityFramework-Extensions/assets/38492330/530b4283-a302-4fe3-94e9-f6f2a0604dea)

**Comment by JonathanMagnan** [comment]
Hello @Wout-M ,

Thank you a lot for the project.

My developer told me he can now reproduce it so he will work on this issue this week.

Best Regards,

Jon

**Comment by Wout-M** [comment]
Hey @JonathanMagnan ,

Sorry to bother you, but is there any update on this already?

Kind regards
Wout

**Comment by Wout-M** [comment]
Hi @JonathanMagnan,

Has there been any progress on this?

**Comment by JonathanMagnan** [comment]
Hello @Wout-M ,

Sorry for the delay in my answer.

We have made some progress on this request. We currently know what caused the issue and how we could fix it.

We are currently working on it, but some core changes are required to be modified in our library to allow this scenario.

So it will take a few more weeks, but a fix is coming.

One easy way for you to still be able to use the `WhereBulkContains` method meanwhile is just having a second context that has no stored procedure that you can use only for this kind of scenario.

Best Regards,

Jon

**Comment by Wout-M** [comment]
Hi @JonathanMagnan,

Is there any news on the progress?

**Comment by JonathanMagnan** [comment]
Hello @Wout-M ,

I talked with my developer today.

We plan to fix it, but it's currently not part of our short-term plan (it will come eventually during the year). However, my developer proposed an alternative solution that we could use to fix the issue; it's not the best solution, but it will be better than nothing.

So we will start to work on it and see if his idea is working. I will be better to give you a better update in 1-2 weeks, and let's hope that his idea is working.

Best Regards,

Jon

**Comment by JonathanMagnan** [comment]
Hello @Wout-M ,

Just to let you know that the temporary fix made by my developer has been merged in the master and will be available next time we release this project (on February 20 or 27).

Best Regards,

Jon

**Comment by JonathanMagnan** [comment]
Hello @Wout-M ,

A new version has been released today.

Could you try it and let us know if the issue has been fixed correctly?

As said, we have currently done a quick fix, which should work, but a better fix will also come very soon.

Best Regards,

Jon

**Comment by Wout-M** [comment]
Hey @JonathanMagnan ,

I've let the team know that uses it.
I'll tell you when I hear back from them.

Kind regards
Wout

**Comment by JonathanMagnan** [comment]
Hello @Wout-M, 

Great to hear everything is working as expected. 

Let me know if you need further assistance. 

Best regards, 
Jon
