### ISSUE TITLE
IncludeOptimizedByPath case sensitivity

### ISSUE THREAD

**Issue by madatanic** [zzzprojects/EntityFramework-Extensions#57]
It looks like the IncludeOptimizedByPath's string parameter is case sensitive while out-of-the-box EF's Include is not.

**Comment by JonathanMagnan** [comment]
Hello @madatanic ,

Thank you for letting me know, I didn't know Include was not case sensitive ;)

I will for sure investigate this issue.

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment]
Hello @madatanic ,

The v1.7.2 has been released.

IncludeOptimizedByPath is now string insensitive

Please reopen if we have not fixed correctly and make sure to post the issue in the right forum :) https://github.com/zzzprojects/EntityFramework-Plus

Best Regards,

Jonathan
