### ISSUE TITLE
While inserting new record through BulkMerge it's not overriding default constraint value

### ISSUE THREAD

**Issue by Omprakashkumar21** [zzzprojects/EntityFramework-Extensions#572]
### Description
While inserting new record through BulkMerge it's not overriding default constraint value for a column but it's working fine with update. I am using EFCore 7 and .net 6.

```csharp
public virtual void InsertOrUpdateRange(IEnumerable<T> entities, bool autoDetectChanges = true)
        {
            _entities.Database.SetCommandTimeout(180);
            _entities.ChangeTracker.AutoDetectChangesEnabled = autoDetectChanges;
            try
            {
                _entities.BulkMerge(entities, options => options.ColumnPrimaryKeyExpression = r => r.Id);
            }
            catch (DbUpdateConcurrencyException)
            {
                throw;
            }
            finally
            {
                _entities.ChangeTracker.AutoDetectChangesEnabled = true;
            }
        }
```

**Comment by Omprakashkumar21** [comment]
Example - default value for a Int column is 60 in database, but I am setting it as 1 from UI/Code , but after bulkmerge database is reflecting 60 only while insert but while update it is setting 1

**Comment by JonathanMagnan** [comment]
Hello @Omprakashkumar21 ,

See the option [ForceValueGeneratedStrategy](https://entityframework-extensions.net/forcevaluegeneratedstrategy) documentation to understand more about this behavior and how to fix it.

Let me know if that solved your issue.

Best Regards,

Jon

**Comment by JonathanMagnan** [comment]
Hello @Omprakashkumar21, 

Since our last conversation, we haven't heard from you. 

Let me know if everything is working as expected. 

Best regards, 

Jon
