### ISSUE TITLE
The type initializer for 'Z.BulkOperations.LicenseManager' threw an exception

### ISSUE THREAD

**Issue by YSFKBDY** [zzzprojects/EntityFramework-Extensions#573]
### Description
I have a study project and I am using BulkUpdate int it. The method works on localhost while debugging, but gives an error when I deploy my project to my private server. Do I need a licence for using?

### Exception
The type initializer for 'Z.BulkOperations.LicenseManager' threw an exception.

```
Exception message:
Stack trace: at .(ProviderType , Boolean , Boolean , Boolean , Boolean ) at Z.BulkOperations.BulkOperation.Execute() at Z.BulkOperations.BulkOperation.BulkUpdate() at .BulkUpdate[T](DbContext this, IEntityType entityType, IEnumerable`1 list, Action`1 options, SavingSelector savingSelector, Boolean forceSpecificTypeMapping) at .BulkUpdate[T](DbContext this, IEnumerable`1 entities, Action`1 options, Boolean isBulkSaveChanges) at DbContextExtensions.BulkUpdate[T](DbContext this, IEnumerable`1 entities, Action`1 options) at DbContextExtensions.`1.() at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state) --- End of stack trace from previous location where exception was thrown --- at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread) --- End of stack trace from previous location where exception was thrown --- at .[](DbContext , Func`2 , Action`1 , CancellationToken ) at Libraries.odex.api.ScheduleTasks.CheckCurrencyTask.Process(DataContext context, IConfiguration config)
```

### Further technical details

- EF version: [EF Core v3.1.32]
- EF Extensions version: [EFE Core v3.102.1]

**Comment by JonathanMagnan** [comment]
Hello @YSFKBDY ,

Do you think you could create a runnable project with the issue? It doesn’t need to be your project, just a new solution with the minimum code to reproduce the issue.

If it contains a real license, you can send the project here: info@zzzprojects.com

Without a license, you can use our library for free (updating to the latest version every month to keep being in trial mode).

So, this error is not expected at all.

Best Regards,

Jon

**Comment by YSFKBDY** [comment]
Hi @JonathanMagnan,

I don't think I can do that, but I can show you my code changes before and after BulkOperation changes.

**Before:**

    foreach (var u in users)
    {
        u.UpdatedOn = DateTime.Now;

        context.Entry(u).State = EntityState.Modified;
    }

    await context.SaveChangesAsync();

**After:**

    foreach (var u in users)
    {
        u.UpdatedOn = DateTime.Now;
    }

    await context.BulkUpdateAsync(users, opt => opt.BatchSize = 5000);

I have appr. 20k test datas, but that will go way up while testing day by day. As you can see, I've changed only two lines.

I hope that would be helpful.

Regards,
Y.

**Comment by JonathanMagnan** [comment]
Hello @YSFKBDY ,

Unfortunately, that will not help.

The current error happens in our static method in the `Z.BulkOperations.LicenseManager` that tries to initialize. So, the error will happen as soon as you use any of our paid features (and even a few free).

Why does it happen in your case? It is almost impossible at this moment to know. Perhaps that's only a missing dependency that has been deleted in your project or something like that. We already have some try/catch in the static method so we don't expect any error to be able to happen.

The only way to better understand this issue is by having a project that can reproduce it.

Best Regards,

Jon

**Comment by YSFKBDY** [comment]
Hey @JonathanMagnan,

It was a missing dependency. I forgot to upload a dll file. When I've uploaded it, it worked like a charm. So, my mistake. :( Thank you for your time.

Regards,
Y.

**Comment by JonathanMagnan** [comment]
Hello @YSFKBDY , 

Great to hear everything is working as expected. 

Don't hesitate to contact us if you need further assistance. 

Best regards, 

Jon

**Comment by YSFKBDY** [comment]
Hello again @JonathanMagnan,

When the trial period is expired - which I am checking it with like this:

    if (Z.BulkOperations.LicenseManager.IsTrialExpired())
    {
        //Doing some stuff to warn me.
    }

I've uninstalled the NuGet package and reinstalled it, then deployed it, but it doesn't work.  `Z.BulkOperations.LicenseManager.IsTrialExpired()` is returning true instead of false. What am I missing here? Am I doing this "updating to the latest version every month to keep being in trial mode" part wrong?

**Comment by JonathanMagnan** [comment]
Hello @YSFKBDY ,

Sometimes you just need to clean the solution and rebuild it (the old `dll` might still be used). Your code look perfect.

If the problem persists, do you think you could create a runnable project with the issue? It doesn’t need to be your project, just a new solution with the minimum code to reproduce the issue. You can send it in private here: info@zzzprojects.com

That will be way easier for us to understand why it's not working on your case with a project. It looks like an issue with dll, so we cannot really reproduce it in our side.

Best Regards,

Jon

**Comment by YSFKBDY** [comment]
Hi @JonathanMagnan,

I've cleaned and rebuild the solution, then published it to my server, but nothing changed. Still not using the bulk update. 

I tried to reproduce this issue with a new solution, but it works as intended. 

Steps that I follow to update:

* Manage NuGet packages, and remove the package.
* Reinstall the package
* Clean the solution
* Rebuild the solution
* Publish it

Are there any hints for it updated successfully that I understand?

Regards,
Y.

**Comment by YSFKBDY** [comment]
Hi @JonathanMagnan,

It says `Assembly: Z.EntityFramework.Extensions.EFCore, Version=3.102.2.0, Culture=neutral, PublicKeyToken=XXXXXXXXXXX`. Don't know it is correct or not.

**Comment by JonathanMagnan** [comment]
Hello @YSFKBDY ,

That is indeed the latest version. I was not expecting this answer, which makes it harder to understand why it is happening.

What is the date on your server? It looks like a dumb question, but this is the only thing I can think of at this moment that could cause the issue if your server date has, by example, the wrong year.

**Comment by JonathanMagnan** [comment]
Hello @YSFKBDY , 

Since our last conversation, we haven't heard from you. 

Let me know if you need more infomation. 

Best regards, 
Jon

**Comment by JonathanMagnan** [comment]
Hello again, 

A simple reminder that we are here to assist you. 

Don't hesitate to contact us if you have any questions. 

Best regards, 
Jon
