### ISSUE TITLE
`PublicExtensions` static dictionaries are filling up

### ISSUE THREAD

**Issue by alexeygnetko** [zzzprojects/EntityFramework-Extensions#574]
Hello,

### Description

We found that static dictionaries from the `PublicExtensions` class are leaking in our project. They're getting filled up till we get Out of Memory kill. 

Could you let me know if you've seen this issue?

Please see the screenshot below. The dictionaries grow to approximately these sizes before OOM kill (we have a memory limit set to 4GB in Kubernetes):
```
# from PublicExtensions.cs
EntityTypeZInfoDict: 4174 items
PropertyZInfoDict: 36049 items
ModelZInfoDict: 604 items
```
<img width="552" alt="image" src="https://github.com/zzzprojects/EntityFramework-Extensions/assets/33511189/b34743b2-7473-4a85-8fa0-dd9b2093d283">

I don't have a reproducible code example at the moment, but I will provide it when I have it.

### Exception

No exceptions.

### Further technical details

- EF version: [EF Core v7.0.16]
- EF Extensions version: [EFE Core v7.18.1]
- Database Server version: [SQL Server 2018]
- Database Provider version (NuGet): [Microsoft.Data.SqlClient v5.1.4]

**Comment by JonathanMagnan** [comment]
Hello @alexeygnetko ,

Is there something special with your context?

The `EntityTypeZInfoDict` holds your entity type. Does your model really have 4174 and more entity types? Could you let us know more about your context? (if you want to keep some info private, you can contact us here: info@zzzprojects.com)

You can clear those cached dictionaries with `context.RefreshModel();` but surely better understanding why it happens in your case is the best idea.

Best Regards,

Jon

**Comment by JonathanMagnan** [comment]
Hello @alexeygnetko, 

Since our last conversation, we haven't heard from you. 

Let me know if you need further assistance. 

Best regards, 
Jon

**Comment by alexeygnetko** [comment]
Hi @JonathanMagnan,

Thanks for pointing it out. We already did a cleanup of these dictionaries after a certain threshold, but haven't found a root cause yet.

Please, feel free to close the ticket as my replies can be delayed. If I have a reproducible example, I'll get back to you and re-open the issue.

Thank you.
