### ISSUE TITLE
Microsoft.Data.SqlClient is on a vulnerable version - security update

### ISSUE THREAD

**Issue by tim-stuyckens-materialise** [zzzprojects/EntityFramework-Extensions#580]
### Description
Upgrade Microsoft.Data.SqlClient to patched version

Currently 3th party vulnerability scanning tools are pointing out a possible issue.
Not saying this is a risk, but it would be nice to have clean reports.

### Exception
If you are seeing an exception, include the full exceptions details (message and stack trace).

![image](https://github.com/zzzprojects/EntityFramework-Extensions/assets/134292323/b49db4fb-1b6f-454d-9a8d-827d46c22d57)

**Comment by JonathanMagnan** [comment]
Hello @tim-stuyckens-materialise ,

That's not our library. You are currently using another paid library and not https://entityframework-extensions.net/

Best Regards,

Jon
