### ISSUE TITLE
Open connections asynchronously when using AAD authentication

### ISSUE THREAD

**Issue by patilsagar-suma** [zzzprojects/EntityFramework-Extensions#589]
### Description
BulkInsertAsync() throw exception when inserting bulk record in database. 

Same method was working properly with version Framework.Extensions.EFCore 7.102.2.1

SQL: Azure DB

### Exception
Open connections asynchronously when using AAD authentication

### Further technical details

- EF version: [EF Core v7.0.8]
- EF Extensions version: [EFE Core v7.102.3]

**Comment by JonathanMagnan** [comment]
Hello @patilsagar-suma ,

We will need more information to help you with this issue.

What exactly is the exception that has been thrown? Could you show us the error message and stack trace?

Best Regards,

Jon

**Comment by JonathanMagnan** [comment]
Thank you @patilsagar-suma for this additional information,

We might need some part of your code but first we will try using the interceptor we found on this blog to try it: https://mderriey.com/2020/09/12/resolve-ef-core-interceptors-with-dependency-injection/

Best Regards,

Jon

**Comment by patilsagar-suma** [comment]
Thank you @JonathanMagnan I have verified all code. All existing EF methods work fine with the same code but when I use BulkInsertAsync then throwing exception.

My observation: With previous version 7.102.2.1 everything works fine.
When I started a recent investigation, the previous package version was not available and with version 7.102.3 getting exception.

Is there any chance to use EFCore v7.102.2.1 (for a short time) then I will confirm.

**Comment by patilsagar-suma** [comment]
Thank you @JonathanMagnan I have verified all code. All existing EF methods work fine with the same code but when I use BulkInsertAsync then throwing exception.

My observation: With previous version 7.102.2.1 everything works fine.
When I started a recent investigation, the previous package version was not available and with version 7.102.3 getting exception.

Is there any chance to use EFCore v7.102.2.1 (pre-release also fine for testing for brief time) then I will confirm.

**Comment by patilsagar-suma** [comment]
Thank you @JonathanMagnan I have verified all code. All existing EF methods work fine with the same code but when I use BulkInsertAsync then throwing exception.

My observation: With previous version 7.102.2.1 everything works fine.
When I started a recent investigation, the previous package version was not available and with version 7.102.3 getting exception.

Is there any chance to use EFCore v7.102.2.1 (for short time) then I will confirm.

**Comment by JonathanMagnan** [comment]
Hello @patilsagar-suma ,

Any previous version is always available through the Package Manager command, they are just hidden by from the "NuGet Package Manager" but always available.

That being said, I make this version visible again: https://www.nuget.org/packages/Z.EntityFramework.Extensions.EFCore/7.102.1.1

I will wait for your confirmation before exploring this as AAD Authentification is currently something we have never done.

Best Regards,

Jon

**Comment by patilsagar-suma** [comment]
Hi @JonathanMagnan Thanks for re-opening package.

Looks like something wrong when open connection by BulkInsertAsync method. We have two scenario to use of BulkInserAsysn method.

Example:

1. For Table1 we are inserting 26K records and it's works fine without any error. **await Context.Table1.BulkInsertAsync(records);**
2. For table2 we are inserting 5K records and here is error. **await Context.Table2.BulkInsertAsync(records);**

For scenario 1 **DbConnectionInterceptor** use **ConnectionOpeningAsync** method. But for scenario 2 it is using **ConnectionOpening**. In the second case behavior of method is different, can you have any idea why second table BulkInsertAsync method use non async method for opening connection?

Thanks in advance. We also debug the same to find out root cause for this. Let me know if you want any more information

Attaching DbConnectionInterceptor screenshot.
![image](https://github.com/zzzprojects/EntityFramework-Extensions/assets/160761713/fe91767d-5e04-42ef-990e-f7d35542d8e7)

**Comment by JonathanMagnan** [comment]
Hello @patilsagar-suma ,

Is it possible on the first BulkInsert (`await Context.Table1.BulkInsertAsync(records);`) that you already opened the connection yourself?

Our library doesn't use `OpenAsync` when using `BulkInsertAsync`. We keep using the same path as we are currently using for the `BulkInsert` for some part such as how we handle the connection.

From what we know, there should not be any difference in the behavior, but we could be wrong.

Could you share your interceptor code for your AAD authentification or a minimum prototype project that reproduces it? We would like to make sure we will work to debug the same problem as you.

Best Regards,

Jon

**Comment by patilsagar-suma** [comment]
Hi @JonathanMagnan we figured out a solution. We need to use BulkInsertAsync method inside DbContextTransaction then it is working. 
Now we will figure out why DbContextTransaction is needed to open connection async. If we do not use DbContextTransaction then the connection is opening in non async way.
