### ISSUE TITLE
Error when Attempting BulkOperations

### ISSUE THREAD

**Issue by mitchelsellers** [zzzprojects/EntityFramework-Extensions#59]
Looking at the documentation, we cannot see where we have gone wrong at all, but any inclusion of a bulk operation fails....

We have our Context, with the following two constructors.

```
public MyAppContext(DbContextOptions<MyAppContext> options) : base(options)
        {
            //Setup Audit save
            AuditManager.DefaultConfiguration.ExcludeDataAnnotation();
            AuditManager.DefaultConfiguration.IgnorePropertyUnchanged = true;
        }

        public RCSDbContext()
        {
        }
```

When we try to use any of the Bulk operations we are given the following error.

`InvalidOperationException: No database provider has been configured for this DbContext. A provider can be configured by overriding the DbContext.OnConfiguring method or by using AddDbContext on the application service provider. If AddDbContext is used, then also ensure that your DbContext type accepts a DbContextOptions<TContext> object in its constructor and passes it to the base constructor for DbContext.`

Based on that error, and this post: https://github.com/aspnet/EntityFrameworkCore/issues/6826 we tried removing the parameterless constructor and get this error

`A default DbContext context must exist, or a context factory must be provided (EntityFrameworkManager.ContextFactory). This setting is required for some additional features.
`

This is using latest version of all packages, including EFE and EFCore.

**Comment by JonathanMagnan** [comment]
Hello @mitchelsellers ,

Starting with `EF Core`, our library require either your context to contains a paramelerless constructor or provide a factory.

By example:

```csharp
EntityFrameworkManager.ContextFactory = context => {
                // CREATE a real new context here
                var db = new DbContextOptionsBuilder();
                db.UseInMemoryDatabase();
                return new EntityContext(db.Options);
}
```

We use this context to only get additional information about entity to make sure we don't impact the context you are currently using.

Let me know if that's working once you set a `ContextFactory`

Best Regards,

Jonathan

**Comment by mitchelsellers** [comment]
Jonathan - We have the parameterless constructor though?  Would it have to be the ONLY constructor?  We are using DI for injection of our context, so I don't necessarily want to go around creating new ones everywhere

**Comment by mitchelsellers** [comment]
@JonathanMagnan I did decide to try that, and it does work with this step.  My temporary hack around is to do this, in the one area I'm working right now.

`EntityFrameworkManager.ContextFactory = context => { return _context; };`

Can I do this in startup.cs?  And just have it call the serviceProvider to get the proper dependency Injected object?

**Comment by JonathanMagnan** [comment]
Hello @mitchelsellers ,

Sure you can do it in `startup.cs`.

>  And just have it call the serviceProvider to get the proper dependency Injected object?

The question is a little bit to vague on my side to make sure of my answer. The answer will be probably yes

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment]
Hello @mitchelsellers ,

I will close this issue since it seems answered.

Feel free to reopen if you have more questions.

Best Regards,

Jonathan
