### ISSUE TITLE
BulkMerge not inserting records in Temporal table

### ISSUE THREAD

**Issue by dsorre** [zzzprojects/EntityFramework-Extensions#593]
When using the BulkMerge feature none of the updated/added records are recorded into the associated temporal table, however using BulkDelete does record temporal data correctly. Is there an option on BulkMerge to allow recording of temporal data?

**Comment by JonathanMagnan** [comment]
Hello @dsorre ,

I just double-checked, and everything works on my side with Temporal Table.

Newly added rows are never recorded in the associated temporal table, but this is the normal behavior of a temporal table

However, any updated rows were correctly recorded into the associated table.

Perharps, when you tested, you only had new rows which could explain why you didn't see anything?

Best Regards,

Jon

**Comment by dsorre** [comment]
Jon -

I think this is a classic "duh" moment and you are right! There was one other issue where it populated all fields except for one in the temporal table, but I was able to fix that by just manually specifying the properties using ColumnInputExpression.

Thanks for your quick reply!
