### ISSUE TITLE
ForceValueGeneratedStrategy - Where'd it go?

### ISSUE THREAD

**Issue by TonyValenti** [zzzprojects/EntityFramework-Extensions#594]
In some of our code, we had:
```
Options.ForceValueGeneratedStrategy = Z.EntityFramework.Extensions.ValueGeneratedStrategyType.OnAdd;
```

When testing the latest version, this seems to have gone away.  What is its replacement?

**Comment by JonathanMagnan** [comment]
Hello @TonyValenti ,

See the following release notes: https://github.com/zzzprojects/EntityFramework-Extensions/releases/tag/8.103.0.0

On your side:

```csharp
// The option `options.ForceValueGeneratedStrategy = ValueGeneratedStrategyType.OnAdd` has been replaced by:
options.ExplicitValueResolutionMode = Z.EntityFramework.Extensions.ExplicitValueResolutionMode.AlwaysKeepValueOnInsert;
```

The article is not 100% completed, but you can see most important information about this new option here: [How EFE Bulk Extensions Handle Explicit Values in EF Core](https://entityframework-extensions.net/explicit-value-resolution-mode)

Let me know if you need more information.

Best Regards,

Jon

**Comment by TonyValenti** [comment]
Thank you!
