### ISSUE TITLE
Please allow us to choose where we want to see extension methods

### ISSUE THREAD

**Issue by GertArnold** [zzzprojects/EntityFramework-Extensions#597]
When EntityFramework.Extensions (but I think your libraries in general) is referenced a vast amount of extension methods is visible *everywhere*, because, as I infer, they're not in a namespace. Hence, it's impossible to exclude them from intellisense. That's a serious pain in the neck and in the past it has been a reason for us to stop using one of your libraries.

At the moment we're again looking at bulk insert providers. Is there any chance to get a version of your library that doesn't have this extremely disruptive effect on our daily coding practice? Let us choose where we see extension methods by applying `using` statements as we see fit, just as most third-partly libraries allow.

- EF version: [EF Core v8.06]
- EF Extensions version: [EFE Core v8.103.0]
- Database Server version: [SQL Server 2019]

**Comment by JonathanMagnan** [comment]
Hello @GertArnold ,

Thank you for your feedback.

We don't plan to create a new NuGet package to cover this case, but I'm talking to my developer, and we might have an alternative solution for you.

What could be done is setting on your side an [extern alias](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/extern-alias) for our library and adding a file we will create that contains all extension methods under a namespace (that will use the `extern-alias` you will choose).

So, the extension method will no longer appear unless you add the namespace from this adding file.

What do you think of this alternative solution? I cannot promise you anything, but at first sight, it was working well in my test.

Best Regards,

Jon

**Comment by JonathanMagnan** [comment]
Hello @GertArnold, 

Since our last conversation, we haven't heard from you. 

Let me know if you need more information. 

Best regards, 

Jon

**Comment by GertArnold** [comment]
Thanks Jon, I'll need some time to test how this would work out for us. As far as I can tell, it would be a fairly acceptable work-around, but it requires developers to be aware of how to reference your library. It's a deviation from the normal `using`s that various IDE tools add automatically, so I figure we'd have to correct those whenever they occur.

**Comment by JonathanMagnan** [comment]
Hello @GertArnold ,

I just created an article about how to [Add a Namespace for Entity Framework Extensions](https://entityframework-extensions.net/adding-a-namespace-to-entity-framework-extensions)

If you proceed with this solution, let me know if all steps are clear enough.

While we cannot change the default behavior, this technic will let you add the namespace you want.

Best Regards,

Jon

**Comment by GertArnold** [comment]
Thanks, that's clear enough and it's nice to have this prepared file as part of the library. FWIW, sorry for you, but we decided not to use EFE. The performance benefit it would offer is in a part of the application that's not important enough to invest in.

**Comment by JonathanMagnan** [comment]
On the good side, at least this is now done for anyone who wants to use a namespace within our library.

Have a great week,

Best Regards,

Jon
