### ISSUE TITLE
it does not save related objects 

### ISSUE THREAD

**Issue by mwinner313** [zzzprojects/EntityFramework-Extensions#6]
var Retrivedmailinglist = db.MailingLists.Where(l => l.Name == listName).FirstOrDefault();
            var convertedMembers = members.Distinct().Select(m => new EmailMember { EmailAddress =         m.EmailAddress }).ToList();
            foreach (var emaliMember in convertedMembers)
                emaliMember.MailingLists.Add(Retrivedmailinglist);

            db.BulkInsert(convertedMembers);
            db.BulkSaveChanges();

**Comment by zzzprojects** [comment]
Direct bulk operations (BulkInsert, BulkUpdate, BulkDelete, BulkMerge) doesn't save related entities and doesn't use the ObjectTracking for performance reason (we want these methods to be as fast as possible). However, BulkSaveChanges work exactly like SaveChanges

You have two solution to perform your scenario:

**Solution 1 - BulkInsert x2**
```
db.BulkInsert(convertedMembers);
db.BulkInsert(convertedMembers.SelectMany(x => x.MailingLists);
```

**Solution 2 - AddRange + BulkSaveChanges**
```
db.AddRange(convertedMembers);
db.BulkSaveChanges();
```

> Note: You don't have to call BulkSaveChanges after BulkInsert

**Comment by mwinner313** [comment]
thanks

**Comment by zzzprojects** [comment]
Closing: Question answered
