### ISSUE TITLE
Error attempting BulkInsert with SQLite on Model with manually specified Key value

### ISSUE THREAD

**Issue by xadozuk** [zzzprojects/EntityFramework-Extensions#60]
Hello,

I'm trying to use the method BulkInsert to perform a insert of a ~1000 entities.
These entities are loaded from an external source (ex: csv file) and already have a primary key value (Id).
I need to keep these values, allowing me to build relationships.

According to your documentation, I use BulkInsert like this
```csharp
context.BulkInsert(
    entities,
        options =>
        {
            options.InsertKeepIdentity = true;
        }
);
```
Here's my model class 
```csharp
public class Customer
{
    [Key]
    [DatabaseGenerated(DatabaseGeneratedOption.None)]
    public int Id { get; set; }

    // ...
}
```

When I execute this code I get the following error :

> System.Data.SQLite.SQLiteException : 'SQL logic error or missing database. 4 values for 5 columns'

I get no errors when I don't specify the option.InsertKeepIdentity but the IDs don't stay the same.
I get the result expected when I use a classic AddRange + SaveChanges.

I use :
- Entity Framework 6.1.3
- Entity Framwork Extension 3.13.6
- SQLite 1.0.105.2
- .NET Framework 4.6.1

**Comment by JonathanMagnan** [comment]
Hello @xadozuk 

Thank you for reporting this issue, we will look at it today.

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment]
Hello @xadozuk ,

It looks this option has never been supported for SQLite yet.

The support has been added and a new version should be available in around 3h

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment]
Hello @xadozuk ,

The v3.13.8 has been released,

Please let me know if this error is fixed on your side.

Best Regards,

Jonathan

**Comment by xadozuk** [comment]
Hello @JonathanMagnan,

The new version fixed the issue.

Thank you for quick work,

Best regard
