### ISSUE TITLE
"The Provider could not be resolved. You must explicity set the Provider." Exception Even Though I Have Set The Provider

### ISSUE THREAD

**Issue by dtanders** [zzzprojects/EntityFramework-Extensions#606]
### Description
When doing a bulk operation with the library, eg `BulkSaveChanges` the library throws the an exception with the message "The Provider could not be resolved. You must explicity set the Provider."

### Exception

```
Exception message: The Provider could not be resolved. You must explicity set the Provider.
Stack trace:
    ..(Z.BulkOperations.BulkOperation)
    ..(Z.BulkOperations.BulkOperation)
    Z.BulkOperations.BulkOperation.BulkInsert()
    Z.EntityFramework.Extensions.BulkSaveChanges.(System.Data.Entity.DbContext, System.Collections.Generic.List<System.Data.Entity.Core.Objects.ObjectStateEntry>, System.Collections.Generic.List<System.Data.Entity.Core.Objects.ObjectStateEntry>, System.Action<Z.BulkOperations.BulkOperation>)
    DbContextExtensions.(System.Data.Entity.DbContext, bool, System.Action<Z.BulkOperations.BulkOperation>, bool)
```
I have set the provider in the web config:
```
  <entityFramework>
    <defaultConnectionFactory type="System.Data.Entity.Infrastructure.LocalDbConnectionFactory, EntityFramework">
      <parameters>
        <parameter value="mssqllocaldb" />
      </parameters>
    </defaultConnectionFactory>
    <providers>
      <provider invariantName="Microsoft.Data.SqlClient" type="System.Data.Entity.SqlServer.MicrosoftSqlProviderServices, Microsoft.EntityFramework.SqlServer" />
    </providers>
  </entityFramework>
```

### Further technical details

- EF version: 6.5.1
- EF Extensions version: 3.14.7, 3.16.23
- Database Server version: Azure SQL
- Database Provider version (NuGet): Microsoft.Data.SqlClient 5.0.0

Do we need to buy an update to get support for this provider?

**Comment by JonathanMagnan** [comment]
Hello @dtanders ,

Could you try with the latest version? Our library now supports `Microsoft.Data.SqlClient` for EF6 since a few months

But older versions, such as the one you are currently using, do not support it (it was not yet supported by EF6 either at this time).

> Do we need to buy an update to get support for this provider?

Indeed, if your current license doesn't allow you to use the latest version, you will need to renew your license. You can contact our sales team to know what they can offer you: sales@zzzprojects.com

Best Regards,

Jon
