### ISSUE TITLE
ArgumentException on BulkMergeAsync

### ISSUE THREAD

**Issue by Farami** [zzzprojects/EntityFramework-Extensions#61]
Hello,

EF Version 6.1.3
EF Extensions Version 3.13.8
Provider: SQL

I can't get BulkMerge to work properly. The exception I am getting is:
> `
> [ArgumentException: Ein Element mit dem gleichen Schlüssel wurde bereits hinzugefügt.]
>    System.ThrowHelper.ThrowArgumentException(ExceptionResource resource) +52
>    System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add) +12534430
>    System.Linq.Enumerable.ToDictionary(IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer) +247
>    ..(Schema ) +1016
>    ..(Schema , Boolean ) +74
>    ..(String , String , String , String ) +2609
>    ..(DbContext ) +124
>    ..(DbContext ) +179
>    DbContextExtensions.GetModel(DbContext this) +223
>    ..(DbContext , String ) +94
>    Z.EntityFramework.Extensions.InternalBulkOperationManager.(DbContext , BulkOperation`1 , IEnumerable`1 ) +192
>    Z.EntityFramework.Extensions.InternalBulkOperationManager.(BulkOperation`1 , DbContext , IEnumerable`1 ) +77
>    DbContextExtensions.BulkMerge(DbContext this, IEnumerable`1 entities, Action`1 bulkOperationFactory) +681
>    DbContextExtensions.BulkMerge(DbContext this, IEnumerable`1 entities) +72
>    .() +63
>    System.Threading.Tasks.Task.InnerInvoke() +73
>    System.Threading.Tasks.Task.Execute() +47
>    System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) +99
>    System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) +58
>    .() +388
>    System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) +99
>    System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) +58
>    System.Runtime.CompilerServices.TaskAwaiter.GetResult() +26
>    TrackPilotN.Data.Repositories.Generic.<InsertOrUpdateManyAsync>d__21.MoveNext() in C:\Users\oconnor\Source\PLT Workspaces\Web\TrackPilotN.Data\Repositories\Generic\GenericRepository.cs:138
>    System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) +99
>    System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) +58
>    System.Runtime.CompilerServices.TaskAwaiter.GetResult() +26
>    TrackPilotN.Business.Service.<EditOrInsertAddresses>d__60.MoveNext() in C:\Users\oconnor\Source\PLT Workspaces\Web\TrackPilotN.Business\Service\AddressService.cs:958
>    System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) +99
>    System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) +58
>    System.Runtime.CompilerServices.TaskAwaiter`1.GetResult() +28
>    TrackPilotN.Business.Service.<ImportAsync>d__58.MoveNext() in C:\Users\oconnor\Source\PLT Workspaces\Web\TrackPilotN.Business\Service\AddressService.cs:917
>    System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) +99
>    System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) +58
>    System.Runtime.CompilerServices.TaskAwaiter`1.GetResult() +28
>    TrackPilotN.Areas.Data.Controllers.<ImportConfirmed>d__14.MoveNext() in C:\Users\oconnor\Source\PLT Workspaces\Web\TrackPilotN\Areas\Data\Controllers\AddressController.cs:296
>    System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) +99
>    System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) +58
>    System.Web.Mvc.Async.TaskAsyncActionDescriptor.EndExecute(IAsyncResult asyncResult) +97
>    System.Web.Mvc.Async.<>c__DisplayClass37.<BeginInvokeAsynchronousActionMethod>b__36(IAsyncResult asyncResult) +17
>    System.Web.Mvc.Async.WrappedAsyncResult`1.CallEndDelegate(IAsyncResult asyncResult) +10
>    System.Web.Mvc.Async.WrappedAsyncResultBase`1.End() +48
>    System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeActionMethod(IAsyncResult asyncResult) +32
>    System.Web.Mvc.Async.AsyncInvocationWithFilters.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3d() +50
>    System.Web.Mvc.Async.<>c__DisplayClass46.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3f() +228
>    System.Web.Mvc.Async.<>c__DisplayClass46.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3f() +228
>    System.Web.Mvc.Async.<>c__DisplayClass33.<BeginInvokeActionMethodWithFilters>b__32(IAsyncResult asyncResult) +10
>    System.Web.Mvc.Async.WrappedAsyncResult`1.CallEndDelegate(IAsyncResult asyncResult) +10
>    System.Web.Mvc.Async.WrappedAsyncResultBase`1.End() +48
>    System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeActionMethodWithFilters(IAsyncResult asyncResult) +34
>    System.Web.Mvc.Async.<>c__DisplayClass2b.<BeginInvokeAction>b__1c() +26
>    System.Web.Mvc.Async.<>c__DisplayClass21.<BeginInvokeAction>b__1e(IAsyncResult asyncResult) +100
>    System.Web.Mvc.Async.WrappedAsyncResult`1.CallEndDelegate(IAsyncResult asyncResult) +10
>    System.Web.Mvc.Async.WrappedAsyncResultBase`1.End() +49
>    System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeAction(IAsyncResult asyncResult) +27
>    System.Web.Mvc.Controller.<BeginExecuteCore>b__1d(IAsyncResult asyncResult, ExecuteCoreState innerState) +13
>    System.Web.Mvc.Async.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult) +29
>    System.Web.Mvc.Async.WrappedAsyncResultBase`1.End() +49
>    System.Web.Mvc.Controller.EndExecuteCore(IAsyncResult asyncResult) +36
>    System.Web.Mvc.Controller.<BeginExecute>b__15(IAsyncResult asyncResult, Controller controller) +12
>    System.Web.Mvc.Async.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult) +22
>    System.Web.Mvc.Async.WrappedAsyncResultBase`1.End() +49
>    System.Web.Mvc.Controller.EndExecute(IAsyncResult asyncResult) +26
>    System.Web.Mvc.Controller.System.Web.Mvc.Async.IAsyncController.EndExecute(IAsyncResult asyncResult) +10
>    System.Web.Mvc.MvcHandler.<BeginProcessRequest>b__5(IAsyncResult asyncResult, ProcessRequestState innerState) +21
>    System.Web.Mvc.Async.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult) +29
>    System.Web.Mvc.Async.WrappedAsyncResultBase`1.End() +49
>    System.Web.Mvc.MvcHandler.EndProcessRequest(IAsyncResult asyncResult) +28
>    System.Web.Mvc.MvcHandler.System.Web.IHttpAsyncHandler.EndProcessRequest(IAsyncResult result) +9
>    System.Web.CallHandlerExecutionStep.OnAsyncHandlerCompletion(IAsyncResult ar) +129
> `

I am not doing anything out of the ordinary. I have a regular list of entities I want to Upsert.

**Comment by JonathanMagnan** [comment]
Hello @Farami ,

It seems our library have an issue when reading your model. There is a something in your model that we doesn't support yet.

The only way to solve this kind of bug is by providing to us the model you use.

You can send it directly to us: info@zzzprojects.com

### Database First
Simply send us your .edmx file.

### Code First
You can generate the XML model by using the following method. 
           
```                           
public string GetModelXDocument(DbContext context)
{
    XDocument doc;
    using (var memoryStream = new MemoryStream())
    {
        using (XmlWriter xmlWriter = XmlWriter.Create(memoryStream, new XmlWriterSettings { Indent = true }))
        {
            EdmxWriter.WriteEdmx(context, xmlWriter);
        }
 
        memoryStream.Position = 0;
 
        doc = XDocument.Load(memoryStream);
    }
    return doc.ToString();
}
 ```

Best Regards,

Jonathan

**Comment by Farami** [comment]
I have sent the EDMX.

**Comment by JonathanMagnan** [comment]
Hello @Farami ,

Unfortunately, the `EDMX` provided work perfectly on our side.

Since we know exactly which method throw the error, we will improve the error message to give us information about which item already exists in the Dictionary.

Perhaps that will give us a hint about what's happening.

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment]
Hello @Farami ,

The v3.13.9 has been released.

Since we have not been able to find the issue even with your `EDMX` file, we added some debug information on the dictionary to at least have some information about the dictionary in error.

Could you report the error that should look like this one:

```txt
Oops! An error occurred when reading your model. A duplicate key has been found when adding value to a dictionary. Please report the issue to our support team: info@zzzprojects.com;Dictionary ID=Index_Associations_Name;Key=Z1;Value=Z.EntityFramework.Extensions.Core.SchemaObjectModel.Relationship
```

Best Regards,

Jonathan

**Comment by Farami** [comment]
Hello @JonathanMagnan!

Thank you for the quick response!
Today is a public holiday in germany so I will take a look first thing tomorrow.

Best regards

**Comment by Farami** [comment]
Hey @JonathanMagnan,

here's the requested error message:

`Oops! An error occurred when reading your model. A duplicate key has been found when adding value to a dictionary. Please report the issue to our support team: info@zzzprojects.com;Dictionary ID=Index_EntitySets_Name;Key=Order;Value=Z.EntityFramework.Extensions.Core.SchemaObjectModel.EntityContainerEntitySet`

**Comment by JonathanMagnan** [comment]
Thank you @Farami  for this additional information.

That explains why I cannot reproduce it on my side.

Do you think you could reproduce this scenario in a test project that we could try? We normally support multiple files and multiple contexts but perhaps there is something we are missed to make it compatible with your projects.

Best Regards,

Jonathan

**Comment by Farami** [comment]
@JonathanMagnan I have sent you a zip file containing a small project that reproduces the issue.

**Comment by JonathanMagnan** [comment]
Hello @Farami ,

We made a temporary fix today but we will look for a better fixe for next Monday.

The v3.13.10 has been released

To make it compatible with your model, you will need to enable the option `TmpForceDatabaseFirstSingleModel `

```csharp
EntityFrameworkManager.TmpForceDatabaseFirstSingleModel = true;
```

Let me know if that's working with this option on

Best Regards,

Jonathan

**Comment by Farami** [comment]
Hello @JonathanMagnan,

This seems to have fixed the problem. Thank you very much for your quick response.

Best regards
