### ISSUE TITLE
Issue with Trial License Expiration for Z.EntityFramework.Extensions

### ISSUE THREAD

**Issue by katsumory** [zzzprojects/EntityFramework-Extensions#610]
Hello,

I’m reaching out regarding an issue with the trial version of Z.EntityFramework.Extensions. According to the information on your website, the trial version can be used indefinitely as long as it is updated to the latest version. However, after updating to version 8.103.6.0, I am still encountering a "license expired" error.

I have taken the following steps to resolve this issue:

- Uninstalled and reinstalled the package to ensure it is the latest version.
- Cleared the NuGet cache and rebuilt the project.
- Verified that all projects in the solution are referencing the updated package.

Despite these efforts, the "license expired" error persists, preventing me from using the library. The release notes for version 8.103.6.0 indicate that the trial should be valid until the end of November, but it expired on November 5th.

Please note that my project is not for commercial use, so purchasing a perpetual license is not feasible for me. Could you please advise on how to resolve this issue, or if there’s anything specific I need to do to continue using the trial version?

Thank you for your assistance.

Best regards,

### Further technical details

- EF version: [EF v5.0.0] (also tried with v6.0.0 same error)
- EF Extensions version: [EFE.EF5 v8.103.6] (also tried with [EFE v8.103.6] and had same error)
- Database Server version: [SQL Server 2016]
- Database Provider version (NuGet): [v5.11.6.4]

**Comment by katsumory** [comment]
Hello @JonathanMagnan ,

Thank you for the quick response and clarification regarding the trial version. I understand the situation, and I will wait for the new trial release.

I appreciate the prompt support and assistance.

Best regards,
Katsumory

**Comment by JonathanMagnan** [comment]
Hello @katsumory !

The trial 8.103.6.1 is now available. 

Don’t hesitate to contact us if you need further assistance. 

Best regards, 

Jon
