### ISSUE TITLE
Issue with WhereBulkContains After PostgreSQL Migration

### ISSUE THREAD

**Issue by hackwithbalaji** [zzzprojects/EntityFramework-Extensions#612]
### Description

Hi Team,

We are in the process of migrating our database from MSSQL to PostgreSQL. During this migration, all database objects, including table and column names, have been converted to lowercase. Our system uses Zentity, and we have encountered a critical issue with the WhereBulkContains functionality.

### Issue Details:

The issue occurs when a column name matches its table name (e.g., Table: user, Column: username).
When invoking WhereBulkContains on tables with such columns, an exception is thrown.

```
Exception message:

System.Exception: Oops! The following table name `.user AS ` has not been found in the command text for the `WhereBulkContains` features. at Z.EntityFramework.Plus.WhereBulkContainsBuilder`1.CommandTextBuilderPostgreSQL(String schema, String tableName, String nameTempTable, List`1 KeyNamesBD, String commandText, Boolean isLast, Boolean isNotContains, Boolean addZZZIndex) at Z.EntityFramework.Plus.WhereBulkContainsBuilder`1.CommandTextBuilder(String schema, String tableName, String nameTempTable, List`1 KeyNamesBD, String commandText, Boolean isLast, Boolean isNotCTE, Tuple`2 temporalName)

```

This is happening only in postgres. Even if I have lowercase objects in MSSQL, it is working there. 

### Further technical details

- EF Core version: 8.0.4
- EF Extensions version: 8.103.3

This is a blocker for our migration to PostgreSQL, and we kindly request you to prioritize this issue. Please check it at the earliest and revert with a solution/suggestion. Let us know if you need additional information.

@JonathanMagnan

Thanks,
--Balaji

**Comment by JonathanMagnan** [comment]
Hello @hackwithbalaji ,

Thank you for reporting.

My developer told me that he successfully reproduced the issue, and he is working on a fix.

Best Regards,

Jon

**Comment by hackwithbalaji** [comment]
Thank you @JonathanMagnan. I appreciate the quick response!

Since this issue is critical for our migration, I kindly request an estimated timeline for when the fix will be ready and released.

We rely heavily on ZEntity and are using the licensed version in our system, with usage across multiple modules. Due to this, exploring alternative solutions is not a feasible option for us. The resolution of this issue is essential for planning and executing our migration effectively.

Please let me know the expected release date for the fix, so we can adjust our timeline accordingly. 

Thank you for your support!!!

**Comment by JonathanMagnan** [comment]
Hello @hackwithbalaji ,

A new version will be released within a few hours.

We are currently running all our unit tests before making our deployment at this moment.

Best Regards,

Jon

**Comment by JonathanMagnan** [comment]
Hello @hackwithbalaji ,

The v9.103.6.3 is now available: https://github.com/zzzprojects/EntityFramework-Extensions/releases/tag/9.103.6.3

Could you let us know if we fixed the issue correctly?

Best Regards,

Jon

**Comment by hackwithbalaji** [comment]
Hello @JonathanMagnan ,

I have verified the changes, the issue is resolved and working as expected now.

Thanks for the quick action and support!!

**Comment by JonathanMagnan** [comment]
Great to know everything is working as expected!

Let me know if you need further assistance. 

Best regards, 
Jon
