### ISSUE TITLE
Exception on BulkSaveChanges

### ISSUE THREAD

**Issue by cxs-mahendra** [zzzprojects/EntityFramework-Extensions#63]
Hi,

When I add a list of entity using AddRange and then I call the BulkSaveChanges, it throws the following error. I am using .Net Core 2.0. Could you please let me know what could be causing the exception.
Exception: KeyNotFoundException
Message: The given key was not present in the dictionary.

using (DbContext _Con = GetDbContext())
                {
                    _Con.AddRange(NewProducts);
                    _Con.BulkSaveChanges(bulk => bulk.BatchSize = 100);
                }

**Comment by JonathanMagnan** [comment]
Hello @cxs-mahendra ,

Thank you for reporting,

Do you think you could provide us the Stack Trace, it might give us the information required to check which dictionary cause this error.

Also, is there something special about your `Product` class we should be aware?

Best Regards,

Jonathan

**Comment by cxs-mahendra** [comment]
Hi Jonathan,

Here is the stack trace.
   at System.ThrowHelper.ThrowKeyNotFoundException()
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at .`1.( )
   at .Read()
   at .MoveNext()
   at System.Data.SqlClient.SqlBulkCopy.ReadFromRowSource()
   at System.Data.SqlClient.SqlBulkCopy.ReadFromRowSourceAsync(CancellationToken cts)
   at System.Data.SqlClient.SqlBulkCopy.WriteToServerInternalAsync(CancellationToken ctoken)
   at System.Data.SqlClient.SqlBulkCopy.WriteRowSourceToServerAsync(Int32 columnCount, CancellationToken ctoken)
   at System.Data.SqlClient.SqlBulkCopy.WriteToServer(IDataReader reader)
   at .( , SqlConnection , SqlTransaction )
   at .(List`1 )
   at Z.BulkOperations.BulkOperation.()
   at .[](DbContext this, IEnumerable`1 , Action`1 )
   at .(DbContext this, StateManager , IReadOnlyList`1 )
   at .(DbContext this, StateManager , IReadOnlyList`1 )
   at .(DbContext this, Action`1 )
   at CitiXsys.iVend365.EntityFrameworkCore.Repositories.iVend365RepositoryBase`2.BulkInsertIntoProductAndInventoryItem(List`1 NewProducts, List`1 ModifiedProducts, List`1 InventoryItems, List`1 POSKeys) in D:\CXS.Retail\Development\iVend365\src\CitiXsys.iVend365.EntityFrameworkCore\EntityFrameworkCore\Repositories\iVend365RepositoryBase.cs:line 175

No I don't think there is anything special about my product class. There is no foreign key in my Product Entity or Product Class.

If you feel you may come online on GTM to see the issue, I can send you a GTM invite....

Regards,
Mahendra

**Comment by JonathanMagnan** [comment]
Hello @cxs-mahendra ,

We have investigated this issue but unfortunately, we have not found anything yet.

We will continue to check it tomorrow and perhaps release a "debug" version.

We currently knew which dictionary cause the error but we are not able to understand why this is happening yet.

I don't think it will change anything but could you provide your `Product`  class. We never know, perhaps there is something we forget to support.

Best Regards,

Jonathan

**Comment by cxs-mahendra** [comment]
Hi Jonathan,

Here is my complete Product Class. You may like to rename it to Product.cs.
I am actually stuck with BulkSaveChanges. Please help me urgently. You may also give me some hint that I can also try at my end....

Regards,
Mahendra



[Product.txt](https://github.com/zzzprojects/EntityFramework-Extensions/files/1493674/Product.txt)

**Comment by cxs-mahendra** [comment]
I am not sure whether you received the class file (as an attachment) therefore re-sending the complete class...

using CitiXsys.iVend365.Enterprises;
using CitiXsys.iVend365.MCCore;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace CitiXsys.iVend365.Products
{
    [Table("InvProduct")]
    public class Product : MCFullAuditedEntity
    {
        public const int MaxEntityIDLength = 100;
        public const int MaxDescriptionLength = 100;
        public const int MaxDescription2Length = 200;
        public const int MaxUPCLength = 200;
        public const int MaxExternalLinkLength = 400;
        public const int MaxHSNCodeLength = 20;

        [Column("ProductKey")]
        [Key, DatabaseGenerated(DatabaseGeneratedOption.None)]
        public override long Id { get; set; }

        [Column("Id")]
        [Required]
        [MaxLength(MaxEntityIDLength)]
        public virtual string EntityId { get; set; }

        [Required]
        [MaxLength(MaxDescriptionLength)]
        public virtual string Description { get; set; }

        [MaxLength(MaxDescription2Length)]
        public virtual string Description2 { get; set; }

        [Required]
        public virtual long ProductGroupKey { get; set; }

        [Required]
        public virtual long SalesTaxCodeKey { get; set; }

        [Required]
        public virtual long PurchaseTaxCodeKey { get; set; }

        [Required]
        public virtual bool IsNonStock { get; set; } = false;

        [Required]
        public virtual bool IsRefundable { get; set; } = true;

        [Required]
        public virtual bool IsSaleable { get; set; } = true;

        [Required]
        public virtual bool IsInclusiveTaxed { get; set; }

        [Required]
        public virtual decimal BasePrice { get; set; }

        [MaxLength(MaxUPCLength)]
        public virtual string UPC { get; set; }

        [Required]
        public virtual bool LoyaltyPointsRedeemable { get; set; }

        [MaxLength(MaxExternalLinkLength)]
        public virtual string ExternalLink { get; set; }

        [MaxLength(MaxHSNCodeLength)]
        public virtual string HSNCode { get; set; }

        public virtual bool IsARPaymentProduct { get; set; }

        #region Properties not part of Dto for now

        [DefaultValue("")]
        public virtual string Description3 { get; set; }
        public virtual long PreferedVendorKey { get; set; }
        public virtual bool AllowFractionalQuantity { get; set; } = true;
        public virtual bool DiscountsAllowed { get; set; } = true;
        public virtual bool HasUpsells { get; set; }
        public virtual bool HasAlternateProducts { get; set; }
        public virtual bool HasWarrantyAvailable { get; set; }
        public virtual bool IsBatchTracked { get; set; }
        public virtual bool IsExchangable { get; set; }
        public virtual bool IsRentable { get; set; }
        public virtual bool IsSerialTracked { get; set; }
        public virtual bool IsWeighed { get; set; }
        public virtual bool IsKit { get; set; }
        public virtual bool IsAssembly { get; set; }
        public virtual bool CanLayaway { get; set; }
        public virtual bool CanOrder { get; set; }
        public virtual bool IsOnHold { get; set; }
        public virtual bool IsTaxExempt { get; set; }
        public virtual bool IsOpenPrice { get; set; }
        public virtual bool IsOpenDescription { get; set; }
        public virtual decimal DefaultQuantity { get; set; }
        public virtual bool RequireAgeVerification { get; set; }
        public virtual int MinAge { get; set; }
        public virtual bool HasImage { get; set; }
        public virtual long ManufacturerKey { get; set; }
        public virtual bool IsGiftCertificate { get; set; }
        public virtual bool IsZeroValue { get; set; }
        public virtual bool IsPurchasable { get; set; }
        public virtual bool IsMatrixItem { get; set; }
        public virtual bool IsMatrixChildItem { get; set; }
        public virtual bool IsTwoDimensionalMatrixItem { get; set; }
        public virtual long ParentMartixProductKey { get; set; }
        public virtual int DefaultExpiryPeriod { get; set; }
        public virtual GiftCertificateType GiftCertificateType { get; set; } = GiftCertificateType.None;
        public virtual bool PriceOverrideAllowed { get; set; } = true;
        public virtual bool CanSellExpiredItem { get; set; } = true;
        public virtual int ExpiryMessageDays { get; set; }
        public virtual bool CanRefundExpiredItem { get; set; } = true;
        public virtual bool IsStoreCredit { get; set; }
        public virtual decimal MaximumOpenPrice { get; set; }
        public virtual bool IgnoreDiscountItemsForSaleDiscount { get; set; }
        public virtual bool SaleDiscountsAllowed { get; set; } = true;
        public virtual long ProductClassKey { get; set; }
        public virtual long PackageGroupKey { get; set; }
        public virtual bool HasPackageGroup { get; set; }
        public virtual string GiftCertificatePassTemplate { get; set; } = "Default";
        public virtual string GiftCertificateEmailTemplate { get; set; } = string.Empty;
        public virtual string PassDescription { get; set; } = string.Empty;
        public virtual string PassValue { get; set; } = string.Empty;
        public virtual long CommentKey { get; set; }
        public virtual AutoSelectSerialBatchType AutoSelectSerialBatchType { get; set; }
        public virtual bool UsePriceEmbeddedBarcode { get; set; }
        public virtual bool MustSwipeCard { get; set; }
        public virtual long UOMGroupKey { get; set; }
        public virtual bool DiscountsGroupAllowed { get; set; } = true;
        public virtual long PurchaseUOMKey { get; set; }
        public virtual long PurchaseUOMPackageKey { get; set; }
        public virtual long SaleUOMKey { get; set; }
        public virtual long SaleUOMPackageKey { get; set; }
        public virtual long InventoryUOMKey { get; set; }
        public virtual long InventoryCountingUOMKey { get; set; }
        public virtual long BarCodeMaskKey { get; set; }
        public virtual bool IsEBTItem { get; set; }
        public virtual string AccountingID { get; set; }
        public virtual int LeadTime { get; set; }
        public virtual bool ExpiryDateRequiredForBatch { get; set; }
        public virtual bool ExpiryDateRequiredForSerial { get; set; }
        public virtual int ReturnDays { get; set; }
        public virtual CostingMethod CostingMethod { get; set; } = CostingMethod.StandardCost;
        public virtual CostingSubMethod CostingSubMethod { get; set; } = CostingSubMethod.PerProductWarehouse;
        public virtual long PrimaryFilterAttributeKey { get; set; }
        public virtual long TwoDimensionalFilterAttributeKey { get; set; }
        public virtual int GracePeriod { get; set; }
        public virtual long ProductDiscountGroupKey { get; set; }
        public virtual bool IsTaxOnly { get; set; }
        public virtual string VariantCode { get; set; }
        public virtual bool ReprintGCOnRedemption { get; set; }
        public virtual decimal MinimumReprintingAmount { get; set; }
        public virtual bool IsPrintingRequired { get; set; }
        public virtual decimal LoyaltyPointAllocationRatio { get; set; }

        public virtual decimal Cost { get; set; }

        #endregion
    }

    public enum GiftCertificateType
    {
        /// <summary>
        /// The none
        /// </summary>
        None = 0,
        /// <summary>
        /// The pre printed
        /// </summary>
        PrePrinted = 1,
        /// <summary>
        /// The system generated
        /// </summary>
        SystemGenerated = 2,
        /// <summary>
        /// The user defined
        /// </summary>
        UserDefined = 3,
        /// <summary>
        /// The email
        /// </summary>
        Email = 4
    }
    //public enum AutoSelectSerialBatchType
    //{
    //    /// <summary>
    //    /// The manual
    //    /// </summary>
    //    Manual = 0,
    //    /// <summary>
    //    /// The expiry date
    //    /// </summary>
    //    ExpiryDate = 1,
    //    /// <summary>
    //    /// The lowest price first
    //    /// </summary>
    //    LowestPriceFirst = 2,
    //    /// <summary>
    //    /// The highest price first
    //    /// </summary>
    //    HighestPriceFirst = 3,
    //    /// <summary>
    //    /// The creation date
    //    /// </summary>
    //    CreationDate = 4,
    //    /// <summary>
    //    /// The only if one available
    //    /// </summary>
    //    OnlyIfOneAvailable = 5
    //}
    public enum CostingMethod
    {
        /// <summary>
        /// The none
        /// </summary>
        None = 0,
        /// <summary>
        /// The average cost
        /// </summary>
        AverageCost = 1,
        /// <summary>
        /// The standard cost
        /// </summary>
        StandardCost = 2
    }
    public enum CostingSubMethod
    {
        /// <summary>
        /// The none
        /// </summary>
        None = 0,
        /// <summary>
        /// The per product
        /// </summary>
        PerProduct = 1,
        /// <summary>
        /// The per product warehouse
        /// </summary>
        PerProductWarehouse = 2
    }

}

**Comment by JonathanMagnan** [comment]
Hello @cxs-mahendra ,

The v2.0.8 has been released.

I believe we successfully fixed your issue using the model you provided.

Let us know if it's now working.

Best Regards,

Jonathan

**Comment by cxs-mahendra** [comment]
Thanks Jonathan....it worked...

**Comment by JonathanMagnan** [comment]
Hello @cxs-mahendra ,

We are currently making some issue cleanup.

Feel free to reopen if you believe we closed it by mistake

Best Regards,

Jonathan
