### ISSUE TITLE
Error: 0013: Oops! A general error has occurred

### ISSUE THREAD

**Issue by lizhengzhou** [zzzprojects/EntityFramework-Extensions#65]
Error: 0013: Oops! A general error has occurred. Please report the issue including the stack trace to our support team: info@zzzprojects.com

BulkInsert

BulkDelete

**Comment by JonathanMagnan** [comment]
Hello @lizhengzhou ,

It's possible that your company currently use an illegal license?

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment]
Hello @lizhengzhou ,

We are currently making some issue cleanup.

Feel free to reopen if you believe we closed it by mistake

Best Regards,

Jonathan

**Comment by JasonDevStudio** [comment]
Hello , 


I also reported this error, can you give me a license for a period of 2-3 months? I have submitted a grant application for 5-9 development licenses, but the company needs me to give a test report, for some reason, I am probationary period A month has passed, just developed functional modules, the need for some stress tests.

Thank you
