### ISSUE TITLE
Error: 0013: Oops! A general error has occurred

### ISSUE THREAD

**Issue by JasonDevStudio** [zzzprojects/EntityFramework-Extensions#68]
`--------------------------------------------------------------------------------------------------------------------
记录时间：2017-12-14 18:39:47,418 
线程ID:[21] 
日志级别：ERROR 
执行类：LDS.EF.Data.Access.EFHelper`1  
描述：Error: 0013: Oops! A general error has occurred. Please report the issue including the stack trace to our support team: info@zzzprojects.com

System.Exception: Error: 0013: Oops! A general error has occurred. Please report the issue including the stack trace to our support team: info@zzzprojects.com
   在 ..(BulkOperation )
   在 Z.BulkOperations.BulkOperation.BulkUpdate()
   在 Z.EntityFramework.Extensions.EntityBulkOperation`1.BulkUpdate()
   在 Z.EntityFramework.Extensions.InternalBulkOperationManager.[](BulkOperation`1 , DbContext , List`1 , Boolean , Type , String )
   在 Z.EntityFramework.Extensions.InternalBulkOperationManager.?.(SchemaEntityType )
   在 System.Collections.Generic.List`1.ForEach(Action`1 action)
   在 Z.EntityFramework.Extensions.InternalBulkOperationManager.[](DbContext , BulkOperation`1 , IEnumerable`1 )
   在 Z.EntityFramework.Extensions.InternalBulkOperationManager.[](BulkOperation`1 , DbContext , IEnumerable`1 )
   在 DbContextExtensions.BulkUpdate[T](DbContext this, IEnumerable`1 entities, Action`1 bulkOperationFactory)
 

BulkUpdate<TEntity> at offset 456 in file:line:column <filename unknown>:0:0

BulkUpdateTasks at offset 810 in file:line:column <filename unknown>:0:0

<ExecuteMain>b__1 at offset 2760 in file:line:column <filename unknown>:0:0

Execute at offset 70 in file:line:column <filename unknown>:0:0

RunInternal at offset 354 in file:line:column <filename unknown>:0:0

Run at offset 20 in file:line:column <filename unknown>:0:0

ExecuteWithThreadLocal at offset 540 in file:line:column <filename unknown>:0:0

ExecuteEntry at offset 115 in file:line:column <filename unknown>:0:0

Dispatch at offset 338 in file:line:column <filename unknown>:0:0`

I also reported this error, can you give me a license for a period of 2-3 months? I have submitted a grant application for 5-9 development licenses, but the company needs me to give a test report, for some reason, I am probationary period A month has passed, just developed functional modules, the need for some stress tests.

Thank you

**Comment by JonathanMagnan** [comment]
Hello @JasonDevStudio ,

It's possible that your company currently use an illegal license?

You can extend the trial period by downloading the latest version at the beginning of every month. However, to enable the trial version, you will need to remove the illegal license you have added to your application (if this is the case).

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment]
We have been contacted by a company from China yesterday. However, we are not able to contact them back with the email address provided.

Perhaps that is your company? If this is the case, please could you try to contact us again with another email.

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment]
Hello @JasonDevStudio ,

I will close this issue since I believe there are no more activities to do on it. The issue was caused because of an illegal license.

Feel free to reopen it if you believe it should not have been closed.

Best Regards,

Jonathan

---
_Help us to support this library: [Donate](http://www.zzzprojects.com/contribute)_
