### ISSUE TITLE
An error occured while resolving mapping by name. See the inner exception for details

### ISSUE THREAD

**Issue by JasonDevStudio** [zzzprojects/EntityFramework-Extensions#69]
Hello, I also appear in the debugging hrowKeyNotFoundException, I checked the code, it seems that did not find the problem, available to you, hoping to help you improve EFE.

In addition, you say the mail from China, can not be restored contact, I have been looking for colleagues check, if the message claiming to be from "China Huawei", then it may be, I confirmed here, if it is our mail, I will ask my colleagues to reissue an email, with a list of possible contacts.

Thank  you

--------------------------------------------------------------------------------------------------------------------
记录时间：2017-12-15 14:33:14,761 
线程ID:[7] 
日志级别：ERROR 
执行类：LDS.EF.Data.Access.EFHelper`1  
描述：An error occured while resolving mapping by name. See the inner exception for details

System.Exception: An error occured while resolving mapping by name. See the inner exception for details ---> System.Collections.Generic.KeyNotFoundException: 给定关键字不在字典中。
   在 System.ThrowHelper.ThrowKeyNotFoundException()
   在 System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   在 Z.BulkOperations.BulkOperation.()
   --- 内部异常堆栈跟踪的结尾 ---
   在 Z.BulkOperations.BulkOperation.()
   在 ..(BulkOperation )
   在 Z.BulkOperations.BulkOperation.BulkMerge()
   在 Z.EntityFramework.Extensions.EntityBulkOperation`1.BulkMerge()
   在 Z.EntityFramework.Extensions.InternalBulkOperationManager.[](BulkOperation`1 , DbContext , List`1 , Boolean , Type , String )
   在 Z.EntityFramework.Extensions.InternalBulkOperationManager..(SchemaEntityType )
   在 System.Collections.Generic.List`1.ForEach(Action`1 action)
   在 Z.EntityFramework.Extensions.InternalBulkOperationManager.[](DbContext , BulkOperation`1 , IEnumerable`1 )
   在 Z.EntityFramework.Extensions.InternalBulkOperationManager.[](BulkOperation`1 , DbContext , IEnumerable`1 )
   在 DbContextExtensions.BulkMerge[T](DbContext this, IEnumerable`1 entities, Action`1 bulkOperationFactory)
   在 LDS.EF.Data.Access.EFHelper`1.BulkMerge[TEntity](List`1 entities, BulkOperation`1 option, String operateUser, Expression`1 ignoreUpdateExp, Expression`1 ignoreInsertExp, Expression`1 keyExp, Expression`1 inputExp) 位置 

BulkMerge<TEntity> at offset 599 in file:line:column <filename unknown>:0:0

BulkInsertShmoos at offset 6996 in file:line:column <filename unknown>:0:0

BulkInsertShmoosForRes at offset 2094 in file:line:column <filename unknown>:0:0

ResToLdsData at offset 4977 in file:line:column <filename unknown>:0:0

ExecuteResDataToLds at offset 2101 in file:line:column <filename unknown>:0:0

<ExecuteMain>b__1 at offset 2908 in file:line:column <filename unknown>:0:0

Execute at offset 70 in file:line:column <filename unknown>:0:0

RunInternal at offset 354 in file:line:column <filename unknown>:0:0

Run at offset 20 in file:line:column <filename unknown>:0:0

ExecuteWithThreadLocal at offset 540 in file:line:column <filename unknown>:0:0

ExecuteEntry at offset 115 in file:line:column <filename unknown>:0:0

Dispatch at offset 338 in file:line:column <filename unknown>:0:0

**Comment by JonathanMagnan** [comment]
Hello @JasonDevStudio ,

About the email, you are fine. We don't have the problem to communicate with your company.

Sometimes, we receive email looking like this: `outlook_8616D51778397D49@outlook.com` that we cannot reply back.

Do you think you could provide us the entities model used in this scenario? We will try to improve this weekend this error message to better find which column is not found.

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment]
Hello @JasonDevStudio ,

I will close this issue since we cannot go further in our investigation.

Feel free to reopen it if you can provide us more information.

Best Regards,

Jonathan

---
_Help us to support this library: [Donate](http://www.zzzprojects.com/contribute)_
