### ISSUE TITLE
BulkInset Unsupported types

### ISSUE THREAD

**Issue by shvalev** [zzzprojects/EntityFramework-Extensions#70]
BulkInsert throws error if PostgreSql table contains field with type; character varying
Message:
Oops! Unsupported types : character varying
StackTrace:
   at .( , String[] )
   at .(Boolean , String[] )
   at Z.BulkOperations.BulkOperation.()

**Comment by JonathanMagnan** [comment]
Hello @shvalev ,

Thank you for reporting,

We will try to add the support to this type tomorrow.

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment]
Hello @shvalev ,

Sorry for the delay,

The v3.14.5 has been released.

We have not been able to reproduce this issue, however, we have added the support to the type.

Please let us know if you still have the same error message.

Best Regards,

Jonathan
