### ISSUE TITLE
EFE did not refresh the CacheKey problem

### ISSUE THREAD

**Issue by JasonDevStudio** [zzzprojects/EntityFramework-Extensions#71]
Hello, there is a question to consult with you, I have such a scene, I need according to different connection strings, use the same dbcontext to connect different Oracle user, of course these different Oracle user table structure consistent. So I have to write a Rawdbcontext class, inherit from DbContext, implement Interface Idbmodelcachekeyprovider, to refresh the EF schemaname, I use the EF query when there is no problem, but in the use of Efe Bulkmerge or Bulkinsert, the SQL statement that EFE writes to the database is the Oracle User before the last EF refresh SchemaName, causing a data write error.

For example, I last used pro_4241 Oracle user to write data. This time using pro_4250 Oracle user to write data, the result of the execution of the SQL statement is as follows, which is incorrect:

Can you provide a parameter or a way to set Oracle User or SchemaName?

`INSERT  INTO "PRO_4241"."TEST_FLOW" ("ID", "TESTER", "ADDI", "LOOP", "TEST_TEMP", "MTE", "FLOW_TEST_TIME", "PROGRAM_TEST_TIME", "FLOW_REV", "PROGRAM_NAME", "RESERVED_1", "JOB_REV", "RESERVED_3", "RESERVED_4", "LOADBOARD_TYPE", "PROJECT_ID", "RESERVED_2", "TEMPCONTROLLER", "PATH", "SORTNO", "VERSION", "LEVEL_TEST_TIME", "RESERVED_5", "FLOW_NAME", "PROJECT_NAME", "STATUS", "START_TIME") VALUES(:P_0, :P_1, :P_2, :P_3, :P_4, :P_5, :P_6, :P_7, :P_8, :P_9, :P_10, :P_11, :P_12, :P_13, :P_14, :P_15, :P_16, :P_17, :P_18, :P_19, :P_20, :P_21, :P_22, :P_23, :P_24, :P_25, :P_26)`

**Comment by JonathanMagnan** [comment]
Hello @JasonDevStudio ,

Thank you for reporting, we will look about what's possible to do to try to provide you a solution.

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment]
Hello @JasonDevStudio ,

Is your scenario a concurrency scenario? I believe not since you change the `user` of the connection.

We have implemented in the past a `RefreshModel` method for people that change some connection setting at runtime.

Could you try the following code after you have modified the Oracle user to use?

```csharp
context.RefreshModel();
```

Let me know if that work. This solution doesn't work for concurrency scenario.

Best Regards,

Jonathan

**Comment by JasonDevStudio** [comment]
Hello, @JonathanMagnan  ,Thank you for your reply, I have seen the function, there is free time behind, I will be a special test of this issue, and timely feedback results to you, thank you for your help.

**Comment by JonathanMagnan** [comment]
Hello @JasonDevStudio ,

Did you succeed to make it works?

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment]
Hello @JasonDevStudio ,

This issue will be closed since we haven't heard back from you.

Feel free to reopen it if you can provide the information we asked.

Best Regards,

Jonathan
