### ISSUE TITLE
Using cache extension with Asp.net Core Membership provider

### ISSUE THREAD

**Issue by mehmetilker** [zzzprojects/EntityFramework-Extensions#73]
Is there any example how can we use cache extension with membership provider coming with asp.net core?
For example caching roles per user on login and serving it from cache for subsequent request.

**Comment by JonathanMagnan** [comment]
Hello @mehmetilker ,

I believe this request should be under [Entity Framework Plus](http://entityframework-plus.net/) and not EFE?

Beside the current documentation about Query Cache: http://entityframework-plus.net/query-cache there is no additional information.

This kind of scenario depends too much on how the application has been built.

I believe this request could be out of the range of the `Query Cache` features

Best Regards,

Jonathan

**Comment by mehmetilker** [comment]
Oh yes, sorry, I was looking for this repo https://github.com/zzzprojects/EntityFramework-Plus
My question was more related if any example/experience rather then support by library.

Thank you for your reply.
