### ISSUE TITLE
UpdateFromQuery not executing for MySQL

### ISSUE THREAD

**Issue by watkinzez2** [zzzprojects/EntityFramework-Extensions#76]
Hi,

I am using EntityFramework Extensions 3.11.21.0, and attempting to use UpdateFromQuery doesn't execute any statements on my MySQL database. Is this method supported for MySQL?

**Comment by JonathanMagnan** [comment]
Hello @watkinzez2 ,

Unfortunately no,

Your version is too much `outdated` and that was not supported yet. However, the latest version supports it.

I recommend you to use the latest version or if you cannot upgrade to use as well [EF+ - Batch Update](http://entityframework-plus.net/batch-update) which is a similar features from our free library.

Let me know if that answer correctly to your question.

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment]
Hello @watkinzez2 ,

This issue will be closed since it has been resolved.

Feel free to reopen it if you feel otherwise.

Best Regards,

Jonathan
