### ISSUE TITLE
BulkInsert/Update support for split table

### ISSUE THREAD

**Issue by wojMark** [zzzprojects/EntityFramework-Extensions#77]
BulkInsert & BulkUpdate does not support split table (when one table is split into 2 or more entities) - in such case if we need to use bulkInsert than we need to use bulkUpdate on "dependent" entity (Address in example). Without that data for dependent entity wont be saved. Below test

```C#
    public class TestContext : DbContext
    {
        public DbSet<User2> Users { get; set; }

        public TestContext() : base("testDbEF")
        {

        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            modelBuilder.Entity<AddressDetail>().ToTable("Users");
            modelBuilder.Entity<User2>().ToTable("Users")
                .HasRequired(a => a.Address)
                .WithRequiredPrincipal(a => a.User);
        }
    }

    public class User2
    {
        [Key]
        public int Id { get; set; }
        public string Name { get; set; }
        [ForeignKey(nameof(Id))]
        public virtual AddressDetail Address { get; set; }
    }

    public class AddressDetail
    {
        [Key]
        public int Id { get; set; }
        public string City { get; set; }
        public virtual User2 User { get; set; }
    }

    [TestClass]
    public class BulkInsertTests
    {
       [TestMethod]
        public void BulkInsert__TableSplittedIntoTwoEntities__DependentEntityPropertiesShouldBeUpdate()
        {
            string cityTestName = "CityTemplateName";
            using (TestContext insertContext = new TestContext())
            {
                insertContext.Database.ExecuteNonQuery("truncate table Users");
                AddressDetail address = new AddressDetail()
                {
                    City = cityTestName
                };
                User2 user = new User2()
                {
                    Name = "TestUser1",
                    Address = address
                };
                insertContext.BulkInsert(new User2[] { user });
            }
            using (TestContext context = new Repositories.TestContext())
            {
                User2 user = context.Users.Single();
                user.Address.City.Should().Be(cityTestName);
            }
        }
    }
```

**Comment by JonathanMagnan** [comment]
Hello @wojMark ,

Thank you for reporting, we will try your scenario and see what's happening on our side.

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment]
Hello @wojMark ,

Sorry for the big delay.

We started to investigate this issue. However, we find your model very strange.

Even without our library, Entity Framework cannot do all operations. By example, the following code throws an error if the table contains at least one row.

```csharp
using (TestContext context = new TestContext())
{
    context.Users.RemoveRange(context.Users);
    context.SaveChanges();
}
```

> Invalid data encountered. A required relationship is missing. Examine StateEntries to determine the source of the constraint violation.

Is there a reason why you don't use complex type? [MSDN Doc](https://msdn.microsoft.com/en-us/library/jj680147(v=vs.113).aspx)

This kind of scenario is normally handled with a complex type which has been designed for this.

Best Regards,

Jonathan

**Comment by wojMark** [comment]
We are not using complex type because I need lazy loading for one property (I cannot change database schema). In greenfield project it would be easy to correct this by changing database schema but in current i need deal with what i got. Thats why using split table would solve my problems without doing some magic.

Your example will throw exception but there is little hack to solve it
```C#
  using (TestContext context = new TestContext())
  {
       context.Users.RemoveRange(context.Users.Include(a=>a.Address));
       context.SaveChanges();
   }
```
Best regards,
Marek

**Comment by JonathanMagnan** [comment]
Hello @wojMark ,

Thank you, we will check if that's possible to support this scenario.

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment]
Hello @wojMark ,

Sorry for the late answer, it seems we forgot the follow-up on this one.

We will need to, unfortunately, close this issue. When we tried it two months ago and last week, our attempt to support this scenario was introducing some issue. So the risk is a little bit too high.

However, the `BulkSaveChanges` seem to work fine like `SaveChanges` with this scenario. So perhaps only using `BulkSaveChanges` when you need to deal with this entity is the best solution for both of us.

Best Regards,

Jonathan
