### ISSUE TITLE
BulkUpdate with obfuscated code

### ISSUE THREAD

**Issue by virzak** [zzzprojects/EntityFramework-Extensions#78]
Hello,

I'm using [obfuscar](https://github.com/lextm/obfuscar) with assembly that calls the BulkUpdate.

One of the issues is that they always obfuscate anonymous types https://github.com/lextm/obfuscar/issues/131 and the resulting names don't match the original ones.

Is there a way of calling BulkUpdate with having a strong type or with explicit expressions?

**Comment by JonathanMagnan** [comment]
Hello @virzak ,

Looking at this answer https://github.com/lextm/obfuscar/issues/130, it seems you can skip anonymous class.

Could you try it and let us know if that's working?

Best Regards,

Jonathan

**Comment by virzak** [comment]
@JonathanMagnan, thanks for the tip.

Certainly solves the issue.

Since there is no way of knowing the exact type name, we need to use wildcards which will exclude all anonymous types.

```xml
<SkipType name="*AnonymousType*" skipProperties="true" skipMethods="true" skipFields="true" skipEvents="true" skipStringHiding="true" />
```

Since I barely use anonymous types, I would prefer excluding them and not introduce new classes or expressions.

Just out of curiousity, is anonymous type the only way to work with options?

Thanks

**Comment by JonathanMagnan** [comment]
Hello @virzak ,

Nope, you can explicitly set the column to map. Under the hood, this library uses our other library Z.BulkOperations

Example:

```csharp
using Z.BulkOperations;

ctx.BulkUpdate(list, option =>
{
    option.ColumnMappings.Add("ID");
    option.ColumnMappings.Add("Name");
});
```

Best Regards,

Jonathan

**Comment by virzak** [comment]
@JonathanMagnan This is probably the best solution, since the obfuscation can be default.
Thanks!

**Comment by virzak** [comment]
@JonathanMagnan I added this into my project. Could be a good idea for the library:

```csharp
    using Z.BulkOperations;
    public static class ColumnMappingExtensions
    {
        public static void AddRange<T>(this List<ColumnMapping<T>> list, IEnumerable<string> columnNames)
        {
            foreach (string columnName in columnNames)
            {
                list.Add(columnName);
            }
        }
    }

```

**Comment by JonathanMagnan** [comment]
Hello @virzak ,

Thank you, we might include it later when we will revamp the project.

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment]
Hello @virzak ,

This issue will be closed since it has been resolved.

We have also noted your suggestion.

Feel free to reopen it if you feel otherwise.

Best Regards,

Jonathan
