### ISSUE TITLE
Licence

### ISSUE THREAD

**Issue by sanybee** [zzzprojects/EntityFramework-Extensions#8]
I woul like to know how does the licence  key work for 4 developpers
what happends if a developper leave the company 
The licence iremain to the company or for the developper ?

**Comment by zzzprojects** [comment]
Hello,

The license is for the company. No user own a license, it just allows your company to use the library legally with four developers.

So it doesn't matter if one developer leave, your company still can use the license with four developers.

Let me know if that answer clearly to your question.

Best Regards,

Jonathan

**Comment by zzzprojects** [comment]
Closing this question, we provided additional information by mail.
