### ISSUE TITLE
UpdateFromQuery with abstract class does not work

### ISSUE THREAD

**Issue by marcselman** [zzzprojects/EntityFramework-Extensions#80]
I have an abstract base class 'Import' and two derived classes 'Shop' and 'Feed'.
They are all EntityFramework Entities.
When I try to update an Import I cannot pass a `new Import` because it's an abstract class but when I pass a `new Feed` for example I get an error: 
> Incorrect syntax near the keyword 'WHEN'

If I remove the abstract modifier it works as expected.
```
db.Imports.Where(r => r.Id == 123).UpdateFromQuery(r => new Import
{
	Progress = null,
	LastProcessedUtc = DateTime.UtcNow
});
```

I don't want to remove the abstract modifier because the base class should not be instantiated.

**Comment by JonathanMagnan** [comment]
Hello @marcselman ,

Which type of inheritance are you using? TPC, TPH, TPT?

It will help us to reproduce this scenario.

Best Regards,

Jonathan

**Comment by marcselman** [comment]
In this case TPT inheritance. If you need me to do some tests let me know.

**Comment by JonathanMagnan** [comment]
Thank you @marcselman ,

`TPT` is currently unsupported but we will try during the weekend to see if something can be done.

I will give you an update at the beginning of next week.

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment]
Hello @marcselman 

This issue will be closed since it has been resolved.

Feel free to reopen it if you feel otherwise.

Best Regards,

Jonathan

**Comment by marcselman** [comment]
I just wanted to say thanks for the fix! Better late than never ;)

**Comment by JonathanMagnan** [comment]
True ;) Have a nice day.
