### ISSUE TITLE
Bulkupdate with list of around 40000 records does not update db

### ISSUE THREAD

**Issue by ramarathna** [zzzprojects/EntityFramework-Extensions#81]
Bulk update , though executes without any problem  but the changes are not reflected in the database.
It works for a smaller set of test data.

**Comment by JonathanMagnan** [comment]
Hello @ramarathna ,

Which provider are you using? Do you think you could reproduce this issue in a standalone project?

You are the first one to report us this kind of error so I'm not sure we have enough information to try to reproduce it yet.

Best Regards,

Jonathan

**Comment by ramarathna** [comment]
Hi Jonathan,

It is working now,I am using bulkupdate with batch size.
Thank you.

Regards
Raamarathna B C

**Comment by JonathanMagnan** [comment]
Hello @ramarathna ,

That's great, however, that should have worked from the start.

If you can provide us more information, we will be happy to investigate this issue deeper.

Best Regards,

Jonathan
