### ISSUE TITLE
How To Use Update INNER JOIN or Delete INNER JOIN

### ISSUE THREAD

**Issue by x91270** [zzzprojects/EntityFramework-Extensions#83]
I need to update some records using inner join in EntityFramework-Extensions.

UPDATE b  
SET b.InPrice = 0, b.InMoney = 0   
FROM  Data_OwnProductInStock a  
INNER JOIN Data_OwnProductInStockItem b ON a.Billnumber = b.Billnumber  
INNER JOIN Financial_TermPrice c ON b.GoodsID = c.GoodsID  
WHERE  
a.IsDelete=0 AND b.IsDelete=0

**Comment by JonathanMagnan** [comment]
Hello @x91270 ,

The answer depends highly on your DbContext && Navigation Property available.

In short, it's similar to perform a `ToList()` to retrieve the Data_OwnProductInStockItem using the predicate specified. I'm not sure why you need the `Financial_TermPrice ` join?

Do you think you could send us a project with your entities to let us try? info@zzzprojects.com

Best Regards,

Jonathan

**Comment by x91270** [comment]
For Example


`UPDATE b
SET b.InPrice = c.InPrice , b.InMoney = b.Amount * c.InPrice
FROM Data_Own a
INNER JOIN Data_OwnItem b ON a.Billnumber = b.Billnumber
INNER JOIN TermPrice c ON b.GoodsID = c.GoodsID
WHERE
a.IsDelete = 0 AND b.IsDelete = 0
AND a.AccountDate = '2018-01-02 00:00:00.000'`

Example Tabel Record

[Desktop.zip](https://github.com/zzzprojects/EntityFramework-Extensions/files/1746819/Desktop.zip)

**Comment by x91270** [comment]
Thanks

**Comment by JonathanMagnan** [comment]
Hello @x91270 ,

Thank you for the SQL database but we will need entity as well.

As said, the answer depends highly on your DbContext && Navigation Property available.

Best Regards,

Jonathan

**Comment by x91270** [comment]
I use DBFirst

**Comment by JonathanMagnan** [comment]
Hello @x91270 ,

This is the entities we need or an example.

For example:

```csharp
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Request
{
    public static class Request
    {
        public const string connection = "Server=127.0.0.1;Initial Catalog=Z;Integrated Security=True;";

        public static void Execute()
        {  
            // CLEAN
            using (var context = new EntityContext())
            {
                context.EntitySimples.RemoveRange(context.EntitySimples);
                context.SaveChanges();
            }

            // SEED
            using (var context = new EntityContext())
            {
                context.EntitySimples.Add(new EntitySimple() { ColumnInt = 1 });
                context.EntitySimples.Add(new EntitySimple() { ColumnInt = 2 });
                context.EntitySimples.Add(new EntitySimple() { ColumnInt = 3 });
                context.SaveChanges();
            }

            // TEST
            using (var context = new EntityContext())
            {
                var list = context.EntitySimples.ToList(); 
            }
        }

        public class EntityContext : DbContext
        {
            public EntityContext() : base(connection)
            {
            }

            public DbSet<EntitySimple> EntitySimples { get; set; }

            protected override void OnModelCreating(DbModelBuilder modelBuilder)
            {
                modelBuilder.Types().Configure(x =>
                    x.ToTable(GetType().DeclaringType != null
                        ? GetType().DeclaringType.FullName.Replace(".", "_") + "_" + x.ClrType.Name
                        : ""));

                base.OnModelCreating(modelBuilder);
            }
        }

        public class EntitySimple
        {
            public int ID { get; set; }
            public int ColumnInt { get; set; }
        }
    }
}
```

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment]
Hello @x91270 ,

Do you think you could provide us the requested information?

Best Regards,

Jonathan

**Comment by langdonx** [comment]
@JonathanMagnan Can you answer the question with my samples?

Person is abstract and can be a ClientPerson, ClientRegionPerson or ClientLocationPerson.
Communication is abstract and can be a PersonCommunication (and other unimportant types).
A Person can have zero or more PersonCommunications.

```
public abstract class Person
{
    public int Id { get; set; }
    public Guid? Uuid { get; set; }

    internal int PersonTypeId { get; set; }

    public ICollection<PersonCommunication> Communications { get; set; } = new HashSet<PersonCommunication>();

    public bool? ActiveFlag { get; set; }
    public DateTime? CreateDate { get; set; }
    public DateTime? LastEditDate { get; set; }
    public string CreateUserId { get; set; }
    public string Department { get; set; }
    public string EditUserId { get; set; }
    public string FirstName { get; set; }
    public string LastName { get; set; }
    public string Title { get; set; }
}

public class ClientPerson : Person
{
    public Client Client { get; set; }
        
    // this is here for mapping only
    internal int EntityId { get; set; }
}

// NOTE: ClientRegionPerson and ClientLocationPerson look identical

public abstract class Communication
{
    public int Id { get; set; }

    internal int EntityTypeId { get; set; }

    public CommunicationMediaType MediaType { get; set; }
    public CommunicationType CommunicationType { get; set; }
    public string Value { get; set; }
    public string CacheValue { get; set; }
}

public class PersonCommunication : Communication
{
    public Person Person { get; set; }

    internal int EntityId { get; set; }
}
```

I need to be able to update AND delete a Person's Communications where Person.Uuid is a specific value.

Right now I'm hard-coding SQL and want to get away from that:

```
// update example
var updateEmailSql = "update tc set communication_value = {0}, cache_value = {0}" +
					 "  from communication tc" +
					 " inner join person tp on tp.person_id = tc.entity_id" +
					 " where tp.person_uuid = {1}" +
					 "   and tc.base_type = {2}";

// delete exxample
var deleteMobileSubscriptionsSql = "delete tc" +
                                   "  from communication tc" +
                                   " inner join person tp on tp.person_id = tc.entity_id" +
                                   " where tp.person_uuid = {0}" +
                                   "   and communication_value = {1}";
```

The database is horrible, I know, but it's what we're working with at the moment.

**Comment by JonathanMagnan** [comment]
Hello @langdonx ,

Unfortunately, your scenario looks to use some inheritance (TPH) and our library doesn't support it for `DeleteFromQuery` and `UpdateFromQuery`.

One way to do it is by using `BulkDelete` and `BulkUpdate`  but it will require you to load all data first which you probably don't want to do.

Best Regards,

Jonathan
