### ISSUE TITLE
Postgresql schema problem

### ISSUE THREAD

**Issue by tedypranolo** [zzzprojects/EntityFramework-Extensions#84]
I'm getting an exception while trying to do bulkinsert. It seems that EntityFramework-Extensions
 is generating an incorrect sql statement while trying to get schema information
```
SELECT	
	table_schema AS BaseSchemaName,
	table_name AS BaseTableName,
	column_name AS ColumnName,
	data_type as DateType,
	ordinal_position AS Ordinal,
	CASE WHEN EXISTS (
		SELECT 1 FROM
		INFORMATION_SCHEMA.TABLE_CONSTRAINTS X 
		JOIN INFORMATION_SCHEMA.CONSTRAINT_COLUMN_USAGE AS Y USING (constraint_schema, constraint_name) 
		WHERE X.constraint_type = 'PRIMARY KEY' AND X.table_name = A.table_name AND Y.column_name = A.column_name) 
	THEN 1 ELSE 0 END AS IsKey,
    CASE WHEN pg_get_serial_sequence('"' || TABLE_NAME || '"', COLUMN_NAME) IS NOT NULL
    THEN 1 ELSE 0 END AS IsIdentity
FROM INFORMATION_SCHEMA.COLUMNS AS A
WHERE SCHEMA_NAME = 'misc' AND  TABLE_NAME = 'misc.word60kfrequency'
```
My table is in the "misc" schema, and the name is "word60kfrequency". This generated sql is incorrect because in postgresql INFORMATION_SCHEMA.TABLE_CONSTRAINTS does not have `schema_name` column, instead it has a `table_schema` column. And `TABLE_NAME = 'misc.word60kfrequency'` should have been `TABLE_NAME = 'word60kfrequency'`.

I'm using
Npgsql 3.2.6
Npgsql.EntityFrameworkCore.Postgresql 2.0.1

**Comment by JonathanMagnan** [comment]
Hello @tedypranolo ,

Thank you for reporting, we will look at it today.

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment]
Hello @tedypranolo ,

The v2.0.15 has been released.

Everything should work as expected when the table has a schema table.

Let me know if the issue has been successfully fixed.

Best Regards,

Jonathan

**Comment by tedypranolo** [comment]
It's working correctly now. Thank you very much.

**Comment by JonathanMagnan** [comment]
Hello @tedypranolo ,

This issue will be closed since it has been resolved.

Feel free to reopen it if you feel otherwise.

Best Regards,

Jonathan
