### ISSUE TITLE
Core: Oops! Unsupported types

### ISSUE THREAD

**Issue by combl** [zzzprojects/EntityFramework-Extensions#86]
Hi,

I'm evaluating EntityFramwork.Extensions. I have no Problems using it with SQL Express. But with PostgreSQL I get an exception on BulkInsertAsnyc():

**Oops! Unsupported types : character varying**

Using NuGet Z.EntityFramework.Extensions.EFCore v2.0.16

Thanks and best regards
Chris

**Comment by JonathanMagnan** [comment]
Hello @combl ,

Thank you for reporting.

We will try this issue on our side today.

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment]
Hello @combl ,

The v2.0.17 has been released.

Let me know if that now work for you.

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment]
Hello @combl ,

This issue will be closed since it has been resolved.

Feel free to reopen it if you feel otherwise.

Best Regards,

Jonathan
