### ISSUE TITLE
DeleteFromQuery producing null reference exception

### ISSUE THREAD

**Issue by watkinzez2** [zzzprojects/EntityFramework-Extensions#87]
Hi,

I get a "Object reference not set to an instance of an object" exception when attempting to use DeleteFromQuery.

The query in particular uses an OfType filter to search with a property in a derived class. QuoteId is a property of GridComment, and BaseComment is the base class of GridComment. The DbSet Comments is of type BaseComment.

`Context.Comments.OfType<GridComment>().Where(gc => gc.QuoteId == quote.Id)`

The exception stack trace is this:

"   at Z.EntityFramework.Extensions.Internal.BatchDelete.\u0001[\u0001](IQueryable`1 )\r\n   at DbContextExtensions.\u0001[\u0001](IQueryable`1 , Action`1 , CancellationToken )\r\n   at DbContextExtensions.DeleteFromQuery[TEntity](IQueryable`1 query, Action`1 bulkOperationFactory)\r\n   at DbContextExtensions.DeleteFromQuery[TEntity](IQueryable`1 query)\r\n ""

**Comment by JonathanMagnan** [comment]
Hello @watkinzez2 ,

Since you use `OfType`, I would suspect you use some inheritance (`TPC`, `TPH`, or `TPT1`).

Unfortunately, inheritance is not yet supported.

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment]
Hello @watkinzez2 ,

This issue will be closed since it has been resolved.

Feel free to reopen it if you feel otherwise.

Best Regards,

Jonathan
