### ISSUE TITLE
AuditEntries link to entities

### ISSUE THREAD

**Issue by UOAlien** [zzzprojects/EntityFramework-Extensions#88]
Is there an easy way of connecting the AuditEntries list to the original list of entities?  Is it as simple as the AuditEntries return in the same order as the entities?

**Comment by JonathanMagnan** [comment]
Hello @UOAlien ,

Unfortunately no,

We do not have any mechanism like this one and you cannot assume the order is the same. You will need to check your primary key with the AuditProperty key entry corresponding to be sure.

If you use an operation like `BulkInsert` and has one key, I recommend you to create a dictionary after to retrieve the corresponding audit faster.

For example:

```csharp
var auditDict = auditEntries.ToDictionary(x => Convert.ToInt32(x.Values.Single(y => y.ColumnName == "ID").NewValue));
```

Let me know if that answer correctly to your question.

Best Regards,

Jonathan

**Comment by UOAlien** [comment]
Thank you @JonathanMagnan for the example. 

I'm trying to write a generic, catch-all option to be able to handle single-field and multi-field situations and you pointed me in the right direction.  
I'm focused on the BulkMerge as we use it and it doesn't hit our DbContext as normal.

What I have come up with is ... messy, but it does work.  Any chance you have an example of matching over a multi-column key?  If not, I'll post my mess on here and see if you can come up with any improvements.

**Comment by JonathanMagnan** [comment]
Hello @UOAlien ,

If that's for testing purpose, you can concatenate all key into string.

Something similar to this:

```csharp
var auditDict = auditEntries.ToDictionary(x => 
	x.Values.Single(y => y.ColumnName == "ID1").NewValue.ToString()
	+ ";"
	+ x.Values.Single(y => y.ColumnName == "ID2").NewValue).ToString()
);
```

**Comment by UOAlien** [comment]
I went a bit more overboard than that I think...this is what I came up with:
`
//(parameter passed in to my method)
Expression<Func<T, object>> key
var keyFieldNames = ((NewExpression)key.Body)?.Members.Select(x => x.Name).ToList();
                var keyPropertyInfos = keyFieldNames.Select(x => typeof(T).GetProperty(keyFieldNames[0])).ToList();
                var localContext = new NRDBContext();
                updates.ForEach(ae =>
                {
                    var q = entities;
                    keyPropertyInfos.ForEach(kpi =>
                    {
                        q = entities.Where(x => kpi.GetValue(x)?.ToString() == ae.Values.Single(y => y.ColumnName == kpi.Name).NewValue?.ToString());
                    });
                    var entity = q.FirstOrDefault();
                    if (entity != null)
                    {
                        //Do stuff here
                    }
                });`

**Comment by JonathanMagnan** [comment]
That's great ;) 

I will close this issue then

Best Regards,

Jonathan
