### ISSUE TITLE
Whether to support query for new data

### ISSUE THREAD

**Issue by JasonDevStudio** [zzzprojects/EntityFramework-Extensions#89]
Hello, can support query data in the absence of a new, already exist in the case, then ignore, do not update, nor Add. For example, the function "Bulkmerge" To remove the update function is satisfied.

**Comment by JasonDevStudio** [comment]
你好，我有个需求，就是在新增数据时，判断表中是否已经存在数据，如果不存在，就新增到数据表，如果需要新增的数据已经存在了，就不新增，也不更新。 是否支持呢？ 如果不支持，是否考虑能支持呢？

Hello, I have a demand, is in the new data, judge whether the table already exists data, if it does not exist, add to the datasheet, if you need new data already exist, do not add, nor update. Do you support it? If it is not supported, will it consider supporting it?

**Comment by JonathanMagnan** [comment]
Hello @JasonDevStudio ,

For some provider, there is an options named `InsertIfNotExists` that only insert if the data doesn't already exist (using the key)

```csharp
context.BulkInsert(list, options => options.InsertIfNotExists = true);
```

Let me know if this options could work for your scenario.

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment]
Hello @JasonDevStudio ,

Here is an example:

```csharp
using System.Collections.Generic;
using System.Data.Entity;
using System.Windows.Forms;

namespace Z.EntityFramework.Extensions.Lab
{
    public partial class Form_Request_InsertIfNotExists : Form
    {
        public Form_Request_InsertIfNotExists()
        {
            InitializeComponent();

            // CLEAR
            using (var ctx = new CurrentContext())
            {
                ctx.EntitySimples.RemoveRange(ctx.EntitySimples);
                ctx.BulkSaveChanges();
            }

            // SEED
            using (var ctx = new CurrentContext())
            {
                ctx.EntitySimples.Add(new EntitySimple {IntColumn = 1});
                ctx.EntitySimples.Add(new EntitySimple {IntColumn = 2});
                ctx.BulkSaveChanges();
            }

            // TEST
            using (var ctx = new CurrentContext())
            {
                var list = new List<EntitySimple>();
                list.Add(new EntitySimple {IntColumn = 1});
                list.Add(new EntitySimple {IntColumn = 3});

                ctx.BulkInsert(list, options =>
                {
                    options.InsertIfNotExists = true;
                    options.ColumnPrimaryKeyExpression = x => x.IntColumn;
                });
            }
        }

        public class CurrentContext : DbContext
        {
            public CurrentContext()
                : base("CodeFirstEntities")
            {
            }

            public DbSet<EntitySimple> EntitySimples { get; set; }

            protected override void OnModelCreating(DbModelBuilder modelBuilder)
            {
                modelBuilder.Types().Configure(x => x.ToTable(GetType().DeclaringType != null ? GetType().DeclaringType.FullName.Replace(".", "_") + "_" + x.ClrType.Name : ""));

                base.OnModelCreating(modelBuilder);
            }
        }

        public class EntitySimple
        {
            public int Id { get; set; }

            public int IntColumn { get; set; }
        }
    }
}
```

Let me know if that helped you to make it works.

If you are using another provider than SQL Server, just let me know which provider.

Best Regards,

Jonathan

**Comment by JasonDevStudio** [comment]
@JonathanMagnan 我使用的是Oracle

**Comment by JasonDevStudio** [comment]
Oracle.DataAccess.

**Comment by JonathanMagnan** [comment]
Oh that explain,

We will look at it, this features may not be implemented for this provided.

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment]
Hello @JasonDevStudio ,

I have some bad news, after some research it seems it cannot be possible to support this feature for Oracle at this moment.

Doing it will mean that we will no longer to "Bulk Insert" data.

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment]
Hello @JasonDevStudio ,

This issue will be closed since we have not found any performance way to support it with `Oracle`.

Best Regards,

Jonathan
