### ISSUE TITLE
BulkMerge does not use ColumnPrimaryKeyExpression

### ISSUE THREAD

**Issue by staff0rd** [zzzprojects/EntityFramework-Extensions#97]
I execute the following;

```
var category = new GeneralLedgerCategory
{
    Id = Guid.NewGuid(),
    GeneralLedgerCode = "12345"
};

db.BulkMerge(new[] { category }, (options) =>
{
    options.ColumnPrimaryKeyExpression = type => type.GeneralLedgerCode;
});
```

But this fails on subsequent attempts due to a unique key constraint that exists on `GeneralLedgerCode`, however, I am expecting `BulkMerge` to be aware of this considering I have set `ColumnPrimaryKeyExpression`.

Investigating the profiler, I see the following `ON` clause within the `MERGE`;

```
ON (DestinationTable.[Id] = StagingTable.[Id] OR (DestinationTable.[Id] IS NULL AND StagingTable.[Id] IS NULL)) AND (DestinationTable.[GeneralLedgerCode] = StagingTable.[GeneralLedgerCode] OR (DestinationTable.[GeneralLedgerCode] IS NULL AND StagingTable.[GeneralLedgerCode] IS NULL))
```

Why is `Id` (primary key) in there, when I have specifically set `ColumnPrimaryKeyExpression` to `GeneralLedgerCode`?

**Comment by JonathanMagnan** [comment]
Hello @staff0rd ,

Thank you for reporting.

By looking at our code, when no `ColumnInputExpression` has been provided, we map all Entity Framework columns and the key specified (Oops!).

The `ColumnPrimaryKeyExpression` later specify which column is used as the key. However, some column has already been flagged which is an error.

We will try to release a fix later today with this issue.

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment]
Hello @staff0rd ,

The v2.1.8 (for EF Core) has been released.

Let me know if it's work as expected or you were using another version than EF Core.

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment]
Hello @staff0rd ,

This issue will be closed since it has been resolved.

Feel free to reopen it if you feel otherwise.

Best Regards,

Jonathan

**Comment by staff0rd** [comment]
Thanks Jonathan, I have tested this and can confirm the fix works.
